* Generated by KPABAP 10.11.2022  10:10:54
INCLUDE MP902010.                      " Data Definitions
INCLUDE MPPDAT00.                      " Global Data     - Do not change
INCLUDE FP50PPSB.                      " Buffer          - Do not change
INCLUDE MPPERS00.                      " Standard Modules- Do not change
INCLUDE MP902020.                      " Output Modules
INCLUDE MP902030.                      " Input Modules
INCLUDE MP902040.                      " Subroutines

INCLUDE MP902050.
