"Name: \PR:SAPLV45P\FO:USEREXIT_SET_STATUS_VBUK\SE:BEGIN\EI
ENHANCEMENT 0 YSD_CREDIT_CHECK.
IF SY-TCODE EQ 'VA01' OR SY-TCODE EQ 'VA02'.

"IF VBAK-AUART EQ 'YBBR' .
data: lv_flag.

get PARAMETER ID 'MEM' FIELD lv_flag.

    IF LV_FLAG IS NOT INITIAL.

    vbuk-CMGST = 'B'.
    VBUK-CMPSB = 'B'.
    CLEAR lv_flag.
    free MEMORY ID 'MEM' .

"ENDIF.
ENDIF.
ENDIF.



ENDENHANCEMENT.
