*&---------------------------------------------------------------------*
*&  Include           Z_QAREJECTION_REPORT_VARI_TOP
*&---------------------------------------------------------------------*

TABLES: MSEG.

TYPES: BEGIN OF TY_LFA1,
        LIFNR TYPE LFA1-LIFNR,
        NAME1 TYPE LFA1-NAME1,
       END OF TY_LFA1.

DATA: WA_LFA1 TYPE TY_LFA1,
      IT_LFA1 TYPE TABLE OF TY_LFA1.

TYPES: BEGIN OF TY_MAKT,
        MATNR TYPE MAKT-MATNR,
        MAKTX TYPE MAKT-MAKTX,
       END OF TY_MAKT.

DATA: WA_MAKT TYPE TY_MAKT,
      IT_MAKT TYPE TABLE OF TY_MAKT.

TYPES: BEGIN OF TY_T001W,
        WERKS TYPE T001W-WERKS,
        NAME1 TYPE T001W-NAME1,
       END OF TY_T001W.

DATA: WA_T001W TYPE TY_T001W,
      IT_T001W TYPE TABLE OF TY_T001W.


TYPES: BEGIN OF TY_MSEG,
         LIFNR TYPE MSEG-LIFNR,
         MATNR TYPE MSEG-MATNR,
         WERKS TYPE MSEG-WERKS,
         BWART TYPE MSEG-BWART,
         GRUND TYPE MSEG-GRUND ,
         MBLNR TYPE MSEG-MBLNR,
         ZEILE TYPE MSEG-ZEILE,
         MJAHR TYPE MSEG-MJAHR,
         BUDAT TYPE MSEG-BUDAT_MKPF,
         EBELN TYPE MSEG-EBELN,
         EBELP TYPE MSEG-EBELP,
         CHARG TYPE MSEG-CHARG,
         MENGE TYPE MSEG-MENGE,
         MEINS TYPE MSEG-MEINS,
         TCODE TYPE MSEG-TCODE2_MKPF,
       END OF TY_MSEG.


DATA: WA_MSEG TYPE TY_MSEG,
      IT_MSEG TYPE TABLE OF TY_MSEG,
      WA_MSEG1 TYPE TY_MSEG,
      IT_MSEG1 TYPE TABLE OF TY_MSEG.


TYPES: BEGIN OF TY_FINAL,
         LIFNR TYPE MSEG-LIFNR,
         NAME  TYPE LFA1-NAME1,
         MATNR TYPE MSEG-MATNR,
         MAKTX TYPE MAKT-MAKTX,
         WERKS TYPE MSEG-WERKS,
         NAME1 TYPE T001W-NAME1,
         BWART TYPE MSEG-BWART,
         GRUND TYPE MSEG-GRUND,
         MBLNR TYPE MSEG-MBLNR,
         MJAHR TYPE MSEG-MJAHR,
         BUDAT TYPE MSEG-BUDAT_MKPF,
         EBELN TYPE MSEG-EBELN,
         EBELP TYPE MSEG-EBELP,
         PRUEFLOS TYPE QAMB-PRUEFLOS,
         CHARG TYPE MSEG-CHARG,
         LICHA TYPE MCH1-LICHA,
         XBLNR TYPE MKPF-XBLNR,
         MENGE TYPE MSEG-MENGE,
         MEINS TYPE MSEG-MEINS,
         MENGE1 TYPE MSEG-MENGE,
         MEINS1 TYPE MSEG-MEINS,
         GRTXT TYPE  T157E-GRTXT,
         CATEG  TYPE CHAR30,
       END OF TY_FINAL.

DATA: WA_FINAL TYPE TY_FINAL,
     IT_FINAL TYPE TABLE OF TY_FINAL.


TYPES : BEGIN OF TY_T157E,
        BWART TYPE T157E-BWART,
        GRUND TYPE T157E-GRUND,
        GRTXT TYPE T157E-GRTXT,
      END OF TY_T157E.

DATA: WA_T157E TYPE TY_T157E,
     IT_T157E TYPE TABLE OF TY_T157E.

TYPES: BEGIN OF TY_QAMB,
        PRUEFLOS TYPE QAMB-PRUEFLOS,
        MBLNR TYPE QAMB-MBLNR,
        MJAHR TYPE QAMB-MJAHR,
        ZEILE TYPE QAMB-ZEILE,
       END OF TY_QAMB.

DATA: WA_QAMB1 TYPE TY_QAMB,
      WA_QAMB2 TYPE TY_QAMB,
      IT_QAMB1 TYPE TABLE OF TY_QAMB,
      IT_QAMB2 TYPE TABLE OF TY_QAMB.


TYPES: BEGIN OF TY_NEW,
        MENGE TYPE MSEG-MENGE,
        MEINS TYPE MSEG-MEINS,
       END OF TY_NEW.

DATA: WA_NEW TYPE TY_NEW,
      IT_NEW TYPE TABLE OF TY_NEW.

TYPES: BEGIN OF TY_MCH1,
        LIFNR TYPE MCH1-LIFNR,
        MATNR TYPE MCH1-MATNR,
        CHARG TYPE MCH1-CHARG,
        LICHA TYPE MCH1-LICHA,
      END OF TY_MCH1.

DATA : WA_MCH1 TYPE TY_MCH1,
      IT_MCH1 TYPE TABLE OF TY_MCH1.

TYPES: BEGIN OF TY_MKPF,
        MBLNR TYPE MKPF-MBLNR,
        MJAHR TYPE MKPF-MJAHR,
        XBLNR TYPE MKPF-XBLNR,
      END OF TY_MKPF.

DATA: WA_MKPF TYPE TY_MKPF,
      IT_MKPF TYPE TABLE OF TY_MKPF.


TYPES: BEGIN OF TY_QMEL,
        PRUEFLOS TYPE QMEL-PRUEFLOS,
      END OF TY_QMEL.

DATA: WA_QMEL TYPE TY_QMEL,
      IT_QMEL TYPE TABLE OF TY_QMEL.

*****************************GRID DISPLAY*************************************

DATA: IT_FCAT TYPE SLIS_T_FIELDCAT_ALV,
      WA_FCAT TYPE SLIS_FIELDCAT_ALV,
      LAYOUT TYPE SLIS_LAYOUT_ALV,
      IT_LISTHEADER TYPE SLIS_T_LISTHEADER,
      WA_LISTHEADER TYPE SLIS_LISTHEADER,
      IT_EVENT TYPE SLIS_T_EVENT,
      WA_EVENT TYPE SLIS_ALV_EVENT.

******************************************************************************
