*&---------------------------------------------------------------------*
*&  Include           ZZ_TEST_BAPI_CREATE_TOP
*&---------------------------------------------------------------------*
* Data declarations.

TABLES: ymard_nsap.


DATA: V_VBELN            LIKE VBAK-VBELN.
DATA: HEADER             LIKE BAPISDHD1 .""bapisdhead1.
DATA: HEADERX            LIKE BAPISDHD1X .""bapisdhead1x.
DATA: ITEM               LIKE BAPISDITM  OCCURS 0 WITH HEADER LINE.
DATA: ITEMX              LIKE BAPISDITMX OCCURS 0 WITH HEADER LINE.
DATA: PARTNER            LIKE BAPIPARNR  OCCURS 0 WITH HEADER LINE.
DATA: RETURN             LIKE BAPIRET2    OCCURS 0 WITH HEADER LINE.
DATA: RETURN1             LIKE BAPIRET2    OCCURS 0 WITH HEADER LINE.
DATA: LT_SCHEDULES_INX   TYPE STANDARD TABLE OF BAPISCHDLX
                         WITH HEADER LINE.
DATA: LT_SCHEDULES_IN    TYPE STANDARD TABLE OF BAPISCHDL
                         WITH HEADER LINE.
DATA : CONDITION         LIKE BAPICOND  OCCURS 0 WITH HEADER LINE. "bapi condition
DATA : CONDITIONX        LIKE BAPICONDX OCCURS 0 WITH HEADER LINE. "bapi condition

TYPES : BEGIN OF TY_VBFA,
    VBELV TYPE VBFA-VBELV,
    POSNV TYPE VBFA-POSNV,
    VBELN TYPE VBFA-VBELN,
    POSNN TYPE VBFA-POSNN,
    VBTYP_N TYPE VBFA-VBTYP_N,
    END OF TY_VBFA.

DATA  : IT_VBFA TYPE TABLE OF TY_VBFA,
      WA_VBFA TYPE TY_VBFA.

TYPES : BEGIN OF TY_VBRK,
    VBELN TYPE VBRK-VBELN,
    FKART TYPE VBRK-FKART,
    FKDAT TYPE VBRK-FKDAT,
    FKSTO TYPE VBRK-FKSTO,
    DATE_OF_DELIVERY TYPE VBRK-DATE_OF_DELIVERY,
    REMARKS TYPE VBRK-REMARKS,
    END OF TY_VBRK.

DATA  : IT_VBRK TYPE TABLE OF TY_VBRK,
        WA_VBRK TYPE TY_VBRK.


TYPES : BEGIN OF ST_YMARD_NSAP.
        INCLUDE STRUCTURE YMARD_NSAP.
TYPES : END OF ST_YMARD_NSAP.

TYPES : BEGIN OF ST_ZCUSTMAT_ROL,
         KUNNR TYPE ZCUSTMAT_ROL-KUNNR,
         MATNR TYPE ZCUSTMAT_ROL-MATNR,
         NEW_VAL TYPE ZCUSTMAT_ROL-NEW_VAL,
        END OF ST_ZCUSTMAT_ROL.

TYPES : BEGIN OF ST_MARA,
          MATNR TYPE MARA-MATNR,
          SPART TYPE MARA-SPART,
          ZTERM TYPE MARA-ZTERM,
       END OF ST_MARA.

TYPES : BEGIN OF ST_MARA_LK,
          MATNR TYPE MARA-MATNR,
        END OF ST_MARA_LK.

TYPES : BEGIN OF ST_KUNNR_LK,
          kunnr TYPE kna1-kunnr,
        END OF ST_KUNNR_LK.

TYPES : BEGIN OF ST_KNVV,
           KUNNR TYPE KNVV-KUNNR,
           VKORG TYPE KNVV-VKORG,
           VTWEG TYPE KNVV-VTWEG,
           SPART TYPE KNVV-SPART,
           VKBUR TYPE KNVV-VKBUR,
        END OF ST_KNVV.

TYPES : BEGIN OF ST_VBBE,
         VBELN TYPE VBBE-VBELN,
         POSNR TYPE VBBE-POSNR,
         MATNR TYPE VBBE-MATNR,
         WERKS TYPE VBBE-WERKS,
         OMENG TYPE VBBE-OMENG,
         KUNNR TYPE VBBE-KUNNR,
         TOT_OPEN TYPE VBBE-OMENG,
       END OF ST_VBBE.

TYPES : BEGIN OF ST_VBUK,
         VBELN TYPE VBUK-VBELN,
         LFGSK TYPE vbuk-LFGSK,
         VBTYP type vbuk-VBTYP,
       END OF ST_VBUK.


TYPES : BEGIN OF ST_VBAK,
          VBELN TYPE VBAK-VBELN,
          KUNNR TYPE VBAK-KUNNR,
       END OF ST_VBAK.

TYPES : BEGIN OF ST_VBAP,
             VBELN TYPE VBAP-VBELN,
             POSNR TYPE VBAP-POSNR,
             MATNR TYPE VBAP-MATNR,
             SPART TYPE VBAP-SPART,
             KWMENG TYPE VBAP-KWMENG,
             WERKS TYPE VBAP-WERKS,
             ERDAT TYPE VBAP-ERDAT,
         END OF ST_VBAP.

TYPES : BEGIN OF ST_VBRP,
    VBELN TYPE VBRP-VBELN,
    POSNR TYPE VBRP-POSNR,
    FKIMG TYPE VBRP-FKIMG,
    NETWR TYPE VBRP-NETWR,
    AUBEL TYPE VBRP-AUBEL,
    AUPOS TYPE VBRP-AUPOS,
    END OF ST_VBRP.

TYPES : BEGIN OF ST_OPEN,
         VBELN TYPE VBAK-VBELN,
         KUNNR TYPE VBAK-KUNNR,
         POSNR TYPE VBAP-POSNR,
         MATNR TYPE VBAP-MATNR,
         SPART TYPE VBAP-SPART,
         KWMENG TYPE VBAP-KWMENG,
         WERKS TYPE VBAP-WERKS,
         TOT_OPEN TYPE VBBE-OMENG,
         Aft_par TYPE vbap-KWMENG,
        END OF ST_OPEN.

TYPES : BEGIN OF ST_KNVP,
           KUNNR TYPE KNVP-KUNNR,
           VKORG TYPE KNVP-VKORG,
           VTWEG TYPE KNVP-VTWEG,
           SPART TYPE KNVP-SPART,
           PARVW TYPE KNVP-PARVW,
           KUNN2 TYPE KNVP-KUNN2,
           PERNR TYPE KNVP-PERNR,
        END OF ST_KNVP.

TYPES : BEGIN OF ST1_FINAL,
         KUNNR TYPE YMARD_NSAP-KUNNR,
         MATNR TYPE YMARD_NSAP-MATNR,
         ERDAT TYPE YMARD_NSAP-ERDAT,
         ERZET TYPE YMARD_NSAP-ERZET,
         MEINS TYPE YMARD_NSAP-MEINS,
         LABST TYPE YMARD_NSAP-LABST,
         TRAME TYPE YMARD_NSAP-TRAME,
         TOT_STK TYPE YMARD_NSAP-LABST,
         PEN_ORD TYPE YMARD_NSAP-LABST,
         AFT_ROL TYPE YMARD_NSAP-LABST,
         AFT_OPEN TYPE YMARD_NSAP-LABST,
         M_SPART TYPE MARA-SPART,
         ZTERM TYPE MARA-ZTERM,
         C_CHE TYPE KNVV-VTWEG,
         C_SPART TYPE KNVV-SPART,
         SA_ORG TYPE KNVV-VKORG,
         SP_PAR TYPE KNVP-KUNN2,
         BP_PAR TYPE KNVP-KUNN2,
         PY_PAR TYPE KNVP-KUNN2,
         SH_PAR TYPE KNVP-KUNN2,
         SO_NO TYPE KNVP-PERNR,
         ASM_NO TYPE KNVP-PERNR,
         RSM_NO TYPE KNVP-PERNR,
         NSM_NO TYPE KNVP-PERNR,
         BR_NO TYPE KNVP-PERNR,
         VKBUR TYPE KNVV-VKBUR,
         IT_NO TYPE VBAP-POSNR,
      END OF ST1_FINAL.

DATA : I_YMARD TYPE TABLE OF ST_YMARD_NSAP,
       W_YMARD TYPE ST_YMARD_NSAP.

DATA : I1_YMARD TYPE TABLE OF ST_YMARD_NSAP,
       W1_YMARD TYPE ST_YMARD_NSAP.

DATA : I2_YMARD TYPE TABLE OF ST_YMARD_NSAP,
       W2_YMARD TYPE ST_YMARD_NSAP.

DATA : I1_MARA TYPE TABLE OF ST_MARA,
       W1_MARA TYPE ST_MARA.

DATA : I2_MARA TYPE TABLE OF ST_MARA,
       W2_MARA TYPE ST_MARA.

DATA : GT_MARA TYPE TABLE OF ST_MARA_LK,
       GS_MARA TYPE ST_MARA_LK.

DATA : GT_KUNNR TYPE TABLE OF ST_KUNNR_LK,
       GS_KUNNR TYPE ST_KUNNR_LK.

DATA : I1_KNVV TYPE TABLE OF ST_KNVV,
       W1_KNVV TYPE ST_KNVV.

DATA : I_ROL TYPE TABLE OF ST_ZCUSTMAT_ROL,
       W_ROL TYPE ST_ZCUSTMAT_ROL.

DATA : I1_ROL TYPE TABLE OF ST_ZCUSTMAT_ROL,
       W1_ROL TYPE ST_ZCUSTMAT_ROL.

DATA : I1_FINAL TYPE TABLE OF ST1_FINAL,
       W1_FINAL TYPE ST1_FINAL.

DATA : IR_FINAL TYPE TABLE OF ST1_FINAL,
       WR_FINAL TYPE ST1_FINAL.

DATA : I2_FINAL TYPE TABLE OF ST1_FINAL,
       W2_FINAL TYPE ST1_FINAL.

DATA : I3_FINAL TYPE TABLE OF ST1_FINAL,
       W3_FINAL TYPE ST1_FINAL.

*DATA : I1_VBBE TYPE TABLE OF ST_VBBE,
*       W1_VBBE TYPE ST_VBBE.
*
*DATA : I2_VBBE TYPE TABLE OF ST_VBBE,
*       W2_VBBE TYPE ST_VBBE.

DATA : I_VBUK TYPE TABLE OF ST_VBUK,
       W_VBUK TYPE ST_VBUK.

DATA : I_VBAK TYPE TABLE OF ST_VBAK,
       W_VBAK TYPE ST_VBAK.

DATA : I_VBAP TYPE TABLE OF ST_VBAP,
       W_VBAP TYPE ST_VBAP.

DATA  : I_VBRP TYPE TABLE OF ST_VBRP,
        W_VBRP TYPE ST_VBRP.

DATA : I_OPEN TYPE TABLE OF ST_OPEN,
       W_OPEN TYPE ST_OPEN.

DATA : I1_OPEN TYPE TABLE OF ST_OPEN,
       W1_OPEN TYPE ST_OPEN.

DATA : I1_KNVP TYPE TABLE OF ST_KNVP,
       W1_KNVP TYPE ST_KNVP.

DATA : GV_PRICE_OK TYPE C .

DATA : ITEM_NO TYPE VBAP-POSNR.


DATA : I_COUNT(10) TYPE N .

DATA : W_COUNT(10) TYPE N .

*DATA : SY_DATE TYPE SY-DATUM .
*DATA : CUR_DATE TYPE SY-DATUM.
*DATA : CUR1_DATE TYPE SY-DATUM.
