FUNCTION ZBAPI_VENDOR_PORTAL_ACC.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(OBJID) TYPE  CHAR10
*"     VALUE(BUKRS) TYPE  BUKRS
*"     VALUE(DATE_FRM) TYPE  BUDAT
*"     VALUE(DATE_TO) TYPE  BUDAT
*"  TABLES
*"      IT_VENDOR_BSIK STRUCTURE  BSIK
*"      IT_VENDOR_BSAK STRUCTURE  BSAK
*"----------------------------------------------------------------------

  TRANSLATE OBJID TO UPPER CASE.

  IF OBJID = 'ZLVR_BSIK'.

    DATA: IT_BSIK TYPE STANDARD TABLE OF BSIK,
        WA_VENDOR_BSIK TYPE BSIK,
        WA_BSIK TYPE BSIK.


SELECT * INTO TABLE IT_BSIK FROM BSIK WHERE BUDAT GE DATE_FRM AND BUDAT LE DATE_TO.

    IF IT_BSIK IS NOT INITIAL.
      LOOP AT IT_BSIK INTO WA_BSIK.
        MOVE-CORRESPONDING WA_BSIK TO WA_VENDOR_BSIK.
        APPEND WA_VENDOR_BSIK TO  IT_VENDOR_BSIK.
        CLEAR:WA_BSIK,WA_VENDOR_BSIK.

      ENDLOOP.
    ENDIF.

  ELSEIF OBJID = 'ZLVR_BSAK'.

    DATA: IT_BSAK TYPE STANDARD TABLE OF BSAK,
             WA_VENDOR_BSAK TYPE BSAK,
             WA_BSAK TYPE BSAK.

      SELECT * INTO TABLE IT_BSAK FROM BSAK WHERE BUDAT GE DATE_FRM AND BUDAT LE DATE_TO.

      IF  IT_BSAK IS NOT INITIAL.
        LOOP AT IT_BSAK INTO WA_BSAK.
          MOVE-CORRESPONDING WA_BSAK to WA_VENDOR_BSAK.
          APPEND WA_VENDOR_BSAK to IT_VENDOR_BSAK.
          CLEAR: WA_BSAK,WA_VENDOR_BSAK.

        ENDLOOP.
      ENDIF.


  ENDIF.




ENDFUNCTION.
