class ZCL_IM_MM_STO_ALLOW definition
  public
  final
  create public .

public section.

  interfaces IF_EX_ME_PO_PRICING_CUST .
protected section.
private section.
ENDCLASS.



CLASS ZCL_IM_MM_STO_ALLOW IMPLEMENTATION.


method IF_EX_ME_PO_PRICING_CUST~PROCESS_KOMK.
endmethod.


method IF_EX_ME_PO_PRICING_CUST~PROCESS_KOMP.

*  IF SY-TCODE EQ 'ME21N' OR SY-TCODE EQ 'ME22N' OR SY-TCODE EQ 'ME23N'.
*     IF SY-UCOMM EQ 'MESAVE' and im_ekpo-LOEKZ NE 'L'.
*  DATA : LV1_MAT TYPE ZPLANT_MAT_AGE-MATERIAL .
*  DATA : LV_FLAG TYPE ZPLANT_MAT_AGE-FLAG.
*  SELECT SINGLE MATERIAL INTO LV1_MAT FROM ZPLANT_MAT_AGE WHERE MATERIAL = IM_EKPO-MATNR.
*  IF LV1_MAT IS NOT INITIAL.
*    SELECT SINGLE FLAG INTO LV_FLAG FROM ZPLANT_MAT_AGE WHERE PLANT = IM_EKPO-WERKS AND MATERIAL = IM_EKPO-MATNR .
*    IF LV_FLAG EQ 'Y' OR LV_FLAG EQ ' '  .
*      IF LV_FLAG EQ 'Y' .
*     UPDATE ZPLANT_MAT_AGE SET FLAG = 'N' WHERE PLANT = IM_EKPO-WERKS AND MATERIAL = IM_EKPO-MATNR.
*     ENDIF.
*    ELSE.
*     MESSAGE 'Material stock age exceeds more than allowed days' TYPE 'E'.
*    ENDIF.
*  ENDIF.
*  CLEAR : LV1_MAT,LV_FLAG.
*  "ENDIF.
*  ENDIF.
*ENDIF.

  IF SY-TCODE EQ 'ME21N' OR SY-TCODE EQ 'ME22N' .

  IF IM_EKKO-BUKRS = '1000' .
    DATA:LV_MAT TYPE MARA-MATNR.

    SELECT SINGLE MATERIAL FROM ZMM_MAT_BLOCK INTO LV_MAT WHERE MATERIAL = IM_EKPO-MATNR.
      IF LV_MAT IS NOT INITIAL.

      IF IM_EKPO-PSTYP EQ '0' OR 'IM_EKPO-PSTYP ' EQ ''.

MESSAGE E001(ZMB).
LEAVE TO CURRENT TRANSACTION.

ENDIF.
ENDIF.
ENDIF.
ENDIF.


endmethod.
ENDCLASS.
