class ZCL_IM_BADI_FOR_EXCISES definition
  public
  final
  create public .

public section.

  interfaces IF_EX_MB_CHECK_LINE_BADI .
protected section.
private section.
ENDCLASS.



CLASS ZCL_IM_BADI_FOR_EXCISES IMPLEMENTATION.


METHOD IF_EX_MB_CHECK_LINE_BADI~CHECK_LINE.
*  Requirment given by:Umapathy.N
*  Developer:Savariar.s
*  Date:09.06.2015
 "BREAK-POINT.
  IF SY-TCODE = 'MIGO'.
  DATA:MSG(200) TYPE C.
  DATA : LV_PO TYPE J_1IEXCDTL-RDOC1."(PO No )
  DATA : LV_GR TYPE J_1IEXCDTL-MENGA ."(GR Qty )
  DATA : LV_STATUS TYPE J_1IEXCDTL-STATUS."Status
  DATA : LV_EXCISNO TYPE J_1IEXCDTL-RDOC2." 101 material document no*

  DATA : GT_J_1IEXCDTL TYPE TABLE OF J_1IEXCDTL,
         WA_J_1IEXCDTL TYPE J_1IEXCDTL.

  IF IS_MKPF-BLART EQ 'ZNB' OR IS_MKPF-BLART EQ 'ZIM'.

  IF IS_MSEG-EBELN IS NOT INITIAL.

    SELECT * FROM J_1IEXCDTL INTO TABLE GT_J_1IEXCDTL WHERE RDOC1  = IS_MSEG-EBELN.
  ENDIF.
*IF IS_MKPF-BUDAT GT '01.06.2015'.
   IF IS_MKPF-BUDAT GT '01.06.2015' .
LOOP AT GT_J_1IEXCDTL INTO WA_J_1IEXCDTL.

  LV_GR = WA_J_1IEXCDTL-MENGA.
  LV_PO = WA_J_1IEXCDTL-RDOC1.
  LV_STATUS = WA_J_1IEXCDTL-STATUS.
  LV_EXCISNO = WA_J_1IEXCDTL-RDOC2.


IF LV_PO EQ IS_MSEG-EBELN AND LV_GR EQ 0 AND LV_STATUS EQ ' '.

  CONCATENATE 'Excise Already In-Process condition for this 101 Mat.Doc No ' LV_EXCISNO INTO MSG SEPARATED BY SPACE.
  MESSAGE MSG TYPE 'E' DISPLAY LIKE 'I'.
  LEAVE TO CURRENT TRANSACTION. "#EC CI_NOORDER " Added by <IT-CAR Tool> during Code Remediation
 ENDIF.
ENDLOOP.
ENDIF.
ENDIF.
ENDIF.
ENDMETHOD.
ENDCLASS.
