class ZCL_IM_LE_TRANSIT_BADI definition
  public
  final
  create public .

public section.

  interfaces IF_BADI_INTERFACE .
  interfaces IF_EX_LE_SHP_GOODSMOVEMENT .
protected section.
private section.
ENDCLASS.



CLASS ZCL_IM_LE_TRANSIT_BADI IMPLEMENTATION.


method IF_EX_LE_SHP_GOODSMOVEMENT~CHANGE_INPUT_HEADER_AND_ITEMS.

  IF SY-TCODE EQ 'VL02' OR SY-TCODE EQ 'VL02N' OR SY-TCODE EQ 'VL01' OR SY-TCODE EQ 'VL01N' OR SY-TCODE EQ 'VL10B' .

DATA : LV_STATUS TYPE ZTRAM_LOG_TABLE-STATUS,
       LV_STATUS1 TYPE ZTRAM_LOG_TABLE-STATUS1.


DATA : MSG(400).


SELECT SINGLE STATUS INTO LV_STATUS FROM ZTRAM_LOG_TABLE WHERE WERKS = IS_LIKP-VSTEL .

SELECT SINGLE STATUS1 INTO LV_STATUS1 FROM ZTRAM_LOG_TABLE WHERE WERKS = IS_LIKP-VSTEL .

 IF LV_STATUS EQ 'NO'  .
*
*
     IF LV_STATUS1 NE 'YES' .


"IF VBAK-VKBUR EQ '4127' .

 CONCATENATE IS_LIKP-VSTEL 'IS MAXIMUM TRANSIT DAYS' INTO MSG SEPARATED BY SPACE .
MESSAGE MSG TYPE 'E' DISPLAY LIKE 'E' .
*
*SKIP TCODE .
*

ENDIF.
  ENDIF.


    ENDIF.
endmethod.
ENDCLASS.
