"Name: \PR:SAPMV60A\FO:CUST_ITEM_ACTIVATE\SE:BEGIN\EI
ENHANCEMENT 0 ZEXPORT_ITEM.
*
  "ADDED BY RAM ON 9/8/16
    LOOP AT SCREEN .  "ADDED BY RAM ON 21/9/2015
    IF SCREEN-NAME EQ 'TABSTRIP_TAB07' .
      GS_CUST_TAB-ITEM_CAPTION = 'Export Items' .
      GS_CUST_TAB-ITEM_PROGRAM = 'ZBILLITEM' .
      GS_CUST_TAB-ITEM_DYNPRO = '0001' .
        IF NOT GS_CUST_TAB-ITEM_DYNPRO IS INITIAL .
          SCREEN-ACTIVE = 1 .
          SCREEN-INVISIBLE = 0 .
          MODIFY SCREEN.
          TABSTRIP_TAB07 = GS_CUST_TAB-ITEM_CAPTION .
        ENDIF.
      ENDIF.
   ENDLOOP .
  "ENDED BY RAM ON 9/8/16

ENDENHANCEMENT.
