"Name: \PR:SAPMV60A\FO:CUST_HEAD_ACTIVATE\SE:BEGIN\EI
ENHANCEMENT 0 ZEXPORT_HEADER.
*
  "ADDED BY RAM ON 8/9/16

  LOOP AT SCREEN.
  IF SCREEN-NAME EQ 'TABSTRIP_TAB06'.
    GS_CUST_TAB-HEAD_CAPTION = 'Export Header'.
  GS_CUST_TAB-HEAD_PROGRAM = 'ZBILLHEADER'.
  GS_CUST_TAB-HEAD_DYNPRO = '0001'.

  IF NOT GS_CUST_TAB-HEAD_DYNPRO IS INITIAL.
    SCREEN-ACTIVE = 1.
    SCREEN-INVISIBLE = 0.
    MODIFY SCREEN.
        TABSTRIP_TAB06 = GS_CUST_TAB-HEAD_CAPTION.
    ENDIF.
    ENDIF.

    ENDLOOP.

  "ENDED BY RAM ON 9/8/16


ENDENHANCEMENT.
