FUNCTION ZBAPI_GET_INVOICE_JNPL .
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(P_BUKRS) TYPE  TVKO-BUKRS
*"     VALUE(P_KUNNR) TYPE  KNA1-KUNNR OPTIONAL
*"     VALUE(P_CANCEL) TYPE  FLAG OPTIONAL
*"     VALUE(P_SALESRET) TYPE  FLAG OPTIONAL
*"  TABLES
*"      S_DATE STRUCTURE  ZSTR_SKU_DATE OPTIONAL
*"      S_TIME STRUCTURE  ZSTR_SKU_TIME OPTIONAL
*"      IT_INVOICE_LIST_VBRK STRUCTURE  ZSTR_SKU_VBRK_LIST1_JNPL
*"       OPTIONAL
*"      IT_INVOICE_LIST_VBRP STRUCTURE  ZSTR_SKU_VBRP_LIST1_JNPL
*"       OPTIONAL
*"      IT_CONDITION_LIST_KONV STRUCTURE  ZSTR_SKU_KONV_LIST1_JNPL
*"       OPTIONAL
*"----------------------------------------------------------------------

*&----------------------------------------------------------------------------------------------------------
*&----------------------------------------------------------------------------------------------------------
*&    AUTHOR          : Govindarajan M
*&    CREATED ON      : 07.07.2015
*&    OBJECTIVE       : THIS FUNCTION MODULE CAN BE USED TO GET INVOICE LIST FOR A GIVEN INPUT
*&----------------------------------------------------------------------------------------------------------
*&----------------------------------------------------------------------------------------------------------

  TYPES:  BEGIN OF GTY_VBRK,
            VBELN TYPE VBRK-VBELN,
            FKART TYPE VBRK-FKART,
            KNUMV TYPE VBRK-KNUMV ,
            FKDAT TYPE VBRK-FKDAT,
            KDGRP TYPE VBRK-KDGRP,
            INCO2 type vbrk-INCO2,
            BUKRS TYPE VBRK-BUKRS,
            NETWR TYPE VBRK-NETWR,
            ERNAM TYPE VBRK-ERNAM,
            ERZET TYPE VBRK-ERZET,
            ERDAT TYPE VBRK-ERDAT,
            GJAHR TYPE VBRK-GJAHR,
            KUNRG TYPE VBRK-KUNRG,
            KUNAG TYPE VBRK-KUNAG,
            MWSBK TYPE VBRK-MWSBK ,
            FKSTO TYPE VBRK-FKSTO,
            AEDAT TYPE VBRK-AEDAT,
          END OF GTY_VBRK,

          BEGIN OF GTY_VBRP,
            VBELN TYPE VBRK-VBELN,
        "    KNUMV TYPE VBRK-KNUMV ,  "ADDED BY RAM ON 8/7/2015
            POSNR TYPE VBRP-POSNR,
            FKIMG TYPE VBRP-FKIMG,
            VRKME TYPE VBRP-VRKME,
            BRGEW TYPE VBRP-BRGEW,
            GEWEI TYPE VBRP-GEWEI,
            VOLUM TYPE VBRP-VOLUM,
            VOLEH TYPE VBRP-VOLEH,
            NETWR TYPE VBRP-NETWR,
            VGBEL TYPE VBRP-VGBEL,
            VGPOS TYPE VBRP-VGPOS,
            VGTYP TYPE VBRP-VGTYP,
            AUBEL TYPE VBRP-AUBEL,
            AUPOS TYPE VBRP-AUPOS,
            MATNR TYPE VBRP-MATNR,
            MWSBP TYPE VBRP-MWSBP,
            ARKTX TYPE VBRP-ARKTX,
            CHARG TYPE VBRP-CHARG,
            WERKS TYPE VBRP-WERKS,
            LGORT TYPE VBRP-LGORT,
          END OF GTY_VBRP,

          BEGIN OF GTY_KNVP,
          KUNNR TYPE KNVP-KUNNR,
          VKORG TYPE KNVP-VKORG,
          VTWEG TYPE KNVP-VTWEG,
          SPART TYPE KNVP-SPART,
          PARVW TYPE KNVP-PARVW,
          PERNR TYPE KNVP-PERNR,
          END OF GTY_KNVP,

         BEGIN OF GTY_VBRP1,
          VBELN TYPE VBRP-VBELN,
          WERKS TYPE VBRP-WERKS,
         END OF GTY_VBRP1,

          BEGIN OF GTY_KONV,
          KNUMV TYPE KONV-KNUMV,
          KPOSN TYPE KONV-KPOSN,
          KAPPL TYPE KONV-KAPPL,
          KSCHL TYPE KONV-KSCHL,
**          KDATU TYPE KONV-KDATU,  "CR Activity
          KBETR TYPE KONV-KBETR,
          WAERS TYPE KONV-WAERS,
          KWERT TYPE KONV-KWERT,
          END OF GTY_KONV .

TYPES : BEGIN OF GS_LIPS,
           VBELN TYPE LIPS-VBELN,
           POSNR TYPE LIPS-POSNR,
           MATNR TYPE LIPS-MATNR,
           CHARG TYPE LIPS-CHARG,
           LFIMG TYPE LIPS-LFIMG,
        END OF GS_LIPS.

  DATA: GT_VBRK TYPE STANDARD TABLE OF GTY_VBRK,
        GS_VBRK TYPE                     GTY_VBRK,
        GT_VBRP TYPE STANDARD TABLE OF GTY_VBRP,
        GS_VBRP TYPE                     GTY_VBRP,
        GT_KNVP TYPE STANDARD TABLE OF GTY_KNVP,
        GS_KNVP TYPE                     GTY_KNVP,
        GT_VBRP1 TYPE STANDARD TABLE OF GTY_VBRP1,
        GS_VBRP1 TYPE                     GTY_VBRP1,
        GT_KONV TYPE STANDARD TABLE OF GTY_KONV,
        GS_KONV TYPE                     GTY_KONV,
        GT_KONV1 TYPE STANDARD TABLE OF GTY_KONV,
        GS_KONV1 TYPE                     GTY_KONV,
        GS_INVOICE_LIST_VBRK LIKE IT_INVOICE_LIST_VBRK,
        GS_INVOICE_LIST_VBRP LIKE IT_INVOICE_LIST_VBRP ,
        GS_INVOICE_LIST_KONV LIKE IT_CONDITION_LIST_KONV .

DATA : WA_INVOICE_LIST_VBRK LIKE IT_INVOICE_LIST_VBRK .

DATA : WA_INVOICE_LIST_VBRP LIKE IT_INVOICE_LIST_VBRP .

DATA : WA_INVOICE_LIST_KONV TYPE ZSTR_SKU_KONV_LIST1_JNPL .

  DATA : GT_LIPS TYPE TABLE OF gs_lips,
         wa_lips type gs_lips.


  IF P_CANCEL <> 'X' AND P_SALESRET <> 'X'. " Added By Govind On 10-06-2015 for Cancel Invoice Split
    SELECT VBELN "#EC CI_DB_OPERATION_OK[2768887] " Added by <IT-CAR Tool> during Code Remediation
           FKART
           KNUMV
           FKDAT
           KDGRP
           INCO2
           BUKRS
           NETWR
           ERNAM
           ERZET
           ERDAT
           GJAHR
           KUNRG
           KUNAG
           MWSBK
           FKSTO
           AEDAT
      INTO TABLE GT_VBRK
      FROM VBRK
      WHERE BUKRS = P_BUKRS
      AND   FKART = 'YBBR'
      AND  ( KDGRP = '09' OR KDGRP = '02')
      AND   ERDAT IN S_DATE
     AND   ERZET IN S_TIME.

  ENDIF.

  IF P_CANCEL = 'X'. " Added By Govind On 10-06-2015 for Cancel Invoice Split
    SELECT VBELN "#EC CI_DB_OPERATION_OK[2768887] " Added by <IT-CAR Tool> during Code Remediation
        FKART
        KNUMV
        FKDAT
        KDGRP
        INCO2
        BUKRS
        NETWR
        ERNAM
        ERZET
        ERDAT
        GJAHR
        KUNRG
        KUNAG
        MWSBK
        FKSTO
        AEDAT
   INTO TABLE GT_VBRK
   FROM VBRK
   WHERE BUKRS = P_BUKRS
   AND   FKART = 'YBBR'
   AND   ( KDGRP = '09' OR KDGRP = '02')
   AND FKSTO = 'X'
   AND   AEDAT IN S_DATE
  AND   ERZET IN S_TIME .

  ENDIF.

  IF P_SALESRET = 'X'.
    SELECT VBELN "#EC CI_DB_OPERATION_OK[2768887] " Added by <IT-CAR Tool> during Code Remediation
         FKART
         KNUMV
         FKDAT
         KDGRP
         INCO2
         BUKRS
         NETWR
         ERNAM
         ERZET
         ERDAT
         GJAHR
         KUNRG
         KUNAG
         MWSBK
         FKSTO
         AEDAT
    INTO TABLE GT_VBRK
    FROM VBRK
    WHERE BUKRS = P_BUKRS
    AND   FKART = 'YBRE'
    AND   ( KDGRP = '09' OR KDGRP = '02')
     AND   AEDAT IN S_DATE
   AND   ERZET IN S_TIME .

  ENDIF.

IF GT_VBRK IS NOT INITIAL .

SELECT
      KUNNR
      VKORG
      VTWEG
      SPART
      PARVW
      PERNR FROM KNVP INTO TABLE GT_KNVP FOR ALL ENTRIES IN GT_VBRK WHERE KUNNR = GT_VBRK-KUNRG AND VKORG = GT_VBRK-BUKRS .

  SELECT
    VBELN
    WERKS
      FROM VBRP INTO TABLE GT_VBRP1 FOR ALL ENTRIES IN GT_VBRK WHERE VBELN = GT_VBRK-VBELN AND WERKS GE '4200' .

ENDIF.

  LOOP AT GT_VBRK INTO GS_VBRK.
    GS_INVOICE_LIST_VBRK-VBELN = GS_VBRK-VBELN.
    GS_INVOICE_LIST_VBRK-FKART = GS_VBRK-FKART.
    GS_INVOICE_LIST_VBRK-KNUMV = GS_VBRK-KNUMV .
    GS_INVOICE_LIST_VBRK-FKDAT = GS_VBRK-FKDAT.
    GS_INVOICE_LIST_VBRK-KDGRP = GS_VBRK-KDGRP.
    GS_INVOICE_LIST_VBRK-INCO2 = GS_VBRK-INCO2 .
    GS_INVOICE_LIST_VBRK-NETWR = GS_VBRK-NETWR.
    GS_INVOICE_LIST_VBRK-ERNAM = GS_VBRK-ERNAM.
    GS_INVOICE_LIST_VBRK-ERZET = GS_VBRK-ERZET.
    GS_INVOICE_LIST_VBRK-ERDAT = GS_VBRK-ERDAT.
    GS_INVOICE_LIST_VBRk-GJAHR = GS_VBRK-GJAHR.
    GS_INVOICE_LIST_VBRK-KUNRG = GS_VBRK-KUNRG.
    GS_INVOICE_LIST_VBRK-KUNAG = GS_VBRK-KUNAG.
    GS_INVOICE_LIST_VBRK-MWSBK = GS_VBRK-MWSBK.
    GS_INVOICE_LIST_VBRK-FKSTO = GS_VBRK-FKSTO.

    READ TABLE GT_VBRP1 INTO GS_VBRP1 WITH KEY VBELN = GS_VBRK-VBELN.
    IF SY-SUBRC = 0 .
      GS_INVOICE_LIST_VBRK-WERKS = GS_VBRP1-WERKS.
      ENDIF.

    READ TABLE GT_KNVP INTO GS_KNVP WITH KEY KUNNR = GS_VBRK-KUNRG PARVW = 'L5'.
    IF SY-SUBRC = 0.
      GS_INVOICE_LIST_VBRK-PERNR = GS_KNVP-PERNR.
    ENDIF.
    READ TABLE GT_KNVP INTO GS_KNVP WITH KEY KUNNR = GS_VBRK-KUNRG PARVW = 'L3' .
    IF SY-SUBRC = 0 .
      GS_INVOICE_LIST_VBRK-PERNR1 = GS_KNVP-PERNR .
    ENDIF .

    LOOP AT GT_KONV INTO GS_KONV WHERE KNUMV = GS_VBRK-KNUMV .
      GS_INVOICE_LIST_VBRK-TOTDIS = GS_INVOICE_LIST_VBRK-TOTDIS + GS_KONV-KBETR .
      GS_INVOICE_LIST_KONV-KNUMV = GS_KONV-KNUMV .
    ENDLOOP.

    APPEND GS_INVOICE_LIST_VBRK TO IT_INVOICE_LIST_VBRK.
    CLEAR GS_INVOICE_LIST_VBRK .
  ENDLOOP.

  IF SY-SUBRC = 0.
    IF NOT P_KUNNR IS INITIAL.
      DELETE IT_INVOICE_LIST_VBRK WHERE KUNRG <> P_KUNNR.
    ENDIF.

    CHECK IT_INVOICE_LIST_VBRK[] IS NOT INITIAL.
    SELECT  VBELN
            POSNR
            FKIMG
            VRKME
            BRGEW
            GEWEI
            VOLUM
            VOLEH
            NETWR
            VGBEL
            VGPOS
            VGTYP
            AUBEL
            AUPOS
            MATNR
            MWSBP
            ARKTX
            CHARG
            WERKS
            LGORT
      FROM  VBRP
      INTO TABLE IT_INVOICE_LIST_VBRP
      FOR ALL ENTRIES IN IT_INVOICE_LIST_VBRK
      WHERE VBELN = IT_INVOICE_LIST_VBRK-VBELN AND WERKS GE '4200'.

      SELECT
           VBELN
           POSNR
           MATNR
           CHARG
           LFIMG
        FROM LIPS INTO TABLE GT_LIPS FOR ALL ENTRIES IN IT_INVOICE_LIST_VBRP WHERE VBELN = IT_INVOICE_LIST_VBRP-VGBEL .

       LOOP AT IT_INVOICE_LIST_VBRP INTO WA_INVOICE_LIST_VBRP .

         LOOP AT GT_LIPS INTO WA_LIPS WHERE VBELN = WA_INVOICE_LIST_VBRP-VGBEL AND MATNR = WA_INVOICE_LIST_VBRP-MATNR .

           WA_INVOICE_LIST_VBRP-BATCH = WA_LIPS-CHARG .

MODIFY IT_INVOICE_LIST_VBRP FROM WA_INVOICE_LIST_VBRP  TRANSPORTING BATCH .
CLEAR WA_INVOICE_LIST_VBRP.

           ENDLOOP.

         ENDLOOP.

      SELECT
        KNUMV
        KPOSN
        KAPPL
        KSCHL
        KDATU
        KBETR
        WAERS
        KWERT
      FROM  prcd_elemenTs  ""KONV
      INTO TABLE IT_CONDITION_LIST_KONV
      FOR ALL ENTRIES IN IT_INVOICE_LIST_VBRK
      WHERE KNUMV = IT_INVOICE_LIST_VBRK-KNUMV  .

  ENDIF.

CHECK IT_INVOICE_LIST_VBRK[] IS NOT INITIAL.

LOOP AT IT_CONDITION_LIST_KONV INTO WA_INVOICE_LIST_KONV .

  LOOP AT IT_INVOICE_LIST_VBRK INTO WA_INVOICE_LIST_VBRK WHERE KNUMV = WA_INVOICE_LIST_KONV-KNUMV AND WERKS EQ ' '.

   DELETE IT_CONDITION_LIST_KONV .

  ENDLOOP.

ENDLOOP.

DELETE IT_INVOICE_LIST_VBRK WHERE WERKS EQ ' ' .

IF GT_VBRK IS NOT INITIAL.

  SELECT
    KNUMV
    KPOSN
    KAPPL
    KSCHL
    "KDATU
    KBETR
    WAERS FROM prcd_elemenTs  ""KONV
    INTO TABLE GT_KONV1 FOR ALL ENTRIES IN GT_VBRK WHERE KNUMV = GT_VBRK-KNUMV . " AND ( KSCHL = 'Y004' OR  KSCHL = 'YBSD' OR KSCHL = 'Y007'
ENDIF.



ENDFUNCTION.
