*---------------------------------------------------------------------*
*    view related data declarations
*---------------------------------------------------------------------*
*...processing: ZVALPN_CATEG....................................*
TABLES: ZVALPN_CATEG, *ZVALPN_CATEG. "view work areas
CONTROLS: TCTRL_ZVALPN_CATEG
TYPE TABLEVIEW USING SCREEN '0001'.
DATA: BEGIN OF STATUS_ZVALPN_CATEG. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZVALPN_CATEG.
* Table for entries selected to show on screen
DATA: BEGIN OF ZVALPN_CATEG_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZVALPN_CATEG.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVALPN_CATEG_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZVALPN_CATEG_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZVALPN_CATEG.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVALPN_CATEG_TOTAL.

*...processing: ZVALPN_MATERIAL.................................*
TABLES: ZVALPN_MATERIAL, *ZVALPN_MATERIAL. "view work areas
CONTROLS: TCTRL_ZVALPN_MATERIAL
TYPE TABLEVIEW USING SCREEN '0003'.
DATA: BEGIN OF STATUS_ZVALPN_MATERIAL. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZVALPN_MATERIAL.
* Table for entries selected to show on screen
DATA: BEGIN OF ZVALPN_MATERIAL_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZVALPN_MATERIAL.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVALPN_MATERIAL_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZVALPN_MATERIAL_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZVALPN_MATERIAL.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVALPN_MATERIAL_TOTAL.

*...processing: ZVALPN_SUBCATEG.................................*
TABLES: ZVALPN_SUBCATEG, *ZVALPN_SUBCATEG. "view work areas
CONTROLS: TCTRL_ZVALPN_SUBCATEG
TYPE TABLEVIEW USING SCREEN '0002'.
DATA: BEGIN OF STATUS_ZVALPN_SUBCATEG. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZVALPN_SUBCATEG.
* Table for entries selected to show on screen
DATA: BEGIN OF ZVALPN_SUBCATEG_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZVALPN_SUBCATEG.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVALPN_SUBCATEG_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZVALPN_SUBCATEG_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZVALPN_SUBCATEG.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVALPN_SUBCATEG_TOTAL.

*.........table declarations:.................................*
TABLES: ZALPN_CATEG                    .
TABLES: ZALPN_MATERIAL                 .
TABLES: ZALPN_SUBCATEG                 .
