*---------------------------------------------------------------------*
*    view related data declarations
*---------------------------------------------------------------------*
*...processing: ZAPI_CHK_TABLE..................................*
DATA:  BEGIN OF STATUS_ZAPI_CHK_TABLE                .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_ZAPI_CHK_TABLE                .
CONTROLS: TCTRL_ZAPI_CHK_TABLE
            TYPE TABLEVIEW USING SCREEN '0002'.
*...processing: ZAPI_CHK_TABLE_T................................*
DATA:  BEGIN OF STATUS_ZAPI_CHK_TABLE_T              .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_ZAPI_CHK_TABLE_T              .
CONTROLS: TCTRL_ZAPI_CHK_TABLE_T
            TYPE TABLEVIEW USING SCREEN '0003'.
*...processing: ZAPI_COMMON_LIST................................*
DATA:  BEGIN OF STATUS_ZAPI_COMMON_LIST              .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_ZAPI_COMMON_LIST              .
CONTROLS: TCTRL_ZAPI_COMMON_LIST
            TYPE TABLEVIEW USING SCREEN '0001'.
*...processing: ZVCUSTTYPE_EXTNS................................*
TABLES: ZVCUSTTYPE_EXTNS, *ZVCUSTTYPE_EXTNS. "view work areas
CONTROLS: TCTRL_ZVCUSTTYPE_EXTNS
TYPE TABLEVIEW USING SCREEN '0008'.
DATA: BEGIN OF STATUS_ZVCUSTTYPE_EXTNS. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZVCUSTTYPE_EXTNS.
* Table for entries selected to show on screen
DATA: BEGIN OF ZVCUSTTYPE_EXTNS_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZVCUSTTYPE_EXTNS.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVCUSTTYPE_EXTNS_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZVCUSTTYPE_EXTNS_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZVCUSTTYPE_EXTNS.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVCUSTTYPE_EXTNS_TOTAL.

*...processing: ZV_API_CHK_TABLE................................*
TABLES: ZV_API_CHK_TABLE, *ZV_API_CHK_TABLE. "view work areas
CONTROLS: TCTRL_ZV_API_CHK_TABLE
TYPE TABLEVIEW USING SCREEN '0005'.
DATA: BEGIN OF STATUS_ZV_API_CHK_TABLE. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZV_API_CHK_TABLE.
* Table for entries selected to show on screen
DATA: BEGIN OF ZV_API_CHK_TABLE_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZV_API_CHK_TABLE.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZV_API_CHK_TABLE_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZV_API_CHK_TABLE_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZV_API_CHK_TABLE.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZV_API_CHK_TABLE_TOTAL.

*...processing: ZV_API_COMM_LIST................................*
TABLES: ZV_API_COMM_LIST, *ZV_API_COMM_LIST. "view work areas
CONTROLS: TCTRL_ZV_API_COMM_LIST
TYPE TABLEVIEW USING SCREEN '0004'.
DATA: BEGIN OF STATUS_ZV_API_COMM_LIST. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZV_API_COMM_LIST.
* Table for entries selected to show on screen
DATA: BEGIN OF ZV_API_COMM_LIST_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZV_API_COMM_LIST.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZV_API_COMM_LIST_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZV_API_COMM_LIST_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZV_API_COMM_LIST.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZV_API_COMM_LIST_TOTAL.

*...processing: ZV_BP_SOFFICE...................................*
TABLES: ZV_BP_SOFFICE, *ZV_BP_SOFFICE. "view work areas
CONTROLS: TCTRL_ZV_BP_SOFFICE
TYPE TABLEVIEW USING SCREEN '0007'.
DATA: BEGIN OF STATUS_ZV_BP_SOFFICE. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZV_BP_SOFFICE.
* Table for entries selected to show on screen
DATA: BEGIN OF ZV_BP_SOFFICE_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZV_BP_SOFFICE.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZV_BP_SOFFICE_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZV_BP_SOFFICE_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZV_BP_SOFFICE.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZV_BP_SOFFICE_TOTAL.

*...processing: ZV_MAP_TABLE_BP.................................*
TABLES: ZV_MAP_TABLE_BP, *ZV_MAP_TABLE_BP. "view work areas
CONTROLS: TCTRL_ZV_MAP_TABLE_BP
TYPE TABLEVIEW USING SCREEN '0006'.
DATA: BEGIN OF STATUS_ZV_MAP_TABLE_BP. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZV_MAP_TABLE_BP.
* Table for entries selected to show on screen
DATA: BEGIN OF ZV_MAP_TABLE_BP_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZV_MAP_TABLE_BP.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZV_MAP_TABLE_BP_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZV_MAP_TABLE_BP_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZV_MAP_TABLE_BP.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZV_MAP_TABLE_BP_TOTAL.

*.........table declarations:.................................*
TABLES: *ZAPI_CHK_TABLE                .
TABLES: *ZAPI_CHK_TABLE_T              .
TABLES: *ZAPI_COMMON_LIST              .
TABLES: ZAPI_CHK_TABLE                 .
TABLES: ZAPI_CHK_TABLE_T               .
TABLES: ZAPI_COMMON_LIST               .
TABLES: ZBP_SOFFICE_TABL               .
TABLES: ZCUSTTYPE_EXTNSN               .
TABLES: ZMAP_TABLE_BP                  .

* general table data declarations..............
  INCLUDE LSVIMTDT                                .
