FUNCTION ZGET_PENDING_ORDER.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(LV_VKORG) TYPE  VKORG OPTIONAL
*"     VALUE(LV_KUNNR) TYPE  KUNNR OPTIONAL
*"     VALUE(BUDAT_LOW) TYPE  AUDAT OPTIONAL
*"     VALUE(BUDAT_HIGH) TYPE  AUDAT OPTIONAL
*"  TABLES
*"      OUTPUT_PEN_ORDER STRUCTURE  ZGET_PENDING_ORDER
*"----------------------------------------------------------------------

TYPES:BEGIN OF TY_VBAKUK,
  VBELN TYPE VBAKUK-VBELN,
  AUDAT TYPE VBAKUK-AUDAT,
  AUART TYPE VBAKUK-AUART,
  VKORG TYPE VBAKUK-VKORG,
  VTWEG TYPE VBAKUK-VTWEG,
  SPART TYPE VBAKUK-SPART,
  VKGRP TYPE VBAKUK-VKGRP,
  VKBUR TYPE VBAKUK-VKBUR,
  KUNNR TYPE VBAKUK-KUNNR,
  NETWR TYPE VBAKUK-NETWR,
  END OF TY_VBAKUK.

  DATA:IT_VBAKUK TYPE TABLE OF TY_VBAKUK,
       WA_VBAKUK TYPE TY_VBAKUK.

  SELECT
    VBELN
    AUDAT
    AUART
    VKORG
    VTWEG
    SPART
    VKGRP
    VKBUR
    KUNNR
    NETWR
    FROM VBAKUK INTO TABLE IT_VBAKUK WHERE VKORG = LV_VKORG AND KUNNR = LV_KUNNR AND BESTK in ('A','B','C') AND LFSTK IN ('A','B') AND LFGSK IN ('A','B')." AND AUDAT >= BUDAT_LOW AND AUDAT =< BUDAT_HIGH  .

    LOOP AT IT_VBAKUK INTO WA_VBAKUK.
      OUTPUT_PEN_ORDER-VKORG = WA_VBAKUK-VKORG.
      OUTPUT_PEN_ORDER-VTWEG = WA_VBAKUK-VTWEG.
      OUTPUT_PEN_ORDER-SPART = WA_VBAKUK-SPART.
      OUTPUT_PEN_ORDER-AUDAT = WA_VBAKUK-AUDAT.
      OUTPUT_PEN_ORDER-KUNNR = WA_VBAKUK-KUNNR.
      OUTPUT_PEN_ORDER-NETPR = WA_VBAKUK-NETWR.
      OUTPUT_PEN_ORDER-AUART = WA_VBAKUK-AUART.
      OUTPUT_PEN_ORDER-VBELN = WA_VBAKUK-VBELN.
      APPEND OUTPUT_PEN_ORDER.

    ENDLOOP.




ENDFUNCTION.
