FUNCTION ZGET_PCO_DETAILS.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(LV_VKORG) TYPE  VKORG
*"     VALUE(LV_KUNNR) TYPE  KUNNR OPTIONAL
*"     VALUE(BUDAT_LOW) TYPE  BUDAT OPTIONAL
*"     VALUE(BUDAT_HIGH) TYPE  BUDAT OPTIONAL
*"  TABLES
*"      OUTPUT_PCO STRUCTURE  ZGET_PCO_DETAILS
*"----------------------------------------------------------------------
 TYPES:BEGIN OF TY_T023T,
 MATKL TYPE T023T-MATKL,
 WGBEZ60 TYPE T023T-WGBEZ60,
 END OF TY_T023T.

 DATA: IT_T023T TYPE TABLE OF TY_T023T,
       WA_T023T TYPE TY_T023T.
 TYPES:BEGIN OF TY_PCO,
    VBELN TYPE Vbrk-VBELN,
    FKART TYPE Vbrk-FKART,
    VKORG TYPE Vbrk-VKORG,
    VTWEG TYPE Vbrk-VTWEG,
    FKDAT TYPE Vbrk-FKDAT,
    KUNAG TYPE Vbrk-KUNAG,
    CMWAE TYPE Vbrk-CMWAE,
    DATE_OF_DELIVERY TYPE Vbrk-DATE_OF_DELIVERY,
    FKIMG TYPE VBRP-FKIMG,
    VRKME TYPE VBRP-VRKME,
    VOLUM TYPE VBRP-VOLUM,
    MATNR TYPE VBRP-MATNR,
    ARKTX TYPE VBRP-ARKTX,
    MATKL TYPE VBRP-MATKL,
    SPART TYPE VBRP-SPART,
    NETWR TYPE VBRP-NETWR,
    MWSBP TYPE VBRP-MWSBP,
  END OF TY_PCO.
  DATA: IT_PCO TYPE TABLE OF TY_PCO,
        WA_PCO TYPE TY_PCO.

SELECT
VBRK~VBELN
VBRK~FKART
VBRK~VKORG
VBRK~VTWEG
VBRK~FKDAT
VBRK~KUNAG
VBRK~CMWAE
VBRK~DATE_OF_DELIVERY
VBRP~FKIMG
VBRP~VRKME
VBRP~VOLUM
VBRP~MATNR
VBRP~ARKTX
VBRP~MATKL
VBRP~SPART
VBRP~NETWR
VBRP~MWSBP
INTO TABLE IT_PCO From VBRK INNER JOIN VBRP on VBRK~VBELN = VBRP~VBELN where VBRK~VKORG = LV_VKORG
                   AND VBRK~KUNAG = LV_KUNNR.
*                   and VBRK~FKDAT >= BUDAT_LOW
*                   AND VBRK~FKDAT <= BUDAT_HIGH.

  IF IT_PCO IS NOT INITIAL.
    SELECT MATKL WGBEZ60 INTO TABLE IT_T023T FROM T023T FOR ALL ENTRIES IN IT_PCO WHERE MATKL = IT_PCO-MATKL AND SPRAS = 'EN'.
  ENDIF.

LOOP AT IT_PCO INTO WA_PCO.
  READ TABLE IT_T023T INTO WA_T023T WITH KEY MATKL = WA_PCO-MATKL.
OUTPUT_PCO-VBELN  = WA_PCO-VBELN.
OUTPUT_PCO-FKART  = WA_PCO-FKART.
OUTPUT_PCO-VKORG  = WA_PCO-VKORG.
OUTPUT_PCO-VTWEG  = WA_PCO-VTWEG.
OUTPUT_PCO-FKDAT  = WA_PCO-FKDAT.
OUTPUT_PCO-KUNAG  = WA_PCO-KUNAG.
OUTPUT_PCO-CMWAE  = WA_PCO-CMWAE.
OUTPUT_PCO-DATE_OF_DELIVERY	=	WA_PCO-DATE_OF_DELIVERY.
OUTPUT_PCO-FKIMG  = WA_PCO-FKIMG.
OUTPUT_PCO-VRKME  = WA_PCO-VRKME.
OUTPUT_PCO-VOLUM  = WA_PCO-VOLUM.
OUTPUT_PCO-MATNR  = WA_PCO-MATNR.
OUTPUT_PCO-ARKTX  = WA_PCO-ARKTX.
OUTPUT_PCO-MATKL  = WA_PCO-MATKL.
OUTPUT_PCO-WGBEZ60  = WA_T023T-WGBEZ60.
OUTPUT_PCO-SPART  = WA_PCO-SPART.
OUTPUT_PCO-NETWR  = WA_PCO-NETWR.
OUTPUT_PCO-MWSBP  = WA_PCO-MWSBP.
APPEND  OUTPUT_PCO.
ENDLOOP.

ENDFUNCTION.
