*&---------------------------------------------------------------------*
*&  Include           ZGLOBAL_TOP_DEC
*&---------------------------------------------------------------------*



TABLES : ZTRAM_LOG_TABLE.
"

TYPES : BEGIN OF GS_T001,
        BUKRS TYPE T001-BUKRS,
        BUTXT TYPE T001-BUTXT,
        END OF GS_T001.


TYPES : BEGIN OF GS_T001W,
        WERKS TYPE WERKS_D,
        NAME1 TYPE T001W-NAME1,
        IWERK TYPE IWERK,
        VKORG TYPE VKOIV,
        CHECK TYPE C,
        CHECK1 TYPE C,
        ST_DAYS TYPE I,
        MN_DAYS1(5) TYPE I,
        STATUS TYPE CHAR3,
        STATUS1 TYPE CHAR3,
        END OF GS_T001W.

TYPES :  BEGIN OF GS_CUS_TABLE,
         WERKS TYPE   WERKS_D,
         NAME1 TYPE NAME1,
         ST_DAYS TYPE  I,
         MN_DAYS1 TYPE  ZVAL_INT_1,
         STATUS TYPE ZSTUT,
         STATUS1 TYPE ZSTUT_1,
         END OF GS_CUS_TABLE.



TYPES : BEGIN OF GS_MARC,
        MATNR TYPE MATNR,
        WERKS TYPE WERKS_D,
        TRAME TYPE TRAME,
        END OF GS_MARC.

TYPES : BEGIN OF GS_MDUB,
        MATNR TYPE MATNR,
        WERKS TYPE EWERK,
        EBELN TYPE EBELN,
        EBELP TYPE EBELP,
        WAMNG TYPE WAMNG,
        WEMNG TYPE WEEMG,
        END OF GS_MDUB.

TYPES : BEGIN OF GS_MSEG,
        MBLNR TYPE MBLNR,
        ZEILE TYPE MBLPO,
        BWART TYPE BWART,
        MATNR	 TYPE MATNR,
        WERKS	 TYPE WERKS_D,
        EBELN TYPE EBELN,
        BUDAT_MKPF TYPE BUDAT,
        SMBLN TYPE MBLNR,
        SMBLP TYPE MBLPO,
         TOT_DAYS TYPE I,
        END OF GS_MSEG.

TYPES : BEGIN OF GS_FINAL,
        WERKS TYPE T001W-WERKS,
        NAME1 TYPE T001W-NAME1,
        ST_DAYS TYPE I,
        MN_DAYS1(5) TYPE I,
        STATUS TYPE CHAR3,
        STATUS1 TYPE CHAR3,
        CHECK TYPE C,
        CHECK1 TYPE C,
        END OF GS_FINAL.



DATA : GT_T001 TYPE STANDARD TABLE OF GS_T001,
       WA_T001 TYPE GS_T001.

DATA  : GT_T001W TYPE STANDARD TABLE OF GS_T001W,
        WA_T001W TYPE GS_T001W.

DATA  : GT_MARC TYPE STANDARD TABLE OF GS_MARC,
        WA_MARC TYPE GS_MARC.

DATA :  GT_MDUB TYPE STANDARD TABLE OF GS_MDUB,
        WA_MDUB TYPE GS_MDUB.

DATA :  GT_MSEG TYPE STANDARD TABLE OF GS_MSEG,
        WA_MSEG TYPE GS_MSEG.

DATA :  GT_MSEG1 TYPE STANDARD TABLE OF GS_MSEG,
        WA_MSEG1 TYPE GS_MSEG.

DATA :  GT_MSEG2 TYPE STANDARD TABLE OF GS_MSEG,
        WA_MSEG2 TYPE GS_MSEG.


DATA : GT_FINAL TYPE STANDARD TABLE OF GS_FINAL,
       WA_FINAL TYPE GS_FINAL.

DATA : GT_CUS_TABLE TYPE STANDARD TABLE OF GS_CUS_TABLE,
       WA_CUS_TABLE TYPE GS_CUS_TABLE.

DATA : GT_CUS_TABLE1 TYPE STANDARD TABLE OF GS_CUS_TABLE,
       WA_CUS_TABLE1 TYPE GS_CUS_TABLE.


DATA : OK_CODE TYPE SY-UCOMM.

DATA : LV_FLAG(1) TYPE C,
       LV_FLAG5(1) TYPE C.

DATA : LT_DATE TYPE SY-DATUM,
       LV_DATE TYPE BUDAT,
       LV_DAYS TYPE I,
       P_BUKRS TYPE BUKRS.


CONTROLS TAB TYPE TABLEVIEW USING SCREEN 9193.
