*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZHR_JOBCODE_V...................................*
FORM GET_DATA_ZHR_JOBCODE_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZHR_JOBCODE WHERE
(VIM_WHERETAB) .
    CLEAR ZHR_JOBCODE_V .
ZHR_JOBCODE_V-MANDT =
ZHR_JOBCODE-MANDT .
ZHR_JOBCODE_V-PARVW =
ZHR_JOBCODE-PARVW .
ZHR_JOBCODE_V-STELL =
ZHR_JOBCODE-STELL .
ZHR_JOBCODE_V-JCODE =
ZHR_JOBCODE-PARVW .
ZHR_JOBCODE_V-PARVW2 =
ZHR_JOBCODE-PARVW2 .
ZHR_JOBCODE_V-PERNR =
ZHR_JOBCODE-PERNR .
    SELECT * FROM HRP1000 WHERE
OBJID = ZHR_JOBCODE-STELL .
ZHR_JOBCODE_V-STEXT =
HRP1000-STEXT .
      EXIT.
    ENDSELECT.
<VIM_TOTAL_STRUC> = ZHR_JOBCODE_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZHR_JOBCODE_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZHR_JOBCODE_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZHR_JOBCODE_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZHR_JOBCODE WHERE
  PARVW = ZHR_JOBCODE_V-PARVW AND
  STELL = ZHR_JOBCODE_V-STELL .
    IF SY-SUBRC = 0.
    DELETE ZHR_JOBCODE .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZHR_JOBCODE WHERE
  PARVW = ZHR_JOBCODE_V-PARVW AND
  STELL = ZHR_JOBCODE_V-STELL .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZHR_JOBCODE.
    ENDIF.
ZHR_JOBCODE-MANDT =
ZHR_JOBCODE_V-MANDT .
ZHR_JOBCODE-PARVW =
ZHR_JOBCODE_V-PARVW .
ZHR_JOBCODE-STELL =
ZHR_JOBCODE_V-STELL .
ZHR_JOBCODE-PARVW =
ZHR_JOBCODE_V-JCODE .
ZHR_JOBCODE-PARVW2 =
ZHR_JOBCODE_V-PARVW2 .
ZHR_JOBCODE-PERNR =
ZHR_JOBCODE_V-PERNR .
    IF SY-SUBRC = 0.
    UPDATE ZHR_JOBCODE ##WARN_OK.
    ELSE.
    INSERT ZHR_JOBCODE .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZHR_JOBCODE_V-UPD_FLAG,
STATUS_ZHR_JOBCODE_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZHR_JOBCODE_V.
  SELECT SINGLE * FROM ZHR_JOBCODE WHERE
PARVW = ZHR_JOBCODE_V-PARVW AND
STELL = ZHR_JOBCODE_V-STELL .
ZHR_JOBCODE_V-MANDT =
ZHR_JOBCODE-MANDT .
ZHR_JOBCODE_V-PARVW =
ZHR_JOBCODE-PARVW .
ZHR_JOBCODE_V-STELL =
ZHR_JOBCODE-STELL .
ZHR_JOBCODE_V-JCODE =
ZHR_JOBCODE-PARVW .
ZHR_JOBCODE_V-PARVW2 =
ZHR_JOBCODE-PARVW2 .
ZHR_JOBCODE_V-PERNR =
ZHR_JOBCODE-PERNR .
    SELECT * FROM HRP1000 WHERE
OBJID = ZHR_JOBCODE-STELL .
ZHR_JOBCODE_V-STEXT =
HRP1000-STEXT .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR ZHR_JOBCODE_V-STEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZHR_JOBCODE_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZHR_JOBCODE_V-PARVW TO
ZHR_JOBCODE-PARVW .
MOVE ZHR_JOBCODE_V-STELL TO
ZHR_JOBCODE-STELL .
MOVE ZHR_JOBCODE_V-MANDT TO
ZHR_JOBCODE-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZHR_JOBCODE'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZHR_JOBCODE TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZHR_JOBCODE'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZHR_JOBCODE_V USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZHR_JOBCODE-MANDT =
ZHR_JOBCODE_V-MANDT .
ZHR_JOBCODE-PARVW =
ZHR_JOBCODE_V-PARVW .
ZHR_JOBCODE-STELL =
ZHR_JOBCODE_V-STELL .
ZHR_JOBCODE-PARVW =
ZHR_JOBCODE_V-JCODE .
ZHR_JOBCODE-PARVW2 =
ZHR_JOBCODE_V-PARVW2 .
ZHR_JOBCODE-PERNR =
ZHR_JOBCODE_V-PERNR .
    SELECT * FROM HRP1000 WHERE
OBJID = ZHR_JOBCODE-STELL .
ZHR_JOBCODE_V-STEXT =
HRP1000-STEXT .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR ZHR_JOBCODE_V-STEXT .
    ENDIF.
ENDFORM.
