*&---------------------------------------------------------------------*
*& Report  ZHRBDC_ALL
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*

REPORT ZHRBDC_ALL.
DATA:
     GT_LIST1     TYPE VRM_VALUES,
      GWA_LIST1    TYPE VRM_VALUE,

      GT_VALUES1   TYPE TABLE OF DYNPREAD,                     " INTERNAL TABLE FOR LIST BOX

      GWA_VALUES1  TYPE DYNPREAD,                              " WORK AREA FOR LIST BOX

      GV_SELECTED_VALUE1(30) TYPE C.



SELECTION-SCREEN: BEGIN OF BLOCK B3.

SELECTION-SCREEN: END OF BLOCK B3.
      SELECTION-SCREEN: BEGIN OF BLOCK B4.

PARAMETERS: PS_PARM1 AS LISTBOX VISIBLE LENGTH 30 USER-COMMAND ABC1 MODIF ID TB1.
SELECTION-SCREEN: END OF BLOCK B4.

AT SELECTION-SCREEN ON PS_PARM1.

  CLEAR: GWA_VALUES1, GT_VALUES1.

  REFRESH GT_VALUES1.

  GWA_VALUES1-FIELDNAME = 'PS_PARM1'.

  APPEND GWA_VALUES1 TO GT_VALUES1.

  CALL FUNCTION 'DYNP_VALUES_READ'
    EXPORTING
      DYNAME             = SY-CPROG
      DYNUMB             = SY-DYNNR
      TRANSLATE_TO_UPPER = 'X'
    TABLES
      DYNPFIELDS         = GT_VALUES1.
*
  READ TABLE GT_VALUES1 INDEX 1 INTO GWA_VALUES1.

  IF SY-SUBRC = 0 AND GWA_VALUES1-FIELDVALUE IS NOT INITIAL.

    READ TABLE GT_LIST1 INTO GWA_LIST1

                      WITH KEY KEY = GWA_VALUES1-FIELDVALUE.

    IF SY-SUBRC = 0.

      GV_SELECTED_VALUE1 = GWA_LIST1-TEXT.

    ENDIF.

  ENDIF.

  INITIALIZATION.

   GWA_LIST1-KEY = '1'.

  GWA_LIST1-TEXT = ' Address(temporary)'.

  APPEND GWA_LIST1 TO GT_LIST1.

  CLEAR: GWA_LIST1.

  GWA_LIST1-KEY = '2'.

  GWA_LIST1-TEXT = 'Pan number'.

  APPEND GWA_LIST1 TO GT_LIST1.

  CLEAR: GWA_LIST1.


  GWA_LIST1-KEY = '3'.

  GWA_LIST1-TEXT = ' Education'.

  APPEND GWA_LIST1 TO GT_LIST1.

  CLEAR: GWA_LIST1.




  GWA_LIST1-KEY = '4'.

  GWA_LIST1-TEXT = ' Previous Employer'.

  APPEND GWA_LIST1 TO GT_LIST1.

  CLEAR: GWA_LIST1.

  GWA_LIST1-KEY = '5'.

  GWA_LIST1-TEXT = 'Official Mail'.

  APPEND GWA_LIST1 TO GT_LIST1.

  CLEAR: GWA_LIST1.

  GWA_LIST1-KEY = '6'.

  GWA_LIST1-TEXT = 'Private Mail'.

  APPEND GWA_LIST1 TO GT_LIST1.

  CLEAR: GWA_LIST1.

 CALL FUNCTION 'VRM_SET_VALUES'
    EXPORTING
      ID              = 'PS_PARM1'
      VALUES          = GT_LIST1
    EXCEPTIONS
      ID_ILLEGAL_NAME = 1
      OTHERS          = 2.
*START-OF-SELECTION.
AT SELECTION-SCREEN.

  IF GWA_VALUES1-FIELDVALUE = 1.

    CALL TRANSACTION 'ZHR_TEMPADDRESS'.

  ENDIF.

  IF GWA_VALUES1-FIELDVALUE = 2.

    CALL TRANSACTION 'ZHR_PANCARD'.

  ENDIF.

  IF GWA_VALUES1-FIELDVALUE = 3.

  CALL TRANSACTION 'ZHR_EDUCATION'.

  ENDIF.

  IF GWA_VALUES1-FIELDVALUE = 4.

    CALL TRANSACTION 'ZHR_PREEMPLOYEMENT'.

  ENDIF.

  IF GWA_VALUES1-FIELDVALUE = 5.

    CALL TRANSACTION 'ZHR_OFFICIALMAIL'.

  ENDIF.

  IF GWA_VALUES1-FIELDVALUE = 6.

    CALL TRANSACTION 'ZHR_PRIVATEMAIL'.

  ENDIF.
