*&---------------------------------------------------------------------*
*& Include ZMIGO_AUTO_TOP                                    Module Pool      ZPO_MIGO_AUTO
*&
*&---------------------------------------------------------------------*

PROGRAM ZPO_MIGO_AUTO.

DATA : S_ASN TYPE ZPO_MIGO_HEADER-ASN_NO.

TYPES: BEGIN OF TY_EKKO,
       EBELN TYPE EBELN,
       BEDAT TYPE BEDAT,
       END OF TY_EKKO.

* Types declaration for EKPO table
TYPES: BEGIN OF TY_EKPO,
       EBELN TYPE EBELN,
       EBELP TYPE EBELP,
       LOEKZ TYPE LOEKZ, "Deletion Indicator
       ELIKZ TYPE ELIKZ, "Delivery Completed
       MATNR TYPE MATNR,
       WERKS TYPE EWERK,
       LGORT TYPE LGORT_D,
       MENGE TYPE BSTMG,
       MEINS TYPE BSTME,
       INSMK TYPE INSMK,
       END OF TY_EKPO.

TYPES: BEGIN OF TY_EKPO_DEL,
EBELN TYPE EBELN,
EBELP TYPE EBELP,
LOEKZ TYPE LOEKZ, "Deletion Indicator
ELIKZ TYPE ELIKZ, "Delivery Completed
MATNR TYPE MATNR,
WERKS TYPE EWERK,
LGORT TYPE LGORT_D,
MENGE TYPE BSTMG,
MEINS TYPE BSTME,
INSMK TYPE INSMK,
END OF TY_EKPO_DEL.

* Types declaration for ZPO_MIGO_HEADER table
TYPES: BEGIN OF TY_ZPO_MIGO_HEADER,
*       MANDT type ZPO_MIGO_HEADER-MANDT,
       ASN_NO TYPE ZPO_MIGO_HEADER-ASN_NO,
       EBELN TYPE ZPO_MIGO_HEADER-EBELN,
       MBLNR TYPE ZPO_MIGO_HEADER-MBLNR,
       BUDAT TYPE ZPO_MIGO_HEADER-BUDAT,
       XBLNR TYPE ZPO_MIGO_HEADER-XBLNR,
       BKTXT TYPE ZPO_MIGO_HEADER-BKTXT,
       FRGRL TYPE ZPO_MIGO_HEADER-FRGRL,
       END OF TY_ZPO_MIGO_HEADER.

*Types declaration for ZPO_MIGO_ITEM table
TYPES: BEGIN OF TY_ZPO_MIGO_ITEM,
        ASN_NO TYPE ZPO_MIGO_ITEM-ASN_NO,
        EBELN TYPE ZPO_MIGO_ITEM-EBELN,
        EBELP TYPE ZPO_MIGO_ITEM-EBELP,
        MATNR TYPE ZPO_MIGO_ITEM-MATNR,
        MENGE TYPE ZPO_MIGO_ITEM-MENGE,
        ERFMG TYPE ZPO_MIGO_ITEM-ERFMG,
        LSMNG TYPE ZPO_MIGO_ITEM-LSMNG,
        MEINS TYPE ZPO_MIGO_ITEM-MEINS,
        INSMK TYPE ZPO_MIGO_ITEM-INSMK,
        LGORT TYPE ZPO_MIGO_ITEM-LGORT,
        CHARG TYPE ZPO_MIGO_ITEM-CHARG,
        LICHA TYPE ZPO_MIGO_ITEM-LICHA,
        VENDOR_INV TYPE ZPO_MIGO_ITEM-VENDOR_INV,
      END OF TY_ZPO_MIGO_ITEM.


*      *Types declaration for FINAL TABLE table
DATA : IT_FINAL TYPE TABLE OF TY_ZPO_MIGO_ITEM,
       WA_FINAL TYPE TY_ZPO_MIGO_ITEM.

*Types declaration for Output data structure
TYPES: BEGIN OF TY_DET,
       EBELN TYPE EBELN,
       MBLNR TYPE MBLNR,
       MJAHR TYPE MJAHR,
       END OF TY_DET.

* Internal Tables Declaration
DATA: IT_EKKO  TYPE STANDARD TABLE OF TY_EKKO,
      IT_EKPO  TYPE STANDARD TABLE OF TY_EKPO,
      IT_EKPO_DEL  TYPE STANDARD TABLE OF TY_EKPO_DEL,
      IT_TEMP  TYPE STANDARD TABLE OF TY_EKPO,
      IT_ZPO_MIGO_HEADER TYPE STANDARD TABLE OF TY_ZPO_MIGO_HEADER,
      IT_ZPO_MIGO_ITEM TYPE STANDARD TABLE OF TY_ZPO_MIGO_ITEM,
      IT_DET   TYPE STANDARD TABLE OF TY_DET.

* Work area Declarations
DATA: WA_EKPO  TYPE TY_EKPO,
      WA_EKPO_DEL  TYPE TY_EKPO_DEL,
      WA_EKKO TYPE TY_EKKO,
      WA_ZPO_MIGO_HEADER TYPE TY_ZPO_MIGO_HEADER,
      WA_ZPO_MIGO_ITEM TYPE TY_ZPO_MIGO_ITEM,
      WA_DET TYPE TY_DET.

* BAPI Structure Declaration
DATA: GMVT_HEADER       TYPE BAPI2017_GM_HEAD_01,
      WA_GMVT_ITEM      TYPE BAPI2017_GM_ITEM_CREATE,
      WA_QCERT_MIGO     TYPE QCERT_MIGO,
      GMVT_HEADRET      TYPE BAPI2017_GM_HEAD_RET,
      RT_BAPIRET        TYPE STANDARD TABLE OF BAPIRET2,
      GMVT_ITEM         TYPE STANDARD TABLE OF BAPI2017_GM_ITEM_CREATE,
      IT_QCERT_MIGO     TYPE STANDARD TABLE OF QCERT_MIGO.

DATA: IT_BDCDATA LIKE BDCDATA  OCCURS 0 WITH HEADER LINE,
      IT_BDCMSG  LIKE BDCMSGCOLL OCCURS 0 WITH HEADER LINE,
      WA_MESSTAB TYPE BDCMSGCOLL,
      EXP_CMNMSG_05 TYPE C ,
      C_DISMODE   TYPE CHAR1 VALUE 'N'.


DATA :LV_MVAR1 TYPE BALM-MSGV1,
     LV_MVAR2 TYPE BALM-MSGV2,
     LV_MVAR3 TYPE BALM-MSGV3,
     LV_MVAR4 TYPE BALM-MSGV4,
     LV_MVAR5 TYPE BALM-MSGV1,
     LV_MVAR6 TYPE BALM-MSGV2,
     LV_MVAR7 TYPE BALM-MSGV3,
     LV_MVAR8 TYPE BALM-MSGV4,
     P_LV_CHECK.

TYPES: BEGIN OF TY_MESSAGE,
        MESS_TYPE(1) TYPE C,
        MESSAGE      TYPE BAPI_MSG,
        STATUS(4)    TYPE C,
       END OF TY_MESSAGE.

DATA:   IT_MESSAGE TYPE TABLE OF TY_MESSAGE,
        WA_MESSAGE TYPE TY_MESSAGE.

DATA :   LO_CONTAINER TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
         LO_ALVGRID   TYPE REF TO CL_GUI_ALV_GRID,
         IT_FCAT      TYPE LVC_T_FCAT,
         WA_FCAT TYPE LVC_S_FCAT,
         LS_LAYOUT    TYPE LVC_S_LAYO,
         FIELDCATALOG TYPE SLIS_T_FIELDCAT_ALV WITH HEADER LINE.

DATA: PO_NUM TYPE ZPO_MIGO_HEADER-EBELN,
      PO_DATE TYPE SY-DATUM,
      PO_DELI TYPE ZPO_MIGO_HEADER-BKTXT,
      HEADER_TX TYPE ZPO_MIGO_HEADER-BKTXT.

DATA :  DELIVERYQTY(10) TYPE C,
        ENTERQTY(10) TYPE C.
