"Name: \PR:RM07MTRB\FO:LISTAUSGABE\SE:BEGIN\EI
ENHANCEMENT 0 ZMM_STOCK_INTRANSIT1.
*
  " Call from FM: ZMM_STOCK_IN_TRANSIT_MIS
  DATA fm_call TYPE c.
  IMPORT FM_CALL FROM MEMORY id 'ZMM_STOCK'.
  IF FM_CALL = 'X'.
    SORT bestand BY matnr werks ebeln ebelp.
    EXPORT bestand TO MEMORY ID 'ZMM_STOCK_INTRANSIT'.
    FREE MEMORY ID 'ZMM_STOCK'.
    LEAVE LIST-PROCESSING.
  ENDIF.


ENDENHANCEMENT.
