*&---------------------------------------------------------------------*
*& Include          ZMM_FERT_PRICE_UPDATE_ME12_SEL
*&---------------------------------------------------------------------*

*** Selection Screen Design *****
DATA: gv_matnr TYPE mara-matnr,
      gv_mtype TYPE mara-mtart.

SELECTION-SCREEN BEGIN OF BLOCK a1 WITH FRAME TITLE TEXT-003.
  PARAMETERS: p_werks  TYPE werks_d OBLIGATORY,
              p_werks2 TYPE werks_d OBLIGATORY.
SELECTION-SCREEN END OF BLOCK a1.
SELECTION-SCREEN BEGIN OF BLOCK b1 WITH FRAME TITLE TEXT-004.
  SELECTION-SCREEN: BEGIN OF LINE.
    PARAMETERS r1 TYPE c RADIOBUTTON GROUP a DEFAULT 'X'.
    SELECTION-SCREEN COMMENT 3(29) TEXT-005 FOR FIELD r1.
    PARAMETERS:   p_ekorg  TYPE ekorg DEFAULT '1000' MATCHCODE OBJECT h_t024e.
  SELECTION-SCREEN: END OF LINE.
  SELECTION-SCREEN: BEGIN OF LINE.
    PARAMETERS r2 TYPE c RADIOBUTTON GROUP a.
    SELECTION-SCREEN COMMENT 3(29) TEXT-006 FOR FIELD p_vkorg.
    PARAMETERS:   p_vkorg  TYPE vkorg DEFAULT '1000'.
  SELECTION-SCREEN: END OF LINE.
SELECTION-SCREEN END OF BLOCK b1.
SELECTION-SCREEN BEGIN OF BLOCK c1 WITH FRAME TITLE TEXT-001.
  SELECT-OPTIONS: s_matnr FOR gv_matnr.
  PARAMETERS: p_mtype TYPE mara-mtart OBLIGATORY DEFAULT 'FERT' MODIF ID md1.
  PARAMETERS: p_date TYPE dats DEFAULT sy-datum.
SELECTION-SCREEN END OF BLOCK c1.
PARAMETERS: p_disp AS CHECKBOX DEFAULT 'X' USER-COMMAND alv.
