*&---------------------------------------------------------------------*
*& Report  ZNEW_SALES_GST
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*

REPORT ZNEW_SALES_GST.

TYPE-POOLS:SLIS.

************** Table Used in Program*****************
TABLES: VBRK,VBRP,KNA1,BKPF,PRCD_ELEMENTS,T001W,TVFKT,BSEG. " KONV Replaced With PRCD_ELEMENTS Added by <IT-CAR Tool> during Code Remediation - tool
TABLES: EKKO,EKPO,LFA1,RBKP,RSEG,BSET,MAKT,T007S,WITH_ITEM.
************** Table Used in Program*****************

****************TYPE START DECLARATION***************
TYPES: BEGIN OF TY_VBRK,
  FKDAT TYPE VBRK-FKDAT,    "DATE
  VBELN TYPE CHAR20,"VBRK-VBELN,    "INVOICE NO
  REGIO TYPE VBRK-REGIO,    "STATE
  WAERK TYPE VBRK-WAERK,    "Currency
  FKART TYPE VBRK-FKART,    "Invoice Type
  XBLNR TYPE VBRK-XBLNR,    "Ref doc
  KNUMV TYPE VBRK-KNUMV,    "Number of the document condition
  BELNR TYPE VBRK-BELNR,
  KUNAG TYPE VBRK-KUNAG,
  BUKRS TYPE VBRK-BUKRS,    "company code
  GJAHR TYPE VBRK-GJAHR,    "Year
  KURRF_DAT TYPE VBRK-KURRF_DAT, "Ref doc date
  LAND1 TYPE VBRK-LAND1,    "Country of Destination

  END OF TY_VBRK.

DATA: IT_VBRK TYPE TABLE OF TY_VBRK,
      WA_VBRK TYPE TY_VBRK.

TYPES: BEGIN OF TY_VBRP,
  VBELN TYPE VBRP-VBELN,
  MATNR TYPE VBRP-MATNR,    "Material Code
  ARKTX TYPE VBRP-ARKTX,    "Material Name
  FKIMG TYPE VBRP-FKIMG,    "Invoice QTY
  VRKME TYPE VBRP-VRKME,    "UOM
  SKFBP TYPE VBRP-SKFBP,    "Total Value
  NETWR TYPE VBRP-NETWR,    "Total Tax Value
  VKBUR TYPE VBRP-VKBUR,    "Sales office
  WERKS TYPE VBRP-WERKS,    "Plant
  WKREG TYPE VBRP-WKREG,    "Plant regino
  POSNR TYPE VBRP-POSNR,
  KURSK TYPE VBRP-KURSK,
  END OF TY_VBRP.

DATA: IT_VBRP TYPE TABLE OF TY_VBRP,
      WA_VBRP TYPE TY_VBRP.

TYPES: BEGIN OF TY_KNA1,
  NAME1 TYPE KNA1-NAME1,    "Customer Name
  STCD3 TYPE KNA1-STCD3,    "Customer GST
  KUNNR TYPE KNA1-KUNNR,
  END OF TY_KNA1.

DATA: IT_KNA1 TYPE TABLE OF TY_KNA1,
      WA_KNA1 TYPE TY_KNA1.

TYPES: BEGIN OF TY_MARC,
  MATNR TYPE MARC-MATNR,
  STEUC TYPE MARC-STEUC,    "Material HSN
  WERKS TYPE MARC-WERKS,
  END OF TY_MARC.

DATA: IT_MARC TYPE TABLE OF TY_MARC,
      WA_MARC TYPE TY_MARC.

TYPES: BEGIN OF TY_BKPF,
  BELNR_RV TYPE BKPF-BELNR,    "RV Number
  AWKEY TYPE BKPF-AWKEY,
  XBLNR TYPE BKPF-XBLNR,
  BLART TYPE BKPF-BLART,
  BUKRS TYPE BKPF-BUKRS,
  KURSF TYPE BKPF-KURSF,
  GJAHR TYPE BKPF-GJAHR,
  END OF TY_BKPF.

DATA: IT_BKPF TYPE TABLE OF TY_BKPF,
      WA_BKPF TYPE TY_BKPF.

TYPES: BEGIN OF TY_BSEG,
        HKONT TYPE BSEG-HKONT,
        BUKRS TYPE BSEG-BUKRS,
        BELNR TYPE BSEG-BELNR,
        GJAHR TYPE BSEG-GJAHR,
        BUZEI TYPE BSEG-BUZEI,
       END OF TY_BSEG.

DATA: IT_BSEG TYPE TABLE OF TY_BSEG,
       WA_BSEG TYPE TY_BSEG.

TYPES : BEGIN OF TY_KONV,
        KNUMV TYPE KONV-KNUMV,                " Number of the document conditio
        KPOSN TYPE KONV-KPOSN,                " Condition item number
        STUNR TYPE KONV-STUNR,                " Step number
        ZAEHK TYPE KONV-ZAEHK,                " Condition counter
        KAWRT TYPE KONV-KAWRT,                " Condition base value
        KBETR TYPE KONV-KBETR,                " Rate (condition amount or percentage)
        KSCHL TYPE KONV-KSCHL,                " Condition type
        KWERT TYPE KONV-KWERT,                " Tax Amount
        KNTYP TYPE KONV-KNTYP,                " Condition category (examples: tax, freight, price, cost)
        KUNNR TYPE KONV-KUNNR,                " Customer number (rebate recipient)

        TAX_SGST TYPE KONV-KBETR,
        RATE_SGST TYPE KONV-KWERT,
        TAX_CGST TYPE KONV-KBETR,
        RATE_CGST TYPE KONV-KWERT,
        TAX_IGST TYPE KONV-KBETR,
        RATE_IGST TYPE KONV-KWERT,
        TAX_UGST TYPE KONV-KBETR,
        RATE_UGST TYPE KONV-KWERT,
        TAX_CCESS TYPE KONV-KBETR,
        RATE_CCESS TYPE KONV-KWERT,
        END OF TY_KONV.

DATA:IT_KONV TYPE TABLE OF TY_KONV,
      WA_KONV TYPE TY_KONV.

TYPES : BEGIN OF TY_KONV_DISC,
        KNUMV TYPE KONV-KNUMV,                " Number of the document conditio
        KPOSN TYPE KONV-KPOSN,                " Condition item number
        STUNR TYPE KONV-STUNR,                " Step number
        ZAEHK TYPE KONV-ZAEHK,                " Condition counter
        KAWRT TYPE KONV-KAWRT,                " Condition base value
        KBETR TYPE KONV-KBETR,                " Rate (condition amount or percentage)
        KSCHL TYPE KONV-KSCHL,                " Condition type
        KWERT TYPE KONV-KWERT,                " Tax Amount
        KNTYP TYPE KONV-KNTYP,                " Condition category (examples: tax, freight, price, cost)
        KUNNR TYPE KONV-KUNNR,                " Customer number (rebate recipient)
        DISC_TOTAL TYPE KONV-KBETR,

        END OF TY_KONV_DISC.
DATA:IT_KONV_DISC TYPE TABLE OF TY_KONV_DISC,
     WA_KONV_DISC TYPE TY_KONV_DISC.

TYPES : BEGIN OF TY_KONV_FRE,
        KNUMV TYPE KONV-KNUMV,                " Number of the document conditio
        KPOSN TYPE KONV-KPOSN,                " Condition item number
        STUNR TYPE KONV-STUNR,                " Step number
        ZAEHK TYPE KONV-ZAEHK,                " Condition counter
        KAWRT TYPE KONV-KAWRT,                " Condition base value
        KBETR TYPE KONV-KBETR,                " Rate (condition amount or percentage)
        KSCHL TYPE KONV-KSCHL,                " Condition type
        KWERT TYPE KONV-KWERT,                " Tax Amount
        KNTYP TYPE KONV-KNTYP,                " Condition category (examples: tax, freight, price, cost)
        KUNNR TYPE KONV-KUNNR,                " Customer number (rebate recipient)
        DISC_FREIGHT TYPE KONV-KBETR,

        END OF TY_KONV_FRE.
DATA:IT_KONV_FRE TYPE TABLE OF TY_KONV_FRE,
     WA_KONV_FRE TYPE TY_KONV_FRE.

DATA: MONTHS TYPE T247-LTX.

TYPES: BEGIN OF TY_T001W,
        WERKS TYPE T001W-WERKS,"Plant
        NAME1_FV60 TYPE T001W-NAME1, "Name
        REGIO TYPE T001W-REGIO,"Division
      END OF TY_T001W.

DATA:IT_T001W TYPE TABLE OF TY_T001W,
     WA_T001W TYPE TY_T001W.

TYPES:BEGIN OF TY_TVFKT,
  SPRAS TYPE TVFKT-SPRAS,
  FKART TYPE TVFKT-FKART,
  VTEXT TYPE TVFKT-VTEXT,
  END OF TY_TVFKT.

DATA:IT_TVFKT TYPE TABLE OF TY_TVFKT,
      WA_TVFKT TYPE TY_TVFKT.

TYPES: BEGIN OF TY_BKPF_FV70,
        BUKRS TYPE BKPF-BUKRS,
        BELNR TYPE BKPF-BELNR,
        GJAHR TYPE BKPF-GJAHR,
        BLDAT TYPE BKPF-BLDAT,
        BUDAT TYPE BKPF-BUDAT,
        TCODE TYPE BKPF-TCODE,
        XBLNR TYPE BKPF-XBLNR,
        WAERS TYPE BKPF-WAERS,
        KURSF TYPE BKPF-KURSF, "Exchange rate
        AWKEY TYPE BKPF-AWKEY,
      END OF TY_BKPF_FV70.

DATA: IT_BKPF_FV70 TYPE TABLE OF TY_BKPF_FV70,
      WA_BKPF_FV70 TYPE TY_BKPF_FV70.

TYPES: BEGIN OF TY_BSEG_FV70,
        BUKRS TYPE BSEG-BUKRS,
        BELNR TYPE BSEG-BELNR,
        GJAHR TYPE BSEG-GJAHR,
        BUZEI TYPE BSEG-BUZEI,
        BUZID TYPE BSEG-BUZID,
        BSCHL TYPE BSEG-BSCHL,
        MWSKZ TYPE BSEG-MWSKZ,
        WRBTR TYPE BSEG-WRBTR,
        HKONT TYPE BSEG-HKONT,
        LIFNR TYPE BSEG-LIFNR,
        KUNNR TYPE BSEG-KUNNR,
        MATNR TYPE BSEG-MATNR,
        WERKS TYPE BSEG-WERKS,
        MENGE TYPE BSEG-MENGE,
        MEINS TYPE BSEG-MEINS,
        EBELN TYPE BSEG-EBELN,
        EBELP TYPE BSEG-EBELP,
        HSN_SAC TYPE BSEG-HSN_SAC,
        TCODE TYPE BKPF-TCODE,
        TAXPS TYPE BSEG-TAXPS,
        SHKZG TYPE BSEG-SHKZG,
      END OF TY_BSEG_FV70.

DATA: IT_BSEG_FV70 TYPE TABLE OF TY_BSEG_FV70,
       WA_BSEG_FV70 TYPE TY_BSEG_FV70.

TYPES: BEGIN OF TY_BSEG1_FV70,
        BUKRS TYPE BSEG-BUKRS,
        BELNR TYPE BSEG-BELNR,
        GJAHR TYPE BSEG-GJAHR,
        BUZEI TYPE BSEG-BUZEI,
        BUZID TYPE BSEG-BUZID,
        BSCHL TYPE BSEG-BSCHL,
        MWSKZ TYPE BSEG-MWSKZ,
        WRBTR TYPE BSEG-WRBTR,
        HKONT TYPE BSEG-HKONT,
        LIFNR TYPE BSEG-LIFNR,
        KUNNR TYPE BSEG-KUNNR,
        MATNR TYPE BSEG-MATNR,
        WERKS TYPE BSEG-WERKS,
        MENGE TYPE BSEG-MENGE,
        MEINS TYPE BSEG-MEINS,
        EBELN TYPE BSEG-EBELN,
        EBELP TYPE BSEG-EBELP,
        HSN_SAC TYPE BSEG-HSN_SAC,
        TAXPS TYPE BSEG-TAXPS,
        SHKZG TYPE BSEG-SHKZG,
 END OF TY_BSEG1_FV70.

DATA: IT_BSEG1_FV70 TYPE TABLE OF TY_BSEG1_FV70,
       WA_BSEG1_FV70 TYPE TY_BSEG1_FV70.

DATA : IT_BSEG2_FV70 TYPE TABLE OF TY_BSEG1_FV70,
       WA_BSEG2_FV70 TYPE TY_BSEG1_FV70.

TYPES: BEGIN OF TY_MAKT,
        MATNR TYPE MAKT-MATNR," Material
        MAKTX TYPE MAKT-MAKTX,"Description
      END OF TY_MAKT.
DATA : IT_MAKT TYPE TABLE OF  TY_MAKT,
        WA_MAKT TYPE TY_MAKT.

TYPES: BEGIN OF TY_LFA1,
        LIFNR TYPE LFA1-LIFNR, "vendor code
        NAME1 TYPE LFA1-NAME1, "Vendor Name
        REGIO TYPE LFA1-REGIO,  "Division
        STCD3 TYPE LFA1-STCD3, "GST IN Of Vendor
      END OF TY_LFA1.

DATA: IT_LFA1 TYPE TABLE OF TY_LFA1,
      WA_LFA1 TYPE TY_LFA1.

TYPES: BEGIN OF TY_T007S,
        MWSKZ TYPE T007S-MWSKZ,"Tax code
        TEXT1 TYPE T007S-TEXT1,"Description
      END OF TY_T007S.

DATA:IT_T007S TYPE TABLE OF TY_T007S,
      WA_T007S TYPE TY_T007S.

TYPES: BEGIN OF TY_TDS,
      BUKRS TYPE WITH_ITEM-BUKRS,
      BELNR TYPE WITH_ITEM-BELNR,
      GJAHR TYPE WITH_ITEM-GJAHR,
      WT_QBSHH TYPE WITH_ITEM-WT_QBSHH,
  END OF TY_TDS.

DATA :IT_TDS TYPE TABLE OF TY_TDS,
      WA_TDS TYPE TY_TDS.

TYPES: BEGIN OF TY_BSET,
     BUKRS TYPE BSET-BUKRS,
     BELNR TYPE BSET-BELNR,
     GJAHR TYPE BSET-GJAHR,
     BUZEI TYPE BSET-BUZEI,
     SHKZG TYPE BSET-SHKZG,
     HWBAS TYPE BSET-HWBAS,
     FWSTE TYPE BSET-FWSTE,
     KSCHL TYPE BSET-KSCHL,
     KBETR TYPE BSET-KBETR,
     TAXPS TYPE BSET-TAXPS,
 END OF TY_BSET.

DATA:IT_BSET TYPE TABLE OF TY_BSET,
      WA_BSET TYPE TY_BSET.

TYPES: BEGIN OF TY_SKAT,
              KTOPL TYPE SKAT-KTOPL,
              SAKNR TYPE SKAT-SAKNR,
              TXT20 TYPE SKAT-TXT20,
        END OF TY_SKAT.

DATA: IT_SKAT TYPE TABLE OF TY_SKAT,
      WA_SKAT TYPE TY_SKAT.

TYPES: BEGIN OF TY_KNA1_FV70,
  NAME1 TYPE KNA1-NAME1,    "Customer Name
  STCD3 TYPE KNA1-STCD3,    "Customer GST
  KUNNR TYPE KNA1-KUNNR,
  REGIO TYPE KNA1-REGIO,
  END OF TY_KNA1_FV70.

DATA: IT_KNA1_FV70 TYPE TABLE OF TY_KNA1_FV70,
      WA_KNA1_FV70 TYPE TY_KNA1_FV70.

****************TYPE END DECLARATION*****************

****************TYPE Final Table Start **************
TYPES:BEGIN OF TY_FINAL,

  FKDAT TYPE VBRK-FKDAT,    "DATE
  VBELN TYPE VBRK-VBELN,    "INVOICE NO
  REGIO TYPE VBRK-REGIO,    "STATE
  WAERK TYPE VBRK-WAERK,    "Currency
  FKART TYPE VBRK-FKART,    "Invoice Type
  XBLNR TYPE VBRK-XBLNR,    "Ref doc
  KURRF_DAT TYPE VBRK-KURRF_DAT, "Ref doc date
  MATNR TYPE VBRP-MATNR,    "Material Code
  ARKTX TYPE VBRP-ARKTX,    "Material Name
  FKIMG TYPE VBRP-FKIMG,    "Invoice QTY
  VRKME TYPE VBRP-VRKME,    "UOM
  SKFBP TYPE VBRP-SKFBP,    "Total Value
  NETWR TYPE VBRP-NETWR,    "Total Tax Value
  VKBUR TYPE VBRP-VKBUR,    "Sales office
  WERKS TYPE VBRP-WERKS,    "Plant
  WKREG TYPE VBRP-WKREG,    "Plant regino
  KUNNR TYPE KNA1-KUNNR,    "customer code
  NAME1 TYPE KNA1-NAME1,    "Customer Name
  STCD3 TYPE KNA1-STCD3,    "Customer GST
  STEUC TYPE MARC-STEUC,    "Material HSN
  BELNR_RV TYPE BKPF-BELNR, "RV Number
  MONTHS TYPE T247-LTX,     "FI No
  TCODE TYPE CHAR4,         "TCode
  REVERSE TYPE CHAR4,         "Reverse charage
  TYPE_INVOICE TYPE CHAR15, "TYPE  Sales/Return
  TYPE_GST_REG TYPE CHAR20, "Description of Transaction
  TYPE_GST TYPE CHAR10, "Type of GST
  "KURSF TYPE BKPF-KURSF,
  KURSK TYPE VBRP-KURSK,  "EX Rate
  NAME2 TYPE T001W-NAME1,
  VTEXT TYPE TVFKT-VTEXT, "Billing Type Name
  HKONT TYPE BSEG-HKONT,
  TYPE_TAX_REG TYPE CHAR25, "Type of tax Desc

  KAWRT TYPE KONV-KAWRT,
  KNTYP TYPE KONV-KNTYP,
  KSCHL TYPE KONV-KSCHL,
  KBETR TYPE KONV-KBETR,
  KNUMV TYPE VBRK-KNUMV,

  TAX_SGST TYPE KONV-KBETR,
  RATE_SGST TYPE KONV-KWERT,
  TAX_CGST TYPE KONV-KBETR,
  RATE_CGST TYPE KONV-KWERT,
  TAX_IGST TYPE KONV-KBETR,
  RATE_IGST TYPE KONV-KWERT,
  TAX_UGST TYPE KONV-KBETR,
  RATE_UGST TYPE KONV-KWERT,
  TAX_CCESS TYPE KONV-KBETR,
  RATE_CCESS TYPE KONV-KWERT,

  TAX_JTCB TYPE KONV-KBETR,
  RATE_JTCB TYPE KONV-KWERT,
  TAX_JTC1(15) TYPE P DECIMALS 3,
  RATE_JTC1 TYPE KONV-KWERT,
  TAX_JTC2(15) TYPE P DECIMALS 3,
  RATE_JTC2 TYPE KONV-KWERT,

  TOTAL_TAX(15) TYPE P DECIMALS 3,
  TOTAL_RATE TYPE KONV-KWERT,

  TOTAL_DISC TYPE KONV-KBETR,
  TOTAL_FRE TYPE KONV-KWERT,

  END OF TY_FINAL.

DATA: IT_FINAL TYPE TABLE OF TY_FINAL,
    WA_FINAL TYPE TY_FINAL.



TYPES:BEGIN OF TY_FINAL1_FV70,
        BUKRS TYPE BSEG-BUKRS,
        BELNR TYPE BSEG-BELNR,
        GJAHR TYPE BSEG-GJAHR,
        BUZEI TYPE BSEG-BUZEI,
        BSCHL TYPE BSEG-BSCHL,
        MWSKZ TYPE BSEG-MWSKZ,
        WRBTR TYPE BSEG-WRBTR,
        WRBTR_H TYPE BSEG-WRBTR,
        WRBTR_S TYPE BSEG-WRBTR,
        HKONT TYPE BSEG-HKONT,
        SEG_HKONT TYPE BSEG-HKONT,
        LIFNR TYPE BSEG-LIFNR,
        KUNNR TYPE BSEG-KUNNR,
        LV_LIFNR TYPE BSEG-LIFNR,
        MATNR TYPE BSEG-MATNR,
        WERKS TYPE BSEG-WERKS,
        MENGE TYPE BSEG-MENGE,
        MEINS TYPE BSEG-MEINS,
        EBELN TYPE BSEG-EBELN,
        EBELP TYPE BSEG-EBELP,
        HSN_SAC TYPE BSEG-HSN_SAC,
        TAXPS  TYPE BSEG-TAXPS,
        SHKZG TYPE BSEG-SHKZG,

        BLDAT TYPE BKPF-BLDAT,
        BUDAT TYPE BKPF-BUDAT,
        TCODE TYPE BKPF-TCODE,
        XBLNR TYPE BKPF-XBLNR,
        WAERS TYPE BKPF-WAERS,
        KURSF TYPE BKPF-KURSF, "Exchange rate
        AWKEY TYPE BKPF-AWKEY,

        HWBAS TYPE BSET-HWBAS,
        HWBAS_GST TYPE BSET-HWBAS,
        HWBAS_TCS TYPE BSET-HWBAS,
        FWSTE TYPE BSET-FWSTE,
        KSCHL TYPE BSET-KSCHL,
        KBETR TYPE BSET-KBETR,

        KTOPL TYPE SKAT-KTOPL,
        SAKNR TYPE SKAT-SAKNR,
        TXT20 TYPE SKAT-TXT20,

        MONTHS TYPE T247-LTX, " month in words

        PO_EBELN TYPE EKKO-EBELN,
        BSART TYPE EKKO-BSART,  "Document Type\
        PO_LIFNR TYPE EKKO-LIFNR,

        MAKTX TYPE MAKT-MAKTX,

*       VEN_LIFNR TYPE LFA1-LIFNR,
        NAME1 TYPE LFA1-NAME1,
        REGIO TYPE LFA1-REGIO,
        STCD3 TYPE  LFA1-STCD3,

        TEXT1 TYPE T007S-TEXT1,

        BRAN_REGIO TYPE LFA1-REGIO,

        DOCNO TYPE BKPF-BELNR,
        DOCYR TYPE BKPF-GJAHR,

        VAL_SGST TYPE BSET-FWSTE,
        VAL_IGST TYPE BSET-FWSTE,
        VAL_CGST TYPE BSET-FWSTE,
        VAL_PTCS(15) TYPE P DECIMALS 3,
        VAL_TOTAL(15) TYPE P DECIMALS 3,

        PER_IGST TYPE BSET-KBETR,
        PER_SGST TYPE BSET-KBETR,
        PER_CGST TYPE BSET-KBETR,
        PER_PTCS(15) TYPE P DECIMALS 3,
        TOT_GST(15) TYPE P DECIMALS 3,
        TDS TYPE WITH_ITEM-WT_QSSHH,
        BSET_TAXPS TYPE BSET-TAXPS,

        MAR_WERKS TYPE MARC-WERKS,
        STEUC TYPE MARC-STEUC,

        T00_WERKS TYPE T001W-WERKS,"Plant
        T00_NAME1 TYPE T001W-NAME1,"Name
        T00_REGIO TYPE T001W-REGIO,"Division

        PUR_RET TYPE CHAR30,
        GST_RET TYPE CHAR4,
        TAX_DEC TYPE CHAR20,
        TYPE_GST_REG TYPE CHAR20, "Description of Transaction
        REVERSE TYPE CHAR4,         "Reverse charage
  END OF TY_FINAL1_FV70.

DATA:IT_FINAL1_FV70 TYPE TABLE OF TY_FINAL1_FV70 ,
      WA_FINAL1_FV70 TYPE TY_FINAL1_FV70.
****************TYPE Final Table End**************

************** Selection Screen Starts*****************
SELECTION-SCREEN BEGIN OF BLOCK SALES WITH FRAME TITLE TEXT-001.
PARAMETERS : R1 RADIOBUTTON GROUP G1 USER-COMMAND UC1 MODIF ID TB2 ,          " SELECTION SCREEN FOR INVOICE
             R2 RADIOBUTTON GROUP G1 MODIF ID TB2 DEFAULT 'X'.
"SELECT-OPTIONS:S_VBELN FOR VBRK-VBELN.
SELECT-OPTIONS:S_VKBUR FOR VBRP-VKBUR MODIF ID TB2 DEFAULT '1101' OBLIGATORY.         "sales office
SELECT-OPTIONS:S_KUNNR FOR VBRK-KUNAG MODIF ID TB2.                    "customer
SELECT-OPTIONS:S_BUDAT FOR VBRK-FKDAT MODIF ID TB2 DEFAULT SY-DATUM OBLIGATORY.         "Date

SELECT-OPTIONS:V_BUKRS FOR BSEG-BUKRS MODIF ID TB2 DEFAULT '1000' OBLIGATORY.         "Vendor Code
SELECT-OPTIONS:V_BUDAT FOR BKPF-BUDAT MODIF ID TB2.                    "Posting Date

PARAMETERS: IC AS CHECKBOX.

SELECTION-SCREEN END OF BLOCK SALES.
************** Selection Screen End*****************
INITIALIZATION.
  IF R2 = 'X'.
    LOOP AT SCREEN.
      IF SCREEN-NAME = 'V_BUKRS-LOW' OR SCREEN-NAME = 'V_BUKRS-HIGH' OR SCREEN-NAME = '%_V_BUKRS_%_APP_%-TEXT'
OR SCREEN-NAME = '%_V_BUKRS_%_APP_%-OPTI_PUSH' OR SCREEN-NAME = '%_V_BUKRS_%_APP_%-TO_TEXT' OR SCREEN-NAME = '%_V_BUKRS_%_APP_%-VALU_PUSH'.
        SCREEN-ACTIVE = 0.
        SCREEN-INPUT = 1.
        MODIFY SCREEN.
      ENDIF.
      IF SCREEN-NAME = 'V_BUDAT-LOW' OR SCREEN-NAME = 'V_BUDAT-HIGH' OR SCREEN-NAME = '%_V_BUDAT_%_APP_%-TEXT'
OR SCREEN-NAME = '%_V_BUDAT_%_APP_%-OPTI_PUSH' OR SCREEN-NAME = '%_V_BUDAT_%_APP_%-TO_TEXT' OR SCREEN-NAME = '%_V_BUDAT_%_APP_%-VALU_PUSH'.
        SCREEN-ACTIVE = 0.
        SCREEN-INPUT = 1.
        MODIFY SCREEN.
      ENDIF.
    ENDLOOP.
  ENDIF.

AT SELECTION-SCREEN OUTPUT.
  IF R2 = 'X'.
    LOOP AT SCREEN.
      IF SCREEN-NAME = 'V_BUKRS-LOW' OR SCREEN-NAME = 'V_BUKRS-HIGH' OR SCREEN-NAME = '%_V_BUKRS_%_APP_%-TEXT'
OR SCREEN-NAME = '%_V_BUKRS_%_APP_%-OPTI_PUSH' OR SCREEN-NAME = '%_V_BUKRS_%_APP_%-TO_TEXT' OR SCREEN-NAME = '%_V_BUKRS_%_APP_%-VALU_PUSH'.
        SCREEN-ACTIVE = 0.
        SCREEN-INPUT = 1.
        MODIFY SCREEN.
      ENDIF.
      IF SCREEN-NAME = 'V_BUDAT-LOW' OR SCREEN-NAME = 'V_BUDAT-HIGH' OR SCREEN-NAME = '%_V_BUDAT_%_APP_%-TEXT'
OR SCREEN-NAME = '%_V_BUDAT_%_APP_%-OPTI_PUSH' OR SCREEN-NAME = '%_V_BUDAT_%_APP_%-TO_TEXT' OR SCREEN-NAME = '%_V_BUDAT_%_APP_%-VALU_PUSH'.
        SCREEN-ACTIVE = 0.
        SCREEN-INPUT = 1.
        MODIFY SCREEN.
      ENDIF.


    ENDLOOP.
  ENDIF.

  IF R1 = 'X'.
    LOOP AT SCREEN.
      IF SCREEN-NAME = 'S_VKBUR-LOW' OR SCREEN-NAME = 'S_VKBUR-HIGH' OR SCREEN-NAME = '%_S_VKBUR_%_APP_%-TEXT'
OR SCREEN-NAME = '%_S_VKBUR_%_APP_%-OPTI_PUSH' OR SCREEN-NAME = '%_S_VKBUR_%_APP_%-TO_TEXT' OR SCREEN-NAME = '%_S_VKBUR_%_APP_%-VALU_PUSH'.
        SCREEN-ACTIVE = 0.
        SCREEN-INPUT = 1.
        MODIFY SCREEN.
      ENDIF.

      IF SCREEN-NAME = 'S_KUNNR-LOW' OR SCREEN-NAME = 'S_KUNNR-HIGH' OR SCREEN-NAME = '%_S_KUNNR_%_APP_%-TEXT'
OR SCREEN-NAME = '%_S_KUNNR_%_APP_%-OPTI_PUSH' OR SCREEN-NAME = '%_S_KUNNR_%_APP_%-TO_TEXT' OR SCREEN-NAME = '%_S_KUNNR_%_APP_%-VALU_PUSH'.
        SCREEN-ACTIVE = 0.
        SCREEN-INPUT = 1.
        MODIFY SCREEN.
      ENDIF.

      IF SCREEN-NAME = 'S_BUDAT-LOW' OR SCREEN-NAME = 'S_BUDAT-HIGH' OR SCREEN-NAME = '%_S_BUDAT_%_APP_%-TEXT'
OR SCREEN-NAME = '%_S_BUDAT_%_APP_%-OPTI_PUSH' OR SCREEN-NAME = '%_S_BUDAT_%_APP_%-TO_TEXT' OR SCREEN-NAME = '%_S_BUDAT_%_APP_%-VALU_PUSH'.
        SCREEN-ACTIVE = 0.
        SCREEN-INPUT = 1.
        MODIFY SCREEN.
      ENDIF.

      IF SCREEN-NAME = 'IC' OR SCREEN-NAME = '%_IC_%_APP_%-TEXT'.
        SCREEN-ACTIVE = 0.
        SCREEN-INPUT = 0.
        MODIFY SCREEN.
      ENDIF.

    ENDLOOP.
  ENDIF.



************** Start Of Selection Screen Starts *****************
START-OF-SELECTION.

  PERFORM GET_DATA.
  IF R2 = 'X' .
    PERFORM READ_DATA_CUS.
  ELSEIF R1 = 'X'.
    PERFORM READ_DATA_FV70.
  ENDIF.


END-OF-SELECTION.

************** END Of Selection Screen Starts *****************

************** ALv Declaraton starts *****************
  DATA: IT_FIELDCAT TYPE  SLIS_T_FIELDCAT_ALV,
        WA_FIELDCAT TYPE SLIS_FIELDCAT_ALV,
        WA_LAYOUT TYPE SLIS_LAYOUT_ALV,
        IT_REPID TYPE SY-REPID VALUE SY-REPID.
  IF R2 = 'X' .
    PERFORM FIELDCAT.
    PERFORM LAYOUT.
    PERFORM DISPLAY_CUS.
  ELSEIF R1 = 'X'.
    PERFORM FIELDCAT_FV70.
    PERFORM LAYOUT.
    PERFORM DISPLAY_FV70.
  ENDIF.

************** ALv Declaraton ends *****************

FORM GET_DATA.
  "BREAK-POINT.
  IF R2 = 'X'.
    IF IC <> 'X'.
      SELECT VBRK~FKDAT VBRK~VBELN VBRK~REGIO VBRK~WAERK VBRK~FKART VBRK~XBLNR VBRK~KNUMV VBRK~BELNR VBRK~KUNAG VBRK~BUKRS VBRK~GJAHR VBRK~KURRF_DAT VBRK~LAND1 INTO CORRESPONDING FIELDS OF TABLE IT_VBRK FROM VBRK JOIN VBRP ON VBRK~VBELN = VBRP~VBELN
        "#EC CI_DB_OPERATION_OK[2768887] "Added by SPLABAP during code remediation
         WHERE
         VBRK~FKDAT IN S_BUDAT AND VBRK~KUNAG IN S_KUNNR AND VBRP~VKBUR IN S_VKBUR AND FKART NOT IN ('YSTO','IV','IVS').
    ELSEIF IC = 'X'.
      SELECT VBRK~FKDAT VBRK~VBELN VBRK~REGIO VBRK~WAERK VBRK~FKART VBRK~XBLNR VBRK~KNUMV VBRK~BELNR VBRK~KUNAG VBRK~BUKRS VBRK~GJAHR VBRK~KURRF_DAT VBRK~LAND1 INTO CORRESPONDING FIELDS OF TABLE IT_VBRK FROM VBRK JOIN VBRP ON VBRK~VBELN = VBRP~VBELN
         "#EC CI_DB_OPERATION_OK[2768887] "Added by SPLABAP during code remediation
        WHERE
         VBRK~FKDAT IN S_BUDAT AND VBRK~KUNAG IN S_KUNNR AND VBRP~WERKS IN S_VKBUR AND FKART IN ('YSTO','IV','IVS').
    ENDIF.


    IF NOT IT_VBRK IS INITIAL.
      SELECT VBELN MATNR ARKTX FKIMG VRKME SKFBP NETWR VKBUR WERKS WKREG POSNR KURSK FROM VBRP INTO TABLE IT_VBRP FOR ALL ENTRIES IN IT_VBRK WHERE VBELN =  IT_VBRK-VBELN(10).

      SELECT
         KNUMV
         KPOSN
         STUNR
         ZAEHK
         KAWRT
         KBETR
         KSCHL
         KWERT
         KNTYP
         KUNNR FROM PRCD_ELEMENTS INTO TABLE IT_KONV FOR ALL ENTRIES IN IT_VBRK
         WHERE KNUMV = IT_VBRK-KNUMV AND
               KSCHL IN ('JOCG','JOSG','JOIG','JOUG','JCOS','JTCB','JTC1','JTC2').

      SELECT
       KNUMV
       KPOSN
       STUNR
       ZAEHK
       KAWRT
       KBETR
       KSCHL
       KWERT
       KNTYP
       KUNNR FROM PRCD_ELEMENTS INTO TABLE IT_KONV_DISC FOR ALL ENTRIES IN IT_VBRK
       WHERE KNUMV = IT_VBRK-KNUMV AND
             KSCHL IN ('Y003','Y004','Y005','Y007','Y007','Y008','Y009','YBSD','ZPRV','ZCAD','Y029','YB04','ZPRB', 'Z008',
             'Z009', 'Z011', 'Z012' ).

      SELECT
      KNUMV
      KPOSN
      STUNR
      ZAEHK
      KAWRT
      KBETR
      KSCHL
      KWERT
      KNTYP
      KUNNR FROM PRCD_ELEMENTS INTO TABLE IT_KONV_FRE FOR ALL ENTRIES IN IT_VBRK
      WHERE KNUMV = IT_VBRK-KNUMV AND
            KSCHL IN ('ZKFR','YBRD').

      SELECT MATNR STEUC WERKS FROM MARC INTO TABLE IT_MARC FOR ALL ENTRIES IN IT_VBRP WHERE MATNR = IT_VBRP-MATNR AND WERKS = IT_VBRP-WERKS.

      SELECT NAME1 STCD3 KUNNR FROM KNA1 INTO TABLE IT_KNA1 FOR ALL ENTRIES IN IT_VBRK WHERE KUNNR = IT_VBRK-KUNAG.

      SELECT BELNR AWKEY XBLNR BLART BUKRS KURSF GJAHR FROM BKPF INTO TABLE IT_BKPF FOR ALL ENTRIES IN IT_VBRK WHERE AWKEY = IT_VBRK-VBELN AND BLART IN ('RV','VG') AND BUKRS = IT_VBRK-BUKRS. "AND GJAHR = IT_VBRK-GJAHR.

      SELECT WERKS NAME1 FROM T001W INTO TABLE IT_T001W FOR ALL ENTRIES IN IT_VBRP WHERE WERKS = IT_VBRP-WERKS.

      SELECT SPRAS FKART VTEXT FROM TVFKT INTO TABLE IT_TVFKT FOR ALL ENTRIES IN IT_VBRK WHERE FKART = IT_VBRK-FKART AND SPRAS = 'EN' .

      SELECT HKONT BUKRS BELNR GJAHR BUZEI FROM BSEG INTO TABLE IT_BSEG FOR ALL ENTRIES IN IT_BKPF"#EC CI_DB_OPERATION_OK[2431747]"Added by SPLABAP during code remediation
        WHERE BELNR = IT_BKPF-BELNR_RV AND BUZEI = '002'
        AND BUKRS = IT_BKPF-BUKRS AND GJAHR = IT_BKPF-GJAHR.


    ENDIF.
  ELSEIF R1 = 'X'.
    SELECT BUKRS BELNR GJAHR BLDAT BUDAT TCODE XBLNR WAERS KURSF AWKEY FROM BKPF
      INTO TABLE IT_BKPF_FV70
      WHERE BUDAT IN V_BUDAT AND BUKRS IN V_BUKRS
        AND  ( TCODE EQ 'FV70' OR TCODE EQ 'FV75' OR TCODE EQ 'FB70' OR TCODE EQ 'FB75' ) AND ( BSTAT NE 'Z' OR BSTAT NE 'V' ).

    IF IT_BKPF_FV70 IS NOT INITIAL.
      SELECT BUKRS BELNR GJAHR BUZEI BUZID BSCHL MWSKZ WRBTR HKONT LIFNR KUNNR MATNR WERKS MENGE MEINS EBELN EBELP HSN_SAC TAXPS SHKZG FROM BSEG"#EC CI_DB_OPERATION_OK[2431747]"Added by SPLABAP during code remediation
        INTO TABLE IT_BSEG1_FV70
        FOR ALL ENTRIES IN IT_BKPF_FV70
         WHERE BUKRS = IT_BKPF_FV70-BUKRS
         AND BELNR = IT_BKPF_FV70-BELNR
         AND GJAHR = IT_BKPF_FV70-GJAHR
         AND BUKRS IN V_BUKRS AND KTOSL NE 'JOC' AND KTOSL NE 'JOI'
        AND KTOSL NE 'JOS' AND KTOSL NE 'JOU' AND KTOSL NE 'JII' AND KTOSL NE 'JIS' AND KTOSL NE 'JIC' ."#EC CI_NOORDER  "Added by SPLABAP during code remediation
    ENDIF.
    IF IT_BSEG1_FV70 IS NOT INITIAL.
      SELECT MATNR MAKTX  FROM MAKT
        INTO TABLE IT_MAKT
        FOR ALL ENTRIES IN IT_BSEG1_FV70
        WHERE MATNR = IT_BSEG1_FV70-MATNR.

      SELECT MATNR WERKS STEUC FROM MARC
        INTO TABLE IT_MARC
        FOR ALL ENTRIES IN IT_BSEG1_FV70
        WHERE MATNR = IT_BSEG1_FV70-MATNR.

      SELECT LIFNR NAME1 REGIO STCD3 FROM LFA1
        INTO TABLE IT_LFA1
        FOR ALL ENTRIES IN IT_BSEG1_FV70
        WHERE LIFNR = IT_BSEG1_FV70-LIFNR.

      SELECT NAME1 STCD3 KUNNR REGIO FROM KNA1
        INTO TABLE IT_KNA1_FV70 FOR ALL ENTRIES IN IT_BSEG1_FV70
        WHERE KUNNR = IT_BSEG1_FV70-KUNNR.

      SELECT MWSKZ TEXT1 FROM T007S"#EC CI_NOORDER  "Added by SPLABAP during code remediation
        INTO TABLE IT_T007S
        FOR ALL ENTRIES IN IT_BSEG1_FV70
        WHERE MWSKZ = IT_BSEG1_FV70-MWSKZ
        AND SPRAS EQ 'EN'
        AND KALSM EQ 'TAXINN' .

      SELECT  WERKS NAME1 REGIO FROM T001W
        INTO TABLE IT_T001W
        FOR ALL ENTRIES IN IT_BSEG1_FV70
        WHERE WERKS = IT_BSEG1_FV70-WERKS.

      SELECT BUKRS BELNR GJAHR WT_QBSHH FROM WITH_ITEM INTO TABLE IT_TDS FOR ALL ENTRIES IN IT_BSEG1_FV70 WHERE BUKRS = IT_BSEG1_FV70-BUKRS
       AND BELNR = IT_BSEG1_FV70-BELNR
       AND GJAHR = IT_BSEG1_FV70-GJAHR.

      SELECT BUKRS BELNR GJAHR BUZEI SHKZG HWBAS FWSTE KSCHL KBETR TAXPS FROM BSET"#EC CI_NOORDER  "Added by SPLABAP during code remediation
        INTO TABLE IT_BSET
        FOR ALL ENTRIES IN IT_BSEG1_FV70
        WHERE BELNR = IT_BSEG1_FV70-BELNR
        AND   GJAHR = IT_BSEG1_FV70-GJAHR
        AND   TAXPS = IT_BSEG1_FV70-TAXPS.

      SELECT   KTOPL SAKNR TXT20  FROM SKAT
       INTO TABLE IT_SKAT
       FOR ALL ENTRIES IN IT_BSEG1_FV70
       WHERE KTOPL = 'YAIN'
       AND   SAKNR = IT_BSEG1_FV70-HKONT.
    ENDIF.

  ENDIF.


ENDFORM.                    "GET_DATA

*&---------------------------------------------------------------------*
*&      Form  READ_DATA
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
FORM READ_DATA_CUS .

  DATA: SGST_TEMP_KWERT TYPE KWERT,
           CGST_TEMP_KWERT TYPE KWERT,
           IGST_TEMP_KWERT TYPE KWERT,
           UGST_TEMP_KWERT TYPE KWERT,
           CCESS_TEMP_KWERT TYPE KWERT,
           JTCB_TEMP_KWERT TYPE KWERT,
           JTC1_TEMP_KWERT TYPE KWERT,
           JTC2_TEMP_KWERT TYPE KWERT,
           SGST_TEMP_TAX TYPE KBETR,
           CGST_TEMP_TAX TYPE KBETR,
           IGST_TEMP_TAX TYPE KBETR,
           UGST_TEMP_TAX TYPE KBETR,
           CCESS_TEMP_TAX TYPE KBETR,
*           JTCB_TEMP_TAX TYPE KBETR,
           JTC1_TEMP_TAX(15) TYPE P DECIMALS 3,
           JTC2_TEMP_TAX(15) TYPE P DECIMALS 3,
           TOTAL_TEMP_DISC TYPE KBETR,
           TOTAL_TEMP_FRD TYPE KBETR,
           TEMP_INDEX TYPE SY-INDEX.

  LOOP AT IT_VBRP INTO WA_VBRP.

    READ TABLE IT_VBRK INTO WA_VBRK WITH KEY VBELN = WA_VBRP-VBELN.
    READ TABLE IT_KNA1 INTO WA_KNA1 WITH KEY KUNNR = WA_VBRK-KUNAG.
    READ TABLE IT_MARC INTO WA_MARC WITH KEY MATNR = WA_VBRP-MATNR.
    READ TABLE IT_BKPF INTO WA_BKPF WITH KEY AWKEY = WA_VBRP-VBELN. "BLART = 'RV' BUKRS = WA_VBRK-BUKRS.
    READ TABLE IT_T001W INTO WA_T001W WITH KEY WERKS = WA_VBRP-WERKS.
    READ TABLE IT_TVFKT INTO WA_TVFKT WITH KEY FKART = WA_VBRK-FKART.
    READ TABLE IT_BSEG INTO WA_BSEG WITH KEY BELNR = WA_BKPF-BELNR_RV. "BUZEI = '002' BUKRS = WA_BKPF-BUKRS GJAHR = WA_BKPF-GJAHR.

    LOOP AT IT_BKPF INTO WA_BKPF WHERE BELNR_RV = WA_BKPF-BELNR_RV AND BUKRS = WA_BKPF-BUKRS.
      WA_FINAL-BELNR_RV = WA_BKPF-BELNR_RV.
    ENDLOOP.

    LOOP AT IT_BSEG INTO WA_BKPF WHERE BELNR = WA_BKPF-BELNR_RV AND BUZEI = '002' AND BUKRS = WA_BKPF-BUKRS AND GJAHR = WA_BKPF-GJAHR.
      WA_FINAL-HKONT = WA_BSEG-HKONT.
    ENDLOOP.

    LOOP AT IT_KONV_DISC INTO WA_KONV_DISC WHERE KNUMV = WA_VBRK-KNUMV AND KPOSN = WA_VBRP-POSNR.
      ADD WA_KONV_DISC-KWERT TO TOTAL_TEMP_DISC.
      WA_FINAL-TOTAL_DISC = WA_FINAL-TOTAL_DISC + TOTAL_TEMP_DISC.
      CLEAR: TOTAL_TEMP_DISC.
    ENDLOOP.

    LOOP AT IT_KONV_FRE INTO WA_KONV_FRE WHERE KNUMV = WA_VBRK-KNUMV AND KPOSN = WA_VBRP-POSNR.
      ADD WA_KONV_FRE-KWERT TO TOTAL_TEMP_FRD.
      WA_FINAL-TOTAL_FRE = WA_FINAL-TOTAL_FRE + TOTAL_TEMP_FRD.
      CLEAR: TOTAL_TEMP_FRD.
    ENDLOOP.

    LOOP AT IT_KONV INTO WA_KONV WHERE KNUMV = WA_VBRK-KNUMV AND KPOSN = WA_VBRP-POSNR .
*      IF SY-SUBRC = 0.
*        TEMP_INDEX = SY-TABIX.
      CASE WA_KONV-KSCHL .
        WHEN 'JOCG'.
          ADD WA_KONV-KWERT TO CGST_TEMP_KWERT.
           CGST_TEMP_TAX = WA_KONV-KBETR / 1.
        WHEN 'JOSG'.
          ADD WA_KONV-KWERT TO SGST_TEMP_KWERT.
           SGST_TEMP_TAX = WA_KONV-KBETR / 1.
        WHEN 'JOIG'.
          ADD WA_KONV-KWERT TO IGST_TEMP_KWERT.
           IGST_TEMP_TAX = WA_KONV-KBETR / 1.
        WHEN 'JOUG'.
          ADD WA_KONV-KWERT TO UGST_TEMP_KWERT.
           UGST_TEMP_TAX = WA_KONV-KBETR / 1.
        WHEN 'JCOS'.
          ADD WA_KONV-KWERT TO CCESS_TEMP_KWERT.
           CCESS_TEMP_TAX = WA_KONV-KBETR / 1.

*          WHEN 'JTCB'.
*          ADD WA_KONV-KWERT TO JTCB_TEMP_KWERT.
*          JTCB_TEMP_TAX = WA_KONV-KBETR / 10.
        WHEN 'JTC1'.
          ADD WA_KONV-KWERT TO JTC1_TEMP_KWERT.
           JTC1_TEMP_TAX = WA_KONV-KBETR / 1.
        WHEN 'JTC2'.
          ADD WA_KONV-KWERT TO JTC2_TEMP_KWERT.
           JTC2_TEMP_TAX = WA_KONV-KBETR / 1.

      ENDCASE.
*      ENDIF.

      WA_FINAL-RATE_SGST  = SGST_TEMP_KWERT.
      WA_FINAL-RATE_CGST  = CGST_TEMP_KWERT.
      WA_FINAL-RATE_IGST  = IGST_TEMP_KWERT.
      WA_FINAL-RATE_UGST  = UGST_TEMP_KWERT.
      WA_FINAL-RATE_CCESS = CCESS_TEMP_KWERT.
      WA_FINAL-TAX_SGST   = SGST_TEMP_TAX.
      WA_FINAL-TAX_CGST   = CGST_TEMP_TAX.
      WA_FINAL-TAX_IGST   = IGST_TEMP_TAX.
      WA_FINAL-TAX_UGST   = UGST_TEMP_TAX.
      WA_FINAL-TAX_CCESS  = CCESS_TEMP_TAX.

*      WA_FINAL-RATE_JTCB  = JTCB_TEMP_KWERT.
      WA_FINAL-RATE_JTC1  = JTC1_TEMP_KWERT.
      WA_FINAL-RATE_JTC2  = JTC2_TEMP_KWERT.

*      WA_FINAL-TAX_JTCB   = JTCB_TEMP_TAX.
      WA_FINAL-TAX_JTC1   = JTC1_TEMP_TAX.
      WA_FINAL-TAX_JTC2   = JTC2_TEMP_TAX.

      WA_FINAL-TOTAL_TAX = SGST_TEMP_TAX + CGST_TEMP_TAX + IGST_TEMP_TAX + UGST_TEMP_TAX + CCESS_TEMP_TAX + JTC1_TEMP_TAX + JTC2_TEMP_TAX.
      WA_FINAL-TOTAL_RATE = SGST_TEMP_KWERT + CGST_TEMP_KWERT + IGST_TEMP_KWERT + UGST_TEMP_KWERT + CCESS_TEMP_KWERT + JTC1_TEMP_KWERT + JTC2_TEMP_KWERT.




    ENDLOOP.

    WA_FINAL-VBELN = WA_VBRK-VBELN(10).
    WA_FINAL-FKDAT = WA_VBRK-FKDAT.
    WA_FINAL-WAERK = WA_VBRK-WAERK.

    IF WA_FINAL-FKART <> 'YBEO'.
      WA_FINAL-REGIO = WA_VBRK-REGIO.
    ELSEIF WA_FINAL-FKART = 'YBEO'.
      WA_FINAL-REGIO = WA_VBRK-LAND1.
    ENDIF.

    WA_FINAL-FKART = WA_VBRK-FKART.

    IF WA_FINAL-FKART = 'S1'.
      WA_FINAL-TCODE = 'VF11'.
    ELSE.
      WA_FINAL-TCODE = 'VF01'.
    ENDIF.

    WA_FINAL-REVERSE = 'N'.
    WA_FINAL-KUNNR = WA_KNA1-KUNNR.
    WA_FINAL-NAME1 = WA_KNA1-NAME1.
    WA_FINAL-STCD3 = WA_KNA1-STCD3.
    WA_FINAL-STEUC = WA_MARC-STEUC.
    WA_FINAL-MATNR = WA_VBRP-MATNR.    "Material Code
    WA_FINAL-ARKTX = WA_VBRP-ARKTX.    "Material Name
    WA_FINAL-FKIMG = WA_VBRP-FKIMG.    "Invoice QTY
    WA_FINAL-VRKME = WA_VBRP-VRKME.    "UOM
    WA_FINAL-VKBUR = WA_VBRP-VKBUR.
    WA_FINAL-WERKS = WA_VBRP-WERKS.
    WA_FINAL-WKREG = WA_VBRP-WKREG.

    WA_FINAL-KURSK = WA_VBRP-KURSK.
    WA_FINAL-NAME2 = WA_T001W-NAME1_FV60.
    WA_FINAL-VTEXT = WA_TVFKT-VTEXT.

    WA_FINAL-SKFBP = WA_VBRP-SKFBP.    "Total Value
    WA_FINAL-NETWR = WA_VBRP-NETWR.    "Total Tax Value


    IF WA_FINAL-FKART = 'YBRE' OR WA_FINAL-FKART = 'YIRE'.
      WA_FINAL-XBLNR = WA_VBRK-XBLNR.
      WA_FINAL-KURRF_DAT = WA_VBRK-KURRF_DAT.
    ENDIF.

    IF WA_FINAL-FKART <> 'YBRE'.
      WA_FINAL-TYPE_INVOICE = 'SALES'.
    ELSEIF WA_FINAL-FKART = 'YBRE'.
      WA_FINAL-TYPE_INVOICE = 'RETURN'.
    ENDIF.

    IF WA_FINAL-STCD3 <> ' '.
      WA_FINAL-TYPE_GST_REG = 'GST Registered'.
    ELSE.
      WA_FINAL-TYPE_GST_REG = 'GST NOT Registered'.
    ENDIF.

    IF WA_FINAL-FKART = 'YBEO' AND WA_FINAL-RATE_SGST = '0' AND WA_FINAL-RATE_CGST = '0'.
      WA_FINAL-TYPE_TAX_REG = 'EXPORT'.
      WA_FINAL-TYPE_GST = 'NON GST'.
    ELSEIF WA_FINAL-FKART = 'YBRF' OR WA_FINAL-FKART = 'YRF2' OR WA_FINAL-FKART = 'YBTE' AND WA_FINAL-RATE_SGST = '0' AND WA_FINAL-RATE_CGST = '0'.
      WA_FINAL-TYPE_GST = 'NON GST'.
      WA_FINAL-TYPE_TAX_REG = 'TAX FREE'.
    ELSEIF WA_FINAL-RATE_IGST <> '0'.
      WA_FINAL-TYPE_GST = 'IGST'.
      WA_FINAL-TYPE_TAX_REG = 'TAXABLE SUPPLY - IGST'.
    ELSEIF WA_FINAL-RATE_SGST <> '0' AND WA_FINAL-RATE_CGST <> '0'.
      WA_FINAL-TYPE_GST = 'GST'.
      WA_FINAL-TYPE_TAX_REG = 'TAXABLE SUPPLY - GST'.
    ENDIF.

**    CALL FUNCTION 'ISP_GET_MONTH_NAME'
**      EXPORTING
**        DATE         = WA_FINAL-FKDAT
**        LANGUAGE     = SY-LANGU
***       MONTH_NUMBER = '00'
**      IMPORTING
***       LANGU_BACK   =
**        LONGTEXT     = WA_FINAL-MONTHS
***       SHORTTEXT    =
**      EXCEPTIONS
**        CALENDAR_ID  = 1
**        DATE_ERROR   = 2
**        NOT_FOUND    = 3
**        WRONG_INPUT  = 4
**        OTHERS       = 5.
**    IF SY-SUBRC <> 0.
**    ENDIF.
  SELECT SINGLE LTX FROM T247
     INTO WA_FINAL-MONTHS
     WHERE SPRAS EQ sy-langu AND MNR EQ WA_FINAL-FKDAT+4(2).

    IF WA_FINAL-FKART = 'YBRE' OR WA_FINAL-FKART = 'S2' OR WA_FINAL-FKART = 'S1' OR WA_FINAL-FKART = 'YIRE'.
      WA_FINAL-SKFBP = WA_FINAL-SKFBP * -1.
      WA_FINAL-TOTAL_DISC = WA_FINAL-TOTAL_DISC * -1.
      WA_FINAL-TOTAL_FRE = WA_FINAL-TOTAL_FRE * -1.
      WA_FINAL-NETWR = WA_FINAL-NETWR * -1.
      WA_FINAL-RATE_SGST = WA_FINAL-RATE_SGST * -1.
      WA_FINAL-RATE_CGST = WA_FINAL-RATE_CGST * -1.
      WA_FINAL-RATE_IGST = WA_FINAL-RATE_IGST * -1.
      WA_FINAL-RATE_CCESS = WA_FINAL-RATE_CCESS * -1.
      WA_FINAL-RATE_JTCB = WA_FINAL-RATE_JTCB * -1.
      WA_FINAL-RATE_JTC1 = WA_FINAL-RATE_JTC1 * -1.
      WA_FINAL-RATE_JTC2 = WA_FINAL-RATE_JTC2 * -1.
      WA_FINAL-TOTAL_RATE = WA_FINAL-TOTAL_RATE * -1.
      WA_FINAL-FKIMG = WA_FINAL-FKIMG * -1.
      WA_FINAL-TYPE_INVOICE = 'RETURN'.
    ENDIF.

    IF WA_FINAL-FKART = 'YBEO'.
      WA_FINAL-SKFBP = WA_FINAL-NETWR .
      WA_FINAL-NETWR = WA_FINAL-NETWR * WA_FINAL-KURSK.

    ENDIF.


    APPEND WA_FINAL TO IT_FINAL.
    CLEAR: WA_FINAL.
    CLEAR: WA_KONV.
    CLEAR: WA_KONV_DISC.
    CLEAR: WA_KONV_FRE.
    CLEAR: WA_BSEG.
    CLEAR: WA_BKPF.
    CLEAR: WA_MARC.
    CLEAR: WA_T001W.
    CLEAR: WA_TVFKT.
    CLEAR:  SGST_TEMP_KWERT,
              CGST_TEMP_KWERT,
              IGST_TEMP_KWERT,
              UGST_TEMP_KWERT,
              CCESS_TEMP_KWERT,
              JTCB_TEMP_KWERT,
              JTC1_TEMP_KWERT,
              JTC2_TEMP_KWERT,
              SGST_TEMP_TAX,
              CGST_TEMP_TAX,
              IGST_TEMP_TAX,
              UGST_TEMP_TAX,
*              JTCB_TEMP_TAX,
              JTC1_TEMP_TAX,
              JTC2_TEMP_TAX,
              CCESS_TEMP_TAX.
  ENDLOOP.

ENDFORM.                    "READ_DATA


*INCLUDE ZNEW_SALES_GST_LAYOUTF01.
*INCLUDE ZNEW_SALES_GST_DISPLAYF01.

*&---------------------------------------------------------------------*
*&      Form  FIELDCAT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
FORM FIELDCAT .


  WA_FIELDCAT-FIELDNAME ='TYPE_GST_REG'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Description of Transaction'.
  WA_FIELDCAT-SELTEXT_L ='Description of Transaction'.
  WA_FIELDCAT-COL_POS   = 1.
  WA_FIELDCAT-OUTPUTLEN = '25'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='MONTHS'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Filing Month'.
  WA_FIELDCAT-SELTEXT_L ='Filing Month'.
  WA_FIELDCAT-COL_POS   = 2.
  WA_FIELDCAT-OUTPUTLEN = '10'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='TCODE'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='T.Code'.
  WA_FIELDCAT-SELTEXT_L ='T.Code'.
  WA_FIELDCAT-COL_POS   = 3.
  WA_FIELDCAT-OUTPUTLEN = '5'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='STCD3'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Customer GST NO'.
  WA_FIELDCAT-SELTEXT_L ='Customer GST NO'.
  WA_FIELDCAT-COL_POS   = 4.
  WA_FIELDCAT-OUTPUTLEN = '17'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='KUNNR'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Customer Code'.
  WA_FIELDCAT-SELTEXT_L ='Customer Code'.
  WA_FIELDCAT-COL_POS   = 5.
  WA_FIELDCAT-OUTPUTLEN = '12'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='NAME1'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Name of Customer'.
  WA_FIELDCAT-SELTEXT_L ='Name of Customer'.
  WA_FIELDCAT-COL_POS   = 6.
  WA_FIELDCAT-OUTPUTLEN = '40'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='VBELN'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Invoice No'.
  WA_FIELDCAT-SELTEXT_L ='Invoice No'.
  WA_FIELDCAT-COL_POS   = 7.
  WA_FIELDCAT-OUTPUTLEN = '10'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='FKDAT'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Invoice Date'.
  WA_FIELDCAT-SELTEXT_L ='Invoice Date'.
  WA_FIELDCAT-COL_POS   = 8.
  WA_FIELDCAT-OUTPUTLEN = '10'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='REGIO'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='State'.
  WA_FIELDCAT-SELTEXT_L ='State'.
  WA_FIELDCAT-COL_POS   = 9.
  WA_FIELDCAT-OUTPUTLEN = '5'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='STEUC'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='HSN Code'.
  WA_FIELDCAT-SELTEXT_L ='HSN Code'.
  WA_FIELDCAT-COL_POS   = 10.
  WA_FIELDCAT-OUTPUTLEN = '14'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='MATNR'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Material Code'.
  WA_FIELDCAT-SELTEXT_L ='Material Code'.
  WA_FIELDCAT-COL_POS   = 11.
  WA_FIELDCAT-OUTPUTLEN = '20'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='ARKTX'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Description'.
  WA_FIELDCAT-SELTEXT_L ='Description'.
  WA_FIELDCAT-COL_POS   = 12.
  WA_FIELDCAT-OUTPUTLEN = '25'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='FKIMG'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='QTY'.
  WA_FIELDCAT-SELTEXT_L ='QTY'.
  WA_FIELDCAT-COL_POS   = 13.
  WA_FIELDCAT-OUTPUTLEN = '10'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='VRKME'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='UOM'.
  WA_FIELDCAT-SELTEXT_L ='UOM'.
  WA_FIELDCAT-COL_POS   = 14.
  WA_FIELDCAT-OUTPUTLEN = '5'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='SKFBP'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Invoice Value'.
  WA_FIELDCAT-SELTEXT_L ='Invoice Value'.
  WA_FIELDCAT-COL_POS   = 15.
  WA_FIELDCAT-OUTPUTLEN = '10'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='TOTAL_DISC'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Discount'.
  WA_FIELDCAT-SELTEXT_L ='Discount'.
  WA_FIELDCAT-COL_POS   = 16.
  WA_FIELDCAT-OUTPUTLEN = '10'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='TOTAL_FRE'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Freight'.
  WA_FIELDCAT-SELTEXT_L ='Freight'.
  WA_FIELDCAT-COL_POS   = 17.
  WA_FIELDCAT-OUTPUTLEN = '10'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='NETWR'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Taxable Value'.
  WA_FIELDCAT-SELTEXT_L ='Taxable Value'.
  WA_FIELDCAT-COL_POS   = 18.
  WA_FIELDCAT-OUTPUTLEN = '10'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='RATE_SGST'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='SGST'.
  WA_FIELDCAT-SELTEXT_L ='SGST'.
  WA_FIELDCAT-COL_POS   = 19.
  WA_FIELDCAT-OUTPUTLEN = '8'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='RATE_CGST'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='CGST'.
  WA_FIELDCAT-SELTEXT_L ='CGST'.
  WA_FIELDCAT-COL_POS   = 20.
  WA_FIELDCAT-OUTPUTLEN = '8'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='RATE_IGST'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='IGST'.
  WA_FIELDCAT-SELTEXT_L ='IGST'.
  WA_FIELDCAT-COL_POS   = 21.
  WA_FIELDCAT-OUTPUTLEN = '8'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='RATE_CCESS'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='CCESS'.
  WA_FIELDCAT-SELTEXT_L ='CCESS'.
  WA_FIELDCAT-COL_POS   = 22.
  WA_FIELDCAT-OUTPUTLEN = '8'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

*  WA_FIELDCAT-FIELDNAME ='RATE_JTCB'.
*  WA_FIELDCAT-TABNAME ='IT_FINAL'.
*  WA_FIELDCAT-SELTEXT_S ='JTCB'.
*  WA_FIELDCAT-SELTEXT_L ='JTCB'.
*  WA_FIELDCAT-COL_POS   = 23.
*  WA_FIELDCAT-OUTPUTLEN = '8'.
*  APPEND WA_FIELDCAT TO IT_FIELDCAT.
*  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='RATE_JTC1'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='JTC1'.
  WA_FIELDCAT-SELTEXT_L ='JTC1'.
  WA_FIELDCAT-COL_POS   = 24.
  WA_FIELDCAT-OUTPUTLEN = '8'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='RATE_JTC2'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='JTC2'.
  WA_FIELDCAT-SELTEXT_L ='JTC2'.
  WA_FIELDCAT-COL_POS   = 25.
  WA_FIELDCAT-OUTPUTLEN = '8'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='TOTAL_RATE'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Taxable Amount'.
  WA_FIELDCAT-SELTEXT_L ='Taxable Amount'.
  WA_FIELDCAT-COL_POS   = 26.
  WA_FIELDCAT-OUTPUTLEN = '8'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='TAX_SGST'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='SGST %'.
  WA_FIELDCAT-SELTEXT_L ='SGST %'.
  WA_FIELDCAT-COL_POS   = 27.
  WA_FIELDCAT-OUTPUTLEN = '8'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='TAX_CGST'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='CGST %'.
  WA_FIELDCAT-SELTEXT_L ='CGST %'.
  WA_FIELDCAT-COL_POS   = 28.
  WA_FIELDCAT-OUTPUTLEN = '8'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='TAX_IGST'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='IGST %'.
  WA_FIELDCAT-SELTEXT_L ='IGST %'.
  WA_FIELDCAT-COL_POS   = 29.
  WA_FIELDCAT-OUTPUTLEN = '8'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='TAX_CCESS'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='CCESS %'.
  WA_FIELDCAT-SELTEXT_L ='CCESS %'.
  WA_FIELDCAT-COL_POS   = 30.
  WA_FIELDCAT-OUTPUTLEN = '8'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

*   WA_FIELDCAT-FIELDNAME ='TAX_JTCB'.
*  WA_FIELDCAT-TABNAME ='IT_FINAL'.
*  WA_FIELDCAT-SELTEXT_S ='JTCB %'.
*  WA_FIELDCAT-SELTEXT_L ='JTCB %'.
*  WA_FIELDCAT-COL_POS   = 31.
*  WA_FIELDCAT-OUTPUTLEN = '8'.
*  APPEND WA_FIELDCAT TO IT_FIELDCAT.
*  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='TAX_JTC1'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='JTC1 %'.
  WA_FIELDCAT-SELTEXT_L ='JTC1 %'.
  WA_FIELDCAT-COL_POS   = 32.
  WA_FIELDCAT-OUTPUTLEN = '8'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='TAX_JTC2'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='JTC2 %'.
  WA_FIELDCAT-SELTEXT_L ='JTC2 %'.
  WA_FIELDCAT-COL_POS   = 33.
  WA_FIELDCAT-OUTPUTLEN = '8'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='TOTAL_TAX'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Total Tax %'.
  WA_FIELDCAT-SELTEXT_L ='Total Tax %'.
  WA_FIELDCAT-COL_POS   = 34.
  WA_FIELDCAT-OUTPUTLEN = '8'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='REVERSE'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Reverse Charge Applicable'.
  WA_FIELDCAT-SELTEXT_L ='Reverse Charge Applicable'.
  WA_FIELDCAT-COL_POS   = 35.
  WA_FIELDCAT-OUTPUTLEN = '8'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='WAERK'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Currency'.
  WA_FIELDCAT-SELTEXT_L ='Currency'.
  WA_FIELDCAT-COL_POS   = 36.
  WA_FIELDCAT-OUTPUTLEN = '4'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='KURSK'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Exc.Rate'.
  WA_FIELDCAT-SELTEXT_L ='Exc.Rate'.
  WA_FIELDCAT-COL_POS   = 37.
  WA_FIELDCAT-OUTPUTLEN = '6'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='FKART'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Invoice Type'.
  WA_FIELDCAT-SELTEXT_L ='Invoice Type'.
  WA_FIELDCAT-COL_POS   = 38.
  WA_FIELDCAT-OUTPUTLEN = '5'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='VTEXT'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Invoice Type Desc'.
  WA_FIELDCAT-SELTEXT_L ='Invoice Type Desc'.
  WA_FIELDCAT-COL_POS   = 39.
  WA_FIELDCAT-OUTPUTLEN = '20'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='VKBUR'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Business Place'.
  WA_FIELDCAT-SELTEXT_L ='Business Place'.
  WA_FIELDCAT-COL_POS   = 40.
  WA_FIELDCAT-OUTPUTLEN = '5'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='NAME2'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Business Place Name'.
  WA_FIELDCAT-SELTEXT_L ='Business Place Name'.
  WA_FIELDCAT-COL_POS   = 41.
  WA_FIELDCAT-OUTPUTLEN = '5'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='BELNR_RV'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Acc Document No'.
  WA_FIELDCAT-SELTEXT_L ='Acc Document No'.
  WA_FIELDCAT-COL_POS   = 42.
  WA_FIELDCAT-OUTPUTLEN = '15'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='XBLNR'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Original Invoice'.
  WA_FIELDCAT-SELTEXT_L ='Original Invoice'.
  WA_FIELDCAT-COL_POS   = 43.
  WA_FIELDCAT-OUTPUTLEN = '15'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='KURRF_DAT'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Original Date'.
  WA_FIELDCAT-SELTEXT_L ='Original Date'.
  WA_FIELDCAT-COL_POS   = 44.
  WA_FIELDCAT-OUTPUTLEN = '15'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='HKONT'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Sale Income GL Name'.
  WA_FIELDCAT-SELTEXT_L ='Sale Income GL Name'.
  WA_FIELDCAT-COL_POS   = 45.
  WA_FIELDCAT-OUTPUTLEN = '10'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.


  WA_FIELDCAT-FIELDNAME ='TYPE_TAX_REG'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Type of Tax'.
  WA_FIELDCAT-SELTEXT_L ='Type of Tax'.
  WA_FIELDCAT-COL_POS   = 46.
  WA_FIELDCAT-OUTPUTLEN = '20'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='TYPE_INVOICE'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Sales/Return'.
  WA_FIELDCAT-SELTEXT_L ='Sales/Return'.
  WA_FIELDCAT-COL_POS   = 47.
  WA_FIELDCAT-OUTPUTLEN = '15'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='WERKS'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Division'.
  WA_FIELDCAT-SELTEXT_L ='Division'.
  WA_FIELDCAT-COL_POS   = 48.
  WA_FIELDCAT-OUTPUTLEN = '5'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='WKREG'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Division Regio'.
  WA_FIELDCAT-SELTEXT_L ='Division Regio'.
  WA_FIELDCAT-COL_POS   = 49.
  WA_FIELDCAT-OUTPUTLEN = '10'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='TYPE_GST'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='GST/IGST'.
  WA_FIELDCAT-SELTEXT_L ='GST/IGST'.
  WA_FIELDCAT-COL_POS   = 50.
  WA_FIELDCAT-OUTPUTLEN = '10'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

ENDFORM.                    " FIELDCAT
*&---------------------------------------------------------------------*
*&      Form  READ_DATA_FV70
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM READ_DATA_FV70 .
  SORT IT_BKPF_FV70 BY BELNR GJAHR.

  LOOP AT IT_BSEG1_FV70 INTO WA_BSEG1_FV70.
    WA_BSEG_FV70-BELNR = WA_BSEG1_FV70-BELNR.
    WA_BSEG_FV70-GJAHR = WA_BSEG1_FV70-GJAHR.
    WA_BSEG_FV70-BUZID = WA_BSEG1_FV70-BUZID.
    WA_BSEG_FV70-BSCHL = WA_BSEG1_FV70-BSCHL.
    WA_BSEG_FV70-MWSKZ = WA_BSEG1_FV70-MWSKZ.
    WA_BSEG_FV70-WRBTR = WA_BSEG1_FV70-WRBTR.
    WA_BSEG_FV70-LIFNR = WA_BSEG1_FV70-LIFNR.
    WA_BSEG_FV70-KUNNR = WA_BSEG1_FV70-KUNNR.
    WA_BSEG_FV70-HKONT = WA_BSEG1_FV70-HKONT.
    WA_BSEG_FV70-MATNR = WA_BSEG1_FV70-MATNR.
    WA_BSEG_FV70-WERKS = WA_BSEG1_FV70-WERKS.
    WA_BSEG_FV70-MENGE = WA_BSEG1_FV70-MENGE.
    WA_BSEG_FV70-MEINS = WA_BSEG1_FV70-MEINS.
    WA_BSEG_FV70-EBELN = WA_BSEG1_FV70-EBELN.
    WA_BSEG_FV70-EBELP = WA_BSEG1_FV70-EBELP.
    WA_BSEG_FV70-HSN_SAC = WA_BSEG1_FV70-HSN_SAC.
    WA_BSEG_FV70-BUKRS = WA_BSEG1_FV70-BUKRS.
    WA_BSEG_FV70-TAXPS = WA_BSEG1_FV70-TAXPS.
    WA_BSEG_FV70-SHKZG = WA_BSEG1_FV70-SHKZG.

    READ TABLE IT_BKPF_FV70 INTO WA_BKPF_FV70 WITH KEY BELNR = WA_BSEG_FV70-BELNR
                                             GJAHR = WA_BSEG_FV70-GJAHR BINARY SEARCH."BUKRS = WA_BSEG_FV70-BUKRS BINARY SEARCH.
    IF SY-SUBRC EQ 0 .
      WA_BSEG_FV70-TCODE = WA_BKPF_FV70-TCODE.

    ENDIF.
    APPEND WA_BSEG_FV70 TO IT_BSEG_FV70.
    CLEAR WA_BSEG1_FV70.
    CLEAR WA_BSEG_FV70.

  ENDLOOP.


*  DELETE IT_BKPF_FV70 WHERE TCODE EQ 'FV70' AND .
*  DELETE IT_BSEG_FV70 WHERE KUNNR EQ ' '.
  SORT IT_BKPF_FV70 BY BELNR GJAHR.
  SORT IT_MARC BY MATNR WERKS.
*  SORT IT_EKKO BY EBELN .
  SORT IT_MAKT BY MATNR.
  SORT IT_LFA1 BY LIFNR.
  SORT IT_KNA1_FV70 BY KUNNR.
  SORT IT_T007S BY MWSKZ.
  SORT IT_T001W BY WERKS.
  SORT IT_SKAT BY SAKNR.


  LOOP AT IT_BSEG_FV70 INTO WA_BSEG_FV70 .

    WA_FINAL1_FV70-BELNR = WA_BSEG_FV70-BELNR.
    WA_FINAL1_FV70-GJAHR = WA_BSEG_FV70-GJAHR.
    WA_FINAL1_FV70-MWSKZ = WA_BSEG_FV70-MWSKZ.
    WA_FINAL1_FV70-WRBTR = WA_BSEG_FV70-WRBTR.

    WA_FINAL1_FV70-SHKZG = WA_BSEG_FV70-SHKZG.
    WA_FINAL1_FV70-REVERSE = 'N'.

    IF WA_BSEG_FV70-SHKZG = 'H'.
      WA_FINAL1_FV70-WRBTR_H = WA_FINAL1_FV70-WRBTR_H + WA_BSEG_FV70-WRBTR.
    ELSEIF WA_BSEG_FV70-SHKZG = 'S'.
      WA_FINAL1_FV70-WRBTR_S = WA_FINAL1_FV70-WRBTR_S + WA_BSEG_FV70-WRBTR.
    ENDIF.


*    IF WA_BSEG_FV70-TCODE EQ 'FV60'.

    IF WA_BSEG_FV70-LIFNR = ' '.
      WA_FINAL1_FV70-LIFNR = WA_BSEG_FV70-HKONT.
    ELSE.
      WA_FINAL1_FV70-LIFNR = WA_BSEG_FV70-LIFNR.
    ENDIF.
*    ENDIF.
    IF WA_BSEG_FV70-KUNNR = ' '.
      WA_FINAL1_FV70-LIFNR = WA_BSEG_FV70-HKONT.
    ELSE.
      WA_FINAL1_FV70-LIFNR = WA_BSEG_FV70-KUNNR.
    ENDIF.

    WA_FINAL1_FV70-MATNR = WA_BSEG_FV70-MATNR.
    WA_FINAL1_FV70-WERKS = WA_BSEG_FV70-WERKS.
    WA_FINAL1_FV70-MENGE = WA_BSEG_FV70-MENGE.
    WA_FINAL1_FV70-MEINS = WA_BSEG_FV70-MEINS.
    WA_FINAL1_FV70-EBELN = WA_BSEG_FV70-EBELN.
    WA_FINAL1_FV70-EBELP = WA_BSEG_FV70-EBELP.
    WA_FINAL1_FV70-HSN_SAC = WA_BSEG_FV70-HSN_SAC.
    WA_FINAL1_FV70-BUKRS = WA_BSEG_FV70-BUKRS.
    WA_FINAL1_FV70-TAXPS = WA_BSEG_FV70-TAXPS.

    IF WA_BSEG_FV70-BSCHL EQ '89'.
      WA_FINAL1_FV70-SEG_HKONT = WA_BSEG_FV70-HKONT.
    ENDIF.

    READ TABLE IT_BKPF_FV70 INTO WA_BKPF_FV70 WITH KEY BELNR = WA_BSEG_FV70-BELNR
                                             GJAHR = WA_BSEG_FV70-GJAHR BINARY SEARCH.
*    IF WA_FINAL1_FV70-MWSKZ = 'R*'.
*      WA_FINAL1_FV70-TAX_DEC = 'RCM '.
*    ELSEIF WA_FINAL1_FV70-MWSKZ NE 'R*' .
*      WA_FINAL1_FV70-TAX_DEC = 'TAXABLE – GST'.
*    ENDIF.

    IF SY-SUBRC = 0.
      WA_FINAL1_FV70-BELNR = WA_BKPF_FV70-BELNR.
      WA_FINAL1_FV70-GJAHR = WA_BKPF_FV70-GJAHR.
      WA_FINAL1_FV70-BLDAT = WA_BKPF_FV70-BLDAT.
      WA_FINAL1_FV70-BUDAT = WA_BKPF_FV70-BUDAT.
      WA_FINAL1_FV70-TCODE = WA_BKPF_FV70-TCODE.
      WA_FINAL1_FV70-XBLNR = WA_BKPF_FV70-XBLNR.
      WA_FINAL1_FV70-WAERS = WA_BKPF_FV70-WAERS.
      WA_FINAL1_FV70-KURSF = WA_BKPF_FV70-KURSF.
      WA_FINAL1_FV70-AWKEY = WA_BKPF_FV70-AWKEY.
      WA_FINAL1_FV70-KURSF = WA_BKPF_FV70-KURSF.

**      CALL FUNCTION 'ISP_GET_MONTH_NAME'
**        EXPORTING
**          DATE         = WA_FINAL1_FV70-BLDAT
**          LANGUAGE     = SY-LANGU
***         MONTH_NUMBER = '00'
**        IMPORTING
***         LANGU_BACK   =
**          LONGTEXT     = WA_FINAL1_FV70-MONTHS
***         SHORTTEXT    =
**        EXCEPTIONS
**          CALENDAR_ID  = 1
**          DATE_ERROR   = 2
**          NOT_FOUND    = 3
**          WRONG_INPUT  = 4
**          OTHERS       = 5.
**      IF SY-SUBRC <> 0.
*** Implement suitable error handling here
**      ENDIF.
  SELECT SINGLE LTX FROM T247
     INTO WA_FINAL1_FV70-MONTHS
     WHERE SPRAS EQ sy-langu AND MNR EQ WA_FINAL1_FV70-BLDAT+4(2).

    ENDIF.
    WA_FINAL1_FV70-DOCNO = WA_FINAL1_FV70-BELNR.
    READ TABLE IT_LFA1 INTO WA_LFA1 WITH KEY LIFNR = WA_FINAL1_FV70-LIFNR .

    IF SY-SUBRC = 0.
      WA_FINAL1_FV70-NAME1 = WA_LFA1-NAME1.
      WA_FINAL1_FV70-REGIO = WA_LFA1-REGIO.
      WA_FINAL1_FV70-STCD3 = WA_LFA1-STCD3.
    ENDIF.

    READ TABLE IT_KNA1_FV70 INTO WA_KNA1_FV70 WITH KEY KUNNR = WA_FINAL1_FV70-LIFNR .

    IF SY-SUBRC = 0.
      WA_FINAL1_FV70-NAME1 = WA_KNA1_FV70-NAME1.
      WA_FINAL1_FV70-REGIO = WA_KNA1_FV70-REGIO.
      WA_FINAL1_FV70-STCD3 = WA_KNA1_FV70-STCD3.
    ENDIF.

    IF WA_FINAL1_FV70-STCD3 <> ' '.
      WA_FINAL1_FV70-TYPE_GST_REG = 'GST Registered'.
    ELSE.
      WA_FINAL1_FV70-TYPE_GST_REG = 'GST NOT Registered'.
    ENDIF.

    READ TABLE IT_MAKT INTO WA_MAKT WITH KEY MATNR =  WA_FINAL1_FV70-MATNR .
    IF SY-SUBRC = 0.
      WA_FINAL1_FV70-MAKTX = WA_MAKT-MAKTX.
    ENDIF.

    READ TABLE IT_MARC INTO WA_MARC WITH KEY MATNR =  WA_BSEG_FV70-MATNR WERKS =  WA_BSEG_FV70-WERKS BINARY SEARCH.

    IF SY-SUBRC = 0.
      WA_FINAL1_FV70-STEUC = WA_MARC-STEUC.
    ENDIF.

    READ TABLE IT_SKAT INTO WA_SKAT WITH KEY  SAKNR = WA_BSEG_FV70-HKONT .

    IF WA_FINAL1_FV70-NAME1 = ' '.
      WA_FINAL1_FV70-SAKNR = WA_SKAT-SAKNR.
      WA_FINAL1_FV70-NAME1 = WA_SKAT-TXT20.
    ENDIF.
    IF  SY-SUBRC = 0."WA_LFA1-NAME1 = ''.
      WA_FINAL1_FV70-SAKNR = WA_SKAT-SAKNR.
      WA_FINAL1_FV70-TXT20 = WA_SKAT-TXT20.
    ENDIF.

    READ TABLE IT_T007S INTO WA_T007S WITH KEY MWSKZ = WA_FINAL1_FV70-MWSKZ . "BINARY SEARCH.

    IF SY-SUBRC = 0.
      WA_FINAL1_FV70-TEXT1 = WA_T007S-TEXT1.
    ENDIF.

    READ TABLE IT_T001W INTO WA_T001W WITH KEY WERKS = WA_BSEG_FV70-WERKS BINARY SEARCH.

    IF SY-SUBRC = 0.
      WA_FINAL1_FV70-T00_REGIO = WA_T001W-REGIO.
      WA_FINAL1_FV70-T00_NAME1 = WA_T001W-NAME1_FV60.
    ENDIF.

    LOOP AT IT_BSET INTO WA_BSET WHERE BUKRS = WA_BSEG_FV70-BUKRS AND
                                        BELNR = WA_BSEG_FV70-BELNR AND
                                        GJAHR = WA_BSEG_FV70-GJAHR AND
                                        TAXPS = WA_BSEG_FV70-TAXPS .
*      IF WA_BSEG_FV70-SHKZG = 'H'.
*
*      IF SY-SUBRC = '0' .
      WA_FINAL1_FV70-HWBAS = WA_BSET-HWBAS.
      IF WA_BSET-KSCHL = 'JOIG'.
        WA_FINAL1_FV70-HWBAS_GST = WA_BSET-HWBAS.
        IF WA_BSET-SHKZG = 'H'.
          WA_BSET-FWSTE = WA_BSET-FWSTE * -1.
          WA_FINAL1_FV70-VAL_IGST = WA_BSET-FWSTE .
        ELSEIF WA_BSET-SHKZG = 'S'.
          WA_FINAL1_FV70-VAL_IGST = WA_BSET-FWSTE .
        ENDIF.
        WA_FINAL1_FV70-PER_IGST = WA_BSET-KBETR / 10 .
      ENDIF.
      IF WA_BSET-KSCHL = 'JOCG'.
        IF WA_BSET-SHKZG = 'H'.
          WA_BSET-FWSTE = WA_BSET-FWSTE * -1.
          WA_FINAL1_FV70-VAL_CGST = WA_BSET-FWSTE .
        ELSEIF WA_BSET-SHKZG = 'S'.
          WA_FINAL1_FV70-VAL_CGST = WA_BSET-FWSTE .
        ENDIF.
        WA_FINAL1_FV70-PER_CGST = WA_BSET-KBETR / 10 .
      ENDIF.
      IF WA_BSET-KSCHL = 'JOSG'.
        WA_FINAL1_FV70-HWBAS_GST = WA_BSET-HWBAS.
        IF WA_BSET-SHKZG = 'H'.
          WA_BSET-FWSTE = WA_BSET-FWSTE * -1.
          WA_FINAL1_FV70-VAL_SGST = WA_BSET-FWSTE .
        ELSEIF WA_BSET-SHKZG = 'S'.
          WA_FINAL1_FV70-VAL_SGST = WA_BSET-FWSTE .
        ENDIF.
        WA_FINAL1_FV70-PER_SGST = WA_BSET-KBETR / 10 .
      ENDIF.
      IF WA_BSET-KSCHL = 'JIIG'.
        WA_FINAL1_FV70-HWBAS_GST = WA_BSET-HWBAS.
        IF WA_BSET-SHKZG = 'H'.
          WA_BSET-FWSTE = WA_BSET-FWSTE * -1.
          WA_FINAL1_FV70-VAL_IGST = WA_BSET-FWSTE .
        ELSEIF WA_BSET-SHKZG = 'S'.
          WA_FINAL1_FV70-VAL_IGST = WA_BSET-FWSTE .
        ENDIF.
        WA_FINAL1_FV70-PER_IGST = WA_BSET-KBETR / 10 .
      ENDIF.
      IF WA_BSET-KSCHL = 'JICG'.
        IF WA_BSET-SHKZG = 'H'.
          WA_BSET-FWSTE = WA_BSET-FWSTE * -1.
          WA_FINAL1_FV70-VAL_CGST = WA_BSET-FWSTE .
        ELSEIF WA_BSET-SHKZG = 'S'.
          WA_FINAL1_FV70-VAL_CGST = WA_BSET-FWSTE .
        ENDIF.
        WA_FINAL1_FV70-PER_CGST = WA_BSET-KBETR / 10 .
      ENDIF.
      IF WA_BSET-KSCHL = 'JISG'.
        WA_FINAL1_FV70-HWBAS_GST = WA_BSET-HWBAS.
        IF WA_BSET-SHKZG = 'H'.
          WA_BSET-FWSTE = WA_BSET-FWSTE * -1.
          WA_FINAL1_FV70-VAL_SGST = WA_BSET-FWSTE .
        ELSEIF WA_BSET-SHKZG = 'S'.
          WA_FINAL1_FV70-VAL_SGST = WA_BSET-FWSTE .
        ENDIF.
        WA_FINAL1_FV70-PER_SGST = WA_BSET-KBETR / 10 .
      ENDIF.

      IF WA_BSET-KSCHL = 'PTCS'.
        WA_FINAL1_FV70-HWBAS_TCS = WA_BSET-HWBAS.
        WA_FINAL1_FV70-VAL_PTCS = WA_BSET-FWSTE .
        WA_FINAL1_FV70-PER_PTCS = WA_BSET-KBETR / 10 .
      ENDIF.

      IF WA_FINAL1_FV70-VAL_IGST NE 0 .
        WA_FINAL1_FV70-GST_RET = 'IGST' .
      ENDIF.
      IF WA_FINAL1_FV70-VAL_IGST = 0.
        WA_FINAL1_FV70-GST_RET = 'GST' .
      ENDIF.
      CLEAR: WA_BSET.
*      ENDIF.

    ENDLOOP.

    WA_FINAL1_FV70-VAL_TOTAL = WA_FINAL1_FV70-VAL_IGST + WA_FINAL1_FV70-VAL_CGST + WA_FINAL1_FV70-VAL_SGST ."+ WA_FINAL1_FV70-VAL_PTCS.
    WA_FINAL1_FV70-TOT_GST = WA_FINAL1_FV70-PER_IGST + WA_FINAL1_FV70-PER_CGST + WA_FINAL1_FV70-PER_SGST. ".+ WA_FINAL1_FV70-PER_PTCS .


    LOOP AT IT_TDS INTO WA_TDS WHERE BUKRS = WA_BSEG_FV70-BUKRS AND
                                          BELNR = WA_BSEG_FV70-BELNR AND
                                          GJAHR = WA_BSEG_FV70-GJAHR.
      IF WA_BSEG_FV70-SHKZG = 'H'.

        WA_FINAL1_FV70-TDS = WA_FINAL1_FV70-TDS + WA_TDS-WT_QBSHH.
*              WA_FINAL1-TDS = WA_FINAL1-TDS * -1.
      ENDIF.
      CLEAR: WA_TDS.
    ENDLOOP.


    SHIFT WA_FINAL1_FV70-MATNR LEFT DELETING LEADING '0' .

    APPEND WA_FINAL1_FV70 TO IT_FINAL1_FV70.
    CLEAR  WA_FINAL1_FV70.
    CLEAR  WA_BSET.
    CLEAR  WA_BSEG_FV70.
    CLEAR  WA_BSEG1_FV70.
    CLEAR:  WA_LFA1,WA_TDS.

  ENDLOOP.

  DATA :TEM_BSET_BELNR TYPE BSEG-BELNR,
          TEM_BSET_TAXPS TYPE BSEG-TAXPS,
          TEM_BSEG_BELNR TYPE BSEG-BELNR,
          TEM_BSEG_TAXPS TYPE BSEG-TAXPS.
  DATA : TEMP_AMOUNT_GST  TYPE BSET-FWSTE,
        TEMP_AMOUNT_IGST  TYPE BSET-FWSTE,
        TEMP_GST_AMOUNT TYPE BSET-FWSTE ,
        TEMP_AMOUNT_TCS  TYPE BSET-FWSTE,
        TEMP_AMOUNT_PTCS  TYPE BSET-FWSTE,
        I TYPE I,
        J TYPE I.
  SORT IT_FINAL1_FV70 BY BELNR BUDAT.
  LOOP AT IT_FINAL1_FV70 INTO WA_FINAL1_FV70.
    IF WA_FINAL1_FV70-BELNR = TEM_BSET_BELNR AND WA_FINAL1_FV70-HWBAS_TCS = TEMP_AMOUNT_TCS.
      WA_FINAL1_FV70-HWBAS_TCS = '0'.
      WA_FINAL1_FV70-VAL_PTCS = '0'.
      WA_FINAL1_FV70-PER_PTCS = '0'.
      J = 1.
      MODIFY TABLE IT_FINAL1_FV70 FROM WA_FINAL1_FV70.
    ELSE.
      J = 0.
    ENDIF.

    IF J = 0.
      CLEAR : TEM_BSET_BELNR,TEMP_AMOUNT_TCS,TEMP_AMOUNT_PTCS.
      TEM_BSET_BELNR = WA_FINAL1_FV70-BELNR.
      TEMP_AMOUNT_TCS = WA_FINAL1_FV70-HWBAS_TCS.
      TEMP_AMOUNT_PTCS = WA_FINAL1_FV70-VAL_PTCS."#EC CI_FLDEXT_OK[2610650] "Added by SPLABAP during code remediation

    ENDIF.

    IF WA_FINAL1_FV70-BELNR = TEM_BSET_BELNR AND WA_FINAL1_FV70-VAL_SGST = TEMP_AMOUNT_GST AND WA_FINAL1_FV70-VAL_SGST <> 0.
      WA_FINAL1_FV70-TOT_GST = '0'.
      WA_FINAL1_FV70-VAL_TOTAL = '0'.
      WA_FINAL1_FV70-VAL_TOTAL = '0'.
      WA_FINAL1_FV70-VAL_CGST = '0'.
      WA_FINAL1_FV70-VAL_SGST = '0'.
      WA_FINAL1_FV70-PER_CGST = '0'.
      WA_FINAL1_FV70-PER_SGST = '0'.

      IF WA_FINAL1_FV70-HWBAS_GST = TEMP_GST_AMOUNT.
        WA_FINAL1_FV70-HWBAS_GST = '0'.
      ENDIF.

      I = 1.
      MODIFY TABLE IT_FINAL1_FV70 FROM WA_FINAL1_FV70.

    ELSEIF WA_FINAL1_FV70-BELNR = TEM_BSET_BELNR AND WA_FINAL1_FV70-VAL_IGST = TEMP_AMOUNT_IGST AND WA_FINAL1_FV70-VAL_IGST <> 0.
      WA_FINAL1_FV70-TOT_GST = '0'.
      WA_FINAL1_FV70-VAL_TOTAL = '0'.
      WA_FINAL1_FV70-VAL_IGST = '0'.
      WA_FINAL1_FV70-PER_IGST = '0'.

      IF WA_FINAL1_FV70-HWBAS_GST = TEMP_GST_AMOUNT.
        WA_FINAL1_FV70-HWBAS_GST = '0'.
      ENDIF.

      I = 1.
      MODIFY TABLE IT_FINAL1_FV70 FROM WA_FINAL1_FV70.
    ELSE.
      I = 0.
    ENDIF.

    IF I = 0.
      CLEAR : TEM_BSET_BELNR,TEMP_AMOUNT_GST,TEMP_AMOUNT_IGST,TEMP_GST_AMOUNT.
      TEM_BSET_BELNR = WA_FINAL1_FV70-BELNR.
      TEMP_GST_AMOUNT = WA_FINAL1_FV70-HWBAS_GST.
      IF  WA_FINAL1_FV70-VAL_SGST <> 0.
        TEMP_AMOUNT_GST = WA_FINAL1_FV70-VAL_SGST.
      ENDIF.
      IF WA_FINAL1_FV70-VAL_IGST <> 0.
        TEMP_AMOUNT_IGST = WA_FINAL1_FV70-VAL_IGST.
      ENDIF.
    ENDIF.

    CLEAR WA_FINAL1_FV70.

  ENDLOOP.


ENDFORM.                    " READ_DATA_FV70
*&---------------------------------------------------------------------*
*&      Form  FIELDCAT_FV70
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM FIELDCAT_FV70 .

  WA_FIELDCAT-FIELDNAME ='TYPE_GST_REG'.
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='Description of Transaction'.
  WA_FIELDCAT-SELTEXT_L ='Description of Transaction'.
  WA_FIELDCAT-COL_POS   = 1.
  WA_FIELDCAT-OUTPUTLEN = '25'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='MONTHS'. "BKPF-BLDAT
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='Filing Month'.
  WA_FIELDCAT-SELTEXT_L ='Filing Month'.
  WA_FIELDCAT-COL_POS   = 2.
  WA_FIELDCAT-OUTPUTLEN = '10'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='TCODE'. "BKPF-TCODE,  "Transaction Code
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='T-Code'.
  WA_FIELDCAT-SELTEXT_L ='T-Code'.
  WA_FIELDCAT-COL_POS   = 3.
  WA_FIELDCAT-OUTPUTLEN = '10'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='STCD3'. "LFA1-STCD3
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='GST Vendor'.
  WA_FIELDCAT-SELTEXT_L ='GST IN Of Vendor'.
  WA_FIELDCAT-COL_POS   = 4.
  WA_FIELDCAT-OUTPUTLEN = '15'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='LIFNR'. "BSEG-LIFNR,  "Vendor Code
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='Vendor No'.
  WA_FIELDCAT-SELTEXT_L ='Vendor Number'.
  WA_FIELDCAT-COL_POS   = 5.
  WA_FIELDCAT-OUTPUTLEN = '12'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='NAME1'. "LFA1-NAME1, SKAT-TXT20 "Vendor Name
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='Vendor'.
  WA_FIELDCAT-SELTEXT_L ='Vendor Name'.
  WA_FIELDCAT-COL_POS   = 6.
  WA_FIELDCAT-OUTPUTLEN = '15'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='BELNR'. "BSEG-BELNR,"Inv. Doc. No.
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='Doc NO'.
  WA_FIELDCAT-SELTEXT_L ='Document Number'.
  WA_FIELDCAT-COL_POS   = 7.
  WA_FIELDCAT-OUTPUTLEN = '15'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='BUDAT'. "BKPF-BUDAT, "Posting Date
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='Post Date'.
  WA_FIELDCAT-SELTEXT_L ='Posting Date '.
  WA_FIELDCAT-COL_POS   = 8.
  WA_FIELDCAT-OUTPUTLEN = '15'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='REGIO'. " LFA1-REGIO
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='State/Code'.
  WA_FIELDCAT-SELTEXT_L ='State/Code'.
  WA_FIELDCAT-COL_POS   = 9.
  WA_FIELDCAT-OUTPUTLEN = '10'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='STEUC'. "BSEG-HSN_SAC  MARC-STEUC
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='HSN/SAC'.
  WA_FIELDCAT-SELTEXT_L ='HSN/SAC Code'.
  WA_FIELDCAT-COL_POS   = 10.
  WA_FIELDCAT-OUTPUTLEN = '15'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.


  WA_FIELDCAT-FIELDNAME ='MATNR'. "BSEG-MATNR, "Material
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='Material No'.
  WA_FIELDCAT-SELTEXT_L ='Material Number'.
  WA_FIELDCAT-COL_POS   = 11.
  WA_FIELDCAT-OUTPUTLEN = '15'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='MAKTX'. "MAKT-MAKTX,"Description
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='Material Desc'.
  WA_FIELDCAT-SELTEXT_L ='Material Description'.
  WA_FIELDCAT-COL_POS   = 12.
  WA_FIELDCAT-OUTPUTLEN = '15'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='MENGE'. " BSEG-MENGE, "Quantity
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='Quantity'.
  WA_FIELDCAT-SELTEXT_L ='PO Quantity'.
  WA_FIELDCAT-COL_POS   = 13.
  WA_FIELDCAT-OUTPUTLEN = '15'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='MEINS'. "BSEG-MEINS, "Base Unit
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='UOM'.
  WA_FIELDCAT-SELTEXT_L ='UOM'.
  WA_FIELDCAT-COL_POS   = 14.
  WA_FIELDCAT-OUTPUTLEN = '5'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

*  WA_FIELDCAT-FIELDNAME ='WRBTR'. "BSEG-WRBTR, "Amount
*  WA_FIELDCAT-TABNAME ='IT_FINAL1'.
*  WA_FIELDCAT-SELTEXT_S ='Invoice Value'.
*  WA_FIELDCAT-SELTEXT_L ='Invoice Value'.
*  WA_FIELDCAT-COL_POS   = 18.
*  WA_FIELDCAT-OUTPUTLEN = '15'.
*
*  APPEND WA_FIELDCAT TO IT_FIELDCAT.
*  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='WRBTR_H'. "BSEG-WRBTR, "Amount
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='Invoice CR Value'.
  WA_FIELDCAT-SELTEXT_L ='Invoice CR Value'.
  WA_FIELDCAT-COL_POS   = 15.
  WA_FIELDCAT-OUTPUTLEN = '15'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.


  WA_FIELDCAT-FIELDNAME ='WRBTR_S'. "BSEG-WRBTR, "Amount
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='Invoice DR Value'.
  WA_FIELDCAT-SELTEXT_L ='Invoice DR Value'.
  WA_FIELDCAT-COL_POS   = 16.
  WA_FIELDCAT-OUTPUTLEN = '15'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

*  WA_FIELDCAT-FIELDNAME ='HWBAS'. " BSET-HWBAS
*  WA_FIELDCAT-TABNAME ='IT_FINAL1'.
*  WA_FIELDCAT-SELTEXT_S ='Taxable Value'.
*  WA_FIELDCAT-SELTEXT_L ='Taxable Value'.
*  WA_FIELDCAT-COL_POS   = 21.
*  WA_FIELDCAT-OUTPUTLEN = '15'.
*
*  APPEND WA_FIELDCAT TO IT_FIELDCAT.
*  CLEAR WA_FIELDCAT.


  WA_FIELDCAT-FIELDNAME ='HWBAS_GST'. " BSET-HWBAS
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='GST Taxable Value'.
  WA_FIELDCAT-SELTEXT_L ='GST Taxable Value'.
  WA_FIELDCAT-COL_POS   = 17.
  WA_FIELDCAT-OUTPUTLEN = '15'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.


  WA_FIELDCAT-FIELDNAME ='HWBAS_TCS'. " BSET-HWBAS
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='TCS Taxable Value'.
  WA_FIELDCAT-SELTEXT_L ='TCS Taxable Value'.
  WA_FIELDCAT-COL_POS   = 18.
  WA_FIELDCAT-OUTPUTLEN = '15'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='VAL_SGST'.
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='Value of SGST'.
  WA_FIELDCAT-SELTEXT_L ='Value of SGST'.
  WA_FIELDCAT-COL_POS   = 19.
  WA_FIELDCAT-OUTPUTLEN = '12'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='VAL_CGST'.
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='Value of CGST'.
  WA_FIELDCAT-SELTEXT_L ='Value of CGST'.
  WA_FIELDCAT-COL_POS   = 20.
  WA_FIELDCAT-OUTPUTLEN = '12'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.
*
  WA_FIELDCAT-FIELDNAME ='VAL_IGST'.
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='Value of IGST'.
  WA_FIELDCAT-SELTEXT_L ='Value of IGST'.
  WA_FIELDCAT-COL_POS   = 21.
  WA_FIELDCAT-OUTPUTLEN = '12'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='VAL_PTCS'.
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='Value of TCS'.
  WA_FIELDCAT-SELTEXT_L ='Value of TCS'.
  WA_FIELDCAT-COL_POS   = 22.
  WA_FIELDCAT-OUTPUTLEN = '12'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='TDS'.
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='Value of TDS'.
  WA_FIELDCAT-SELTEXT_L ='Value of TDS'.
  WA_FIELDCAT-COL_POS   = 23.
  WA_FIELDCAT-OUTPUTLEN = '12'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='VAL_TOTAL'.
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='Total GST Value'.
  WA_FIELDCAT-SELTEXT_L ='Total GST Value'.
  WA_FIELDCAT-COL_POS   = 24.
  WA_FIELDCAT-OUTPUTLEN = '15'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='PER_SGST'.
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='Tax SGST'.
  WA_FIELDCAT-SELTEXT_L ='Rate of Tax SGST'.
  WA_FIELDCAT-COL_POS   = 25.
  WA_FIELDCAT-OUTPUTLEN = '15'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='PER_CGST'.
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='Tax CGST'.
  WA_FIELDCAT-SELTEXT_L ='Rate of Tax CGST'.
  WA_FIELDCAT-COL_POS   = 26.
  WA_FIELDCAT-OUTPUTLEN = '12'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='PER_IGST'.
  WA_FIELDCAT-TABNAME ='IT_FINAL11_FV70'.
  WA_FIELDCAT-SELTEXT_S ='Tax IGST'.
  WA_FIELDCAT-SELTEXT_L ='Rate of Tax IGST'.
  WA_FIELDCAT-COL_POS   = 27.
  WA_FIELDCAT-OUTPUTLEN = '12'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='PER_PTCS'.
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='Tax TCS'.
  WA_FIELDCAT-SELTEXT_L ='Rate of Tax TCS'.
  WA_FIELDCAT-COL_POS   = 28.
  WA_FIELDCAT-OUTPUTLEN = '15'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='TOT_GST'.
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='Total TAX %'.
  WA_FIELDCAT-SELTEXT_L ='Total TAX %'.
  WA_FIELDCAT-COL_POS   = 29.
  WA_FIELDCAT-OUTPUTLEN = '15'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='REVERSE'.
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='Reverse Charge Applicable'.
  WA_FIELDCAT-SELTEXT_L ='Reverse Charge Applicable'.
  WA_FIELDCAT-COL_POS   = 30.
  WA_FIELDCAT-OUTPUTLEN = '8'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='WAERS'. "BKPF-WAERS, "Currency
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='Curr Key'.
  WA_FIELDCAT-SELTEXT_L ='Currency Key'.
  WA_FIELDCAT-COL_POS   = 31.
  WA_FIELDCAT-OUTPUTLEN = '6'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='KURSF'. "BKPF-KURSF
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='Exc Rate'.
  WA_FIELDCAT-SELTEXT_L ='Exchange Rate'.
  WA_FIELDCAT-COL_POS   = 32.
  WA_FIELDCAT-OUTPUTLEN = '15'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.


  WA_FIELDCAT-FIELDNAME ='BSART'. "EKKO-BSART,  "Document Type
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='Doc Type'.
  WA_FIELDCAT-SELTEXT_L ='Document Type'.
  WA_FIELDCAT-COL_POS   = 34.
  WA_FIELDCAT-OUTPUTLEN = '8'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='WERKS'. "BSEG-WERKS," plant
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='PO Plant'.
  WA_FIELDCAT-SELTEXT_L ='PO Plant'.
  WA_FIELDCAT-COL_POS   = 35.
  WA_FIELDCAT-OUTPUTLEN = '6'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='T00_NAME1'. "BSEG-WERKS," plant
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='PO Plant Name'.
  WA_FIELDCAT-SELTEXT_L ='PO Plant Name'.
  WA_FIELDCAT-COL_POS   = 36.
  WA_FIELDCAT-OUTPUTLEN = '6'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='DOCNO'. "BKPF-BELNR
  WA_FIELDCAT-TABNAME ='IT_FINAL11_FV70'.
  WA_FIELDCAT-SELTEXT_S ='Ac Doc'.
  WA_FIELDCAT-SELTEXT_L ='Account Document'.
  WA_FIELDCAT-COL_POS   = 37.
  WA_FIELDCAT-OUTPUTLEN = '15'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.



  WA_FIELDCAT-FIELDNAME ='XBLNR'. "BKPF-XBLNR,"Reference
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='Vendor Invoice '.
  WA_FIELDCAT-SELTEXT_L ='Vendor Invoice '.
  WA_FIELDCAT-COL_POS   = 38.
  WA_FIELDCAT-OUTPUTLEN = '15'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='BLDAT'. "BKPF-BLDAT,"Document Date
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='Doc Date'.
  WA_FIELDCAT-SELTEXT_L ='Document Date'.
  WA_FIELDCAT-COL_POS   = 39.
  WA_FIELDCAT-OUTPUTLEN = '12'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.


  WA_FIELDCAT-FIELDNAME ='SEG_HKONT'. " BSEG-HKONT
  WA_FIELDCAT-TABNAME ='IT_FINAL1'.
  WA_FIELDCAT-SELTEXT_S ='Purchase GL Name'.
  WA_FIELDCAT-SELTEXT_L ='Purchase GL Name'.
  WA_FIELDCAT-COL_POS   = 40.
  WA_FIELDCAT-OUTPUTLEN = '15'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='SEG_HKONT'. " BSEG-HKONT
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='Purchase GL Name'.
  WA_FIELDCAT-SELTEXT_L ='Purchase GL Name'.
  WA_FIELDCAT-COL_POS   = 41.
  WA_FIELDCAT-OUTPUTLEN = '15'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='MWSKZ '. "BSEG-MWSKZ, "Tax code
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='Tax code'.
  WA_FIELDCAT-SELTEXT_L ='Tax code'.
  WA_FIELDCAT-COL_POS   = 42.
  WA_FIELDCAT-OUTPUTLEN = '10'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='TAX_DEC'. "  base on Tax Code
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='Tax Description'.
  WA_FIELDCAT-SELTEXT_L ='Tax Description'.
  WA_FIELDCAT-COL_POS   = 43.
  WA_FIELDCAT-OUTPUTLEN = '15'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='T00_REGIO'. " T001W-REGIO
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='Division'.
  WA_FIELDCAT-SELTEXT_L ='Division'.
  WA_FIELDCAT-COL_POS   = 44.
  WA_FIELDCAT-OUTPUTLEN = '6'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='TEXT1'. "  T007S-TEXT1
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='Tax Code Desc'.
  WA_FIELDCAT-SELTEXT_L ='Tax Code Description'.
  WA_FIELDCAT-COL_POS   = 45.
  WA_FIELDCAT-OUTPUTLEN = '20'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.


  WA_FIELDCAT-FIELDNAME ='PUR_RET'. " based on EKKO- bsart
  WA_FIELDCAT-TABNAME ='IT_FINAL1_FV70'.
  WA_FIELDCAT-SELTEXT_S ='PO or Return'.
  WA_FIELDCAT-SELTEXT_L ='Purchase or Return'.
  WA_FIELDCAT-COL_POS   = 46.
  WA_FIELDCAT-OUTPUTLEN = '15'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

ENDFORM.                    " FIELDCAT_FV70
*&---------------------------------------------------------------------*
*&      Form  DISPLAY_FV70
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM DISPLAY_FV70 .
  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
*   I_INTERFACE_CHECK                 = ' '
*   I_BYPASSING_BUFFER                = ' '
*   I_BUFFER_ACTIVE                   = ' '
    I_CALLBACK_PROGRAM                = IT_REPID
*   I_CALLBACK_PF_STATUS_SET          = ' '
*   I_CALLBACK_USER_COMMAND           = ' '
*   I_CALLBACK_TOP_OF_PAGE            = ' '
*   I_CALLBACK_HTML_TOP_OF_PAGE       = ' '
*   I_CALLBACK_HTML_END_OF_LIST       = ' '
*   I_STRUCTURE_NAME                  =
*   I_BACKGROUND_ID                   = ' '
*   I_GRID_TITLE                      =
*   I_GRID_SETTINGS                   =
      IS_LAYOUT                         = WA_LAYOUT
      IT_FIELDCAT                       = IT_FIELDCAT
*   IT_EXCLUDING                      =
*   IT_SPECIAL_GROUPS                 =
*   IT_SORT                           =
*   IT_FILTER                         =
*   IS_SEL_HIDE                       =
*   I_DEFAULT                         = 'X'
*   I_SAVE                            = ' '
*   IS_VARIANT                        =
*   IT_EVENTS                         =
*   IT_EVENT_EXIT                     =
*   IS_PRINT                          =
*   IS_REPREP_ID                      =
*   I_SCREEN_START_COLUMN             = 0
*   I_SCREEN_START_LINE               = 0
*   I_SCREEN_END_COLUMN               = 0
*   I_SCREEN_END_LINE                 = 0
*   I_HTML_HEIGHT_TOP                 = 0
*   I_HTML_HEIGHT_END                 = 0
*   IT_ALV_GRAPHICS                   =
*   IT_HYPERLINK                      =
*   IT_ADD_FIELDCAT                   =
*   IT_EXCEPT_QINFO                   =
*   IR_SALV_FULLSCREEN_ADAPTER        =
* IMPORTING
*   E_EXIT_CAUSED_BY_CALLER           =
*   ES_EXIT_CAUSED_BY_USER            =
     TABLES
       T_OUTTAB                          = IT_FINAL1_FV70
* EXCEPTIONS
*   PROGRAM_ERROR                     = 1
*   OTHERS                            = 2
             .
  IF SY-SUBRC <> 0.
* Implement suitable error handling here
  ENDIF.
ENDFORM.                    " DISPLAY_FV70
*&---------------------------------------------------------------------*
*&      Form  DISPLAY_CUS
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM DISPLAY_CUS .

  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
   EXPORTING
*   I_INTERFACE_CHECK                 = ' '
*   I_BYPASSING_BUFFER                = ' '
*   I_BUFFER_ACTIVE                   = ' '
   I_CALLBACK_PROGRAM                = IT_REPID
*   I_CALLBACK_PF_STATUS_SET          = ' '
*   I_CALLBACK_USER_COMMAND           = ' '
*   I_CALLBACK_TOP_OF_PAGE            = ' '
*   I_CALLBACK_HTML_TOP_OF_PAGE       = ' '
*   I_CALLBACK_HTML_END_OF_LIST       = ' '
*   I_STRUCTURE_NAME                  =
*   I_BACKGROUND_ID                   = ' '
*   I_GRID_TITLE                      =
*   I_GRID_SETTINGS                   =
     IS_LAYOUT                         = WA_LAYOUT
     IT_FIELDCAT                       = IT_FIELDCAT
*   IT_EXCLUDING                      =
*   IT_SPECIAL_GROUPS                 =
*   IT_SORT                           =
*   IT_FILTER                         =
*   IS_SEL_HIDE                       =
*   I_DEFAULT                         = 'X'
*   I_SAVE                            = ' '
*   IS_VARIANT                        =
*   IT_EVENTS                         =
*   IT_EVENT_EXIT                     =
*   IS_PRINT                          =
*   IS_REPREP_ID                      =
*   I_SCREEN_START_COLUMN             = 0
*   I_SCREEN_START_LINE               = 0
*   I_SCREEN_END_COLUMN               = 0
*   I_SCREEN_END_LINE                 = 0
*   I_HTML_HEIGHT_TOP                 = 0
*   I_HTML_HEIGHT_END                 = 0
*   IT_ALV_GRAPHICS                   =
*   IT_HYPERLINK                      =
*   IT_ADD_FIELDCAT                   =
*   IT_EXCEPT_QINFO                   =
*   IR_SALV_FULLSCREEN_ADAPTER        =
* IMPORTING
*   E_EXIT_CAUSED_BY_CALLER           =
*   ES_EXIT_CAUSED_BY_USER            =
    TABLES
      T_OUTTAB                          = IT_FINAL
* EXCEPTIONS
*   PROGRAM_ERROR                     = 1
*   OTHERS                            = 2
            .
  IF SY-SUBRC <> 0.
* Implement suitable error handling here
  ENDIF.

ENDFORM.                    " DISPLAY_CUS
*&---------------------------------------------------------------------*
*&      Form  LAYOUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM LAYOUT .
  WA_LAYOUT-ZEBRA = 'X'.

ENDFORM.                    " LAYOUT
