FUNCTION ZPO_MIGO_DATA_UPLOAD.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(PO_ASN_NO) TYPE  ZPO_MIGO_HEADER-ASN_NO
*"     VALUE(PO_EBELN) TYPE  ZPO_MIGO_HEADER-EBELN
*"     VALUE(PO_XBLNR) TYPE  ZPO_MIGO_HEADER-XBLNR
*"     VALUE(PO_STATU) TYPE  ZPO_MIGO_HEADER-FRGRL OPTIONAL
*"     VALUE(PO_EBELP) TYPE  ZPO_MIGO_ITEM-EBELP
*"     VALUE(PO_MATNR) TYPE  ZPO_MIGO_ITEM-MATNR
*"     VALUE(PO_QTY) TYPE  ZPO_MIGO_ITEM-ERFMG
*"     VALUE(PO_MENGE) TYPE  ZPO_MIGO_ITEM-MENGE
*"     VALUE(PO_MEINS) TYPE  ZPO_MIGO_ITEM-MEINS
*"     VALUE(PO_LICHA) TYPE  ZPO_MIGO_ITEM-LICHA
*"     VALUE(PO_DATE) TYPE  ZPO_MIGO_HEADER-EBELN
*"     VALUE(PO_VEN_INV) TYPE  ZPO_MIGO_ITEM-VENDOR_INV
*"----------------------------------------------------------------------

  DATA : WA_MIGO_HEADER TYPE ZPO_MIGO_HEADER,
         WA_MIGO_ITEM   TYPE ZPO_MIGO_ITEM,
         IT_MIGO_HEADER TYPE TABLE OF ZPO_MIGO_HEADER,
         IT_MIGO_ITEM   TYPE TABLE OF ZPO_MIGO_ITEM.
  TYPES : BEGIN OF TY_ZPO_MIGO_HEADER1,
          ASN_NO TYPE ZPO_MIGO_HEADER-ASN_NO,
          EBELN TYPE ZPO_MIGO_HEADER-EBELN,
          BUDAT TYPE ZPO_MIGO_HEADER-BUDAT,
          XBLNR TYPE ZPO_MIGO_HEADER-XBLNR ,
          STATU TYPE ZPO_MIGO_HEADER-FRGRL,
          END OF TY_ZPO_MIGO_HEADER1.

  DATA:   WA_MIGO_ITEM1   TYPE TY_ZPO_MIGO_HEADER1,
          IT_MIGO_HEADER1 TYPE TABLE OF TY_ZPO_MIGO_HEADER1.

  TYPES: BEGIN OF TY_EKPO,
       EBELN TYPE EBELN,
       EBELP TYPE EBELP,
       MATNR TYPE MATNR,
       WERKS TYPE EWERK,
       LGORT TYPE LGORT_D,
       MENGE TYPE BSTMG,
       MEINS TYPE BSTME,
       INSMK TYPE INSMK,
       END OF TY_EKPO.

  DATA: WA_EKPO  TYPE TY_EKPO,
        IT_EKPO  TYPE STANDARD TABLE OF TY_EKPO.

  DATA: LV_DATE1 TYPE SY-DATUM ,
        LV_DATE TYPE CHAR10,
        LV_DATE2 TYPE SY-DATUM ,
        LV_DATE3 TYPE CHAR10.

  LV_DATE1 = SY-DATUM  .
  CONCATENATE LV_DATE1+6(2) LV_DATE1+4(2) LV_DATE1+0(4) INTO LV_DATE SEPARATED BY '.' .

  WA_MIGO_HEADER-ASN_NO = PO_ASN_NO.
  WA_MIGO_HEADER-EBELN = PO_EBELN.
  WA_MIGO_HEADER-BUDAT = LV_DATE1.
  WA_MIGO_HEADER-XBLNR = PO_XBLNR.
  WA_MIGO_HEADER-FRGRL = PO_STATU.
  WA_MIGO_HEADER-BKTXT = PO_ASN_NO.
  APPEND WA_MIGO_HEADER TO IT_MIGO_HEADER .

  WA_MIGO_ITEM-ASN_NO = PO_ASN_NO.
  WA_MIGO_ITEM-EBELN = PO_EBELN.
  WA_MIGO_ITEM-EBELP = PO_EBELP.
  WA_MIGO_ITEM-MATNR = PO_MATNR.
  WA_MIGO_ITEM-LSMNG = PO_MENGE.
  WA_MIGO_ITEM-MENGE = PO_QTY.
  WA_MIGO_ITEM-ERFMG = PO_MENGE.
  WA_MIGO_ITEM-VENDOR_INV = PO_VEN_INV.

  WA_MIGO_ITEM-MEINS = PO_MEINS.
  WA_MIGO_ITEM-LICHA = PO_LICHA.
*  CONCATENATE PO_DATE+8(2) PO_DATE+5(2) PO_DATE+0(4) INTO LV_DATE3 SEPARATED BY '.' .
  WA_MIGO_ITEM-BUDAT = PO_DATE.
  APPEND WA_MIGO_ITEM TO IT_MIGO_ITEM.

*    IF WA_MIGO_HEADER-ASN_NO = ASN_NO .
*      UPDATE ZPO_MIGO_HEADER SET ASN_NO = WA_MIGO_HEADER-ASN_NO EBELN = WA_MIGO_HEADER-EBELN BUDAT = WA_MIGO_HEADER-BUDAT  XBLNR = WA_MIGO_HEADER-XBLNR STATU = WA_MIGO_HEADER-STATU WHERE ASN_NO = WA_MIGO_HEADER-ASN_NO.
*      UPDATE ZPO_MIGO_ITEM SET EBELN = WA_MIGO_HEADER-EBELN EBELP = WA_MIGO_ITEM-EBELP MATNR = WA_MIGO_ITEM-MATNR MENGE = WA_MIGO_ITEM-MENGE MEINS = WA_MIGO_ITEM-MEINS LICHA = WA_MIGO_ITEM-LICHA.
*    ENDIF.

  MODIFY ZPO_MIGO_HEADER FROM TABLE IT_MIGO_HEADER.
  MODIFY ZPO_MIGO_ITEM FROM TABLE IT_MIGO_ITEM.

*  CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
*    EXPORTING
*      INPUT         = WA_MIGO_ITEM-MATNR
*   IMPORTING
*     OUTPUT        = WA_MIGO_ITEM-MATNR .
*
*  SELECT EBELN EBELP MATNR WERKS LGORT MENGE MEINS INSMK
*       FROM EKPO
*       INTO TABLE IT_EKPO
*       WHERE EBELN = WA_MIGO_ITEM-EBELN AND MATNR = WA_MIGO_ITEM-MATNR.
*
*  LOOP AT IT_EKPO INTO WA_EKPO WHERE ebeln  = WA_MIGO_ITEM-EBELN AND MATNR = WA_MIGO_ITEM-MATNR .
*    WA_MIGO_ITEM-MENGE = WA_EKPO-MENGE.
*    WA_MIGO_ITEM-INSMK = WA_EKPO-INSMK.
*    WA_MIGO_ITEM-LGORT = WA_EKPO-LGORT.
*  ENDLOOP.
*  APPEND WA_MIGO_ITEM TO IT_MIGO_ITEM.
*  MODIFY ZPO_MIGO_ITEM FROM TABLE IT_MIGO_ITEM.

ENDFUNCTION.
