"Name: \PR:SAPMV60A\FO:CUST_HEAD_ACTIVATE\SE:BEGIN\EI
ENHANCEMENT 0 ZPOD.
*

  IF VBRK-FKART EQ 'YBBR' OR VBRK-FKART EQ 'YBDE'  OR  VBRK-FKART EQ 'YBEO' OR VBRK-FKART EQ 'YBFS'
      OR VBRK-FKART EQ 'YBTE' OR VBRK-FKART EQ 'YBDP' OR VBRK-FKART EQ 'YIND' OR VBRK-FKART EQ 'YB2B'
    OR VBRK-FKART EQ 'YLBR'      .

VBRK-ENTRY_DATE = sy-datum .
VBRK-ENTRY_TIME   = SY-UZEIT .
    LOOP AT SCREEN.
    IF SCREEN-NAME EQ 'TABSTRIP_TAB06'.
      GS_CUST_TAB-HEAD_CAPTION  ='Proof of Delivery'.
      GS_CUST_TAB-HEAD_PROGRAM  = 'ZBILLHEADER' .
      GS_CUST_TAB-HEAD_DYNPRO = '0002' .
      IF NOT GS_CUST_TAB-HEAD_DYNPRO IS INITIAL .
        SCREEN-ACTIVE = 1 .
        SCREEN-INVISIBLE = 0 .
        MODIFY SCREEN .
TABSTRIP_TAB06 = GS_CUST_TAB-HEAD_CAPTION .
ENDIF.
      ENDIF.
 ENDLOOP.

 ENDIF.


ENDENHANCEMENT.
