*&---------------------------------------------------------------------*
*& Include ZSALES_MONTHLY_TGT_TOP                            Module Pool      ZSALES_MONTHLY_TGT
*&
*&---------------------------------------------------------------------*

PROGRAM ZSALES_MONTHLY_TGT.


DATA : P_MONT TYPE T54C6-SMONT,
       P_YEAR TYPE T54C6-SYEAR . "N.

TYPES: BEGIN OF TY_TPAR,
       PARVW TYPE TPAR-PARVW,
       NRART TYPE TPAR-NRART,
       END OF TY_TPAR.

DATA: IT_TPAR TYPE TABLE OF TY_TPAR,
      WA_TPAR TYPE TY_TPAR.

TYPES: BEGIN OF TY_KNVP,
       PARVW TYPE KNVP-PARVW,
       PERNR TYPE KNVP-PERNR,
       END OF TY_KNVP.

DATA: IT_KNVP TYPE TABLE OF TY_KNVP,
      WA_KNVP TYPE TY_KNVP.


TYPES: BEGIN OF TY_PA0001,
        PERNR TYPE PA0001-PERNR,
        ENAME TYPE PA0001-ENAME,
        ENDDA TYPE PA0001-ENDDA,
        BEGDA TYPE PA0001-BEGDA,
      END OF TY_PA0001.

DATA : IT_PA001 TYPE TABLE OF TY_PA0001,
       WA_PA001 TYPE TY_PA0001.

TYPES: BEGIN OF TY_PA0000,
        PERNR TYPE PA0000-PERNR,
        ENDDA TYPE PA0000-ENDDA,
        BEGDA TYPE PA0000-BEGDA,
        STAT2 TYPE PA0000-STAT2,
      END OF TY_PA0000.

DATA : IT_PA000 TYPE TABLE OF TY_PA0000,
       WA_PA000 TYPE TY_PA0000.

TYPES :  BEGIN OF TY_modify,
        EMPLOY_CODE TYPE ZSALES_MONTH_TGT-EMPLOY_CODE,
        EMP_NAME TYPE ZSALES_MONTH_TGT-EMP_NAME,
        ENDDA TYPE PA0001-ENDDA,
        BEGDA TYPE PA0001-BEGDA,
        STAT2 TYPE PA0000-STAT2,
        MON TYPE ZSALES_MONTH_TGT-MON,
        YR TYPE ZSALES_MONTH_TGT-YR,
        CX TYPE ZSALES_MONTH_TGT-CX,
        CY TYPE ZSALES_MONTH_TGT-CY,
        DECO TYPE ZSALES_MONTH_TGT-DECO,
        SNC TYPE ZSALES_MONTH_TGT-SNC,
        PROJECT TYPE ZSALES_MONTH_TGT-PROJECT,
        CKY TYPE ZSALES_MONTH_TGT-CKY,
      END OF TY_modify.

DATA : it_modify TYPE TABLE OF ty_modify,
       wa_modify TYPE ty_modify.


DATA : IT_FINAL TYPE TABLE OF ZSALES_MONTH_TGT,
       WA_FINAL TYPE ZSALES_MONTH_TGT.

DATA : STA TYPE C .
