*&---------------------------------------------------------------------*
*& Report  ZSALESCOLLECTION
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*

REPORT ZSALESCOLLECTION.

*TABLES:KNA1,BSID,BSAD.

TYPES: BEGIN OF TY_KNA1,
       KUNNR TYPE KNA1-KUNNR,                  " Customer Number
       NAME1 TYPE KNA1-NAME1,                  " Customer Name
       END OF TY_KNA1.

DATA: IT_KNA1 TYPE TABLE OF TY_KNA1,
      WA_KNA1 TYPE TY_KNA1.

TYPES: BEGIN OF TY_VBPA,
       VBELN TYPE VBPA-VBELN,
       KUNNR TYPE VBPA-KUNNR,                  " Customer
       PARVW TYPE VBPA-PARVW,                  " Partner Functn
       PERNR TYPE VBPA-PERNR,                  " Personnel No.
       END OF TY_VBPA.

DATA: IT_VBPA TYPE TABLE OF TY_VBPA,
      WA_VBPA TYPE TY_VBPA.

TYPES: BEGIN OF TY_VBRP,
       VBELN TYPE VBRP-VBELN,
       VKBUR TYPE VBRP-VKBUR,                  " sales office
END OF TY_VBRP.

DATA: IT_VBRP TYPE TABLE OF TY_VBRP,
      WA_VBRP TYPE TY_VBRP.

TYPES: BEGIN OF TY_VBRK,
       VBELN TYPE VBPA-VBELN,
       KDGRP TYPE VBRK-KDGRP,
       KUNAG TYPE VBRK-KUNAG,
END OF TY_VBRK.

DATA: IT_VBRK TYPE TABLE OF TY_VBRK,
      WA_VBRK TYPE TY_VBRK.

TYPES:BEGIN OF TY_ZSAL_ZONE_REG,
  VKBUR TYPE ZSAL_ZONE_REG-VKBUR,
  NAME1 TYPE ZSAL_ZONE_REG-NAME1,
  ZONE1 TYPE ZSAL_ZONE_REG-ZONE1,
  REGIO TYPE ZSAL_ZONE_REG-REGIO,
  END OF TY_ZSAL_ZONE_REG.

DATA:IT_ZSAL_ZONE_REG TYPE TABLE OF TY_ZSAL_ZONE_REG,
     WA_ZSAL_ZONE_REG TYPE TY_ZSAL_ZONE_REG.

TYPES: BEGIN OF TY_BKPF,
      BUKRS TYPE BKPF-BUKRS,
      BELNR TYPE BKPF-BELNR,
      GJAHR TYPE BKPF-GJAHR,
      BLART TYPE BKPF-BLART,
      BLDAT TYPE BKPF-BLDAT,
      BUDAT TYPE BKPF-BUDAT,
      TCODE TYPE BKPF-TCODE,
      XBLNR TYPE BKPF-XBLNR,
      PSOBT TYPE BKPF-PSOBT,
  END OF TY_BKPF.

DATA: IT_BKPF TYPE TABLE OF TY_BKPF,
    WA_BKPF TYPE TY_BKPF.

TYPES: BEGIN OF TY_BSEG,
      BUKRS TYPE BSEG-BUKRS,
      BELNR TYPE BSEG-BELNR,
      GJAHR TYPE BSEG-GJAHR,
      KUNNR TYPE BSEG-KUNNR,
      BUZEI TYPE BSEG-BUZEI,  "Line item
      AUGDT TYPE BSEG-AUGDT,  "Clearing
      AUGCP TYPE BSEG-AUGCP,  "ClearingEntDate
      AUGBL TYPE BSEG-AUGBL,  "Clrng doc.
      XUMSW TYPE BSEG-XUMSW,  "Sales-Related
      VBELN TYPE BSEG-VBELN,  "Billing Doc.
      AGZEI TYPE BSEG-AGZEI,  "Clearing Item
      AUGGJ TYPE BSEG-AUGGJ,  "Year of Clearing
      SHKZG TYPE BSEG-SHKZG,
      DMBTR TYPE BSEG-DMBTR,
      REBZG TYPE BSEG-REBZG,
      REBZJ TYPE BSEG-REBZJ,
END OF TY_BSEG.

DATA: IT_BSEG TYPE TABLE OF TY_BSEG,
    WA_BSEG TYPE TY_BSEG,
    IT_BSEG_CLR1 TYPE TABLE OF TY_BSEG,
    WA_BSEG_CLR1 TYPE TY_BSEG.

TYPES: BEGIN OF TY_BSEG_CLR,
BUKRS_CLR   TYPE  BSE_CLR-BUKRS_CLR,     "Company Code
BELNR_CLR   TYPE  BSE_CLR-BELNR_CLR,     "Document Number
GJAHR_CLR   TYPE  BSE_CLR-GJAHR_CLR,     "Fiscal Year
AGZEI   TYPE  BSE_CLR-AGZEI,       "Clearing item
BUKRS   TYPE  BSE_CLR-BUKRS,       "Company Code
BELNR   TYPE  BSE_CLR-BELNR,       "Document Number
GJAHR   TYPE  BSE_CLR-GJAHR,       "Fiscal Year
DMBTR   TYPE  BSE_CLR-DMBTR,       "Amount in LC
END OF TY_BSEG_CLR.

DATA: IT_BSEG_CLR TYPE TABLE OF TY_BSEG_CLR,
    WA_BSEG_CLR TYPE TY_BSEG_CLR.


TYPES: BEGIN OF TY_BSID,
       KUNNR TYPE BSID-KUNNR,                  " Customer Number
       AUGBL TYPE BSID-AUGBL,
       BUDAT TYPE BSID-BUDAT,                  " Posting Date in the Document
       BLDAT TYPE BSID-BLDAT,
       BLART TYPE BSID-BLART,
       ZFBDT TYPE BSID-ZFBDT,                  " Baseline Date for Due Date Calculation
       DMBTR TYPE BSID-DMBTR,                  " Amount in Local Currency
       SHKZG TYPE BSID-SHKZG,                  " Debit/Credit Indicator
       XBLNR TYPE BSID-XBLNR,                  " Reference Document Number
       BELNR TYPE BSID-BELNR,                  " Bill Number
       GSBER TYPE BSID-GSBER,                  " Business Area
       SGTXT TYPE BSID-SGTXT,                  " Text Or Remarks
       VBELN TYPE BSID-VBELN,
       UMSKZ TYPE BSID-UMSKZ,
       BUKRS TYPE BSID-BUKRS,
       GJAHR TYPE BSID-GJAHR,
       SKNTO TYPE BSID-SKNTO ,
       UMSKS TYPE BSID-UMSKS,
       AUGDT TYPE BSID-AUGDT,
       ZUONR TYPE BSID-ZUONR,
       BUZEI TYPE BSID-BUZEI,
       ZTERM TYPE BSID-ZTERM,                  " Payt Terms
       ZBD1T TYPE BSID-ZBD1T,                  " Days
END OF TY_BSID.

DATA: IT_BSID TYPE TABLE OF TY_BSID,
      WA_BSID TYPE TY_BSID.

TYPES: BEGIN OF TY_BSAD,
       KUNNR TYPE BSAD-KUNNR,                  " Customer Number
       AUGBL TYPE BSAD-AUGBL,
       BUDAT TYPE BSAD-BUDAT,                  " Posting Date in the Document
       BLDAT TYPE BSAD-BLDAT,
       BLART TYPE BSAD-BLART,
       ZFBDT TYPE BSAD-ZFBDT,                  " Baseline Date for Due Date Calculation
       DMBTR TYPE BSAD-DMBTR,                  " Amount in Local Currency
       SHKZG TYPE BSAD-SHKZG,                  " Debit/Credit Indicator
       XBLNR TYPE BSAD-XBLNR,                  " Reference Document Number
       BELNR TYPE BSAD-BELNR,                  " Bill Number
       GSBER TYPE BSAD-GSBER,                  " Business Area
       SGTXT TYPE BSAD-SGTXT,                  " Text OR Remarks
       VBELN TYPE BSAD-VBELN,                  " Billing Doc.No
       UMSKZ TYPE BSAD-UMSKZ,                  " Spl.Gl.Ind
       BUKRS TYPE BSAD-BUKRS,
       GJAHR TYPE BSAD-GJAHR,
       SKNTO TYPE BSAD-SKNTO ,
       UMSKS TYPE BSAD-UMSKS,
       AUGDT TYPE BSAD-AUGDT,
       ZUONR TYPE BSAD-ZUONR,
       BUZEI TYPE BSAD-BUZEI,
       ZTERM TYPE BSAD-ZTERM,                  " Payt Terms
       ZBD1T TYPE BSAD-ZBD1T,                  " Days
END OF TY_BSAD.

DATA: IT_BSAD TYPE TABLE OF TY_BSAD,
      WA_BSAD TYPE TY_BSAD.


TYPES: BEGIN OF TY_FINAL,
       ZONE TYPE ZSAL_ZONE_REG-ZONE1,          " Zone
       VKBUR TYPE VBRP-VKBUR,                  " Sales office
       PERNR_RS TYPE VBPA-PERNR,               " Personnel No RSM.
       PERNR_MA TYPE VBPA-PERNR,               " Personnel No ASM.
       PERNR_SO TYPE VBPA-PERNR,               " Personnel No SO.
       KDGRP TYPE VBRK-KDGRP,                  " Customer Group
       KUNNR TYPE BSAD-KUNNR,                  " Customer Number
       NAME1 TYPE KNA1-NAME1,                  " Customer Name
       BELNR TYPE BSAD-BELNR,                  " Bill Number
       VBELN TYPE BSAD-VBELN,                  " Billing Document Number
       XBLNR TYPE BSID-XBLNR,                  " Reference Document Number
       BLART TYPE BSID-BLART,                  " Bill Doc. Type
       LC_AMT TYPE BSAD-DMBTR,                 " Amount in Local Currency
       CLR_AMT TYPE BSAD-DMBTR,                " Clr Amount
       CLR_DATE TYPE BSEG-AUGDT,               " Clr date
       BUDAT  TYPE BSID-BUDAT,                 " Posting Date
       BLDAT TYPE BSAD-BLDAT,                  " Posting Date in the Document
       ZTERM TYPE BSID-ZTERM,                  " Payt Terms
       UMSKZ TYPE BSID-UMSKZ,                  " Spl.GL Ind
       SGTXT TYPE BSID-SGTXT,                  " Text OR Remarks
       GSBER TYPE BSID-GSBER,                  " Business Area
       SHKZG TYPE BSID-SHKZG,                  " Dbit/Crdit ind.
       BAL_AMT TYPE BSAD-DMBTR,                " Balance Amount
       STATUS TYPE STRING,                     "Status
       BUKRS TYPE BSID-BUKRS ,
       GJAHR TYPE BSID-GJAHR,
       SKNTO TYPE BSAD-SKNTO ,
       ZBD1T TYPE BSID-ZBD1T,                  " Days
       DUE_DATE TYPE BSAD-BLDAT,
       ARR_DATE TYPE I,
       ZAGE TYPE P DECIMALS 2,              " Not Due
       ZAGE1 TYPE P DECIMALS 2,             " A1 < 30 Days
       ZAGE2 TYPE P DECIMALS 2,             " A2 31-45 Days
       ZAGE3 TYPE P DECIMALS 2,             " A3 46-90 Days
       ZAGE4 TYPE P DECIMALS 2,             " A4 91-180 Days
       ZAGE5 TYPE P DECIMALS 2,             " A5 Above 180 Days
       PSOBT TYPE BKPF-PSOBT,
       PERNR TYPE VBPA-PERNR,               "ID
       SNAME_RS TYPE PA0001-SNAME,          "RS Name
       SNAME_MA TYPE PA0001-SNAME,          "AS Name
       SNAME_SO TYPE PA0001-SNAME,          "SO Name
       KTEXT TYPE T151T-KTEXT,              " Cust Group Name
       LV_OPN TYPE BSAD-DMBTR,
      RV_OPN TYPE BSAD-DMBTR,
 END OF TY_FINAL.


DATA: IT_FINAL TYPE TABLE OF TY_FINAL WITH HEADER LINE,
      WA_FINAL TYPE TY_FINAL.

TYPES:BEGIN OF STR_PA0001,
      PERNR TYPE PA0001-PERNR,
      ENDDA TYPE PA0001-ENDDA,
      BEGDA TYPE PA0001-BEGDA,
      SNAME TYPE PA0001-SNAME,
      END OF STR_PA0001.

DATA: IT_PA0001 TYPE TABLE OF STR_PA0001,
      WA_PA0001 TYPE STR_PA0001.

TYPES:BEGIN OF TY_T151T,
      SPRAS TYPE T151T-SPRAS,
      KDGRP TYPE T151T-KDGRP,
      KTEXT TYPE T151T-KTEXT,
      END OF TY_T151T.

DATA: IT_T151T TYPE TABLE OF TY_T151T,
      WA_T151T TYPE TY_T151T.

DATA: OR_KUNNR TYPE KNA1-KUNNR,
      OR_BUKRS TYPE BSID-BUKRS,
      OR_BSAD  TYPE BSAD-BUDAT.

DATA: LV_OPN TYPE BSAD-DMBTR,
      RV_OPN TYPE BSAD-DMBTR,
      LV_TOTAL TYPE BSAD-DMBTR,
      LV_TRANS TYPE BSAD-DMBTR,
      LV_DATE TYPE SY-DATUM,
      LV_FRDAT TYPE SY-DATUM,
      LV_TODAT TYPE SY-DATUM,
      LV_SUM TYPE BSAD-DMBTR,
      LV_BUK TYPE T001-BUKRS,
      LV_CRAMT TYPE BSAD-DMBTR,
      LV_DBAMT TYPE BSAD-DMBTR.


DATA:T_DAYS TYPE I,
     S_DATE TYPE SY-DATUM.

S_DATE = SY-DATUM.

SELECTION-SCREEN: BEGIN OF BLOCK  B1 WITH FRAME TITLE TEXT-001.
SELECT-OPTIONS: SO_KUNNR FOR OR_KUNNR,
                SO_BUKRS FOR OR_BUKRS  DEFAULT '1000' NO INTERVALS NO-EXTENSION OBLIGATORY,
                SO_BUDAT FOR OR_BSAD DEFAULT '20180401' TO '20190331'.
SELECTION-SCREEN: END OF BLOCK B1.

PERFORM GET_DATA .
PERFORM READ_DATA .

************** ALv Declaraton starts *****************
  DATA: IT_FIELDCAT TYPE  SLIS_T_FIELDCAT_ALV,
        WA_FIELDCAT TYPE SLIS_FIELDCAT_ALV,
        WA_LAYOUT TYPE SLIS_LAYOUT_ALV,
        IT_REPID TYPE SY-REPID VALUE SY-REPID.

  PERFORM FIELDCAT.
  PERFORM LAYOUT.
  PERFORM DISPLAY.


************** ALv Declaraton ends *****************

*&---------------------------------------------------------------------*
*&      Form  GET_DATA
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
FORM GET_DATA .
    SELECT
    BUKRS
    BELNR
    GJAHR
    BLART
    BLDAT
    BUDAT
    TCODE
    XBLNR
    PSOBT
    INTO TABLE IT_BKPF
    FROM BKPF WHERE BUDAT IN SO_BUDAT AND BUKRS IN SO_BUKRS AND BLART = 'RV'.

  IF IT_BKPF IS NOT INITIAL.

      SELECT "#EC CI_DB_OPERATION_OK[2431747] " Added by <IT-CAR Tool> during Code Remediation
        BUKRS
        BELNR
        GJAHR
        KUNNR
        BUZEI
        AUGDT
        AUGCP
        AUGBL
        XUMSW
        VBELN
        AGZEI
        AUGGJ
        SHKZG
      DMBTR
      REBZG
      REBZJ
      FROM BSEG INTO TABLE IT_BSEG FOR ALL ENTRIES IN IT_BKPF WHERE BELNR = IT_BKPF-BELNR
      AND GJAHR = IT_BKPF-GJAHR AND BUKRS = IT_BKPF-BUKRS AND KUNNR IN SO_KUNNR ORDER BY PRIMARY KEY.  " Added by <IT-CAR Tool> during Code Remediation

              SELECT "#EC CI_DB_OPERATION_OK[2431747] " Added by <IT-CAR Tool> during Code Remediation
        BUKRS
        BELNR
        GJAHR
        KUNNR
        BUZEI
        AUGDT
        AUGCP
        AUGBL
        XUMSW
        VBELN
        AGZEI
        AUGGJ
        SHKZG
      DMBTR
      REBZG
      REBZJ
      FROM BSEG INTO TABLE IT_BSEG_CLR1 FOR ALL ENTRIES IN IT_BSEG WHERE GJAHR = IT_BSEG-GJAHR AND BUKRS = IT_BSEG-BUKRS AND VBELN = IT_BSEG-VBELN ORDER BY PRIMARY KEY.  " Added by <IT-CAR Tool> during Code Remediation

SORT IT_BSEG_CLR1 BY BELNR.

  APPEND LINES OF IT_BSEG_CLR1 TO IT_BSEG.

    IF SY-SUBRC NE 0.
      MESSAGE 'Enter Valid Input' TYPE 'E'.
    ENDIF.
  ENDIF.
  IF IT_BSEG IS NOT INITIAL.

    SELECT
    BUKRS_CLR
    BELNR_CLR
    GJAHR_CLR
    AGZEI
    BUKRS
    BELNR
    GJAHR
    DMBTR
    FROM BSE_CLR INTO TABLE IT_BSEG_CLR FOR ALL ENTRIES IN IT_BSEG WHERE BELNR_CLR = IT_BSEG-AUGBL AND GJAHR_CLR = IT_BSEG-AUGGJ AND BUKRS_CLR = IT_BSEG-BUKRS AND AGZEI = IT_BSEG-AGZEI.

    SELECT
    KUNNR
    AUGBL
    BUDAT
    BLDAT
    BLART
    ZFBDT
    DMBTR
    SHKZG
    XBLNR
    BELNR
    GSBER
    SGTXT
    VBELN
    UMSKZ
    BUKRS
    GJAHR
    SKNTO
    UMSKS
    AUGDT
    ZUONR
    BUZEI
    ZTERM
    ZBD1T
      FROM BSID INTO TABLE IT_BSID FOR ALL ENTRIES IN IT_BKPF
      WHERE BELNR = IT_BKPF-BELNR AND XBLNR = IT_BKPF-XBLNR AND BUKRS = IT_BKPF-BUKRS AND KUNNR IN SO_KUNNR.

    SELECT
    KUNNR
    AUGBL
    BUDAT
    BLDAT
    BLART
    ZFBDT
    DMBTR
    SHKZG
    XBLNR
    BELNR
    GSBER
    SGTXT
    VBELN
    UMSKZ
    BUKRS
    GJAHR
    SKNTO
    UMSKS
    AUGDT
    ZUONR
    BUZEI
    ZTERM
    ZBD1T
      FROM BSAD INTO TABLE IT_BSAD FOR ALL ENTRIES IN IT_BKPF
      WHERE BELNR = IT_BKPF-BELNR AND XBLNR = IT_BKPF-XBLNR AND BUKRS = IT_BKPF-BUKRS AND KUNNR IN SO_KUNNR.
  ENDIF.

  SORT IT_BSAD BY BELNR AUGBL BUDAT.

  APPEND LINES OF IT_BSAD TO IT_BSID.

  IF IT_BSID IS NOT INITIAL.
    SELECT
       KUNNR
       NAME1
       FROM KNA1 INTO TABLE IT_KNA1 FOR ALL ENTRIES IN IT_BSID
       WHERE KUNNR = IT_BSID-KUNNR.

    SELECT
      VBELN
      KDGRP
      KUNAG
     FROM VBRK INTO TABLE IT_VBRK FOR ALL ENTRIES IN IT_BSID
       WHERE VBELN = IT_BSID-VBELN.

     SELECT
       SPRAS
       KDGRP
       KTEXT
     FROM T151T INTO TABLE IT_T151T FOR ALL ENTRIES IN IT_VBRK
       WHERE KDGRP = IT_VBRK-KDGRP AND SPRAS = 'EN'.


    SELECT
      VBELN
      VKBUR
      FROM VBRP INTO TABLE IT_VBRP FOR ALL ENTRIES IN IT_BSID
   WHERE VBELN = IT_BSID-VBELN.

  ENDIF.

  IF IT_VBRK IS NOT INITIAL.
    SELECT
      VBELN
      KUNNR
      PARVW
      PERNR
      FROM VBPA INTO TABLE IT_VBPA FOR ALL ENTRIES IN IT_VBRK
      WHERE VBELN = IT_VBRK-VBELN AND PARVW IN ('L2','L3','L5').
  ENDIF.

  SELECT   PERNR
           ENDDA
           BEGDA
           SNAME
           FROM PA0001 INTO TABLE IT_PA0001 FOR ALL ENTRIES IN IT_VBPA WHERE PERNR = IT_VBPA-PERNR.


  IF IT_VBRP IS NOT INITIAL.
    SELECT
      VKBUR
      NAME1
      ZONE1
      REGIO
      FROM
      ZSAL_ZONE_REG
      INTO TABLE IT_ZSAL_ZONE_REG FOR ALL ENTRIES IN IT_VBRP
      WHERE VKBUR = IT_VBRP-VKBUR.
  ENDIF.
ENDFORM.                    "GET_DATA

*&---------------------------------------------------------------------*
*&      Form  READ_DATA
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
FORM READ_DATA.


  LOOP AT IT_BSID INTO WA_BSID.
    READ TABLE IT_BKPF INTO WA_BKPF WITH KEY BELNR = WA_BSID-BELNR.
    READ TABLE IT_VBRP INTO WA_VBRP WITH KEY VBELN = WA_BSID-VBELN.
    WA_FINAL-VKBUR = WA_VBRP-VKBUR.
    READ TABLE IT_ZSAL_ZONE_REG INTO WA_ZSAL_ZONE_REG WITH KEY VKBUR = WA_FINAL-VKBUR.
    WA_FINAL-ZONE = WA_ZSAL_ZONE_REG-ZONE1.
    READ TABLE IT_VBPA INTO WA_VBPA WITH KEY VBELN = WA_BSID-VBELN KUNNR = WA_BSID-KUNNR.
    LOOP AT IT_VBPA INTO WA_VBPA WHERE VBELN = WA_BSID-VBELN.
      IF WA_VBPA-PARVW = 'L2'.
        IF WA_VBPA-VBELN = WA_BSID-VBELN .
          WA_FINAL-PERNR_RS = WA_VBPA-PERNR.
        ENDIF.
      ENDIF.

      IF WA_VBPA-PARVW = 'L3'.
        IF WA_VBPA-VBELN = WA_BSID-VBELN .
          WA_FINAL-PERNR_MA = WA_VBPA-PERNR.
        ENDIF.
      ENDIF.
      IF WA_VBPA-PARVW = 'L5'.
        IF WA_VBPA-VBELN = WA_BSID-VBELN .
          WA_FINAL-PERNR_SO = WA_VBPA-PERNR.
        ENDIF.
      ENDIF.
      READ TABLE IT_PA0001 INTO WA_PA0001 WITH KEY PERNR =  WA_FINAL-PERNR_RS.
      IF SY-SUBRC = 0.
      WA_FINAL-SNAME_RS = WA_PA0001-SNAME.
      ENDIF.
      READ TABLE IT_PA0001 INTO WA_PA0001 WITH KEY PERNR =  WA_FINAL-PERNR_MA.
      IF SY-SUBRC = 0.
      WA_FINAL-SNAME_MA = WA_PA0001-SNAME.
      ENDIF.
      READ TABLE IT_PA0001 INTO WA_PA0001 WITH KEY PERNR =  WA_FINAL-PERNR_SO.
      IF SY-SUBRC = 0.
      WA_FINAL-SNAME_SO = WA_PA0001-SNAME.
      ENDIF.
      CLEAR: WA_VBPA , WA_PA0001.
    ENDLOOP.

    READ TABLE IT_VBRK INTO WA_VBRK WITH KEY VBELN = WA_BSID-VBELN.
    WA_FINAL-KDGRP = WA_VBRK-KDGRP.
    READ TABLE IT_T151T INTO WA_T151T WITH KEY KDGRP = WA_FINAL-KDGRP.
    WA_FINAL-KTEXT = WA_T151T-KTEXT.
    WA_FINAL-KUNNR = WA_BSID-KUNNR.
    READ TABLE IT_KNA1 INTO WA_KNA1 WITH KEY KUNNR = WA_BSID-KUNNR.
    WA_FINAL-NAME1 = WA_KNA1-NAME1.
    WA_FINAL-BELNR = WA_BSID-BELNR.
    WA_FINAL-XBLNR = WA_BSID-XBLNR.
    WA_FINAL-VBELN = WA_BSID-VBELN.
    WA_FINAL-BLART = WA_BSID-BLART.
    WA_FINAL-LC_AMT = WA_BSID-DMBTR.
    WA_FINAL-ZTERM = WA_BSID-ZTERM.
    WA_FINAL-BLDAT = WA_BSID-BLDAT.
    WA_FINAL-BUDAT = WA_BSID-BUDAT.
    WA_FINAL-GSBER = WA_BSID-GSBER.
    WA_FINAL-SGTXT = WA_BSID-SGTXT.
    WA_FINAL-UMSKZ = WA_BSID-UMSKZ.
    WA_FINAL-BUKRS = WA_BSID-BUKRS.
    WA_FINAL-SHKZG = WA_BSID-SHKZG.
    WA_FINAL-ZBD1T = WA_BSID-ZBD1T.
    WA_FINAL-DUE_DATE = WA_BSID-BLDAT + WA_FINAL-ZBD1T .
    WA_FINAL-PSOBT = WA_BKPF-PSOBT.

    IF WA_FINAL-DUE_DATE => WA_BSID-AUGDT.
       CALL FUNCTION 'HR_99S_INTERVAL_BETWEEN_DATES'
          EXPORTING
            BEGDA = WA_FINAL-DUE_DATE
            ENDDA = S_DATE
          IMPORTING
            DAYS  = T_DAYS.
            WA_FINAL-ARR_DATE = T_DAYS.
    ELSE.
        CALL FUNCTION 'HR_99S_INTERVAL_BETWEEN_DATES'
          EXPORTING
            BEGDA = WA_FINAL-DUE_DATE
            ENDDA = WA_BSID-AUGDT
          IMPORTING
            DAYS  = T_DAYS.
            WA_FINAL-ARR_DATE = T_DAYS.
    ENDIF.


    IF WA_FINAL-ARR_DATE <= 0.
      WA_FINAL-ZAGE = WA_FINAL-LC_AMT.    "#EC CI_FLDEXT_OK[2610650]   "Added by SPLABAP during code remediation
    ELSEIF WA_FINAL-ARR_DATE BETWEEN 1 AND 30.
      WA_FINAL-ZAGE1 = WA_FINAL-LC_AMT. "#EC CI_FLDEXT_OK[2610650]     "Added by SPLABAP during code remediation
    ELSEIF WA_FINAL-ARR_DATE BETWEEN 31 AND 45.
      WA_FINAL-ZAGE2 = WA_FINAL-LC_AMT. "#EC CI_FLDEXT_OK[2610650]    "Added by SPLABAP during code remediation
    ELSEIF WA_FINAL-ARR_DATE BETWEEN 46 AND 90.
      WA_FINAL-ZAGE3 = WA_FINAL-LC_AMT.   "#EC CI_FLDEXT_OK[2610650]   "Added by SPLABAP during code remediation
    ELSEIF WA_FINAL-ARR_DATE BETWEEN 91 AND 180.
      WA_FINAL-ZAGE4 = WA_FINAL-LC_AMT. "#EC CI_FLDEXT_OK[2610650]   "Added by SPLABAP during code remediation
    ELSEIF WA_FINAL-ARR_DATE > 180.
      WA_FINAL-ZAGE5 = WA_FINAL-LC_AMT.   "#EC CI_FLDEXT_OK[2610650]   "Added by SPLABAP during code remediation
    ENDIF.


    READ TABLE IT_BSEG_CLR INTO WA_BSEG_CLR WITH KEY BELNR_CLR = WA_BSID-AUGBL BELNR = WA_BSID-BELNR.
    WA_FINAL-CLR_AMT = WA_BSEG_CLR-DMBTR.
    WA_FINAL-CLR_DATE = WA_BSID-AUGDT.
    WA_FINAL-BAL_AMT = WA_FINAL-LC_AMT - WA_FINAL-CLR_AMT.
    IF WA_FINAL-BAL_AMT = 0.
      WA_FINAL-STATUS = 'Fully Paid'.
    ELSEIF WA_FINAL-BAL_AMT = WA_FINAL-LC_AMT .
      WA_FINAL-STATUS = 'NOT Paid'.
    ELSEIF WA_FINAL-BAL_AMT < WA_FINAL-LC_AMT.
      WA_FINAL-STATUS = 'Partially Paids'.
    ENDIF.

    IF WA_FINAL-STATUS = 'NOT Paid'.
      "READ TABLE IT_BSEG INTO WA_BSEG WITH KEY BELNR = WA_BSID-BELNR.

    LOOP AT IT_BSEG INTO WA_BSEG WHERE VBELN = WA_BSID-VBELN AND REBZG = WA_BSID-BELNR AND REBZJ = WA_BSID-GJAHR.

      IF WA_BSEG-SHKZG = 'H'.
        WA_FINAL-RV_OPN  = WA_FINAL-RV_OPN + WA_BSEG-DMBTR.
        WA_FINAL-CLR_DATE = WA_BSEG-AUGDT.
      ENDIF.

    ENDLOOP.
    CLEAR : WA_BSEG.
    WA_FINAL-BAL_AMT = WA_FINAL-LC_AMT - WA_FINAL-RV_OPN.
    WA_FINAL-CLR_AMT = WA_FINAL-RV_OPN.

    IF WA_FINAL-BAL_AMT < WA_FINAL-LC_AMT.
      WA_FINAL-STATUS = 'Partially Paids'.
    ENDIF.
    ENDIF.
    APPEND WA_FINAL TO IT_FINAL.
    SORT IT_FINAL BY BELNR BUDAT .
    CLEAR : WA_FINAL,WA_BSID,WA_VBRK,WA_VBRP,WA_VBPA,WA_ZSAL_ZONE_REG,WA_BSEG_CLR,WA_BSAD,WA_BKPF,WA_T151T.
  ENDLOOP.
ENDFORM.                    "READ_DATA
FORM FIELDCAT.
  WA_FIELDCAT-FIELDNAME ='ZONE'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Region'.
  WA_FIELDCAT-SELTEXT_L ='Region'.
  WA_FIELDCAT-COL_POS   = 1.
  WA_FIELDCAT-OUTPUTLEN = '15'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='VKBUR'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Branch Code'.
  WA_FIELDCAT-SELTEXT_L ='Branch Code'.
  WA_FIELDCAT-COL_POS   = 2.
  WA_FIELDCAT-OUTPUTLEN = '10'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='PERNR_RS'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='RSM Code'.
  WA_FIELDCAT-SELTEXT_L ='RSM Code'.
  WA_FIELDCAT-COL_POS   = 3.
  WA_FIELDCAT-OUTPUTLEN = '25'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='SNAME_RS'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Regional Manager'.
  WA_FIELDCAT-SELTEXT_L ='Regional Manager'.
  WA_FIELDCAT-COL_POS   = 4.
  WA_FIELDCAT-OUTPUTLEN = '25'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='PERNR_MA'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='ASM Code'.
  WA_FIELDCAT-SELTEXT_L ='ASM Code'.
  WA_FIELDCAT-COL_POS   = 5.
  WA_FIELDCAT-OUTPUTLEN = '25'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='SNAME_MA'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Manager'.
  WA_FIELDCAT-SELTEXT_L ='Manager'.
  WA_FIELDCAT-COL_POS   = 6.
  WA_FIELDCAT-OUTPUTLEN = '25'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='PERNR_SO'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='SO Code'.
  WA_FIELDCAT-SELTEXT_L ='SO Code'.
  WA_FIELDCAT-COL_POS   = 7.
  WA_FIELDCAT-OUTPUTLEN = '25'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='SNAME_SO'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Sales Officer'.
  WA_FIELDCAT-SELTEXT_L ='Sales Officer'.
  WA_FIELDCAT-COL_POS   = 8.
  WA_FIELDCAT-OUTPUTLEN = '25'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='KDGRP'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Customer Classification'.
  WA_FIELDCAT-SELTEXT_L ='Customer Classification'.
  WA_FIELDCAT-COL_POS   = 9.
  WA_FIELDCAT-OUTPUTLEN = '10'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='KTEXT'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Customer Classification Name'.
  WA_FIELDCAT-SELTEXT_L ='Customer Classification Name'.
  WA_FIELDCAT-COL_POS   = 10.
  WA_FIELDCAT-OUTPUTLEN = '15'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='KUNNR'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Customer Code'.
  WA_FIELDCAT-SELTEXT_L ='Customer Code'.
  WA_FIELDCAT-COL_POS   = 11.
  WA_FIELDCAT-OUTPUTLEN = '25'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='NAME1'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Customer Name'.
  WA_FIELDCAT-SELTEXT_L ='Customer Name'.
  WA_FIELDCAT-COL_POS   = 12.
  WA_FIELDCAT-OUTPUTLEN = '35'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='BELNR'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Document Number'.
  WA_FIELDCAT-SELTEXT_L ='Document Number'.
  WA_FIELDCAT-COL_POS   = 13.
  WA_FIELDCAT-OUTPUTLEN = '15'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='BLART'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Document Type'.
  WA_FIELDCAT-SELTEXT_L ='Document Type'.
  WA_FIELDCAT-COL_POS   = 14.
  WA_FIELDCAT-OUTPUTLEN = '5'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='LC_AMT'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Amount'.
  WA_FIELDCAT-SELTEXT_L ='Amount'.
  WA_FIELDCAT-COL_POS   = 15.
  WA_FIELDCAT-OUTPUTLEN = '10'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='BUDAT'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Document Date'.
  WA_FIELDCAT-SELTEXT_L ='Document Date'.
  WA_FIELDCAT-COL_POS   = 16.
  WA_FIELDCAT-OUTPUTLEN = '10'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='ZTERM'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Payment Term'.
  WA_FIELDCAT-SELTEXT_L ='Payment Term'.
  WA_FIELDCAT-COL_POS   = 17.
  WA_FIELDCAT-OUTPUTLEN = '10'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='DUE_DATE'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Due Date'.
  WA_FIELDCAT-SELTEXT_L ='Due Date'.
  WA_FIELDCAT-COL_POS   = 18.
  WA_FIELDCAT-OUTPUTLEN = '10'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='ARR_DATE'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Arrears after net due date'.
  WA_FIELDCAT-SELTEXT_L ='Arrears after net due date'.
  WA_FIELDCAT-COL_POS   = 19.
  WA_FIELDCAT-OUTPUTLEN = '10'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='ZAGE'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Not Due'.
  WA_FIELDCAT-SELTEXT_L ='Not Due'.
  WA_FIELDCAT-COL_POS   = 20.
  WA_FIELDCAT-OUTPUTLEN = '10'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='ZAGE1'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='1-30 Day'.
  WA_FIELDCAT-SELTEXT_L ='1-30 Day'.
  WA_FIELDCAT-COL_POS   = 21.
  WA_FIELDCAT-OUTPUTLEN = '10'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='ZAGE2'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='31-45 Day'.
  WA_FIELDCAT-SELTEXT_L ='31-45 Day'.
  WA_FIELDCAT-COL_POS   = 22.
  WA_FIELDCAT-OUTPUTLEN = '10'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='ZAGE3'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='46-90 Days'.
  WA_FIELDCAT-SELTEXT_L ='46-90 Days'.
  WA_FIELDCAT-COL_POS   = 23.
  WA_FIELDCAT-OUTPUTLEN = '10'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='ZAGE4'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='91-180 Days'.
  WA_FIELDCAT-SELTEXT_L ='91-180 Days'.
  WA_FIELDCAT-COL_POS   = 24.
  WA_FIELDCAT-OUTPUTLEN = '10'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='ZAGE5'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='>181 Day'.
  WA_FIELDCAT-SELTEXT_L ='>181 Day'.
  WA_FIELDCAT-COL_POS   = 25.
  WA_FIELDCAT-OUTPUTLEN = '10'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='CLR_DATE'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Payment Made on'.
  WA_FIELDCAT-SELTEXT_L ='Payment Made on'.
  WA_FIELDCAT-COL_POS   = 26.
  WA_FIELDCAT-OUTPUTLEN = '10'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='CLR_AMT'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Amount Paid'.
  WA_FIELDCAT-SELTEXT_L ='Amount Paid'.
  WA_FIELDCAT-COL_POS   = 27.
  WA_FIELDCAT-OUTPUTLEN = '10'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='BAL_AMT'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Amount Pending'.
  WA_FIELDCAT-SELTEXT_L ='Amount Pending'.
  WA_FIELDCAT-COL_POS   = 28.
  WA_FIELDCAT-OUTPUTLEN = '10'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

*  WA_FIELDCAT-FIELDNAME =''.
*  WA_FIELDCAT-TABNAME =''.
*  WA_FIELDCAT-SELTEXT_S ='Amount adjust due to CN'.
*  WA_FIELDCAT-SELTEXT_L ='Amount adjust due to CN'.
*  WA_FIELDCAT-COL_POS   = 28.
*  WA_FIELDCAT-OUTPUTLEN = '15'.
*  APPEND WA_FIELDCAT TO IT_FIELDCAT.
*  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME ='STATUS'.
  WA_FIELDCAT-TABNAME ='IT_FINAL'.
  WA_FIELDCAT-SELTEXT_S ='Status'.
  WA_FIELDCAT-SELTEXT_L ='Status'.
  WA_FIELDCAT-COL_POS   = 29.
  WA_FIELDCAT-OUTPUTLEN = '15'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  ENDFORM.

FORM LAYOUT .
  WA_LAYOUT-ZEBRA = 'X'.
ENDFORM.

FORM DISPLAY .
  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
   EXPORTING
*   I_INTERFACE_CHECK                 = ' '
*   I_BYPASSING_BUFFER                = ' '
*   I_BUFFER_ACTIVE                   = ' '
   I_CALLBACK_PROGRAM                = IT_REPID
*   I_CALLBACK_PF_STATUS_SET          = ' '
*   I_CALLBACK_USER_COMMAND           = ' '
*   I_CALLBACK_TOP_OF_PAGE            = ' '
*   I_CALLBACK_HTML_TOP_OF_PAGE       = ' '
*   I_CALLBACK_HTML_END_OF_LIST       = ' '
*   I_STRUCTURE_NAME                  =
*   I_BACKGROUND_ID                   = ' '
*   I_GRID_TITLE                      =
*   I_GRID_SETTINGS                   =
     IS_LAYOUT                         = WA_LAYOUT
     IT_FIELDCAT                       = IT_FIELDCAT
*   IT_EXCLUDING                      =
*   IT_SPECIAL_GROUPS                 =
*   IT_SORT                           =
*   IT_FILTER                         =
*   IS_SEL_HIDE                       =
*   I_DEFAULT                         = 'X'
*   I_SAVE                            = ' '
*   IS_VARIANT                        =
*   IT_EVENTS                         =
*   IT_EVENT_EXIT                     =
*   IS_PRINT                          =
*   IS_REPREP_ID                      =
*   I_SCREEN_START_COLUMN             = 0
*   I_SCREEN_START_LINE               = 0
*   I_SCREEN_END_COLUMN               = 0
*   I_SCREEN_END_LINE                 = 0
*   I_HTML_HEIGHT_TOP                 = 0
*   I_HTML_HEIGHT_END                 = 0
*   IT_ALV_GRAPHICS                   =
*   IT_HYPERLINK                      =
*   IT_ADD_FIELDCAT                   =
*   IT_EXCEPT_QINFO                   =
*   IR_SALV_FULLSCREEN_ADAPTER        =
* IMPORTING
*   E_EXIT_CAUSED_BY_CALLER           =
*   ES_EXIT_CAUSED_BY_USER            =
    TABLES
      T_OUTTAB                          = IT_FINAL
* EXCEPTIONS
*   PROGRAM_ERROR                     = 1
*   OTHERS                            = 2
            .
  IF SY-SUBRC <> 0.
* Implement suitable error handling here
  ENDIF.
ENDFORM.
