*&---------------------------------------------------------------------*
*& Include          ZSD_CUSTOMER_MASTER_SEL
*&---------------------------------------------------------------------*

*** Radio buttons for process select *.**
SELECTION-SCREEN BEGIN OF BLOCK b1 WITH FRAME TITLE TEXT-002.
  SELECTION-SCREEN BEGIN OF LINE.
    PARAMETERS:r1 RADIOBUTTON GROUP g1 USER-COMMAND r.
    SELECTION-SCREEN COMMENT 5(50) TEXT-003 FOR FIELD r1.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF LINE.
    PARAMETERS:r2 RADIOBUTTON GROUP g1.
    SELECTION-SCREEN COMMENT 5(50) TEXT-004 FOR FIELD r2.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF LINE.
    PARAMETERS:r3 RADIOBUTTON GROUP g1.
    SELECTION-SCREEN COMMENT 5(50) TEXT-005 FOR FIELD r3.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF LINE.
    PARAMETERS:r4 RADIOBUTTON GROUP g1.
    SELECTION-SCREEN COMMENT 3(50) TEXT-006 FOR FIELD r4.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF LINE.
    PARAMETERS r5 RADIOBUTTON GROUP g1.
    SELECTION-SCREEN COMMENT 3(50) TEXT-007 FOR FIELD r5.
  SELECTION-SCREEN END OF LINE.
*Added on 16.12.2023
*Purpose for DMS Customer Master extension
  SELECTION-SCREEN BEGIN OF LINE.
    PARAMETERS r6 RADIOBUTTON GROUP g1.
    SELECTION-SCREEN COMMENT 3(50) TEXT-r06 FOR FIELD r6.
  SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK b1.

SELECTION-SCREEN BEGIN OF BLOCK b2 WITH FRAME TITLE TEXT-001.
  PARAMETERS:p_flname TYPE localfile MODIF ID bl2.        "File Path
SELECTION-SCREEN END OF BLOCK b2.

*Added By Samsudeen M on 16.12.2023 (Purpose DMS Process)
DATA: lv_kunnr TYPE kna1-kunnr.
SELECTION-SCREEN BEGIN OF BLOCK b3 WITH FRAME TITLE TEXT-b03.
  SELECT-OPTIONS: s_kunnr FOR lv_kunnr MODIF ID bl4.        "Customer Number
SELECTION-SCREEN END OF BLOCK b3.
