*&---------------------------------------------------------------------*
*& Report  ZSD_PRODUCT_MONTHWISE
*&
*&---------------------------------------------------------------------*
*&---------------------------------------------------------------------*
*&Functional                   : Mr.Govindarajan M                     * "
*& Developer                   : Mr.Govindarajan M                     *
*& Created On                  :                                       *
*& Company                     : Sheenlac Paints Pvt Ltd               *
*& Verified By                 :                                       *
*& Title                       : Material Analysis Month Wise Report   *
*& Report Name                 : ZSD_PRODUCT_MONTHWISE                 *
*& Development Id              : kpabap                                *
*& Related Information         : Material Analysis Month Wise Report   *
*&---------------------------------------------------------------------*
REPORT ZSD_PRODUCT_MONTHWISE.

DATA:
      W_AUX_FKDAT TYPE VBRK-FKDAT,
      W_FKART TYPE VBRK-FKART,
      W_VBELN TYPE VBRK-VBELN,
      W_KUNAG TYPE VBRK-KUNAG,
      W_MATNR TYPE VBRP-MATNR,
      W_MTART TYPE MARA-MTART,
      W_MVGR1 TYPE MVKE-MVGR1, "ADDED BY RAM
      W_CHARG TYPE LIPS-CHARG,                               " BATCH FOR INVOICE DETAILS
      W_INV_VKBUR TYPE VBRP-VKBUR,                           " SALES OFFICE FOR INVOICE
      W_SPART TYPE VBRK-SPART,

      COUNTER TYPE I VALUE '0',
      GT_LIST     TYPE VRM_VALUES,
      GWA_LIST    TYPE VRM_VALUE,
      GT_VALUES   TYPE TABLE OF DYNPREAD,                     " INTERNAL TABLE FOR LIST BOX
      GWA_VALUES  TYPE DYNPREAD,                              " WORK AREA FOR LIST BOX
      GV_SELECTED_VALUE(10) TYPE C,
      IT_FIELDCAT  TYPE TABLE OF SLIS_FIELDCAT_ALV,
      WA_FIELDCAT  LIKE LINE OF IT_FIELDCAT,
      IT_SORT TYPE SLIS_T_SORTINFO_ALV,
      WA_SORT LIKE LINE OF IT_SORT,
      G_SENT_TO_ALL TYPE SONV-FLAG,
      G_TAB_LINES   TYPE I,


      W_KUNNR TYPE KNC1-KUNNR,
      W_BUKRS TYPE KNC1-BUKRS,                                " VARIABLE DECLARATIONS FOR ACCOUNT BALANCES
      W_VKBUR TYPE KNVV-VKBUR,                                " SALES OFFICE FOR ACCOUNT BALANCES
*      W_GJAHR TYPE KNC1-GJAHR,
      W_RE_PERIOD TYPE BSID-MONAT,

      W_S_MATNR TYPE MARD-MATNR,                               " VARIABLE DECLARATIONS FOR STOCK
      W_S_BUKRS TYPE T001-BUKRS,
      W_S_HKONT TYPE BSEG-HKONT,
      W_S_WERKS TYPE T001W-WERKS,
      W_S_LGORT TYPE T001L-LGORT,
      W_S_CHARG TYPE MCHB-CHARG,
      W_S_BWTAR TYPE MBEW-BWTAR,
      W_S_BWART TYPE MSEG-BWART,
            W_S_DATUM TYPE MKPF-BUDAT.


DATA : LAYOUT TYPE SLIS_LAYOUT_ALV.

*--------------------------------------------------------------*
* TYPES DECLARATION
*--------------------------------------------------------------*


TYPES: BEGIN OF TY_VBRK_VBRP,                           "FINAL TABLE TYPE FOR OVERVIEW REPORT
       BUKRS TYPE VBRK-BUKRS,
       FKDAT TYPE VBRK-FKDAT,
       SPART TYPE VBRK-SPART,
       VRKME TYPE VBRP-VRKME,
       VBELN TYPE VBRK-VBELN,
       FKART TYPE VBRK-FKART,
       KUNAG TYPE VBRK-KUNAG,
       KUNRG TYPE VBRK-KUNRG,
       VKORG TYPE VBRK-VKORG,
       VTWEG TYPE VBRK-VTWEG,
       NETWR TYPE VBRK-NETWR,
       SFAKN TYPE VBRK-SFAKN,
       KNKLI TYPE VBRK-KNKLI,
       MWSBK TYPE VBRK-MWSBK,
       FKSTO TYPE VBRK-FKSTO,
       POSNR TYPE VBRP-POSNR,
       VKBUR TYPE VBRP-VKBUR,
       MATNR TYPE VBRP-MATNR,
       FKIMG TYPE VBRP-FKIMG,
       VOLUM TYPE VBRP-VOLUM,
       VGBEL TYPE VBRP-VGBEL,
       END OF TY_VBRK_VBRP,


       BEGIN OF TY_TVKBT,
       VKBUR TYPE TVKBT-VKBUR,
       BEZEI TYPE TVKBT-BEZEI,
       END OF TY_TVKBT,

       BEGIN OF TY_TSPAT,
       SPART TYPE TSPAT-SPART,
       VTEXT TYPE TSPAT-VTEXT,
       END OF TY_TSPAT,

       BEGIN OF TY_KNA1,
       KUNNR TYPE KNA1-KUNNR,
       NAME1 TYPE KNA1-NAME1,
       NAME2 TYPE KNA1-NAME2,
       REGIO TYPE KNA1-REGIO,
       END OF TY_KNA1,

       BEGIN OF TY_MARM,
       MATNR TYPE MARM-MATNR,
       MEINH TYPE MARM-MEINH,
       UMREZ TYPE MARM-UMREZ,
       UMREN TYPE MARM-UMREN,
       END OF TY_MARM,

 BEGIN OF GS_T005U ,
       BLAND TYPE T005U-BLAND ,                                                                                                           "TABLE 6
       BEZEI TYPE T005U-BEZEI ,                                  "REGION
       END OF GS_T005U ,

       BEGIN OF TY_FINOVR,                           "FINAL TABLE TYPE FOR OVERVIEW REPORT
       FKDAT TYPE VBRK-FKDAT,
       VKBUR TYPE VBRP-VKBUR,
       KUNRG TYPE VBRK-KUNAG,
       SPART TYPE VBRK-SPART,
       VBELN TYPE VBRK-VBELN,
       MVGR1 TYPE MVKE-MVGR1,
       GBEZEI TYPE TVM1T-BEZEI,
       MATNR TYPE MARA-MATNR,
       MAKTX TYPE MAKT-MAKTX,
       CANDOC(1) TYPE C,
       FKART TYPE VBRK-FKART,
       KUNAG TYPE VBRK-KUNAG,
       KUNNR TYPE KNA1-KUNNR,
       VKORG TYPE VBRK-VKORG,
       VTWEG TYPE VBRK-VTWEG,
       SFAKN TYPE VBRK-SFAKN,
       KNKLI TYPE VBRK-KNKLI,
       MWSBK TYPE VBRK-MWSBK,
       FKSTO TYPE VBRK-FKSTO,
       BTGEW TYPE LIKP-BTGEW, " Commended by Govind on 12.05.2014
       INV_VAL TYPE NETWR,
       POSNR TYPE VBRP-POSNR,
       FKIMG TYPE VBRP-FKIMG,
       VFKIMG TYPE  VBRP-FKIMG,
       NETWR TYPE VBRP-NETWR,
       VNETWR TYPE  VBRP-NETWR,
       BEZEI TYPE TVKBT-BEZEI,
       VTEXT TYPE TSPAT-VTEXT,
       NAME1 TYPE KNA1-NAME1,
       NAME2 TYPE KNA1-NAME2,
       M_VOLUM TYPE MARA-VOLUM,
       QTY_LTR TYPE P DECIMALS 2,
       V_COUNT TYPE I,
       FLAG(1) TYPE C,
       N_MONTH TYPE  T009B-POPER,
         " Qty
       QTY0 TYPE P DECIMALS 2,     " APR
       QTY1 TYPE P DECIMALS 2,        "MAY
       QTY2 TYPE P   DECIMALS 2,   " JUNE
       QTY3 TYPE P DECIMALS 2,  " JULY
       QTY4 TYPE P DECIMALS 2,     " AUG
       QTY5 TYPE P DECIMALS 2,        "SEP
       QTY6 TYPE P   DECIMALS 2,   " OCT
       QTY7 TYPE P DECIMALS 2,  " NOV
       QTY8 TYPE P DECIMALS 2,     " DEC
       QTY9 TYPE P DECIMALS 2,        "JAN
       QTY10 TYPE P   DECIMALS 2,   " FEB
       QTY11 TYPE P DECIMALS 2,  " MAR

       VOL0 TYPE P DECIMALS 2,     " APR
       VOL1 TYPE P DECIMALS 2,        "MAY
       VOL2 TYPE P   DECIMALS 2,   " JUNE
       VOL3 TYPE P DECIMALS 2,  " JULY
       VOL4 TYPE P DECIMALS 2,     " AUG
       VOL5 TYPE P DECIMALS 2,        "SEP
       VOL6 TYPE P   DECIMALS 2,   " OCT
       VOL7 TYPE P DECIMALS 2,  " NOV
       VOL8 TYPE P DECIMALS 2,     " DEC
       VOL9 TYPE P DECIMALS 2,        "JAN
       VOL10 TYPE P   DECIMALS 2,   " FEB
       VOL11 TYPE P DECIMALS 2,  " MAR
       AMT0 TYPE P DECIMALS 2,     " APR
       AMT1 TYPE P DECIMALS 2,        "MAY
       AMT2 TYPE P   DECIMALS 2,   " JUNE
       AMT3 TYPE P DECIMALS 2,  " JULY
       AMT4 TYPE P DECIMALS 2,     " AUG
       AMT5 TYPE P DECIMALS 2,        "SEP
       AMT6 TYPE P   DECIMALS 2,   " OCT
       AMT7 TYPE P DECIMALS 2,  " NOV
       AMT8 TYPE P DECIMALS 2,     " DEC
       AMT9 TYPE P DECIMALS 2,        "JAN
       AMT10 TYPE P   DECIMALS 2,   " FEB
       AMT11 TYPE P DECIMALS 2,  " MAR
       MTART TYPE MARA-MTART,
       VOLUM TYPE MARA-VOLUM,
       AVOLUM TYPE P DECIMALS 2,
       VRKME TYPE VBRP-VRKME,  "ADDED BY RAM ON 03/11/2015
       VOLUM_VB TYPE VBRP-VOLUM ,

*&-----Begin of Keerthi CLSS on 26-08-2016-----*
       SO_NO TYPE VBPA-PERNR,       "Sales officer number
       SO_NAME TYPE PA0001-SNAME,   "Sales officer name
       SM_NO TYPE VBPA-PERNR,       "Sales manager number
       SM_NAME TYPE PA0001-SNAME,   "Sales manager name
       END OF TY_FINOVR.
*&------End of Keerthi CLSS on 26-08-2016------*

TYPES: BEGIN OF TY_TVKBT2,
    VKBUR TYPE TVKBT-VKBUR,
    BEZEI TYPE TVKBT-BEZEI,
    END OF TY_TVKBT2,

    BEGIN OF TY_TSPAT2,
    SPART TYPE TSPAT-SPART,
    VTEXT TYPE TSPAT-VTEXT,
    END OF TY_TSPAT2,


    BEGIN OF TY_VBRP, " Added by Govind
       VBELN TYPE VBRP-VBELN,
      POSNR TYPE VBRP-POSNR,
      FKIMG TYPE VBRP-FKIMG,
      VOLUM TYPE VBRP-VOLUM,
      MATNR TYPE VBRP-MATNR,
      NETWR TYPE VBRP-NETWR,
      END OF TY_VBRP,

BEGIN OF TY_MARA,
  MATNR TYPE MARA-MATNR,
  MTART TYPE MARA-MTART,
  VOLUM TYPE MARA-VOLUM,
  VOLEH TYPE MARA-VOLEH,
  END OF TY_MARA,

BEGIN OF TY_MAKT,
MATNR TYPE MAKT-MATNR,
MAKTX TYPE MAKT-MAKTX,
END OF TY_MAKT,

BEGIN OF TY_MARC ,
 MATNR TYPE MARC-MATNR,
 WERKS TYPE MARC-WERKS,
 END OF TY_MARC,

BEGIN OF TY_MVKE ,      "ADDED BY RAM
 MATNR TYPE MVKE-MATNR,
* VKORG TYPE MVKE-VKORG,
 MVGR1 TYPE MVKE-MVGR1,
 END OF TY_MVKE,

 BEGIN OF TY_TVM1T ,
 MVGR1 TYPE TVM1T-MVGR1,
 BEZEI TYPE TVM1T-BEZEI,
 END OF TY_TVM1T,

BEGIN OF TY_VDRK2,
FKDAT TYPE VBRK-FKDAT,
VBELN TYPE VBRP-VBELN,
LPOSNR TYPE LIPS-POSNR,
MATNR TYPE VBRP-MATNR,
MAKTX TYPE MAKT-MAKTX,
FKIMG TYPE VBRP-FKIMG,
VGPOS TYPE VBRP-VGPOS,
VOLUM TYPE VBRP-VOLUM,
VOLEH TYPE VBRP-VOLEH,
PSTYV TYPE LIPS-PSTYV,
SPART TYPE  VBRK-SPART,
NETWR TYPE VBRK-NETWR,
KUNAG TYPE VBRK-KUNAG,
KUNRG TYPE VBRK-KUNRG,
SFAKN TYPE VBRK-SFAKN,
FKSTO TYPE VBRK-FKSTO,
POSNR TYPE VBRP-POSNR,
ARKTX TYPE VBRP-ARKTX,
VRKME TYPE VBRP-VRKME,
VGBEL TYPE VBRP-VGBEL,
VKBUR TYPE VBRP-VKBUR,
LMATNR TYPE LIPS-MATNR,
LVBELN TYPE LIPS-VBELN,
LFIMG TYPE LIPS-LFIMG,
CHARG TYPE LIPS-CHARG,
DEL_FLAG(1) TYPE C,
PROC_KEY(1) TYPE C,

END OF TY_VDRK2.
TYPES: BEGIN OF TY_KNVP,   "Added by Keerthi CLSS on 26.10.2016
       KUNNR TYPE KNVP-KUNNR,
       VKORG TYPE KNVP-VKORG,
       VTWEG TYPE KNVP-VTWEG,
       SPART TYPE KNVP-SPART,
       PARVW TYPE KNVP-PARVW,
       PARZA TYPE KNVP-PARZA,
       PERNR TYPE KNVP-PERNR,
       END OF TY_KNVP.
TYPES:BEGIN OF STR_PA0001,                         "  ADDED BY RAM ON 05-07-2016
      PERNR TYPE PA0001-PERNR,
      ENDDA TYPE PA0001-ENDDA,
      BEGDA TYPE PA0001-BEGDA,
      SNAME TYPE PA0001-SNAME,
      END OF STR_PA0001.
*&------End of Keerthi CLSS on 26-10-2016------*


DATA : LV_COUNT TYPE I,
       V_COUNT TYPE I.


*--------------------------------------------------------------*
*INTERNAL TABLE DECLARATIONS
*--------------------------------------------------------------*



DATA: IT_VBRK TYPE TABLE OF TY_VBRK_VBRP,
IT_TVKBT TYPE TABLE OF TY_TVKBT,
IT_TSPAT  TYPE TABLE OF TY_TSPAT,
GT_KNA1 TYPE TABLE OF TY_KNA1,
IT_MARA TYPE TABLE OF TY_MARA,
IT_MARC TYPE TABLE OF TY_MARC,
IT_MVKE TYPE TABLE OF TY_MVKE,   " ADDED BY RAM
IT_TVM1T TYPE TABLE OF TY_TVM1T,
 GT_T005U TYPE TABLE OF GS_T005U ,
IT_VBRK2 TYPE TABLE OF TY_VDRK2,
IT_TVKBT2 TYPE TABLE OF TY_TVKBT2,
IT_TSPAT2  TYPE TABLE OF TY_TSPAT2,
IT_MARM TYPE TABLE OF TY_MARM,
GT_MAKT TYPE TABLE OF TY_MAKT,
IT_VBRP TYPE TABLE OF TY_VBRP,
IT_FINOVR TYPE TABLE OF TY_FINOVR,
IT1_FINOVR TYPE TABLE OF TY_FINOVR.



*--------------------------------------------------------------*
*WORK AREA DECLARATIONS
*--------------------------------------------------------------*

DATA: WA_VBRK TYPE TY_VBRK_VBRP,
      WA_TVKBT TYPE  TY_TVKBT,
      WA_TSPAT  TYPE TY_TSPAT,
      WA_KNA1 TYPE TY_KNA1,
      WA_MARA TYPE TY_MARA,
       WA_MARC TYPE TY_MARC,
       WA_MVKE TYPE TY_MVKE, "ADDED BY RAM
       WA_TVM1T TYPE TY_TVM1T,
      WA_MAKT TYPE TY_MAKT,
      WA_T005U TYPE GS_T005U,
      WA_VBRK2 TYPE TY_VDRK2,
      WA_TVKBT2 TYPE  TY_TVKBT2,
      WA_TSPAT2  TYPE TY_TSPAT2,

      WA_FINOVR LIKE LINE OF IT_FINOVR,
      WA1_FINOVR LIKE LINE OF IT_FINOVR,
      WA_MARM LIKE LINE OF IT_MARM,
           WA_VBRP LIKE LINE OF IT_VBRP.


DATA: NO_MONTH TYPE          T009B-POPER,
  D_YEAR  TYPE             T009B-BDATJ.

DATA : LV_BUKRS TYPE VBRK-BUKRS.
DATA : LV_FKART TYPE VBRK-FKART.

*&-----Begin of Keerthi CLSS on 26-08-2016-----*
DATA: IT_KNVP TYPE TABLE OF TY_KNVP,  "Added by Keerthi CLSS on 26.10.2016
      WA_KNVP TYPE TY_KNVP,
      IT_KNVP1 TYPE TABLE OF TY_KNVP,  "Added by Keerthi CLSS on 26.10.2016
      WA_KNVP1 TYPE TY_KNVP,
      IT_PA0001 TYPE TABLE OF STR_PA0001,
      WA_PA0001 TYPE STR_PA0001,
      IT_PA0001_1 TYPE TABLE OF STR_PA0001,
      WA_PA0001_1 TYPE STR_PA0001.
*&------End of Keerthi CLSS on 26-08-2016------*

SELECTION-SCREEN: BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-T01.



SELECT-OPTIONS: SO_BUKRS FOR LV_BUKRS MODIF ID TB2 OBLIGATORY,
                SO_VKBU2 FOR W_INV_VKBUR MODIF ID TB2 OBLIGATORY,
                SO_KUNNR FOR W_KUNAG MODIF ID TB2,
                SO_SPART FOR W_SPART MODIF ID TB2 OBLIGATORY ,
                SO_FKDAT FOR W_AUX_FKDAT MODIF ID TB2 DEFAULT SY-DATUM OBLIGATORY,        " SELECTION SCREEN ELEMENTS FOR INVOICE
                SO_MVGR1 FOR W_MVGR1 MODIF ID TB2 NO-DISPLAY, " ADDED BY RAM
                SO_MATNR FOR W_MATNR MODIF ID TB2,
                SO_MTART FOR W_MTART MODIF ID TB2 OBLIGATORY,
                SO_FKART FOR LV_FKART MODIF ID TB2 OBLIGATORY.


SELECTION-SCREEN SKIP.

PARAMETERS: P_CI AS CHECKBOX USER-COMMAND CBC MODIF ID TB2.
PARAMETERS: P_SR AS CHECKBOX USER-COMMAND CBC MODIF ID TB2.

SELECTION-SCREEN: END OF BLOCK B2.
*

START-OF-SELECTION.

  PERFORM AUTHCHECK_OVERVIEW_NEW.
  PERFORM DATA_RETRIEVAL_OVERVIEW.
  PERFORM AUTHCHECK_OVERVIEW.
  PERFORM BUILD_FIELDCATALOG_OVERVIEW.
  PERFORM BUILD_ALV_OVERVIEW.

*&---------------------------------------------------------------------*
*&      Form  DATA_RETRIEVAL_OVERVIEW
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
FORM DATA_RETRIEVAL_OVERVIEW .
*  IF P_CB <> 'X'. " Added by Goivnd On 05/06/2014



  IF P_CI <> 'X' AND P_SR <> 'X' .

    SELECT    VBRK~BUKRS "#EC CI_DB_OPERATION_OK[2768887] " Added by <IT-CAR Tool> during Code Remediation
              VBRK~FKDAT
              VBRK~SPART
              VBRK~VBELN
              VBRK~FKART
              VBRK~KUNAG
              VBRK~KUNRG
              VBRK~VKORG
              VBRK~VTWEG
              VBRK~NETWR
              VBRK~SFAKN
              VBRK~KNKLI
              VBRK~MWSBK
              VBRK~FKSTO
              VBRP~POSNR
              VBRP~VRKME
              VBRP~VKBUR
              VBRP~MATNR
              VBRP~FKIMG
              VBRP~VGBEL
              VBRP~VOLUM
              VBRP~NETWR
              INTO CORRESPONDING FIELDS OF TABLE IT_VBRK
              FROM VBRK JOIN VBRP ON VBRK~VBELN = VBRP~VBELN "#EC CI_DB_OPERATION_OK[2768887] " Added by <IT-CAR Tool> during Code Remediation
              WHERE VBRK~FKDAT IN SO_FKDAT  AND MATNR IN SO_MATNR
      AND VBRP~VKBUR IN SO_VKBU2  AND VBRK~KUNAG IN SO_KUNNR AND
     VBRK~FKSTO <> 'X' AND VBRK~BUKRS IN SO_BUKRS AND VBRK~SPART IN SO_SPART AND VBRK~FKART NOT IN ('S1','YBRE','S2','JEX','F1','F2','YLRE','YIRE')
      AND VBRK~FKART IN SO_FKART. "ADDED BY RAM ON 7/10/15
*  DELETE ADJACENT DUPLICATES FROM IT_VBRK COMPARING VBELN MATNR.

  ELSEIF P_CI = 'X'.

    SELECT    VBRK~BUKRS "#EC CI_DB_OPERATION_OK[2768887] " Added by <IT-CAR Tool> during Code Remediation
        VBRK~FKDAT
        VBRK~SPART
        VBRK~VBELN
        VBRK~FKART
        VBRK~KUNAG
        VBRK~KUNRG
        VBRK~VKORG
        VBRK~VTWEG
        VBRK~NETWR
        VBRK~SFAKN
        VBRK~KNKLI
        VBRK~MWSBK
        VBRK~FKSTO
        VBRP~POSNR
        VBRP~VRKME
        VBRP~VKBUR
        VBRP~MATNR
        VBRP~FKIMG
        VBRP~VGBEL
        VBRP~VOLUM
        VBRP~NETWR
        INTO CORRESPONDING FIELDS OF TABLE IT_VBRK
        FROM VBRK JOIN VBRP ON VBRK~VBELN = VBRP~VBELN "#EC CI_DB_OPERATION_OK[2768887] " Added by <IT-CAR Tool> during Code Remediation
        WHERE VBRK~FKDAT IN SO_FKDAT  AND MATNR IN SO_MATNR
      AND VBRP~VKBUR IN SO_VKBU2  AND VBRK~KUNAG IN SO_KUNNR AND
      VBRK~BUKRS IN SO_BUKRS AND VBRK~SPART IN SO_SPART AND VBRK~FKART IN SO_FKART AND FKSTO = 'X'.

  ELSEIF P_SR = 'X'.

    SELECT    VBRK~BUKRS "#EC CI_DB_OPERATION_OK[2768887] " Added by <IT-CAR Tool> during Code Remediation
              VBRK~FKDAT
              VBRK~SPART
              VBRK~VBELN
              VBRK~FKART
              VBRK~KUNAG
              VBRK~KUNRG
              VBRK~VKORG
              VBRK~VTWEG
              VBRK~NETWR
              VBRK~SFAKN
              VBRK~KNKLI
              VBRK~MWSBK
              VBRK~FKSTO
              VBRP~POSNR
              VBRP~VRKME
              VBRP~VKBUR
              VBRP~MATNR
              VBRP~FKIMG
              VBRP~VGBEL
              VBRP~VOLUM
              VBRP~NETWR
              INTO CORRESPONDING FIELDS OF TABLE IT_VBRK
              FROM VBRK JOIN VBRP ON VBRK~VBELN = VBRP~VBELN "#EC CI_DB_OPERATION_OK[2768887] " Added by <IT-CAR Tool> during Code Remediation
              WHERE VBRK~FKDAT IN SO_FKDAT  AND MATNR IN SO_MATNR
      AND VBRP~VKBUR IN SO_VKBU2  AND VBRK~KUNAG IN SO_KUNNR AND
*   VBRK~FKSTO <> 'X' AND VBRK~BUKRS IN SO_BUKRS AND VBRK~SPART IN SO_SPART AND VBRK~FKART NOT IN ('S1','YBRE','S2','JEX','F1','F2','YLRE','YIRE').
     VBRK~FKSTO <> 'X' AND VBRK~BUKRS IN SO_BUKRS AND VBRK~SPART IN SO_SPART AND ( FKART = 'YBBR' OR FKART = 'YBRE' OR FKART = 'YIRE' OR FKART = 'YFRE'
      OR FKART = 'IVS' OR FKART <> 'YLRE' ) AND VBRK~FKART NOT IN ('S1','S2','JEX','F1','F2') AND VBRK~FKART IN SO_FKART.

  ENDIF.

  IF IT_VBRK IS NOT INITIAL.

    SELECT  KUNNR
           NAME1
           NAME2
           REGIO FROM KNA1 INTO TABLE GT_KNA1 FOR ALL ENTRIES IN IT_VBRK WHERE KUNNR = IT_VBRK-KUNAG.

    SELECT MATNR MTART VOLUM VOLEH FROM MARA
      INTO  TABLE IT_MARA FOR ALL ENTRIES IN IT_VBRK WHERE MATNR = IT_VBRK-MATNR AND MTART IN SO_MTART .

    SELECT MATNR WERKS FROM MARC
      INTO  TABLE IT_MARC FOR ALL ENTRIES IN IT_VBRK WHERE MATNR = IT_VBRK-MATNR AND WERKS = IT_VBRK-VKBUR .

    SELECT                                  "ADDED BY RAM
      MATNR
*      VKORG
      MVGR1
         FROM MVKE INTO TABLE IT_MVKE FOR ALL ENTRIES IN IT_MARC WHERE MATNR = IT_MARC-MATNR AND MVGR1 IN SO_MVGR1.

    SELECT
      MVGR1
      BEZEI
        FROM TVM1T INTO TABLE IT_TVM1T FOR ALL ENTRIES IN IT_MVKE WHERE MVGR1 = IT_MVKE-MVGR1 .

    SELECT MATNR MAKTX  FROM MAKT
    INTO TABLE GT_MAKT FOR ALL ENTRIES IN IT_MARA WHERE MATNR = IT_MARA-MATNR .

    SELECT VKBUR
           BEZEI
           FROM TVKBT INTO TABLE IT_TVKBT
           FOR ALL ENTRIES IN IT_VBRK
           WHERE VKBUR = IT_VBRK-VKBUR
           AND SPRAS = 'EN'.
  ENDIF.

  SELECT SPART
         VTEXT
         FROM TSPAT INTO TABLE IT_TSPAT
         FOR ALL ENTRIES IN IT_VBRK
         WHERE SPART = IT_VBRK-SPART
         AND SPRAS = 'EN'.

*DELETE ADJACENT DUPLICATES FROM IT_MVKE COMPARING MATNR VKORG .

  LOOP AT GT_KNA1 INTO WA_KNA1 .
    LOOP AT IT_VBRK INTO WA_VBRK WHERE  KUNAG = WA_KNA1-KUNNR.

      LOOP AT IT_MARA INTO WA_MARA WHERE MATNR = WA_VBRK-MATNR .
        WA_FINOVR-KUNNR = WA_VBRK-KUNAG .
        WA_FINOVR-MATNR = WA_MARA-MATNR.
        WA_FINOVR-MTART = WA_MARA-MTART.

*        WA_FINOVR-NETWR =  WA_FINOVR-NETWR + WA_VBRK-NETWR.
*        WA_FINOVR-FKIMG  =   WA_FINOVR-FKIMG + WA_VBRK-FKIMG.
        WA_FINOVR-FKART = WA_VBRK-FKART.

        IF WA_FINOVR-FKART <> 'YLRE' AND WA_FINOVR-FKART <> 'YIRE' AND WA_FINOVR-FKART <> 'YFRE' AND WA_FINOVR-FKART <> 'IVS' AND WA_FINOVR-FKART <> 'YBRE'.   " added by mani 19.02.2016

          WA_FINOVR-NETWR =  WA_FINOVR-NETWR + WA_VBRK-NETWR.
          WA_FINOVR-FKIMG  =   WA_FINOVR-FKIMG + WA_VBRK-FKIMG.
        ENDIF.
        IF P_CI = 'X'.
          IF  WA_FINOVR-FKART = 'YLRE' OR WA_FINOVR-FKART = 'YIRE' OR WA_FINOVR-FKART = 'YFRE' OR WA_FINOVR-FKART = 'IVS' OR WA_FINOVR-FKART = 'YBRE'.        " added by mani 19.02.2016

            WA_FINOVR-NETWR =  WA_FINOVR-NETWR + WA_VBRK-NETWR.
            WA_FINOVR-FKIMG  =   WA_FINOVR-FKIMG + WA_VBRK-FKIMG.
          ENDIF.
        ENDIF.
        IF P_CI NE 'X'.
          IF  WA_FINOVR-FKART = 'YLRE' OR WA_FINOVR-FKART = 'YIRE' OR WA_FINOVR-FKART = 'YFRE' OR WA_FINOVR-FKART = 'IVS' OR WA_FINOVR-FKART = 'YBRE'.        " added by mani 19.02.2016

            WA_FINOVR-NETWR =  ( WA_FINOVR-NETWR - WA_VBRK-NETWR ).
            WA_FINOVR-FKIMG  =  ( WA_FINOVR-FKIMG - WA_VBRK-FKIMG ).
          ENDIF.
        ENDIF.

        CALL FUNCTION 'DATE_TO_PERIOD_CONVERT'
          EXPORTING
            I_DATE         = WA_VBRK-FKDAT
            I_MONMIT       = 00
            I_PERIV        = 'K4'
          IMPORTING
            E_BUPER        = NO_MONTH
            E_GJAHR        = D_YEAR
          EXCEPTIONS
            INPUT_FALSE    = 1
            T009_NOTFOUND  = 2
            T009B_NOTFOUND = 3
            OTHERS         = 4.

        IF WA_FINOVR-FKART <> 'YLRE' AND WA_FINOVR-FKART <> 'YIRE' AND WA_FINOVR-FKART <> 'YFRE' AND WA_FINOVR-FKART <> 'IVS' AND WA_FINOVR-FKART <> 'YBRE'.   " added by mani 19.02.2016

          IF NO_MONTH = '004' .
            WA_FINOVR-QTY0 =  WA_FINOVR-QTY0 +  WA_VBRK-FKIMG .
            WA_FINOVR-AMT0 =  WA_FINOVR-AMT0 + WA_VBRK-NETWR.
            WA_FINOVR-VOL0 =  WA_FINOVR-VOL0 + WA_VBRK-VOLUM .
          ELSEIF NO_MONTH = '005'.
            WA_FINOVR-QTY1 =  WA_FINOVR-QTY1 +  WA_VBRK-FKIMG .
            WA_FINOVR-AMT1 =  WA_FINOVR-AMT1 + WA_VBRK-NETWR.
            WA_FINOVR-VOL1 =  WA_FINOVR-VOL1 + WA_VBRK-VOLUM .
          ELSEIF NO_MONTH = '006'.
            WA_FINOVR-QTY2 =  WA_FINOVR-QTY2 +  WA_VBRK-FKIMG .
            WA_FINOVR-AMT2 =  WA_FINOVR-AMT2 + WA_VBRK-NETWR.
            WA_FINOVR-VOL2 =  WA_FINOVR-VOL2 + WA_VBRK-VOLUM .
          ELSEIF NO_MONTH = '007'.
            WA_FINOVR-QTY3 =  WA_FINOVR-QTY3 +  WA_VBRK-FKIMG .
            WA_FINOVR-AMT3 =  WA_FINOVR-AMT3 + WA_VBRK-NETWR.
            WA_FINOVR-VOL3 =  WA_FINOVR-VOL3 + WA_VBRK-VOLUM .
          ELSEIF NO_MONTH = '008'.
            WA_FINOVR-QTY4 =  WA_FINOVR-QTY4 +  WA_VBRK-FKIMG .
            WA_FINOVR-AMT4 =  WA_FINOVR-AMT4 +  WA_VBRK-NETWR.
            WA_FINOVR-VOL4 =  WA_FINOVR-VOL4 + WA_VBRK-VOLUM .
          ELSEIF NO_MONTH = '009'.
            WA_FINOVR-QTY5 =  WA_FINOVR-QTY5 +  WA_VBRK-FKIMG .
            WA_FINOVR-AMT5 =  WA_FINOVR-AMT5 +   WA_VBRK-NETWR.
            WA_FINOVR-VOL5 =  WA_FINOVR-VOL5 + WA_VBRK-VOLUM .
          ELSEIF NO_MONTH = '010'.
            WA_FINOVR-QTY6 =  WA_FINOVR-QTY6 +  WA_VBRK-FKIMG .
            WA_FINOVR-AMT6 =  WA_FINOVR-AMT6 +  WA_VBRK-NETWR.
            WA_FINOVR-VOL6 =  WA_FINOVR-VOL6 + WA_VBRK-VOLUM .
          ELSEIF NO_MONTH = '011'.
            WA_FINOVR-QTY7 =  WA_FINOVR-QTY7 +  WA_VBRK-FKIMG .
            WA_FINOVR-AMT7 =  WA_FINOVR-AMT7 + WA_VBRK-NETWR.
            WA_FINOVR-VOL7 =  WA_FINOVR-VOL7 + WA_VBRK-VOLUM .
          ELSEIF NO_MONTH = '012'.
            WA_FINOVR-QTY8 =  WA_FINOVR-QTY8 +  WA_VBRK-FKIMG .
            WA_FINOVR-AMT8 =  WA_FINOVR-AMT8 + WA_VBRK-NETWR.
            WA_FINOVR-VOL8 =  WA_FINOVR-VOL8 + WA_VBRK-VOLUM .
          ELSEIF NO_MONTH = '001'.
            WA_FINOVR-QTY9 =  WA_FINOVR-QTY9 +  WA_VBRK-FKIMG .
            WA_FINOVR-AMT9 = WA_FINOVR-AMT9 + WA_VBRK-NETWR.
            WA_FINOVR-VOL9 =  WA_FINOVR-VOL9 + WA_VBRK-VOLUM .
          ELSEIF NO_MONTH = '002'.
            WA_FINOVR-QTY10 =  WA_FINOVR-QTY10 +  WA_VBRK-FKIMG .
            WA_FINOVR-AMT10 =  WA_FINOVR-AMT10 + WA_VBRK-NETWR.
            WA_FINOVR-VOL10 =  WA_FINOVR-VOL10 + WA_VBRK-VOLUM .
          ELSEIF NO_MONTH = '003'.
            WA_FINOVR-QTY11 =  WA_FINOVR-QTY11 +  WA_VBRK-FKIMG .
            WA_FINOVR-AMT11 =  WA_FINOVR-AMT11 + WA_VBRK-NETWR.
            WA_FINOVR-VOL11 =  WA_FINOVR-VOL11 + WA_VBRK-VOLUM .

          ENDIF.
        ENDIF.
        IF P_CI = 'X'.
          IF  WA_FINOVR-FKART = 'YLRE' OR WA_FINOVR-FKART = 'YIRE' OR WA_FINOVR-FKART = 'YFRE' OR WA_FINOVR-FKART = 'IVS' OR WA_FINOVR-FKART = 'YBRE'.     " added by mani 19.02.2016

            IF NO_MONTH = '004' .
              WA_FINOVR-QTY0 =  WA_FINOVR-QTY0 +  WA_VBRK-FKIMG .
              WA_FINOVR-AMT0 =  WA_FINOVR-AMT0 + WA_VBRK-NETWR.
              WA_FINOVR-VOL0 =  WA_FINOVR-VOL0 + WA_VBRK-VOLUM .
            ELSEIF NO_MONTH = '005'.
              WA_FINOVR-QTY1 =  WA_FINOVR-QTY1 +  WA_VBRK-FKIMG .
              WA_FINOVR-AMT1 =  WA_FINOVR-AMT1 + WA_VBRK-NETWR.
              WA_FINOVR-VOL1 =  WA_FINOVR-VOL1 + WA_VBRK-VOLUM .
            ELSEIF NO_MONTH = '006'.
              WA_FINOVR-QTY2 =  WA_FINOVR-QTY2 +  WA_VBRK-FKIMG .
              WA_FINOVR-AMT2 =  WA_FINOVR-AMT2 + WA_VBRK-NETWR.
              WA_FINOVR-VOL2 =  WA_FINOVR-VOL2 + WA_VBRK-VOLUM .
            ELSEIF NO_MONTH = '007'.
              WA_FINOVR-QTY3 =  WA_FINOVR-QTY3 +  WA_VBRK-FKIMG .
              WA_FINOVR-AMT3 =  WA_FINOVR-AMT3 + WA_VBRK-NETWR.
              WA_FINOVR-VOL3 =  WA_FINOVR-VOL3 + WA_VBRK-VOLUM .
            ELSEIF NO_MONTH = '008'.
              WA_FINOVR-QTY4 =  WA_FINOVR-QTY4 +  WA_VBRK-FKIMG .
              WA_FINOVR-AMT4 =  WA_FINOVR-AMT4 +  WA_VBRK-NETWR.
              WA_FINOVR-VOL4 =  WA_FINOVR-VOL4 + WA_VBRK-VOLUM .
            ELSEIF NO_MONTH = '009'.
              WA_FINOVR-QTY5 =  WA_FINOVR-QTY5 +  WA_VBRK-FKIMG .
              WA_FINOVR-AMT5 =  WA_FINOVR-AMT5 +   WA_VBRK-NETWR.
              WA_FINOVR-VOL5 =  WA_FINOVR-VOL5 + WA_VBRK-VOLUM .
            ELSEIF NO_MONTH = '010'.
              WA_FINOVR-QTY6 =  WA_FINOVR-QTY6 +  WA_VBRK-FKIMG .
              WA_FINOVR-AMT6 =  WA_FINOVR-AMT6 +  WA_VBRK-NETWR.
              WA_FINOVR-VOL6 =  WA_FINOVR-VOL6 + WA_VBRK-VOLUM .
            ELSEIF NO_MONTH = '011'.
              WA_FINOVR-QTY7 =  WA_FINOVR-QTY7 +  WA_VBRK-FKIMG .
              WA_FINOVR-AMT7 =  WA_FINOVR-AMT7 + WA_VBRK-NETWR.
              WA_FINOVR-VOL7 =  WA_FINOVR-VOL7 + WA_VBRK-VOLUM .
            ELSEIF NO_MONTH = '012'.
              WA_FINOVR-QTY8 =  WA_FINOVR-QTY8 +  WA_VBRK-FKIMG .
              WA_FINOVR-AMT8 =  WA_FINOVR-AMT8 + WA_VBRK-NETWR.
              WA_FINOVR-VOL8 =  WA_FINOVR-VOL8 + WA_VBRK-VOLUM .
            ELSEIF NO_MONTH = '001'.
              WA_FINOVR-QTY9 =  WA_FINOVR-QTY9 +  WA_VBRK-FKIMG .
              WA_FINOVR-AMT9 = WA_FINOVR-AMT9 + WA_VBRK-NETWR.
              WA_FINOVR-VOL9 =  WA_FINOVR-VOL9 + WA_VBRK-VOLUM .
            ELSEIF NO_MONTH = '002'.
              WA_FINOVR-QTY10 =  WA_FINOVR-QTY10 +  WA_VBRK-FKIMG .
              WA_FINOVR-AMT10 =  WA_FINOVR-AMT10 + WA_VBRK-NETWR.
              WA_FINOVR-VOL10 =  WA_FINOVR-VOL10 + WA_VBRK-VOLUM .
            ELSEIF NO_MONTH = '003'.
              WA_FINOVR-QTY11 =  WA_FINOVR-QTY11 +  WA_VBRK-FKIMG .
              WA_FINOVR-AMT11 =  WA_FINOVR-AMT11 + WA_VBRK-NETWR.
              WA_FINOVR-VOL11 =  WA_FINOVR-VOL11 + WA_VBRK-VOLUM .

            ENDIF.
          ENDIF.
        ENDIF.
        IF P_CI NE 'X'.

          IF  WA_FINOVR-FKART = 'YLRE' OR WA_FINOVR-FKART = 'YIRE' OR WA_FINOVR-FKART = 'YFRE' OR WA_FINOVR-FKART = 'IVS' OR WA_FINOVR-FKART = 'YBRE'.     " added by mani 19.02.2016

            IF NO_MONTH = '004' .
              WA_FINOVR-QTY0 =  ( WA_FINOVR-QTY0 -  WA_VBRK-FKIMG ).
              WA_FINOVR-AMT0 =  ( WA_FINOVR-AMT0 - WA_VBRK-NETWR ).
              WA_FINOVR-VOL0 =  WA_FINOVR-VOL0 + WA_VBRK-VOLUM .
            ELSEIF NO_MONTH = '005'.
              WA_FINOVR-QTY1 =  ( WA_FINOVR-QTY1 -  WA_VBRK-FKIMG ).
              WA_FINOVR-AMT1 =  ( WA_FINOVR-AMT1 - WA_VBRK-NETWR ).
              WA_FINOVR-VOL1 =  WA_FINOVR-VOL1 + WA_VBRK-VOLUM .
            ELSEIF NO_MONTH = '006'.
              WA_FINOVR-QTY2 =   ( WA_FINOVR-QTY2 -  WA_VBRK-FKIMG ) .
              WA_FINOVR-AMT2 =  ( WA_FINOVR-AMT2 - WA_VBRK-NETWR ).
              WA_FINOVR-VOL2 =  WA_FINOVR-VOL2 + WA_VBRK-VOLUM .
            ELSEIF NO_MONTH = '007'.
              WA_FINOVR-QTY3 =  ( WA_FINOVR-QTY3 -  WA_VBRK-FKIMG ) .
              WA_FINOVR-AMT3 =  ( WA_FINOVR-AMT3 - WA_VBRK-NETWR ).
              WA_FINOVR-VOL3 =  WA_FINOVR-VOL3 + WA_VBRK-VOLUM .
            ELSEIF NO_MONTH = '008'.
              WA_FINOVR-QTY4 =  ( WA_FINOVR-QTY4 -  WA_VBRK-FKIMG ) .
              WA_FINOVR-AMT4 =  ( WA_FINOVR-AMT4 -  WA_VBRK-NETWR ).
              WA_FINOVR-VOL4 =  WA_FINOVR-VOL4 + WA_VBRK-VOLUM .
            ELSEIF NO_MONTH = '009'.
              WA_FINOVR-QTY5 =  ( WA_FINOVR-QTY5 -  WA_VBRK-FKIMG ).
              WA_FINOVR-AMT5 =   ( WA_FINOVR-AMT5 -   WA_VBRK-NETWR ).
              WA_FINOVR-VOL5 =  WA_FINOVR-VOL5 + WA_VBRK-VOLUM .
            ELSEIF NO_MONTH = '010'.
              WA_FINOVR-QTY6 =  ( WA_FINOVR-QTY6 -  WA_VBRK-FKIMG ) .
              WA_FINOVR-AMT6 =  ( WA_FINOVR-AMT6 -  WA_VBRK-NETWR ).
              WA_FINOVR-VOL6 =  WA_FINOVR-VOL6 + WA_VBRK-VOLUM .
            ELSEIF NO_MONTH = '011'.
              WA_FINOVR-QTY7 =  ( WA_FINOVR-QTY7 -  WA_VBRK-FKIMG ).
              WA_FINOVR-AMT7 =  ( WA_FINOVR-AMT7 - WA_VBRK-NETWR ) .
              WA_FINOVR-VOL7 =  WA_FINOVR-VOL7 + WA_VBRK-VOLUM .
            ELSEIF NO_MONTH = '012'.
              WA_FINOVR-QTY8 =  ( WA_FINOVR-QTY8 -  WA_VBRK-FKIMG ) .
              WA_FINOVR-AMT8 =  ( WA_FINOVR-AMT8 - WA_VBRK-NETWR ).
              WA_FINOVR-VOL8 =  WA_FINOVR-VOL8 + WA_VBRK-VOLUM .
            ELSEIF NO_MONTH = '001'.
              WA_FINOVR-QTY9 =  ( WA_FINOVR-QTY9 -  WA_VBRK-FKIMG ) .
              WA_FINOVR-AMT9 =  ( WA_FINOVR-AMT9 - WA_VBRK-NETWR ).
              WA_FINOVR-VOL9 =  WA_FINOVR-VOL9 + WA_VBRK-VOLUM .
            ELSEIF NO_MONTH = '002'.
              WA_FINOVR-QTY10 =   ( WA_FINOVR-QTY10 -  WA_VBRK-FKIMG ) .
              WA_FINOVR-AMT10 =  ( WA_FINOVR-AMT10 - WA_VBRK-NETWR ).
              WA_FINOVR-VOL10 =  WA_FINOVR-VOL10 + WA_VBRK-VOLUM .
            ELSEIF NO_MONTH = '003'.
              WA_FINOVR-QTY11 =  ( WA_FINOVR-QTY11 -  WA_VBRK-FKIMG ) .
              WA_FINOVR-AMT11 =  ( WA_FINOVR-AMT11 - WA_VBRK-NETWR ).
              WA_FINOVR-VOL11 =  WA_FINOVR-VOL11 + WA_VBRK-VOLUM .

            ENDIF.
          ENDIF.
        ENDIF .

        WA_FINOVR-FKDAT = WA_VBRK-FKDAT.
        WA_FINOVR-SPART = WA_VBRK-SPART.
*        WA_FINOVR-FKART = WA_VBRK-FKART.
        WA_FINOVR-KUNAG = WA_VBRK-KUNAG.
        WA_FINOVR-KUNRG = WA_VBRK-KUNRG.
        WA_FINOVR-VKORG = WA_VBRK-VKORG.
        WA_FINOVR-VTWEG = WA_VBRK-VTWEG.
*        WA_FINOVR-NETWR =   WA_VBRK-NETWR.
        WA_FINOVR-SFAKN = WA_VBRK-SFAKN.
        WA_FINOVR-VKBUR = WA_VBRK-VKBUR.

        WA_FINOVR-VRKME = WA_VBRK-VRKME . "ADDED BY RAM ON 03/11/2015
        WA_FINOVR-VOLUM_VB = WA_VBRK-VOLUM .

        READ TABLE IT_MVKE INTO WA_MVKE WITH  KEY MATNR = WA_MARA-MATNR .  "CHANGED BY RAM ON 2/7/16
*          IF SY-SUBRC = 0.
*            WA_FINOVR-MVGR1 = WA_MVKE-MVGR1.
*          ENDIF.

        "  ADDED BY RAM ON 02/7/16
        " IF WA_FINOVR-MVGR1 IS INITIAL .
*             READ TABLE IT_MVKE INTO WA_MVKE WITH  KEY MATNR = WA_MARA-MATNR  VKORG = WA_VBRK-VKORG .  "CHANGED BY RAM ON 2/7/16
*           LOOP AT IT_MVKE INTO WA_MVKE WHERE MATNR = WA_MARA-MATNR AND VKORG = WA_VBRK-VKORG .
        IF SY-SUBRC = 0.
          WA_FINOVR-MVGR1 = WA_MVKE-MVGR1.
        ENDIF.

*          ENDLOOP.
        "  ENDED BY RAM ON 02/7/16

      ENDLOOP.

      IF WA_FINOVR-MTART  <> ' ' .
        APPEND WA_FINOVR TO IT_FINOVR.
        CLEAR WA_FINOVR.
      ENDIF.
    ENDLOOP.

  ENDLOOP.

  IF IT_FINOVR IS INITIAL.

    MESSAGE 'No Data Exists for the Input' TYPE 'S' DISPLAY LIKE 'E'.

    STOP.

  ENDIF.

*  SORT IT_VBRK BY KUNAG MATNR.

  LOOP AT IT_FINOVR INTO WA_FINOVR.
    READ TABLE IT_TVKBT INTO WA_TVKBT WITH KEY VKBUR = WA_FINOVR-VKBUR.
    IF SY-SUBRC = 0.
      WA_FINOVR-BEZEI = WA_TVKBT-BEZEI.
    ENDIF.
    READ TABLE GT_MAKT INTO WA_MAKT WITH  KEY MATNR = WA_FINOVR-MATNR.
    WA_FINOVR-MAKTX = WA_MAKT-MAKTX.



    READ TABLE GT_KNA1 INTO WA_KNA1 WITH  KEY KUNNR = WA_FINOVR-KUNNR.
    WA_FINOVR-NAME1 = WA_KNA1-NAME1.
    READ TABLE IT_TVM1T INTO WA_TVM1T WITH KEY MVGR1 = WA_FINOVR-MVGR1 .
    IF SY-SUBRC = 0.
      WA_FINOVR-GBEZEI = WA_TVM1T-BEZEI.
    ENDIF.

    READ TABLE IT_TSPAT INTO WA_TSPAT WITH KEY SPART = WA_FINOVR-SPART.

    IF SY-SUBRC = 0.
      WA_FINOVR-VTEXT = WA_TSPAT-VTEXT.
    ENDIF.

    READ TABLE IT_MARA INTO WA_MARA WITH KEY MATNR = WA_FINOVR-MATNR.
    "WA_FINOVR-MTART = WA_MARA-MTART.
    WA_FINOVR-VOLUM = WA_MARA-VOLUM.

    MODIFY IT_FINOVR FROM WA_FINOVR TRANSPORTING BEZEI MAKTX NAME1 GBEZEI VTEXT VOLUM.
    CLEAR WA_FINOVR.
  ENDLOOP.

  LOOP AT IT_FINOVR INTO WA_FINOVR.
    " WA_FINOVR-QTY_LTR =  WA_FINOVR-FKIMG * WA_FINOVR-VOLUM. COMMENDED BY RAM ON 03/11/2015

    WA_FINOVR-QTY_LTR =  WA_FINOVR-VOLUM_VB .

    IF P_CI NE 'X'.
      IF  WA_FINOVR-FKART = 'YLRE' OR WA_FINOVR-FKART = 'YIRE' OR WA_FINOVR-FKART = 'YFRE' OR WA_FINOVR-FKART = 'IVS' OR WA_FINOVR-FKART = 'YBRE'.        " added by mani 19.02.2016

        WA_FINOVR-QTY_LTR = - ( WA_FINOVR-QTY_LTR ) .
        WA_FINOVR-VOL0 = - ( WA_FINOVR-VOL0 ) .
        WA_FINOVR-VOL1 = - ( WA_FINOVR-VOL1 ) .
        WA_FINOVR-VOL2 = - ( WA_FINOVR-VOL2 ) .
        WA_FINOVR-VOL3 = - ( WA_FINOVR-VOL3 ) .
        WA_FINOVR-VOL4 = - ( WA_FINOVR-VOL4 ) .
        WA_FINOVR-VOL5 = - ( WA_FINOVR-VOL5 ) .
        WA_FINOVR-VOL6 = - ( WA_FINOVR-VOL6 ) .
        WA_FINOVR-VOL7 = - ( WA_FINOVR-VOL7 ) .
        WA_FINOVR-VOL8 = - ( WA_FINOVR-VOL8 ) .
        WA_FINOVR-VOL9 = - ( WA_FINOVR-VOL9 ) .
        WA_FINOVR-VOL10 = - ( WA_FINOVR-VOL10 ) .
        WA_FINOVR-VOL11 = - ( WA_FINOVR-VOL11 ) .

      ENDIF.
    ENDIF.

    """"""""""""""""""""""""""""""""""""""Commended started By Ram on 04/11/2015
*    WA_FINOVR-VOL0 =  WA_FINOVR-QTY0 * WA_FINOVR-VOLUM .
*    WA_FINOVR-VOL1 = WA_FINOVR-QTY1 * WA_FINOVR-VOLUM .
*    WA_FINOVR-VOL2 = WA_FINOVR-QTY2 * WA_FINOVR-VOLUM .
*
*    WA_FINOVR-VOL3 = WA_FINOVR-QTY3 * WA_FINOVR-VOLUM .
*    WA_FINOVR-VOL4 = WA_FINOVR-QTY4 * WA_FINOVR-VOLUM .
*    WA_FINOVR-VOL5 = WA_FINOVR-QTY5 * WA_FINOVR-VOLUM .
*    WA_FINOVR-VOL6 = WA_FINOVR-QTY6 * WA_FINOVR-VOLUM .
*    WA_FINOVR-VOL7 = WA_FINOVR-QTY7 * WA_FINOVR-VOLUM .
*    WA_FINOVR-VOL8 = WA_FINOVR-QTY8 * WA_FINOVR-VOLUM .
*    WA_FINOVR-VOL9 = WA_FINOVR-QTY9 * WA_FINOVR-VOLUM .
*    WA_FINOVR-VOL10 = WA_FINOVR-QTY10 * WA_FINOVR-VOLUM .
*    WA_FINOVR-VOL11 = WA_FINOVR-QTY11 * WA_FINOVR-VOLUM .

    """"""""""""""""""""""""""""""""""""""Commended ended By Ram on 04/11/2015

*    LV_COUNT = LV_COUNT + 1 .
*
*   AT END OF MATNR.
*      WA_FINOVR-V_COUNT = LV_COUNT.

    MODIFY IT_FINOVR FROM WA_FINOVR TRANSPORTING QTY_LTR VOL0  VOL1 VOL2 VOL3 VOL4 VOL5 VOL6 VOL7 VOL8 VOL9 VOL10 VOL11 .
    CLEAR WA_FINOVR.
*    ENDAT.
  ENDLOOP.

*BREAK splabap.
  CLEAR: IT_PA0001, IT_PA0001_1.
  IF IT_FINOVR IS NOT INITIAL.
    SELECT KUNNR
           VKORG
           VTWEG
           SPART
           PARVW
           PARZA
           PERNR
           FROM KNVP INTO TABLE IT_KNVP FOR ALL ENTRIES IN IT_FINOVR WHERE KUNNR    = IT_FINOVR-KUNAG
                                                                       AND VKORG    = IT_FINOVR-VKORG
                                                                       AND VTWEG    = IT_FINOVR-VTWEG
                                                                       AND SPART    = IT_FINOVR-SPART
                                                                       AND PARVW    =  'L5'.", 'L3').   "L5 = SO      L3 = AS

    SELECT KUNNR
       VKORG
       VTWEG
       SPART
       PARVW
       PARZA
       PERNR
       FROM KNVP INTO TABLE IT_KNVP1 FOR ALL ENTRIES IN IT_FINOVR WHERE KUNNR    = IT_FINOVR-KUNAG
                                                                   AND VKORG    = IT_FINOVR-VKORG
                                                                   AND VTWEG    = IT_FINOVR-VTWEG
                                                                   AND SPART    = IT_FINOVR-SPART
                                                                   AND PARVW = 'L3'.   "L5 = SO      L3 = AS
    SELECT PERNR
           ENDDA
           BEGDA
           SNAME
           FROM PA0001 INTO TABLE IT_PA0001 FOR ALL ENTRIES IN IT_KNVP WHERE PERNR = IT_KNVP-PERNR.

    SELECT PERNR
        ENDDA
        BEGDA
        SNAME
        FROM PA0001 INTO TABLE IT_PA0001_1 FOR ALL ENTRIES IN IT_KNVP1 WHERE PERNR = IT_KNVP1-PERNR.

  ENDIF.

  LOOP AT IT_FINOVR INTO WA_FINOVR.

    READ TABLE IT_KNVP INTO WA_KNVP WITH KEY KUNNR = WA_FINOVR-KUNAG  VKORG = WA_FINOVR-VKORG VTWEG = WA_FINOVR-VTWEG SPART = WA_FINOVR-SPART PARVW = 'L5'.
    IF SY-SUBRC = 0.
      WA_FINOVR-SO_NO = WA_KNVP-PERNR.
    ENDIF.
    READ TABLE IT_PA0001 INTO WA_PA0001 WITH KEY PERNR = WA_KNVP-PERNR.
    IF SY-SUBRC = 0.
      WA_FINOVR-SO_NAME = WA_PA0001-SNAME.
    ENDIF.
*&--------------------------------------------------------------------------------------------------------------------------------
    READ TABLE IT_KNVP1 INTO WA_KNVP1 WITH KEY KUNNR = WA_FINOVR-KUNAG  VKORG = WA_FINOVR-VKORG VTWEG = WA_FINOVR-VTWEG SPART = WA_FINOVR-SPART PARVW = 'L3'.
    IF SY-SUBRC = 0.
      WA_FINOVR-SM_NO = WA_KNVP1-PERNR.
    ENDIF.
    READ TABLE IT_PA0001_1 INTO WA_PA0001_1 WITH KEY PERNR =  WA_KNVP1-PERNR.
    IF SY-SUBRC = 0.
      WA_FINOVR-SM_NAME = WA_PA0001_1-SNAME.
    ENDIF.

    MODIFY IT_FINOVR FROM WA_FINOVR TRANSPORTING SO_NO SO_NAME SM_NO SM_NAME .

    CLEAR: WA_FINOVR, WA_KNVP, WA_PA0001, WA_KNVP1, WA_PA0001_1.
  ENDLOOP.
*&--------End of Keerthi CLSS on 25-08-2016---------*

ENDFORM.                    "DATA_RETRIEVAL_OVERVIEW

" DATA_RETRIEVAL_OVERVIEW
*&---------------------------------------------------------------------*
*&      Form  BUILD_FIELDCATALOG_OVERVIEW
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
**----------------------------------------------------------------------*
*&---------------------------------------------------------------------*
*&      Form  AUTHCHECK_OVERVIEW
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM AUTHCHECK_OVERVIEW .

*  LOOP AT IT_FINOVR INTO WA_FINOVR.
*    AUTHORITY-CHECK OBJECT 'ZINVOICE'
*    ID 'ZVKBUR' FIELD WA_FINOVR-VKBUR
*    ID 'ZSPART' DUMMY
*    ID 'ACTVT' FIELD '03'.
*    IF SY-SUBRC NE 0.
*      WA_FINOVR-FLAG = 'x' .
*      MODIFY IT_FINOVR FROM WA_FINOVR TRANSPORTING FLAG.
*      MESSAGE 'NO AUTHORIZATION FOR CERTAIN RECORDS' TYPE 'S'.
*    ENDIF.
*
*    AUTHORITY-CHECK OBJECT 'ZINVOICE'
*    ID 'ZVKBUR' DUMMY
*    ID 'ZSPART' FIELD WA_FINOVR-SPART
*    ID 'ACTVT' FIELD '03'.
*    IF SY-SUBRC NE 0.
*      WA_FINOVR-FLAG = 'x' .
*      MODIFY IT_FINOVR FROM WA_FINOVR TRANSPORTING FLAG.
*      MESSAGE 'NO AUTHORIZATION FOR CERTAIN RECORDS' TYPE 'S'.
*    ENDIF.
*    CLEAR: WA_FINOVR.
*  ENDLOOP.
*
*  DELETE IT_FINOVR WHERE FLAG = 'x'.


*  LOOP AT IT_FINOVR INTO WA_FINOVR.
*    AUTHORITY-CHECK OBJECT 'ZINVOICE'
*    ID 'ZVKBUR' FIELD WA_FINOVR-VKBUR
*    ID 'ZSPART' FIELD WA_FINOVR-SPART
*   " ID 'ZSPART' DUMMY
*    ID 'ACTVT' FIELD '03'.
*    IF SY-SUBRC NE 0.
*      WA_FINOVR-FLAG = 'x' .
*      MODIFY IT_FINOVR FROM WA_FINOVR TRANSPORTING FLAG.
*      MESSAGE 'NO AUTHORIZATION FOR CERTAIN RECORDS' TYPE 'S'.
*    ENDIF.
*    CLEAR: WA_FINOVR.
*  ENDLOOP.
*
*  DELETE IT_FINOVR WHERE FLAG = 'X' .


 LOOP AT IT_FINOVR INTO WA_FINOVR.
  AUTHORITY-CHECK OBJECT 'ZRIGHTS'
    ID 'ZVKBUR' FIELD WA_FINOVR-VKBUR
    ID 'ZSPART' DUMMY
    ID 'ZFKART' DUMMY
    ID 'ZMTART' DUMMY
    ID 'ACTVT' FIELD '03'.
    IF SY-SUBRC NE 0.
      WA_FINOVR-FLAG = 'x' .
      MODIFY IT_FINOVR FROM WA_FINOVR TRANSPORTING FLAG.
      MESSAGE 'NO AUTHORIZATION FOR CERTAIN RECORDS' TYPE 'S'.
    ENDIF.

 AUTHORITY-CHECK OBJECT 'ZRIGHTS'
    ID 'ZVKBUR' DUMMY
    ID 'ZSPART' FIELD WA_FINOVR-SPART
    ID 'ZFKART' DUMMY
    ID 'ZMTART' DUMMY
    ID 'ACTVT' FIELD '03'.
    IF SY-SUBRC NE 0.
      WA_FINOVR-FLAG = 'x' .
      MODIFY IT_FINOVR FROM WA_FINOVR TRANSPORTING FLAG.
      MESSAGE 'NO AUTHORIZATION FOR CERTAIN RECORDS' TYPE 'S'.
    ENDIF.

 AUTHORITY-CHECK OBJECT 'ZRIGHTS'
    ID 'ZVKBUR' DUMMY
    ID 'ZSPART' DUMMY
    ID 'ZFKART' FIELD WA_FINOVR-FKART
    ID 'ZMTART' DUMMY
    ID 'ACTVT' FIELD '03'.
    IF SY-SUBRC NE 0.
      WA_FINOVR-FLAG = 'x' .
      MODIFY IT_FINOVR FROM WA_FINOVR TRANSPORTING FLAG.
      MESSAGE 'NO AUTHORIZATION FOR CERTAIN RECORDS' TYPE 'S'.
    ENDIF.

 AUTHORITY-CHECK OBJECT 'ZRIGHTS'
    ID 'ZVKBUR' DUMMY
    ID 'ZSPART' DUMMY
    ID 'ZFKART' DUMMY
    ID 'ZMTART' FIELD WA_FINOVR-MTART
    ID 'ACTVT' FIELD '03'.
    IF SY-SUBRC NE 0.
      WA_FINOVR-FLAG = 'x' .
      MODIFY IT_FINOVR FROM WA_FINOVR TRANSPORTING FLAG.
      MESSAGE 'NO AUTHORIZATION FOR CERTAIN RECORDS' TYPE 'S'.
    ENDIF.


    CLEAR: WA_FINOVR.
  ENDLOOP.

  DELETE IT_FINOVR WHERE FLAG = 'x'.

ENDFORM.                    " AUTHCHECK_OVERVIEW



*&---------------------------------------------------------------------*
*&      Form  BUILD_FIELDCATALOG_OVERVIEW
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
FORM BUILD_FIELDCATALOG_OVERVIEW .

  WA_FIELDCAT-FIELDNAME   = 'KUNNR'.
  WA_FIELDCAT-SELTEXT_M   = 'Customer Code'.
  WA_FIELDCAT-COL_POS     = 1.
*  WA_FIELDCAT-KEY    = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'NAME1'.           " ADDED BY RAM
  WA_FIELDCAT-SELTEXT_M   = 'Customer Name'.
  WA_FIELDCAT-COL_POS     = 2.
*  WA_FIELDCAT-KEY    = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'GBEZEI'.
  WA_FIELDCAT-SELTEXT_M   = 'MATERIAL GROUP DESC.'.
  WA_FIELDCAT-COL_POS     = 3.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.
*
*  WA_SORT-FIELDNAME = 'GBEZEI'.
*  WA_SORT-UP = 'X'.
*  WA_SORT-GROUP = 'X'.
*  APPEND WA_SORT TO IT_SORT.
*  CLEAR WA_SORT.

  WA_FIELDCAT-FIELDNAME   = 'MATNR'.
  WA_FIELDCAT-SELTEXT_M   = 'MATERIAL'.
  WA_FIELDCAT-COL_POS     = 4.
  WA_SORT-GROUP = 'X'.
*  WA_FIELDCAT-KEY    = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'MAKTX'.
  WA_FIELDCAT-SELTEXT_M   = 'MATERIAL DESCRIPTION'.
  WA_FIELDCAT-COL_POS     = 5.
*  WA_FIELDCAT-KEY    = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.


  WA_FIELDCAT-FIELDNAME   = 'VKBUR'.
  WA_FIELDCAT-SELTEXT_M   = 'SALES OFFICE'.
  WA_FIELDCAT-COL_POS     = 6.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

*  WA_FIELDCAT-FIELDNAME   = 'V_COUNT'.
*  WA_FIELDCAT-SELTEXT_M   = 'Count'.
*  WA_FIELDCAT-COL_POS     = 6.
*  APPEND WA_FIELDCAT TO IT_FIELDCAT.
*  CLEAR  WA_FIELDCAT.
*
*  WA_FIELDCAT-FIELDNAME   = 'VKORG'.
*  WA_FIELDCAT-SELTEXT_M   = 'SALES ORGANIZATION'.
*  WA_FIELDCAT-COL_POS     = 6.
*  APPEND WA_FIELDCAT TO IT_FIELDCAT.
*  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'BEZEI'.
  WA_FIELDCAT-SELTEXT_M   = 'SALES DESCRIPTION'.
  WA_FIELDCAT-COL_POS     = 7.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.
  """""""added by ram on 1/10/2015
  WA_FIELDCAT-FIELDNAME   = 'FKART'.
  WA_FIELDCAT-SELTEXT_M   = 'BILLING TYPE'.
  WA_FIELDCAT-COL_POS     = 10.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.
  """""""ended by ram on 1/10/2015

  WA_FIELDCAT-FIELDNAME   = 'SPART'.
  WA_FIELDCAT-SELTEXT_M   = 'SALES DIVISION'.
  WA_FIELDCAT-COL_POS     = 8.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'VTEXT'.
  WA_FIELDCAT-SELTEXT_M   = 'SALES DIVISION DESC'.
  WA_FIELDCAT-COL_POS     = 9.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

*  WA_FIELDCAT-FIELDNAME   = 'KUNRG'.
*  WA_FIELDCAT-SELTEXT_M   = 'Customer Code'.
*  WA_FIELDCAT-COL_POS     = 11.
*  WA_FIELDCAT-CFIELDNAME   = 'KUNRG'.
*  WA_FIELDCAT-CTABNAME    = 'VBRK'.
*
*  APPEND WA_FIELDCAT TO IT_FIELDCAT.
*  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'VOLUM'.
  WA_FIELDCAT-SELTEXT_M   = 'Liters Per Material'.
  WA_FIELDCAT-COL_POS     = 11.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'FKIMG'.
  WA_FIELDCAT-SELTEXT_M   = 'Total Inv.Qty'.
  WA_FIELDCAT-COL_POS     = 12.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  WA_FIELDCAT-DO_SUM      = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  "                          ADDED BY RAM ON 03/11/2015
  WA_FIELDCAT-FIELDNAME   = 'VRKME'.
  WA_FIELDCAT-SELTEXT_M   = 'UOM'.
  WA_FIELDCAT-COL_POS     = 13.
*  WA_FIELDCAT-NO_ZERO     = 'X'.
*  WA_FIELDCAT-DO_SUM      = 'X'.
  WA_FIELDCAT-CTABNAME    = 'VBRP'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  "                                   ENDED BY RAM ON 03/11/2015


  WA_FIELDCAT-FIELDNAME   = 'QTY_LTR'.
  WA_FIELDCAT-SELTEXT_M   = 'TOTAL IN Liters/KGS'.
  WA_FIELDCAT-COL_POS     = 14.
  WA_FIELDCAT-DO_SUM      = 'X'.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.


  WA_FIELDCAT-FIELDNAME   = 'NETWR'.
  WA_FIELDCAT-SELTEXT_M   = 'NET VALUE'.
  WA_FIELDCAT-COL_POS     = 15.
  WA_FIELDCAT-DO_SUM      = 'X'.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'QTY0'.
  WA_FIELDCAT-SELTEXT_M   = 'April Qty'.
  WA_FIELDCAT-COL_POS     = 16.
*  WA_FIELDCAT-NO_ZERO     = 'X'.
  WA_FIELDCAT-DO_SUM      = 'X'.
*  WA_FIELDCAT-CFIELDNAME   = 'KUNAG'.
*  WA_FIELDCAT-CTABNAME    = 'VBRK'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.


*WA_FIELDCAT-FIELDNAME   = 'AVOLUM'.
*  WA_FIELDCAT-SELTEXT_M   = 'April Volume'.
*  WA_FIELDCAT-COL_POS     = 16.
*  WA_FIELDCAT-NO_ZERO     = 'X'.
*  WA_FIELDCAT-DO_SUM      = 'X'.
*  WA_FIELDCAT-CFIELDNAME   = 'KUNAG'.
*  WA_FIELDCAT-CTABNAME    = 'VBRK'.
*APPEND WA_FIELDCAT TO IT_FIELDCAT.
*  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'VOL0'.
  WA_FIELDCAT-SELTEXT_M   = 'April Liters/KGS'.
  WA_FIELDCAT-COL_POS     = 17.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  WA_FIELDCAT-DO_SUM      = 'X'.
  WA_FIELDCAT-CTABNAME    = 'VBRK'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'AMT0'.
  WA_FIELDCAT-SELTEXT_M   = 'April Value'.
  WA_FIELDCAT-COL_POS     = 18.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  WA_FIELDCAT-DO_SUM      = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'QTY1'.
  WA_FIELDCAT-SELTEXT_M   = 'May Qty'.
  WA_FIELDCAT-COL_POS     = 19.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  WA_FIELDCAT-DO_SUM      = 'X'.
*  WA_FIELDCAT-CFIELDNAME   = 'KUNAG'.
*  WA_FIELDCAT-CTABNAME    = 'VBRK'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'VOL1'.
  WA_FIELDCAT-SELTEXT_M   = 'May Liters/KGS'.
  WA_FIELDCAT-COL_POS     = 20.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  WA_FIELDCAT-DO_SUM      = 'X'.
*  WA_FIELDCAT-CFIELDNAME   = 'KUNAG'.
  WA_FIELDCAT-CTABNAME    = 'VBRK'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'AMT1'.
  WA_FIELDCAT-SELTEXT_M   = 'May Value'.
  WA_FIELDCAT-COL_POS     = 21.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  WA_FIELDCAT-DO_SUM      = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'QTY2'.
  WA_FIELDCAT-SELTEXT_M   = 'June Qty'.
  WA_FIELDCAT-COL_POS     = 22.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  WA_FIELDCAT-DO_SUM      = 'X'.
*  WA_FIELDCAT-CFIELDNAME   = 'KUNAG'.
*  WA_FIELDCAT-CTABNAME    = 'VBRK'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'VOL2'.
  WA_FIELDCAT-SELTEXT_M   = 'June Liters/KGS'.
  WA_FIELDCAT-COL_POS     = 23.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  WA_FIELDCAT-DO_SUM      = 'X'.
*  WA_FIELDCAT-CFIELDNAME   = 'KUNAG'.
  WA_FIELDCAT-CTABNAME    = 'VBRK'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'AMT2'.
  WA_FIELDCAT-SELTEXT_M   = 'June Value'.
  WA_FIELDCAT-COL_POS     = 24.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  WA_FIELDCAT-DO_SUM      = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'QTY3'.
  WA_FIELDCAT-SELTEXT_M   = 'July Qty'.
  WA_FIELDCAT-COL_POS     = 25.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  WA_FIELDCAT-DO_SUM      = 'X'.
*  WA_FIELDCAT-CFIELDNAME   = 'KUNAG'.
*  WA_FIELDCAT-CTABNAME    = 'VBRK'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'VOL3'.
  WA_FIELDCAT-SELTEXT_M   = 'July Liters/KGS'.
  WA_FIELDCAT-COL_POS     = 26.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  WA_FIELDCAT-DO_SUM      = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.


  WA_FIELDCAT-FIELDNAME   = 'AMT3'.
  WA_FIELDCAT-SELTEXT_M   = 'July Value'.
  WA_FIELDCAT-COL_POS     = 27.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  WA_FIELDCAT-DO_SUM      = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'QTY4'.
  WA_FIELDCAT-SELTEXT_M   = 'August Qty'.
  WA_FIELDCAT-COL_POS     = 28.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  WA_FIELDCAT-DO_SUM      = 'X'.
*  WA_FIELDCAT-CFIELDNAME   = 'KUNAG'.
*  WA_FIELDCAT-CTABNAME    = 'VBRK'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'VOL4'.
  WA_FIELDCAT-SELTEXT_M   = 'August Liters/KGS'.
  WA_FIELDCAT-COL_POS     = 29.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  WA_FIELDCAT-DO_SUM      = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'AMT4'.
  WA_FIELDCAT-SELTEXT_M   = 'Augest Value'.
  WA_FIELDCAT-COL_POS     = 30.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  WA_FIELDCAT-DO_SUM      = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'QTY5'.
  WA_FIELDCAT-SELTEXT_M   = 'September Qty'.
  WA_FIELDCAT-COL_POS     = 31.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  WA_FIELDCAT-DO_SUM      = 'X'.
*  WA_FIELDCAT-CFIELDNAME   = 'KUNAG'.
*  WA_FIELDCAT-CTABNAME    = 'VBRK'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'VOL5'.
  WA_FIELDCAT-SELTEXT_M   = 'September Liters/KGS'.
  WA_FIELDCAT-COL_POS     = 32.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  WA_FIELDCAT-DO_SUM      = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'AMT5'.
  WA_FIELDCAT-SELTEXT_M   = 'September Value'.
  WA_FIELDCAT-COL_POS     = 33.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  WA_FIELDCAT-DO_SUM      = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'QTY6'.
  WA_FIELDCAT-SELTEXT_M   = 'October Qty'.
  WA_FIELDCAT-COL_POS     = 34.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  WA_FIELDCAT-DO_SUM      = 'X'.
*  WA_FIELDCAT-CFIELDNAME   = 'KUNAG'.
*  WA_FIELDCAT-CTABNAME    = 'VBRK'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'VOL6'.
  WA_FIELDCAT-SELTEXT_M   = 'October Liters/KGS'.
  WA_FIELDCAT-COL_POS     = 35.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  WA_FIELDCAT-DO_SUM      = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'AMT6'.
  WA_FIELDCAT-SELTEXT_M   = 'October Value'.
  WA_FIELDCAT-COL_POS     = 36.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  WA_FIELDCAT-DO_SUM      = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'QTY7'.
  WA_FIELDCAT-SELTEXT_M   = 'November Qty'.
  WA_FIELDCAT-COL_POS     = 37.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  WA_FIELDCAT-DO_SUM      = 'X'.
*  WA_FIELDCAT-CFIELDNAME   = 'KUNAG'.
*  WA_FIELDCAT-CTABNAME    = 'VBRK'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'VOL7'.
  WA_FIELDCAT-SELTEXT_M   = 'November Liters/KGS'.
  WA_FIELDCAT-COL_POS     = 38.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  WA_FIELDCAT-DO_SUM      = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'AMT7'.
  WA_FIELDCAT-SELTEXT_M   = 'November  Value'.
  WA_FIELDCAT-COL_POS     = 39.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  WA_FIELDCAT-DO_SUM      = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'QTY8'.
  WA_FIELDCAT-SELTEXT_M   = 'December Qty'.
  WA_FIELDCAT-COL_POS     = 40.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  WA_FIELDCAT-DO_SUM      = 'X'.
*  WA_FIELDCAT-CFIELDNAME   = 'KUNAG'.
*  WA_FIELDCAT-CTABNAME    = 'VBRK'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'VOL8'.
  WA_FIELDCAT-SELTEXT_M   = 'December Liters/KGS'.
  WA_FIELDCAT-COL_POS     = 41.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  WA_FIELDCAT-DO_SUM      = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'AMT8'.
  WA_FIELDCAT-SELTEXT_M   = 'December  Value'.
  WA_FIELDCAT-COL_POS     = 42.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  WA_FIELDCAT-DO_SUM      = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'QTY9'.
  WA_FIELDCAT-SELTEXT_M   = 'Jan. Qty'.
  WA_FIELDCAT-COL_POS     = 43.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  WA_FIELDCAT-DO_SUM      = 'X'.
*  WA_FIELDCAT-CFIELDNAME   = 'KUNAG'.
*  WA_FIELDCAT-CTABNAME    = 'VBRK'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'VOL9'.
  WA_FIELDCAT-SELTEXT_M   = 'January Liters/KGS'.
  WA_FIELDCAT-COL_POS     = 44.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  WA_FIELDCAT-DO_SUM      = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'AMT9'.
  WA_FIELDCAT-SELTEXT_M   = 'January Value'.
  WA_FIELDCAT-COL_POS     = 45.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  WA_FIELDCAT-DO_SUM      = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'QTY10'.
  WA_FIELDCAT-SELTEXT_M   = 'Febrary Qty'.
  WA_FIELDCAT-COL_POS     = 46.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  WA_FIELDCAT-DO_SUM      = 'X'.
*  WA_FIELDCAT-CFIELDNAME   = 'KUNAG'.
*  WA_FIELDCAT-CTABNAME    = 'VBRK'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'VOL10'.
  WA_FIELDCAT-SELTEXT_M   = 'Febrary Liters/KGS'.
  WA_FIELDCAT-COL_POS     = 47.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  WA_FIELDCAT-DO_SUM      = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'AMT10'.
  WA_FIELDCAT-SELTEXT_M   = 'Febrary Value'.
  WA_FIELDCAT-COL_POS     = 48.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  WA_FIELDCAT-DO_SUM      = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'QTY11'.
  WA_FIELDCAT-SELTEXT_M   = 'March Qty'.
  WA_FIELDCAT-COL_POS     = 49.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  WA_FIELDCAT-DO_SUM      = 'X'.
*  WA_FIELDCAT-CFIELDNAME   = 'KUNAG'.
*  WA_FIELDCAT-CTABNAME    = 'VBRK'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'VOL11'.
  WA_FIELDCAT-SELTEXT_M   = 'March Liters/KGS'.
  WA_FIELDCAT-COL_POS     = 50.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  WA_FIELDCAT-DO_SUM      = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'AMT11'.
  WA_FIELDCAT-SELTEXT_M   = 'March Value'.
  WA_FIELDCAT-COL_POS     = 51.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  WA_FIELDCAT-DO_SUM      = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

*&-----Begin of Keerthi CLSS on 26-08-2016-----*
  WA_FIELDCAT-FIELDNAME   = 'SO_NO'.
  WA_FIELDCAT-SELTEXT_M   = 'S.O NO'.
  WA_FIELDCAT-COL_POS     = 52.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'SO_NAME'.
  WA_FIELDCAT-SELTEXT_M   = 'S.O Name'.
  WA_FIELDCAT-COL_POS     = 53.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'SM_NO'.
  WA_FIELDCAT-SELTEXT_M   = 'S.M NO'.
  WA_FIELDCAT-COL_POS     = 54.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'SM_NAME'.
  WA_FIELDCAT-SELTEXT_M   = 'S.M Name'.
  WA_FIELDCAT-COL_POS     = 55.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'MTART'.
  WA_FIELDCAT-SELTEXT_M   = 'Material Type'.
  WA_FIELDCAT-COL_POS     = 58.
  WA_FIELDCAT-NO_ZERO     = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.


*&------End of Keerthi CLSS on 26-08-2016------*

  WA_SORT-FIELDNAME = 'KUNNR'.
  WA_SORT-UP = 'X'.
  WA_SORT-GROUP = 'X'.
  WA_SORT-SUBTOT = 'X'.
  APPEND WA_SORT TO IT_SORT.
  CLEAR WA_SORT.
*
  WA_SORT-FIELDNAME = 'NAME1'.
*  WA_SORT-UP = 'X'.
  WA_SORT-GROUP = 'X'.
  APPEND WA_SORT TO IT_SORT.
  CLEAR WA_SORT.
*
  WA_SORT-FIELDNAME = 'MATNR'.
*  WA_SORT-UP = 'X'.
*  WA_SORT-SUBTOT = 'X'.
  WA_SORT-GROUP = 'X'.
  APPEND WA_SORT TO IT_SORT.
  CLEAR WA_SORT.

  WA_SORT-FIELDNAME = 'MAKTX'.
*  WA_SORT-UP = 'X'.
*  WA_SORT-SUBTOT = 'X'.
  WA_SORT-GROUP = 'X'.
  APPEND WA_SORT TO IT_SORT.
  CLEAR WA_SORT.

  WA_SORT-FIELDNAME = 'VKBUR'.
*  WA_SORT-UP = 'X'.
*  WA_SORT-SUBTOT = 'X'.
  WA_SORT-GROUP = 'X'.
  APPEND WA_SORT TO IT_SORT.
  CLEAR WA_SORT.
*
*    WA_SORT-FIELDNAME = 'VKORG'.
**  WA_SORT-UP = 'X'.
**  WA_SORT-SUBTOT = 'X'.
*  WA_SORT-GROUP = 'X'.
*  APPEND WA_SORT TO IT_SORT.
*  CLEAR WA_SORT.

  WA_SORT-FIELDNAME = 'SPART'.
*  WA_SORT-UP = 'X'.
*  WA_SORT-SUBTOT = 'X'.
  WA_SORT-GROUP = 'X'.
  APPEND WA_SORT TO IT_SORT.
  CLEAR WA_SORT.

  WA_SORT-FIELDNAME = 'VTEXT'.
*  WA_SORT-UP = 'X'.
*  WA_SORT-SUBTOT = 'X'.
  WA_SORT-GROUP = 'X'.
  APPEND WA_SORT TO IT_SORT.
  CLEAR WA_SORT.

  WA_SORT-FIELDNAME = 'BEZEI'.
*  WA_SORT-UP = 'X'.
*  WA_SORT-SUBTOT = 'X'.
  WA_SORT-GROUP = 'X'.
  APPEND WA_SORT TO IT_SORT.
  CLEAR WA_SORT.

  WA_SORT-FIELDNAME = 'FKIMG'.
  WA_SORT-DOWN = 'X'.
*  WA_SORT-SUBTOT = 'X'.
  WA_SORT-GROUP = 'X'.
  APPEND WA_SORT TO IT_SORT.
  CLEAR WA_SORT.

  WA_SORT-FIELDNAME = 'VOLUM'.
  WA_SORT-UP = 'X'.
*  WA_SORT-SUBTOT = 'X'.
  WA_SORT-GROUP = 'X'.
  APPEND WA_SORT TO IT_SORT.
  CLEAR WA_SORT.

ENDFORM.                    "BUILD_FIELDCATALOG_OVERVIEW

" BUILD_FIELDCATALOG_OVERVIEW
*&---------------------------------------------------------------------*
*&      Form  BUILD_ALV_OVERVIEW
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM BUILD_ALV_OVERVIEW .

  LAYOUT-COLWIDTH_OPTIMIZE = 'X'.                                  "Changed by S.Savariar as on 20/10/2014.
  LAYOUT-ZEBRA = 'X'.

  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
  EXPORTING
*   I_INTERFACE_CHECK                 = ' '
*   I_BYPASSING_BUFFER                = ' '
*   I_BUFFER_ACTIVE                   = ' '
      I_CALLBACK_PROGRAM                = SY-REPID
*      I_CALLBACK_PF_STATUS_SET          = 'PF_STATUS_GET'
*      I_CALLBACK_USER_COMMAND           = 'MY_USER_COMMAND'
   I_CALLBACK_TOP_OF_PAGE            = 'ALV_CATALOG_HEADER'
*   I_CALLBACK_HTML_TOP_OF_PAGE       = ' '
*   I_CALLBACK_HTML_END_OF_LIST       = ' '
*   I_STRUCTURE_NAME                  =
*   I_BACKGROUND_ID                   = ' '
*   I_GRID_TITLE                      =
*   I_GRID_SETTINGS                   =
   IS_LAYOUT                          = LAYOUT
      IT_FIELDCAT                       = IT_FIELDCAT
*   IT_EXCLUDING                      =
*   IT_SPECIAL_GROUPS                 =
    IT_SORT                           = IT_SORT
*   IT_FILTER                         =
*   IS_SEL_HIDE                       =
   I_DEFAULT                         = 'X'
   I_SAVE                            = 'A'
*   IS_VARIANT                        =
*   IT_EVENTS                         =
*   IT_EVENT_EXIT                     =
*   IS_PRINT                          =
*   IS_REPREP_ID                      =
*   I_SCREEN_START_COLUMN             = 0
*   I_SCREEN_START_LINE               = 0
*   I_SCREEN_END_COLUMN               = 0
*   I_SCREEN_END_LINE                 = 0
*   I_HTML_HEIGHT_TOP                 = 0
*   I_HTML_HEIGHT_END                 = 0
*   IT_ALV_GRAPHICS                   =
*   IT_HYPERLINK                      =
*   IT_ADD_FIELDCAT                   =
*   IT_EXCEPT_QINFO                   =
*   IR_SALV_FULLSCREEN_ADAPTER        =
* IMPORTING
*   E_EXIT_CAUSED_BY_CALLER           =
*   ES_EXIT_CAUSED_BY_USER            =
    TABLES
      T_OUTTAB                          = IT_FINOVR[]
* EXCEPTIONS
*   PROGRAM_ERROR                     = 1
*   OTHERS                            = 2
            .
  IF SY-SUBRC <> 0.
* MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.


ENDFORM.                    "BUILD_ALV_OVERVIEW

*---------------------------------------------------
*&      Form  ALV_CATALOG_HEADER
*&-------------------------------------------------------------------
*       text
*--------------------------------------------------------------------
*  -->  p1        text
*  <--  p2        text
*--------------------------------------------------------------------
FORM ALV_CATALOG_HEADER.
  DATA : LIT_HEADER TYPE  SLIS_T_LISTHEADER,
       LS_LINE TYPE SLIS_LISTHEADER.
  CLEAR LS_LINE.
  LS_LINE-TYP  = 'H'.
  LS_LINE-KEY = ' '.
  LS_LINE-INFO = 'Customer With Product Month Wise Report' .
  APPEND LS_LINE TO LIT_HEADER.
  CALL FUNCTION 'REUSE_ALV_COMMENTARY_WRITE'
    EXPORTING
      IT_LIST_COMMENTARY = LIT_HEADER
      I_LOGO             = 'ZLOGO'.
*  CALL FUNCTION 'CONVERSION_EXIT_SDATE_OUTPUT'
*    EXPORTING
*      INPUT  = LV_BUDAT_MKPF
*    IMPORTING
*      OUTPUT = LV_BUDAT_MKPF.

**  CALL FUNCTION 'CONVERSION_EXIT_SDATE_OUTPUT'
**
**  EXPORTING
**    INPUT         = LV_BEDAT.

*      I_LOGO             = ' '.

ENDFORM.                    "ALV_CATALOG_HEADER


*&---------------------------------------------------------------------*
*&      Form  AUTHCHECK_OVERVIEW_NEW
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM AUTHCHECK_OVERVIEW_NEW .

*  BREAK-POINT.
*
*   LOOP AT IT_FINOVR INTO WA_FINOVR.
*  AUTHORITY-CHECK OBJECT 'ZRIGHTS'
*    ID 'ZVKBUR' FIELD WA_FINOVR-VKBUR
*    ID 'ZSPART' DUMMY
*    ID 'ZFKART' DUMMY
*    ID 'ZMTART' DUMMY
*    ID 'ACTVT' FIELD '03'.
*    IF SY-SUBRC NE 0.
*      WA_FINOVR-FLAG = 'x' .
*      MODIFY IT_FINOVR FROM WA_FINOVR TRANSPORTING FLAG.
*      MESSAGE 'NO AUTHORIZATION FOR CERTAIN RECORDS' TYPE 'S'.
*    ENDIF.
*    CLEAR WA_FINOVR.
*    ENDLOOP.
*
*    DELETE IT_FINOVR WHERE FLAG = 'x'.

ENDFORM.                    " AUTHCHECK_OVERVIEW_NEW
