*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSD_CF_ACTIVATEV................................*
FORM GET_DATA_ZSD_CF_ACTIVATEV.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSD_CF_ACTIVATE WHERE
(VIM_WHERETAB) .
    CLEAR ZSD_CF_ACTIVATEV .
ZSD_CF_ACTIVATEV-MANDT =
ZSD_CF_ACTIVATE-MANDT .
ZSD_CF_ACTIVATEV-KUNNR =
ZSD_CF_ACTIVATE-KUNNR .
ZSD_CF_ACTIVATEV-APPRL =
ZSD_CF_ACTIVATE-APPRL .
ZSD_CF_ACTIVATEV-ACTIVE =
ZSD_CF_ACTIVATE-ACTIVE .
ZSD_CF_ACTIVATEV-CDATE =
ZSD_CF_ACTIVATE-CDATE .
ZSD_CF_ACTIVATEV-CTIME =
ZSD_CF_ACTIVATE-CTIME .
ZSD_CF_ACTIVATEV-CNAME =
ZSD_CF_ACTIVATE-CNAME .
ZSD_CF_ACTIVATEV-AEDAT =
ZSD_CF_ACTIVATE-AEDAT .
ZSD_CF_ACTIVATEV-AETIM =
ZSD_CF_ACTIVATE-AETIM .
ZSD_CF_ACTIVATEV-AENAM =
ZSD_CF_ACTIVATE-AENAM .
    SELECT SINGLE * FROM KNA1 WHERE
KUNNR = ZSD_CF_ACTIVATE-KUNNR .
    IF SY-SUBRC EQ 0.
ZSD_CF_ACTIVATEV-NAME1 =
KNA1-NAME1 .
ZSD_CF_ACTIVATEV-ZCUSTYPE =
KNA1-ZCUSTYPE .
    ENDIF.
<VIM_TOTAL_STRUC> = ZSD_CF_ACTIVATEV.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSD_CF_ACTIVATEV .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSD_CF_ACTIVATEV.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSD_CF_ACTIVATEV-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSD_CF_ACTIVATE WHERE
  KUNNR = ZSD_CF_ACTIVATEV-KUNNR .
    IF SY-SUBRC = 0.
    DELETE ZSD_CF_ACTIVATE .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSD_CF_ACTIVATE WHERE
  KUNNR = ZSD_CF_ACTIVATEV-KUNNR .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSD_CF_ACTIVATE.
    ENDIF.
ZSD_CF_ACTIVATE-MANDT =
ZSD_CF_ACTIVATEV-MANDT .
ZSD_CF_ACTIVATE-KUNNR =
ZSD_CF_ACTIVATEV-KUNNR .
ZSD_CF_ACTIVATE-APPRL =
ZSD_CF_ACTIVATEV-APPRL .
ZSD_CF_ACTIVATE-ACTIVE =
ZSD_CF_ACTIVATEV-ACTIVE .
ZSD_CF_ACTIVATE-CDATE =
ZSD_CF_ACTIVATEV-CDATE .
ZSD_CF_ACTIVATE-CTIME =
ZSD_CF_ACTIVATEV-CTIME .
ZSD_CF_ACTIVATE-CNAME =
ZSD_CF_ACTIVATEV-CNAME .
ZSD_CF_ACTIVATE-AEDAT =
ZSD_CF_ACTIVATEV-AEDAT .
ZSD_CF_ACTIVATE-AETIM =
ZSD_CF_ACTIVATEV-AETIM .
ZSD_CF_ACTIVATE-AENAM =
ZSD_CF_ACTIVATEV-AENAM .
    IF SY-SUBRC = 0.
    UPDATE ZSD_CF_ACTIVATE ##WARN_OK.
    ELSE.
    INSERT ZSD_CF_ACTIVATE .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSD_CF_ACTIVATEV-UPD_FLAG,
STATUS_ZSD_CF_ACTIVATEV-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSD_CF_ACTIVATEV.
  SELECT SINGLE * FROM ZSD_CF_ACTIVATE WHERE
KUNNR = ZSD_CF_ACTIVATEV-KUNNR .
ZSD_CF_ACTIVATEV-MANDT =
ZSD_CF_ACTIVATE-MANDT .
ZSD_CF_ACTIVATEV-KUNNR =
ZSD_CF_ACTIVATE-KUNNR .
ZSD_CF_ACTIVATEV-APPRL =
ZSD_CF_ACTIVATE-APPRL .
ZSD_CF_ACTIVATEV-ACTIVE =
ZSD_CF_ACTIVATE-ACTIVE .
ZSD_CF_ACTIVATEV-CDATE =
ZSD_CF_ACTIVATE-CDATE .
ZSD_CF_ACTIVATEV-CTIME =
ZSD_CF_ACTIVATE-CTIME .
ZSD_CF_ACTIVATEV-CNAME =
ZSD_CF_ACTIVATE-CNAME .
ZSD_CF_ACTIVATEV-AEDAT =
ZSD_CF_ACTIVATE-AEDAT .
ZSD_CF_ACTIVATEV-AETIM =
ZSD_CF_ACTIVATE-AETIM .
ZSD_CF_ACTIVATEV-AENAM =
ZSD_CF_ACTIVATE-AENAM .
    SELECT SINGLE * FROM KNA1 WHERE
KUNNR = ZSD_CF_ACTIVATE-KUNNR .
    IF SY-SUBRC EQ 0.
ZSD_CF_ACTIVATEV-NAME1 =
KNA1-NAME1 .
ZSD_CF_ACTIVATEV-ZCUSTYPE =
KNA1-ZCUSTYPE .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZSD_CF_ACTIVATEV-NAME1 .
      CLEAR ZSD_CF_ACTIVATEV-ZCUSTYPE .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSD_CF_ACTIVATEV USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSD_CF_ACTIVATEV-KUNNR TO
ZSD_CF_ACTIVATE-KUNNR .
MOVE ZSD_CF_ACTIVATEV-MANDT TO
ZSD_CF_ACTIVATE-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSD_CF_ACTIVATE'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSD_CF_ACTIVATE TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSD_CF_ACTIVATE'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZSD_CF_ACTIVATEV USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZSD_CF_ACTIVATE-MANDT =
ZSD_CF_ACTIVATEV-MANDT .
ZSD_CF_ACTIVATE-KUNNR =
ZSD_CF_ACTIVATEV-KUNNR .
ZSD_CF_ACTIVATE-APPRL =
ZSD_CF_ACTIVATEV-APPRL .
ZSD_CF_ACTIVATE-ACTIVE =
ZSD_CF_ACTIVATEV-ACTIVE .
ZSD_CF_ACTIVATE-CDATE =
ZSD_CF_ACTIVATEV-CDATE .
ZSD_CF_ACTIVATE-CTIME =
ZSD_CF_ACTIVATEV-CTIME .
ZSD_CF_ACTIVATE-CNAME =
ZSD_CF_ACTIVATEV-CNAME .
ZSD_CF_ACTIVATE-AEDAT =
ZSD_CF_ACTIVATEV-AEDAT .
ZSD_CF_ACTIVATE-AETIM =
ZSD_CF_ACTIVATEV-AETIM .
ZSD_CF_ACTIVATE-AENAM =
ZSD_CF_ACTIVATEV-AENAM .
    SELECT SINGLE * FROM KNA1 WHERE
KUNNR = ZSD_CF_ACTIVATE-KUNNR .
    IF SY-SUBRC EQ 0.
ZSD_CF_ACTIVATEV-NAME1 =
KNA1-NAME1 .
ZSD_CF_ACTIVATEV-ZCUSTYPE =
KNA1-ZCUSTYPE .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZSD_CF_ACTIVATEV-NAME1 .
      CLEAR ZSD_CF_ACTIVATEV-ZCUSTYPE .
    ENDIF.
ENDFORM.
