*&---------------------------------------------------------------------*
*& Report   ZSD_CUSTREPORT_MONTHWISE
*&
*&---------------------------------------------------------------------*
*&---------------------------------------------------------------------*
*&Functional                   : Mr.Govindarajan M                     *
*& Developer                   : Mr.Govindarajan M                     *
*& Created On                  :                                       *
*& Company                     : Sheenlac Paints Pvt Ltd               *
*& Verified By                 :                                       *
*& Title                       : Customer Register Month wise          *
*& Report Name                 : ZSD_CUSTREPORT_MONTHWISE             *
*& Development Id              : kpabap                                *
*& Related Information         : Customer Register Month wise          *
*&---------------------------------------------------------------------*
REPORT ZSD_CUSTREPORT_MONTHWISE_OLD.

DATA:
      W_AUX_FKDAT TYPE VBRK-FKDAT,
      W_FKART TYPE VBRK-FKART,
      W_VBELN TYPE VBRK-VBELN,
      W_KUNAG TYPE VBRK-KUNAG,
      W_MATNR TYPE VBRP-MATNR,
      W_CHARG TYPE LIPS-CHARG,                               " BATCH FOR INVOICE DETAILS
      W_INV_VKBUR TYPE VBRP-VKBUR,                           " SALES OFFICE FOR INVOICE
      W_SPART TYPE VBRK-SPART,

      COUNTER TYPE I VALUE '0',
      GT_LIST     TYPE VRM_VALUES,
      GWA_LIST    TYPE VRM_VALUE,
      GT_VALUES   TYPE TABLE OF DYNPREAD,                     " INTERNAL TABLE FOR LIST BOX
      GWA_VALUES  TYPE DYNPREAD,                              " WORK AREA FOR LIST BOX
      GV_SELECTED_VALUE(10) TYPE C,
      IT_FIELDCAT  TYPE TABLE OF SLIS_FIELDCAT_ALV,
      WA_FIELDCAT  LIKE LINE OF IT_FIELDCAT,
      IT_SORT TYPE SLIS_T_SORTINFO_ALV,
      WA_SORT LIKE LINE OF IT_SORT,
      G_SENT_TO_ALL TYPE SONV-FLAG,
      G_TAB_LINES   TYPE I,


      W_KUNNR TYPE KNC1-KUNNR,
      W_BUKRS TYPE KNC1-BUKRS,                                " VARIABLE DECLARATIONS FOR ACCOUNT BALANCES
      W_VKBUR TYPE KNVV-VKBUR,                                " SALES OFFICE FOR ACCOUNT BALANCES
*      W_GJAHR TYPE KNC1-GJAHR,
      W_RE_PERIOD TYPE BSID-MONAT,

      W_S_MATNR TYPE MARD-MATNR,                               " VARIABLE DECLARATIONS FOR STOCK
      W_S_BUKRS TYPE T001-BUKRS,
      W_S_HKONT TYPE BSEG-HKONT,
      W_S_WERKS TYPE T001W-WERKS,
      W_S_LGORT TYPE T001L-LGORT,
      W_S_CHARG TYPE MCHB-CHARG,
      W_S_BWTAR TYPE MBEW-BWTAR,
      W_S_BWART TYPE MSEG-BWART,
            W_S_DATUM TYPE MKPF-BUDAT.


DATA : LAYOUT TYPE SLIS_LAYOUT_ALV.


*--------------------------------------------------------------*
* TYPES DECLARATION
*--------------------------------------------------------------*


TYPES: BEGIN OF TY_VBRK_VBRP,                           "FINAL TABLE TYPE FOR OVERVIEW REPORT
       BUKRS TYPE VBRK-BUKRS,
       FKDAT TYPE VBRK-FKDAT,
       SPART TYPE VBRK-SPART,
       VRKME TYPE VBRP-VRKME,
       VBELN TYPE VBRK-VBELN,
       FKART TYPE VBRK-FKART,
       KUNAG TYPE VBRK-KUNAG,
       KUNRG TYPE VBRK-KUNRG,
       VKORG TYPE VBRK-VKORG,
       VTWEG TYPE VBRK-VTWEG,
       NETWR TYPE VBRK-NETWR,
       SFAKN TYPE VBRK-SFAKN,
       KNKLI TYPE VBRK-KNKLI,
       MWSBK TYPE VBRK-MWSBK,
       FKSTO TYPE VBRK-FKSTO,
       POSNR TYPE VBRP-POSNR,
       VKBUR TYPE VBRP-VKBUR,
       MATNR TYPE VBRP-MATNR,
       FKIMG TYPE VBRP-FKIMG,
       VOLUM TYPE VBRP-VOLUM,
       VGBEL TYPE VBRP-VGBEL,
       END OF TY_VBRK_VBRP,


       BEGIN OF TY_TVKBT,
       VKBUR TYPE TVKBT-VKBUR,
       BEZEI TYPE TVKBT-BEZEI,
       END OF TY_TVKBT,

       BEGIN OF TY_TSPAT,
       SPART TYPE TSPAT-SPART,
       VTEXT TYPE TSPAT-VTEXT,
       END OF TY_TSPAT,

       BEGIN OF TY_KNA1,
       KUNNR TYPE KNA1-KUNNR,
       NAME1 TYPE KNA1-NAME1,
       NAME2 TYPE KNA1-NAME2,
       REGIO TYPE KNA1-REGIO,
       END OF TY_KNA1,

       BEGIN OF TY_KNVV,                             " ADDED BY RAM ON 21/11/2014
       KUNNR TYPE KNVV-KUNNR,
       VKORG TYPE KNVV-VKORG,
       KDGRP TYPE KNVV-KDGRP,
       SPART TYPE KNVV-SPART, " Added By Govind On 06/12/2014
       END OF TY_KNVV,

       BEGIN OF TY_T151T,
       SPRAS TYPE T151T-SPRAS,
       KDGRP TYPE T151T-KDGRP,
       KTEXT TYPE T151T-KTEXT,
       END OF TY_T151T,

       BEGIN OF TY_MARM,
       MATNR TYPE MARM-MATNR,
       MEINH TYPE MARM-MEINH,
       UMREZ TYPE MARM-UMREZ,
       UMREN TYPE MARM-UMREN,
       END OF TY_MARM,

 BEGIN OF GS_T005U ,
       BLAND TYPE T005U-BLAND ,                                                                                                           "TABLE 6
       BEZEI TYPE T005U-BEZEI ,                                  "REGION
       END OF GS_T005U ,

       BEGIN OF TY_FINOVR,                           "FINAL TABLE TYPE FOR OVERVIEW REPORT
       FKDAT TYPE VBRK-FKDAT,
       VKBUR TYPE VBRP-VKBUR,
       KUNRG TYPE VBRK-KUNAG,
       SPART TYPE VBRK-SPART,
       VBELN TYPE VBRK-VBELN,
       CANDOC(1) TYPE C,
       FKART TYPE VBRK-FKART,
       KUNAG TYPE VBRK-KUNAG,
*       KUNRG TYPE VBRK-KUNRG,
       VKORG TYPE VBRK-VKORG,
       VTWEG TYPE VBRK-VTWEG,
       NETWR TYPE VBRK-NETWR,
       SFAKN TYPE VBRK-SFAKN,
       KNKLI TYPE VBRK-KNKLI,
       MWSBK TYPE VBRK-MWSBK,
       FKSTO TYPE VBRK-FKSTO,
       BTGEW TYPE LIKP-BTGEW, " Commended by Govind on 12.05.2014
       INV_VAL TYPE NETWR,
       POSNR TYPE VBRP-POSNR,
       FKIMG TYPE VBRP-FKIMG,
       VNETWR TYPE VBRP-NETWR,
       BEZEI TYPE TVKBT-BEZEI,
       VTEXT TYPE TSPAT-VTEXT,
       NAME1 TYPE KNA1-NAME1,
       NAME2 TYPE KNA1-NAME2,
       KDGRP TYPE KNVV-KDGRP,              "ADDED BY RAM ON 21/11/2014
       SPRAS TYPE T151T-SPRAS,
       KTEXT TYPE T151T-KTEXT,
       M_VOLUM TYPE MARA-VOLUM,
       QTY_LTR TYPE P DECIMALS 2,
       T_VOLUM TYPE P DECIMALS 2,
       V_COUNT TYPE I,
       FLAG(1) TYPE C,
       N_MONTH TYPE  T009B-POPER,
       VOL0 TYPE P DECIMALS 2,     " APR
       VOL1 TYPE P DECIMALS 2,        "MAY
       VOL2 TYPE P   DECIMALS 2,   " JUNE
       VOL3 TYPE P DECIMALS 2,  " JULY
       VOL4 TYPE P DECIMALS 2,     " AUG
       VOL5 TYPE P DECIMALS 2,        "SEP
       VOL6 TYPE P   DECIMALS 2,   " OCT
       VOL7 TYPE P DECIMALS 2,  " NOV
       VOL8 TYPE P DECIMALS 2,     " DEC
       VOL9 TYPE P DECIMALS 2,        "JAN
       VOL10 TYPE P   DECIMALS 2,   " FEB
       VOL11 TYPE P DECIMALS 2,  " MAR
       AMT0 TYPE P DECIMALS 2,     " APR
       AMT1 TYPE P DECIMALS 2,        "MAY
       AMT2 TYPE P   DECIMALS 2,   " JUNE
       AMT3 TYPE P DECIMALS 2,  " JULY
       AMT4 TYPE P DECIMALS 2,     " AUG
       AMT5 TYPE P DECIMALS 2,        "SEP
       AMT6 TYPE P   DECIMALS 2,   " OCT
       AMT7 TYPE P DECIMALS 2,  " NOV
       AMT8 TYPE P DECIMALS 2,     " DEC
       AMT9 TYPE P DECIMALS 2,        "JAN
       AMT10 TYPE P   DECIMALS 2,   " FEB
       AMT11 TYPE P DECIMALS 2,  " MAR
       END OF TY_FINOVR.

TYPES: BEGIN OF TY_TVKBT2,
    VKBUR TYPE TVKBT-VKBUR,
    BEZEI TYPE TVKBT-BEZEI,
    END OF TY_TVKBT2,

    BEGIN OF TY_TSPAT2,
    SPART TYPE TSPAT-SPART,
    VTEXT TYPE TSPAT-VTEXT,
    END OF TY_TSPAT2,


    BEGIN OF TY_VBRP, " Added by Govind
      VBELN TYPE VBRP-VBELN,
      POSNR TYPE VBRP-POSNR,
      FKIMG TYPE VBRP-FKIMG,
      VOLUM TYPE VBRP-VOLUM,
      MATNR TYPE VBRP-MATNR,
      NETWR TYPE VBRP-NETWR,
      END OF TY_VBRP,

        BEGIN OF GS_VBRP, " Added by Govind
          VBELN TYPE  ZSKU_VBRP-VBELN,
          POSNR TYPE  ZSKU_VBRP-POSNR,
           FKIMG TYPE  ZSKU_VBRP-FKIMG,
          VOLUM TYPE ZSKU_VBRP-LTR,
             MATNR TYPE ZSKU_VBRP-MATNR,
           NETWR TYPE  ZSKU_VBRP-NET_AMOUNT,
         END OF GS_VBRP,

BEGIN OF TY_MARA,
  MATNR TYPE MARA-MATNR,
  VOLUM TYPE MARA-VOLUM,
  VOLEH TYPE MARA-VOLEH,
  END OF TY_MARA,


BEGIN OF TY_VDRK2,
FKDAT TYPE VBRK-FKDAT,
VBELN TYPE VBRP-VBELN,
LPOSNR TYPE LIPS-POSNR,
MATNR TYPE VBRP-MATNR,
FKIMG TYPE VBRP-FKIMG,
VGPOS TYPE VBRP-VGPOS,
VOLUM TYPE VBRP-VOLUM,
VOLEH TYPE VBRP-VOLEH,
PSTYV TYPE LIPS-PSTYV,
SPART TYPE  VBRK-SPART,
NETWR TYPE VBRK-NETWR,
KUNAG TYPE VBRK-KUNAG,
KUNRG TYPE VBRK-KUNRG,
SFAKN TYPE VBRK-SFAKN,
FKSTO TYPE VBRK-FKSTO,
POSNR TYPE VBRP-POSNR,
ARKTX TYPE VBRP-ARKTX,
VRKME TYPE VBRP-VRKME,
VGBEL TYPE VBRP-VGBEL,
VKBUR TYPE VBRP-VKBUR,
LMATNR TYPE LIPS-MATNR,
LVBELN TYPE LIPS-VBELN,
LFIMG TYPE LIPS-LFIMG,
CHARG TYPE LIPS-CHARG,
DEL_FLAG(1) TYPE C,
PROC_KEY(1) TYPE C,

END OF TY_VDRK2.





*--------------------------------------------------------------*
*INTERNAL TABLE DECLARATIONS
*--------------------------------------------------------------*



DATA: IT_VBRK TYPE TABLE OF TY_VBRK_VBRP,
IT_TVKBT TYPE TABLE OF TY_TVKBT,
IT_TSPAT  TYPE TABLE OF TY_TSPAT,
GT_KNA1 TYPE TABLE OF TY_KNA1,
GT_KNVV TYPE TABLE OF TY_KNVV,   "ADDED BY RAM ON 21/11/2014
GT_T151T  TYPE TABLE OF TY_T151T ,
IT_MARA TYPE TABLE OF TY_MARA,
 GT_T005U TYPE TABLE OF GS_T005U ,
IT_VBRK2 TYPE TABLE OF TY_VDRK2,
IT_TVKBT2 TYPE TABLE OF TY_TVKBT2,
IT_TSPAT2  TYPE TABLE OF TY_TSPAT2,
IT_MARM TYPE TABLE OF TY_MARM,
IT_VBRP TYPE TABLE OF TY_VBRP,
GT_VBRP TYPE TABLE OF GS_VBRP,
IT_FINOVR TYPE TABLE OF TY_FINOVR.



*--------------------------------------------------------------*
*WORK AREA DECLARATIONS
*--------------------------------------------------------------*

DATA: WA_VBRK TYPE TY_VBRK_VBRP,
      WA_TVKBT TYPE  TY_TVKBT,
      WA_TSPAT  TYPE TY_TSPAT,
      WA_KNA1 TYPE TY_KNA1,
      WA_KNVV TYPE TY_KNVV,      "ADDED BY RAM ON 21/11/2014
      WA_T151T TYPE TY_T151T,
      WA_MARA TYPE TY_MARA,
      WA_T005U TYPE GS_T005U,
      WA_VBRK2 TYPE TY_VDRK2,
      WA_TVKBT2 TYPE  TY_TVKBT2,
      WA_TSPAT2  TYPE TY_TSPAT2,

      WA_FINOVR LIKE LINE OF IT_FINOVR,
      WA_MARM LIKE LINE OF IT_MARM,
           WA_VBRP LIKE LINE OF IT_VBRP,
           GW_VBRP LIKE LINE OF GT_VBRP.


DATA: NO_MONTH TYPE          T009B-POPER,
  D_YEAR  TYPE             T009B-BDATJ.

DATA : LV_BUKRS TYPE VBRK-BUKRS.



**************** Sales Pro Data  OR Secondary Sales ************************************** Data Declaration ***


  TYPES: BEGIN OF TY_VBRPK,
    VKORG TYPE ZSKU_VBRK-VKORG,
    FKDAT TYPE ZSKU_VBRK-FKDAT,
    FKART TYPE ZSKU_VBRK-FKART,
    VBELN TYPE ZSKU_VBRK-VBELN,
    MATNR TYPE ZSKU_VBRP-MATNR,
    ARKTX TYPE ZSKU_VBRP-ARKTX,
    MEINS TYPE ZSKU_VBRP-MEINS,
    FKIMG TYPE ZSKU_VBRP-FKIMG,
    LTR TYPE ZSKU_VBRP-LTR,
    DIVISION TYPE ZSKU_VBRK-DIVISION,
    KUNNR TYPE ZSKU_VBRK-KUNNR,
    ISCANCELLED TYPE ZSKU_VBRK-ISCANCELLED,
    POSNR TYPE ZSKU_VBRP-POSNR,
    CASEORTIN TYPE ZSKU_VBRP-CASEORTIN,
     SKU_ID TYPE ZSKU_VBRP-SKU_ID,
     NET_AMOUNT TYPE ZSKU_VBRP-NET_AMOUNT,
    TOTAL_AMOUNT TYPE ZSKU_VBRP-TOTAL_AMOUNT,
    CHARG TYPE ZSKU_VBATCH-CHARG,
    END OF TY_VBRPK.

  DATA : IT_VBRPK TYPE TABLE OF TY_VBRPK,
         WA_VBRPK TYPE TY_VBRPK.

*************************** END *************************************************************



SELECTION-SCREEN: BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-T01.
SELECT-OPTIONS: SO_BUKRS FOR LV_BUKRS MODIF ID TB2 OBLIGATORY,
                SO_FKDAT FOR W_AUX_FKDAT MODIF ID TB2 DEFAULT SY-DATUM OBLIGATORY,        " SELECTION SCREEN ELEMENTS FOR INVOICE
                SO_FKART  FOR W_FKART MODIF ID TB2,
                SO_VBELN FOR W_VBELN MODIF ID TB2,
                SO_KUNAG FOR W_KUNAG MODIF ID TB2,
                SO_MATNR FOR W_MATNR MODIF ID TB2 NO-DISPLAY,
                SO_CHARG FOR W_CHARG MODIF ID TB5 NO-DISPLAY,
                SO_VKBU2 FOR W_INV_VKBUR MODIF ID TB2 OBLIGATORY,                                    " SELECT OPTIONS FOR SALES OFFICE IN invoice
                SO_SPART FOR W_SPART MODIF ID TB2.
SELECTION-SCREEN SKIP.

PARAMETERS: P_CB AS CHECKBOX USER-COMMAND CBC MODIF ID TB2.
PARAMETERS: P_SR AS CHECKBOX USER-COMMAND CBC MODIF ID TB2.

SELECTION-SCREEN: END OF BLOCK B2.
*

START-OF-SELECTION.



  PERFORM DATA_RETRIEVAL_OVERVIEW.
  PERFORM AUTHCHECK_OVERVIEW.
  PERFORM BUILD_FIELDCATALOG_OVERVIEW.
  PERFORM BUILD_ALV_OVERVIEW.





*&---------------------------------------------------------------------*
*&      Form  DATA_RETRIEVAL_OVERVIEW
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
FORM DATA_RETRIEVAL_OVERVIEW .
  IF P_CB <> 'X'. " Added by Goivnd On 05/06/2014

    SELECT    VBRK~BUKRS "#EC CI_DB_OPERATION_OK[2768887] " Added by <IT-CAR Tool> during Code Remediation
              VBRK~FKDAT
              VBRK~SPART
              VBRK~VBELN
              VBRK~FKART
              VBRK~KUNAG
              VBRK~KUNRG
              VBRK~VKORG
              VBRK~VTWEG
              VBRK~NETWR
              VBRK~SFAKN
              VBRK~KNKLI
              VBRK~MWSBK
              VBRK~FKSTO
              VBRP~POSNR
              VBRP~VRKME
              VBRP~VKBUR
              VBRP~MATNR
              VBRP~FKIMG
              VBRP~VGBEL
              VBRP~VOLUM
              VBRP~NETWR
              INTO CORRESPONDING FIELDS OF TABLE IT_VBRK
              FROM VBRK JOIN VBRP ON VBRK~VBELN = VBRP~VBELN "#EC CI_DB_OPERATION_OK[2768887] " Added by <IT-CAR Tool> during Code Remediation
              WHERE VBRK~FKDAT IN SO_FKDAT AND VBRK~VBELN IN SO_VBELN
      AND VBRK~KUNAG IN SO_KUNAG AND VBRP~VKBUR IN SO_VKBU2 AND VBRK~SPART IN SO_SPART AND VBRK~FKART IN SO_FKART AND FKSTO <> 'X' AND VBRK~BUKRS IN SO_BUKRS AND  VBRK~FKART NOT IN ('S1','YBRE','S2','JEX','F1','F2').
SORT IT_VBRK BY VBELN. " Added by <IT-CAR Tool> during Code Remediation
    DELETE ADJACENT DUPLICATES FROM IT_VBRK COMPARING VBELN.



  ELSEIF P_CB = 'X'. " Added by Goivnd On 05/06/2014
    SELECT     VBRK~BUKRS "#EC CI_DB_OPERATION_OK[2768887] " Added by <IT-CAR Tool> during Code Remediation
              VBRK~FKDAT
             VBRK~SPART
             VBRK~VBELN
             VBRK~FKART
             VBRK~KUNAG
             VBRK~KUNRG
             VBRK~VKORG
             VBRK~VTWEG
             VBRK~NETWR
             VBRK~SFAKN
             VBRK~KNKLI
             VBRK~MWSBK
             VBRK~FKSTO
             VBRP~POSNR
             VBRP~VRKME
             VBRP~VKBUR
             VBRP~MATNR
             VBRP~FKIMG
             VBRP~VGBEL
             VBRP~VOLUM
             VBRP~NETWR
             INTO CORRESPONDING FIELDS OF TABLE IT_VBRK
             FROM VBRK JOIN VBRP ON VBRK~VBELN = VBRP~VBELN "#EC CI_DB_OPERATION_OK[2768887] " Added by <IT-CAR Tool> during Code Remediation
             WHERE VBRK~FKDAT IN SO_FKDAT AND VBRK~VBELN IN SO_VBELN
     AND VBRK~KUNAG IN SO_KUNAG AND VBRP~VKBUR IN SO_VKBU2 AND VBRK~BUKRS IN SO_BUKRS  AND VBRK~SPART IN SO_SPART AND VBRK~FKART IN SO_FKART AND FKSTO = 'X'  .

SORT IT_VBRK BY VBELN . " Added by <IT-CAR Tool> during Code Remediation
    DELETE ADJACENT DUPLICATES FROM IT_VBRK COMPARING VBELN .
  ENDIF.

  IF P_SR <> 'X' AND P_CB <> 'X'. " Added by Goivnd On 05/06/2014
    SELECT     VBRK~BUKRS "#EC CI_DB_OPERATION_OK[2768887] " Added by <IT-CAR Tool> during Code Remediation
               VBRK~FKDAT
                VBRK~SPART
                VBRK~VBELN
                VBRK~FKART
                VBRK~KUNAG
                VBRK~KUNRG
                VBRK~VKORG
                VBRK~VTWEG
                VBRK~NETWR
                VBRK~SFAKN
                VBRK~KNKLI
                VBRK~MWSBK
                VBRK~FKSTO
                VBRP~POSNR
                VBRP~VRKME
                VBRP~VKBUR
                VBRP~MATNR
                VBRP~FKIMG
                VBRP~VGBEL
                VBRP~VOLUM
                INTO CORRESPONDING FIELDS OF TABLE IT_VBRK
                FROM VBRK JOIN VBRP ON VBRK~VBELN = VBRP~VBELN "#EC CI_DB_OPERATION_OK[2768887] " Added by <IT-CAR Tool> during Code Remediation
                WHERE VBRK~FKDAT IN SO_FKDAT AND VBRK~VBELN IN SO_VBELN
        AND VBRK~KUNAG IN SO_KUNAG AND VBRP~VKBUR IN SO_VKBU2 AND VBRK~BUKRS IN SO_BUKRS AND VBRK~SPART IN SO_SPART AND VBRK~FKART NOT IN ('S1','YBRE','S2','JEX','F1','F2') AND VBRK~FKART IN SO_FKART AND FKSTO <> 'X'  .
SORT IT_VBRK BY VBELN. " Added by <IT-CAR Tool> during Code Remediation
SORT IT_VBRK BY VBELN. " Added by <IT-CAR Tool> during Code Remediation
SORT IT_VBRK BY VBELN. " Added by <IT-CAR Tool> during Code Remediation
    DELETE ADJACENT DUPLICATES FROM IT_VBRK COMPARING VBELN.

REFRESH IT_VBRK.


******************* Sales Pro and Secondary Sales ******* Data Selection *********
    SELECT  ZSKU_VBRK~VKORG
       ZSKU_VBRK~FKDAT
       ZSKU_VBRK~FKART
       ZSKU_VBRK~VBELN
       ZSKU_VBRP~MATNR
       ZSKU_VBRP~ARKTX
      ZSKU_VBRP~MEINS
       ZSKU_VBRP~FKIMG
       ZSKU_VBRP~LTR
       ZSKU_VBRK~DIVISION
       ZSKU_VBRK~KUNNR
       ZSKU_VBRK~ISCANCELLED
      ZSKU_VBRP~POSNR
      ZSKU_VBRP~CASEORTIN
      ZSKU_VBRP~SKU_ID
      ZSKU_VBRP~NET_AMOUNT
      ZSKU_VBRK~NET_AMOUNT
*      ZSKU_VBATCH~CHARG
                INTO TABLE IT_VBRPK
      FROM ZSKU_VBRP JOIN ZSKU_VBRK ON ZSKU_VBRP~VBELN = ZSKU_VBRK~VBELN
*           JOIN ZSKU_VBATCH ON ZSKU_VBRP~VBELN = ZSKU_VBATCH~VBELN
                     WHERE
       ZSKU_VBRK~VKORG IN SO_BUKRS
AND   ZSKU_VBRK~SKU_ID IN SO_VKBU2
AND ZSKU_VBRK~DIVISION IN SO_SPART
AND ZSKU_VBRK~FKART IN SO_FKART
AND ZSKU_VBRK~FKDAT IN SO_FKDAT
AND ZSKU_VBRK~VBELN IN SO_VBELN
AND  ZSKU_VBRK~KUNNR IN SO_KUNAG
      AND ZSKU_VBRP~MATNR IN SO_MATNR
                            AND ZSKU_VBRP~CHARG IN SO_CHARG .

SORT IT_VBRPK BY VBELN MATNR . " Added by <IT-CAR Tool> during Code Remediation
DELETE ADJACENT DUPLICATES FROM IT_VBRPK COMPARING VBELN MATNR .

  ELSEIF P_SR = 'X' . " Added by Goivnd On 05/06/2014
    SELECT    VBRK~BUKRS "#EC CI_DB_OPERATION_OK[2768887] " Added by <IT-CAR Tool> during Code Remediation
         VBRK~FKDAT
        VBRK~SPART
        VBRK~VBELN
        VBRK~FKART
        VBRK~KUNAG
        VBRK~KUNRG
        VBRK~VKORG
        VBRK~VTWEG
        VBRK~NETWR
        VBRK~SFAKN
        VBRK~KNKLI
        VBRK~MWSBK
        VBRK~FKSTO
        VBRP~POSNR
        VBRP~VRKME
        VBRP~VKBUR
        VBRP~MATNR
        VBRP~FKIMG
        VBRP~VGBEL
        VBRP~VOLUM
       VBRP~NETWR
        INTO CORRESPONDING FIELDS OF TABLE IT_VBRK
        FROM VBRK JOIN VBRP ON VBRK~VBELN = VBRP~VBELN "#EC CI_DB_OPERATION_OK[2768887] " Added by <IT-CAR Tool> during Code Remediation
        WHERE VBRK~FKDAT IN SO_FKDAT AND VBRK~VBELN IN SO_VBELN
AND VBRK~KUNAG IN SO_KUNAG AND VBRP~VKBUR IN SO_VKBU2 AND VBRK~BUKRS IN SO_BUKRS AND VBRK~SPART IN SO_SPART AND FKART = 'YBRE'  AND VBRK~FKART IN SO_FKART AND FKSTO <> 'X'   .
SORT IT_VBRK BY VBELN . " Added by <IT-CAR Tool> during Code Remediation
SORT IT_VBRK BY VBELN . " Added by <IT-CAR Tool> during Code Remediation
SORT IT_VBRK BY VBELN . " Added by <IT-CAR Tool> during Code Remediation
    DELETE ADJACENT DUPLICATES FROM IT_VBRK COMPARING VBELN .
  ENDIF.

*BREAK-POINT.
  IF SY-SUBRC = 0.
    SELECT VBELN POSNR FKIMG VOLUM MATNR NETWR
      FROM VBRP INTO  CORRESPONDING FIELDS OF TABLE IT_VBRP
       FOR ALL ENTRIES IN IT_VBRK WHERE VBELN = IT_VBRK-VBELN.
  ENDIF.

 IF NOT IT_VBRPK[] IS INITIAL.
    SELECT  ZSKU_VBRP~VBELN
            ZSKU_VBRP~POSNR
            ZSKU_VBRP~FKIMG
             ZSKU_VBRP~MATNR
              ZSKU_VBRP~LTR
            ZSKU_VBRP~NET_AMOUNT FROM ZSKU_VBRP
                 INTO CORRESPONDING FIELDS OF TABLE GT_VBRP FOR ALL ENTRIES IN  IT_VBRPK WHERE VBELN =  IT_VBRPK-VBELN.
   ENDIF.

******************* Sales Pro and Secondary Sales ******* Data Selection *********
  LOOP AT IT_VBRPK INTO WA_VBRPK.
    WA_VBRK-BUKRS = WA_VBRPK-VKORG.
    WA_VBRK-VKORG = WA_VBRPK-VKORG.
    WA_VBRK-FKDAT = WA_VBRPK-FKDAT.
    WA_VBRK-FKART = WA_VBRPK-FKART.
    WA_VBRK-VBELN = WA_VBRPK-VBELN.
    WA_VBRK-MATNR = WA_VBRPK-MATNR.
    WA_VBRK-VRKME = WA_VBRPK-MEINS.
    WA_VBRK-FKIMG  = WA_VBRPK-FKIMG.
    WA_VBRK-VOLUM = WA_VBRPK-LTR.
    WA_VBRK-SPART = WA_VBRPK-DIVISION.
    WA_VBRK-KUNAG = WA_VBRPK-KUNNR.
     WA_VBRK-KUNRG = WA_VBRPK-KUNNR.
    WA_VBRK-POSNR = WA_VBRPK-POSNR.
    WA_VBRK-VKBUR = WA_VBRPK-SKU_ID.
    WA_VBRK-NETWR  = WA_VBRPK-NET_AMOUNT.

    APPEND WA_VBRK TO IT_VBRK .
    CLEAR WA_VBRK .
  ENDLOOP.

 APPEND LINES OF GT_VBRP TO IT_VBRP.
******************* End Sales Pro And Secondary Sales *****************************


  SELECT MATNR VOLUM VOLEH
    FROM MARA INTO CORRESPONDING FIELDS OF TABLE IT_MARA
     FOR ALL ENTRIES IN IT_VBRP WHERE MATNR = IT_VBRP-MATNR.

* SELECT KUNNR KDGRP SPART
*   FROM KNVV INTO CORRESPONDING FIELDS OF TABLE GT_KNVV
*   FOR ALL ENTRIES IN GT_KNA1 WHERE KUNNR = GT_KNA1-KUNNR.  "ADDED BY RAM ON 21/11/2014

 SELECT KUNNR VKORG KDGRP SPART
   FROM KNVV INTO CORRESPONDING FIELDS OF TABLE GT_KNVV
   FOR ALL ENTRIES IN IT_VBRK WHERE KUNNR = IT_VBRK-KUNRG AND SPART = IT_VBRK-SPART AND VKORG = IT_VBRK-VKORG AND  KUNNR IN SO_KUNAG.  "Added By Govind On 06/12/2014.

 SELECT SPRAS KDGRP KTEXT
   FROM T151T INTO CORRESPONDING FIELDS OF TABLE GT_T151T
    FOR ALL ENTRIES IN GT_KNVV WHERE  KDGRP = GT_KNVV-KDGRP AND SPRAS = 'EN' .
*BREAK-POINT.




  TYPES: BEGIN OF TY_VBRK_TEMP,
       SPART TYPE VBRK-SPART,
       VKBUR TYPE VBRP-VKBUR,
       KUNAG TYPE VBRK-KUNAG,
       KUNRG TYPE VBRK-KUNRG,
  END OF TY_VBRK_TEMP.

  DATA: IT_VBRK_TEMP TYPE STANDARD TABLE OF TY_VBRK_TEMP,
        WA_VBRK_TEMP LIKE LINE OF IT_VBRK_TEMP.

  LOOP AT IT_VBRK INTO WA_VBRK.

    MOVE-CORRESPONDING WA_VBRK TO WA_VBRK_TEMP.
    APPEND WA_VBRK_TEMP TO IT_VBRK_TEMP.
    CLEAR: WA_VBRK, WA_VBRK_TEMP.

  ENDLOOP.

  SORT IT_VBRK_TEMP BY SPART VKBUR KUNAG KUNRG.

  DELETE ADJACENT DUPLICATES FROM IT_VBRK_TEMP COMPARING ALL FIELDS.

  IF IT_VBRK_TEMP IS NOT INITIAL.

    SELECT VKBUR
           BEZEI
           FROM TVKBT INTO TABLE IT_TVKBT
           FOR ALL ENTRIES IN IT_VBRK_TEMP
           WHERE VKBUR = IT_VBRK_TEMP-VKBUR
           AND SPRAS = 'EN'.

    SELECT SPART
           VTEXT
           FROM TSPAT INTO TABLE IT_TSPAT
           FOR ALL ENTRIES IN IT_VBRK_TEMP
           WHERE SPART = IT_VBRK_TEMP-SPART
           AND SPRAS = 'EN'.

    SELECT KUNNR
           NAME1
           NAME2
           FROM KNA1 INTO TABLE GT_KNA1
           FOR ALL ENTRIES IN IT_VBRK
           WHERE KUNNR = IT_VBRK-KUNRG.



    SELECT BLAND
           BEZEI
           FROM T005U INTO TABLE GT_T005U
           FOR ALL ENTRIES IN GT_KNA1
           WHERE BLAND = GT_KNA1-REGIO AND SPRAS = 'EN' AND LAND1 ='IN'.
  ENDIF.





   LOOP AT  GT_KNVV INTO WA_KNVV.
*  LOOP AT GT_KNA1  INTO WA_KNA1. " Hidded By Govind On 06/12/2014
*    MOVE-CORRESPONDING WA_KNA1 TO WA_FINOVR.  " Hidded By Govind On 06/12/2014
    LOOP AT IT_VBRK INTO WA_VBRK WHERE KUNRG  = WA_KNVV-KUNNR AND SPART = WA_KNVV-SPART.
IF SY-SUBRC = 0.
*    WA_FINOVR-FKDAT = WA_VBRK-FKDAT.
      WA_FINOVR-SPART = WA_VBRK-SPART.
*    WA_FINOVR-VBELN = WA_VBRK-VBELN.
      WA_FINOVR-FKART = WA_VBRK-FKART.
      WA_FINOVR-KUNAG = WA_VBRK-KUNAG.
      WA_FINOVR-KUNRG = WA_VBRK-KUNRG.
      WA_FINOVR-VKORG = WA_VBRK-VKORG.
      WA_FINOVR-VTWEG = WA_VBRK-VTWEG.
      WA_FINOVR-NETWR = WA_FINOVR-NETWR +  WA_VBRK-NETWR.
      WA_FINOVR-SFAKN = WA_VBRK-SFAKN.
*    wa_finovr-posnr = wa_vbrk-posnr.
      WA_FINOVR-VKBUR = WA_VBRK-VKBUR.
*    WA_FINOVR-MWSBK = WA_FINOVR-MWSBK. " Modified By Govind
*    WA_FINOVR-MWSBK = WA_VBRK-MWSBK.
*    WA_FINOVR-INV_VAL = WA_VBRK-NETWR + WA_VBRK-MWSBK.
ENDIF.

      CALL FUNCTION 'DATE_TO_PERIOD_CONVERT'
        EXPORTING
          I_DATE         = WA_VBRK-FKDAT
*         I_MONMIT       = 00
          I_PERIV        = 'K4'
        IMPORTING
          E_BUPER        = NO_MONTH
          E_GJAHR        = D_YEAR
        EXCEPTIONS
          INPUT_FALSE    = 1
          T009_NOTFOUND  = 2
          T009B_NOTFOUND = 3
          OTHERS         = 4.

      LOOP AT IT_VBRP INTO WA_VBRP WHERE VBELN = WA_VBRK-VBELN.
        IF SY-SUBRC = 0.
          WA_FINOVR-VNETWR = WA_FINOVR-VNETWR + WA_VBRP-NETWR.
          WA_FINOVR-FKIMG  = WA_FINOVR-FKIMG + WA_VBRP-FKIMG.
          WA_FINOVR-QTY_LTR =  WA_FINOVR-QTY_LTR + WA_VBRP-VOLUM.

        ENDIF.

        IF NO_MONTH = '004' .
          WA_FINOVR-VOL0 =  WA_FINOVR-VOL0 +  WA_VBRP-VOLUM / 10.
          WA_FINOVR-AMT0 =  WA_FINOVR-AMT0 + WA_VBRP-NETWR.
        ELSEIF NO_MONTH = '005'.
          WA_FINOVR-VOL1 = WA_FINOVR-VOL1 + WA_VBRP-VOLUM / 10.
          WA_FINOVR-AMT1 =  WA_FINOVR-AMT1 + WA_VBRP-NETWR.
        ELSEIF NO_MONTH = '006'.
          WA_FINOVR-VOL2 = WA_FINOVR-VOL2 + WA_VBRP-VOLUM / 10 .
          WA_FINOVR-AMT2 =  WA_FINOVR-AMT2 + WA_VBRP-NETWR.
        ELSEIF NO_MONTH = '007'.
          WA_FINOVR-VOL3 = WA_FINOVR-VOL3 + WA_VBRP-VOLUM .
          WA_FINOVR-AMT3 =  WA_FINOVR-AMT3 + WA_VBRP-NETWR.
        ELSEIF NO_MONTH = '008'.
          WA_FINOVR-VOL4 = WA_FINOVR-VOL4 + WA_VBRP-VOLUM.
          WA_FINOVR-AMT4 = WA_FINOVR-AMT4 +  WA_VBRP-NETWR.
        ELSEIF NO_MONTH = '009'.
          WA_FINOVR-VOL5 = WA_FINOVR-VOL5 + WA_VBRP-VOLUM .
          WA_FINOVR-AMT5 =  WA_FINOVR-AMT5 +   WA_VBRP-NETWR.
        ELSEIF NO_MONTH = '010'.
          WA_FINOVR-VOL6 = WA_FINOVR-VOL6 + WA_VBRP-VOLUM.
          WA_FINOVR-AMT6 =  WA_FINOVR-AMT6 +  WA_VBRP-NETWR.
        ELSEIF NO_MONTH = '011'.
          WA_FINOVR-VOL7 = WA_FINOVR-VOL7 + WA_VBRP-VOLUM.
          WA_FINOVR-AMT7 =  WA_FINOVR-AMT7 + WA_VBRP-NETWR.
        ELSEIF NO_MONTH = '012'.
          WA_FINOVR-VOL8 = WA_FINOVR-VOL8 +  WA_VBRP-VOLUM.
          WA_FINOVR-AMT8 =  WA_FINOVR-AMT8 + WA_VBRP-NETWR.
        ELSEIF NO_MONTH = '001'.
          WA_FINOVR-VOL9 = WA_FINOVR-VOL9 +  WA_VBRP-VOLUM.
          WA_FINOVR-AMT9 = WA_FINOVR-AMT9 + WA_VBRP-NETWR.
              ELSEIF NO_MONTH = '002'.
          WA_FINOVR-VOL10 = WA_FINOVR-VOL10 + WA_VBRP-VOLUM .
          WA_FINOVR-AMT10 =  WA_FINOVR-AMT10 + WA_VBRP-NETWR.
        ELSEIF NO_MONTH = '003'.
          WA_FINOVR-VOL11 = WA_FINOVR-VOL11 + WA_VBRP-VOLUM .
          WA_FINOVR-AMT11 =  WA_FINOVR-AMT11 + WA_VBRP-NETWR.

        ENDIF.
      ENDLOOP.

    ENDLOOP.

    READ TABLE IT_MARA INTO WA_MARA WITH  KEY MATNR = WA_VBRP-MATNR.

    WA_FINOVR-M_VOLUM = WA_MARA-VOLUM.

    READ TABLE GT_KNVV INTO WA_KNVV WITH  KEY KUNNR = WA_KNVV-KUNNR.   " ADDED BY RAM ON 21/11/2014
  IF SY-SUBRC = 0 .
    WA_FINOVR-KDGRP = WA_KNVV-KDGRP.
ENDIF.
    READ TABLE GT_T151T INTO WA_T151T WITH  KEY KDGRP = WA_KNVV-KDGRP.

    WA_FINOVR-KTEXT = WA_T151T-KTEXT.

    READ TABLE IT_TVKBT INTO WA_TVKBT WITH KEY VKBUR = WA_VBRK-VKBUR.
    IF SY-SUBRC = 0.
      WA_FINOVR-BEZEI = WA_TVKBT-BEZEI.
    ENDIF.

    READ TABLE IT_TSPAT INTO WA_TSPAT WITH KEY SPART = WA_VBRK-SPART.

    IF SY-SUBRC = 0.
      WA_FINOVR-VTEXT = WA_TSPAT-VTEXT.
    ENDIF.

    APPEND WA_FINOVR TO IT_FINOVR.
    CLEAR: WA_FINOVR,WA_VBRP,WA_TSPAT,WA_MARA,WA_VBRK.
  ENDLOOP.

LOOP AT IT_FINOVR INTO WA_FINOVR. " Added By Govind on 06/12/2014
 READ TABLE GT_KNA1 INTO WA_KNA1 WITH  KEY KUNNR = WA_FINOVR-KUNRG.
 WA_FINOVR-NAME1 = WA_KNA1-NAME1.
 MODIFY IT_FINOVR FROM WA_FINOVR TRANSPORTING NAME1.
 CLEAR WA_FINOVR.
  ENDLOOP.

*SORT IT_FINOVR BY VKBUR SPART KDGRP KUNRG.
  IF IT_FINOVR IS INITIAL.


    MESSAGE 'No Data Exists for the Input' TYPE 'S' DISPLAY LIKE 'E'.

    STOP.

  ENDIF.

ENDFORM.                    "DATA_RETRIEVAL_OVERVIEW






" DATA_RETRIEVAL_OVERVIEW
*&---------------------------------------------------------------------*
*&      Form  BUILD_FIELDCATALOG_OVERVIEW
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
*&---------------------------------------------------------------------*
*&      Form  AUTHCHECK_OVERVIEW
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM AUTHCHECK_OVERVIEW .

  LOOP AT IT_FINOVR INTO WA_FINOVR.
    AUTHORITY-CHECK OBJECT 'ZINVOICE'
    ID 'ZVKBUR' FIELD WA_FINOVR-VKBUR
    ID 'ZSPART' DUMMY
    ID 'ACTVT' FIELD '03'.
    IF SY-SUBRC NE 0.
      WA_FINOVR-FLAG = 'x' .
      MODIFY IT_FINOVR FROM WA_FINOVR TRANSPORTING FLAG.
      MESSAGE 'NO AUTHORIZATION FOR CERTAIN RECORDS' TYPE 'S'.
    ENDIF.

    AUTHORITY-CHECK OBJECT 'ZINVOICE'
    ID 'ZVKBUR' DUMMY
    ID 'ZSPART' FIELD WA_FINOVR-SPART
    ID 'ACTVT' FIELD '03'.
    IF SY-SUBRC NE 0.
      WA_FINOVR-FLAG = 'x' .
      MODIFY IT_FINOVR FROM WA_FINOVR TRANSPORTING FLAG.
      MESSAGE 'NO AUTHORIZATION FOR CERTAIN RECORDS' TYPE 'S'.
    ENDIF.
    CLEAR: WA_FINOVR.
  ENDLOOP.

  DELETE IT_FINOVR WHERE FLAG = 'x'.


ENDFORM.                    " AUTHCHECK_OVERVIEW



*&---------------------------------------------------------------------*
*&      Form  BUILD_FIELDCATALOG_OVERVIEW
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
FORM BUILD_FIELDCATALOG_OVERVIEW .

  WA_FIELDCAT-FIELDNAME   = 'VKBUR'.
  WA_FIELDCAT-SELTEXT_M   = 'Sales Office'.
  WA_FIELDCAT-COL_POS     = 2.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_SORT-FIELDNAME = 'VKBUR'.
  WA_SORT-UP = 'X'.
  WA_SORT-GROUP = 'X'.
  APPEND WA_SORT TO IT_SORT.
  CLEAR WA_SORT.

*  WA_SORT-FIELDNAME = 'VKBUR'.
*  WA_SORT-UP = 'X'.
*  WA_SORT-GROUP = 'X'.
*  APPEND WA_SORT TO IT_SORT.
*  CLEAR WA_SORT.
*
*   WA_SORT-FIELDNAME = 'VKBUR'.
*  WA_SORT-UP = 'X'.
*  WA_SORT-GROUP = 'X'.
*  APPEND WA_SORT TO IT_SORT.
*  CLEAR WA_SORT.

  WA_FIELDCAT-FIELDNAME   = 'BEZEI'.
  WA_FIELDCAT-SELTEXT_M   = 'Sales Desc.'.
  WA_FIELDCAT-COL_POS     = 3.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_SORT-FIELDNAME = 'BEZEI'.
  WA_SORT-UP = 'X'.
  WA_SORT-GROUP = 'X'.
  APPEND WA_SORT TO IT_SORT.
  CLEAR WA_SORT.

  WA_FIELDCAT-FIELDNAME   = 'VKORG'.
  WA_FIELDCAT-SELTEXT_M   = 'Sales Organization'.
  WA_FIELDCAT-COL_POS     = 4.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

 WA_SORT-FIELDNAME = 'VKORG'.
  WA_SORT-UP = 'X'.
  WA_SORT-GROUP = 'X'.
  APPEND WA_SORT TO IT_SORT.
  CLEAR WA_SORT.

  WA_FIELDCAT-FIELDNAME   = 'SPART'.
  WA_FIELDCAT-SELTEXT_M   = 'Sales Division'.
  WA_FIELDCAT-COL_POS     = 6.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_SORT-FIELDNAME = 'SPART'.
  WA_SORT-UP = 'X'.
  WA_SORT-GROUP = 'X'.
  APPEND WA_SORT TO IT_SORT.
  CLEAR WA_SORT.

*  WA_FIELDCAT-FIELDNAME   = 'FKART'.
*  WA_FIELDCAT-SELTEXT_M   = 'BILLING TYPE'.
*  WA_FIELDCAT-COL_POS     = 10.
*  APPEND WA_FIELDCAT TO IT_FIELDCAT.
*  CLEAR  WA_FIELDCAT.
*

  WA_FIELDCAT-FIELDNAME   = 'VTEXT'.
  WA_FIELDCAT-SELTEXT_M   = 'Sales Division Desc.'.
  WA_FIELDCAT-COL_POS     = 7.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_SORT-FIELDNAME = 'VTEXT'.
  WA_SORT-UP = 'X'.
  WA_SORT-GROUP = 'X'.
  APPEND WA_SORT TO IT_SORT.
  CLEAR WA_SORT.

 WA_FIELDCAT-FIELDNAME   = 'KDGRP'.
  WA_FIELDCAT-SELTEXT_M   = 'Customer Group Code'.
  WA_FIELDCAT-COL_POS     = 8.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

WA_SORT-FIELDNAME = 'KDGRP'.
  WA_SORT-UP = 'X'.
  WA_SORT-GROUP = 'X'.
  APPEND WA_SORT TO IT_SORT.
  CLEAR WA_SORT.

  WA_FIELDCAT-FIELDNAME   = 'KTEXT'.
  WA_FIELDCAT-SELTEXT_M   = 'Customer Group Desc.'.
  WA_FIELDCAT-COL_POS     = 9.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

WA_SORT-FIELDNAME = 'KTEXT'.
  WA_SORT-UP = 'X'.
  WA_SORT-GROUP = 'X'.
  APPEND WA_SORT TO IT_SORT.
  CLEAR WA_SORT.

  WA_FIELDCAT-FIELDNAME   = 'KUNRG'.
  WA_FIELDCAT-SELTEXT_M   = 'Customer Code'.
  WA_FIELDCAT-COL_POS     = 11.
  WA_FIELDCAT-CFIELDNAME   = 'KUNRG'.
  WA_FIELDCAT-CTABNAME    = 'VBRK'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_SORT-FIELDNAME = 'KUNRG'.
  WA_SORT-UP = 'X'.
  WA_SORT-GROUP = 'X'.
  APPEND WA_SORT TO IT_SORT.
  CLEAR WA_SORT.

  WA_FIELDCAT-FIELDNAME   = 'NAME1'.
  WA_FIELDCAT-SELTEXT_M   = 'Customer Name'.
  WA_FIELDCAT-COL_POS     = 12.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.


 WA_SORT-FIELDNAME = 'NAME1'.
  WA_SORT-UP = 'X'.
  WA_SORT-GROUP = 'X'.
  APPEND WA_SORT TO IT_SORT.
  CLEAR WA_SORT.

  WA_FIELDCAT-FIELDNAME   = 'FKIMG'.
  WA_FIELDCAT-SELTEXT_M   = 'Total Inv.Qty'.
  WA_FIELDCAT-COL_POS     = 13.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'QTY_LTR'.
  WA_FIELDCAT-SELTEXT_M   = 'Total in Liter/Kgs'.
  WA_FIELDCAT-COL_POS     = 14.
   WA_FIELDCAT-NO_ZERO     = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.


  WA_FIELDCAT-FIELDNAME   = 'VNETWR'.
  WA_FIELDCAT-SELTEXT_M   = 'Net Value'.
  WA_FIELDCAT-COL_POS     = 15.
  WA_FIELDCAT-DO_SUM      = 'X'.
   WA_FIELDCAT-NO_ZERO     = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'VOL0'.
  WA_FIELDCAT-SELTEXT_M   = 'April Volume'.
  WA_FIELDCAT-COL_POS     = 16.
   WA_FIELDCAT-NO_ZERO     = 'X'.
*  WA_FIELDCAT-CFIELDNAME   = 'KUNAG'.
  WA_FIELDCAT-CTABNAME    = 'VBRK'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'AMT0'.
  WA_FIELDCAT-SELTEXT_M   = 'April Value'.
  WA_FIELDCAT-COL_POS     = 28.
   WA_FIELDCAT-NO_ZERO     = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'VOL1'.
  WA_FIELDCAT-SELTEXT_M   = 'May Volume'.
  WA_FIELDCAT-COL_POS     = 17.
*  WA_FIELDCAT-CFIELDNAME   = 'KUNAG'.
   WA_FIELDCAT-NO_ZERO     = 'X'.
  WA_FIELDCAT-CTABNAME    = 'VBRK'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'AMT1'.
  WA_FIELDCAT-SELTEXT_M   = 'May Value'.
  WA_FIELDCAT-COL_POS     = 29.
   WA_FIELDCAT-NO_ZERO     = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'VOL2'.
  WA_FIELDCAT-SELTEXT_M   = 'June Volume'.
  WA_FIELDCAT-COL_POS     = 18.
   WA_FIELDCAT-NO_ZERO     = 'X'.
*  WA_FIELDCAT-CFIELDNAME   = 'KUNAG'.
  WA_FIELDCAT-CTABNAME    = 'VBRK'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'AMT2'.
  WA_FIELDCAT-SELTEXT_M   = 'June Value'.
  WA_FIELDCAT-COL_POS     = 30.
   WA_FIELDCAT-NO_ZERO     = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.


  WA_FIELDCAT-FIELDNAME   = 'AMT3'.
  WA_FIELDCAT-SELTEXT_M   = 'July Value'.
  WA_FIELDCAT-COL_POS     = 31.
   WA_FIELDCAT-NO_ZERO     = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'VOL3'.
  WA_FIELDCAT-SELTEXT_M   = 'July Volume'.
  WA_FIELDCAT-COL_POS     = 19.
 WA_FIELDCAT-NO_ZERO     = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'VOL4'.  "Changes on 07/08/2014 my savariar s VOL4
  WA_FIELDCAT-SELTEXT_M   = 'Augest Volume'.
  WA_FIELDCAT-COL_POS     = 20.
   WA_FIELDCAT-NO_ZERO     = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'AMT4'.  "Changes on 07/08/2014 my savariar s AMT4
  WA_FIELDCAT-SELTEXT_M   = 'Augest Value'.
  WA_FIELDCAT-COL_POS     = 32.
   WA_FIELDCAT-NO_ZERO     = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.


  WA_FIELDCAT-FIELDNAME   = 'VOL5'.
  WA_FIELDCAT-SELTEXT_M   = 'September Volume'.
  WA_FIELDCAT-COL_POS     = 21.
   WA_FIELDCAT-NO_ZERO     = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'AMT5'.
  WA_FIELDCAT-SELTEXT_M   = 'September Value'.
  WA_FIELDCAT-COL_POS     = 33.
   WA_FIELDCAT-NO_ZERO     = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.
  WA_FIELDCAT-FIELDNAME   = 'VOL6'.
  WA_FIELDCAT-SELTEXT_M   = 'October Volume'.
  WA_FIELDCAT-COL_POS     = 22.
   WA_FIELDCAT-NO_ZERO     = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'AMT6'.
  WA_FIELDCAT-SELTEXT_M   = 'October Value'.
  WA_FIELDCAT-COL_POS     = 34.
   WA_FIELDCAT-NO_ZERO     = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.


  WA_FIELDCAT-FIELDNAME   = 'VOL7'.
  WA_FIELDCAT-SELTEXT_M   = 'November Volume'.
  WA_FIELDCAT-COL_POS     = 23.
   WA_FIELDCAT-NO_ZERO     = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'AMT7'.
  WA_FIELDCAT-SELTEXT_M   = 'November  Value'.
  WA_FIELDCAT-COL_POS     = 35.
   WA_FIELDCAT-NO_ZERO     = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'VOL8'.
  WA_FIELDCAT-SELTEXT_M   = 'December Volume'.
  WA_FIELDCAT-COL_POS     = 24.
   WA_FIELDCAT-NO_ZERO     = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'AMT8'.
  WA_FIELDCAT-SELTEXT_M   = 'December  Value'.
  WA_FIELDCAT-COL_POS     = 36.
   WA_FIELDCAT-NO_ZERO     = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.


  WA_FIELDCAT-FIELDNAME   = 'VOL9'.
  WA_FIELDCAT-SELTEXT_M   = 'January Volume'.
  WA_FIELDCAT-COL_POS     = 25.
   WA_FIELDCAT-NO_ZERO     = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'AMT9'.
  WA_FIELDCAT-SELTEXT_M   = 'January Value'.
  WA_FIELDCAT-COL_POS     = 37.
   WA_FIELDCAT-NO_ZERO     = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'VOL10'.
  WA_FIELDCAT-SELTEXT_M   = 'Febrary Volume'.
  WA_FIELDCAT-COL_POS     = 26.
   WA_FIELDCAT-NO_ZERO     = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'AMT10'.
  WA_FIELDCAT-SELTEXT_M   = 'Febrary Value'.
  WA_FIELDCAT-COL_POS     = 38.
   WA_FIELDCAT-NO_ZERO     = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'VOL11'.
  WA_FIELDCAT-SELTEXT_M   = 'March Volume'.
  WA_FIELDCAT-COL_POS     = 27.
   WA_FIELDCAT-NO_ZERO     = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'AMT11'.
  WA_FIELDCAT-SELTEXT_M   = 'March Value'.
  WA_FIELDCAT-COL_POS     = 39.
   WA_FIELDCAT-NO_ZERO     = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

*  WA_SORT-FIELDNAME = 'VKBUR'.
*  WA_SORT-UP = 'X'.
*  WA_SORT-GROUP = 'X'.
*  WA_SORT-SUBTOT = 'X'.
*  APPEND WA_SORT TO IT_SORT.
*  CLEAR WA_SORT.


ENDFORM.                    "BUILD_FIELDCATALOG_OVERVIEW

" BUILD_FIELDCATALOG_OVERVIEW
*&---------------------------------------------------------------------*
*&      Form  BUILD_ALV_OVERVIEW
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM BUILD_ALV_OVERVIEW .


 LAYOUT-COLWIDTH_OPTIMIZE = 'X'.                            "Added by Savariar S as on 21/10/2014.
  LAYOUT-ZEBRA = 'X'.


  LOOP AT IT_FINOVR TRANSPORTING NO FIELDS WHERE CANDOC = 'X'.

    EXIT.

  ENDLOOP.

  IF SY-SUBRC NE 0.

    READ TABLE IT_FIELDCAT INTO WA_FIELDCAT WITH KEY FIELDNAME = 'CANDOC'.

    IF SY-SUBRC = 0.

      WA_FIELDCAT-NO_OUT = 'X'.
      WA_FIELDCAT-TECH   = 'X'.

      MODIFY IT_FIELDCAT FROM WA_FIELDCAT INDEX SY-TABIX.

    ENDIF.

  ENDIF.

  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
  EXPORTING
*   I_INTERFACE_CHECK                 = ' '
*   I_BYPASSING_BUFFER                = ' '
*   I_BUFFER_ACTIVE                   = ' '
      I_CALLBACK_PROGRAM                = SY-REPID
*      I_CALLBACK_PF_STATUS_SET          = 'PF_STATUS_GET'
*      I_CALLBACK_USER_COMMAND           = 'MY_USER_COMMAND'
    I_CALLBACK_TOP_OF_PAGE            = 'ALV_CATALOG_HEADER'
*   I_CALLBACK_HTML_TOP_OF_PAGE       = ' '
*   I_CALLBACK_HTML_END_OF_LIST       = ' '
*   I_STRUCTURE_NAME                  =
*   I_BACKGROUND_ID                   = ' '
*   I_GRID_TITLE                      =
*   I_GRID_SETTINGS                   =
   IS_LAYOUT                          = LAYOUT
      IT_FIELDCAT                       = IT_FIELDCAT
*   IT_EXCLUDING                      =
*   IT_SPECIAL_GROUPS                 =
    IT_SORT                           = IT_SORT
*   IT_FILTER                         =
*   IS_SEL_HIDE                       =
*   I_DEFAULT                         = 'X'
*   I_SAVE                            = ' '
*   IS_VARIANT                        =
*   IT_EVENTS                         =
*   IT_EVENT_EXIT                     =
*   IS_PRINT                          =
*   IS_REPREP_ID                      =
*   I_SCREEN_START_COLUMN             = 0
*   I_SCREEN_START_LINE               = 0
*   I_SCREEN_END_COLUMN               = 0
*   I_SCREEN_END_LINE                 = 0
*   I_HTML_HEIGHT_TOP                 = 0
*   I_HTML_HEIGHT_END                 = 0
*   IT_ALV_GRAPHICS                   =
*   IT_HYPERLINK                      =
*   IT_ADD_FIELDCAT                   =
*   IT_EXCEPT_QINFO                   =
*   IR_SALV_FULLSCREEN_ADAPTER        =
* IMPORTING
*   E_EXIT_CAUSED_BY_CALLER           =
*   ES_EXIT_CAUSED_BY_USER            =
    TABLES
      T_OUTTAB                          = IT_FINOVR
* EXCEPTIONS
*   PROGRAM_ERROR                     = 1
*   OTHERS                            = 2
            .
  IF SY-SUBRC <> 0.
* MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.


ENDFORM.                    "BUILD_ALV_OVERVIEW


*---------------------------------------------------
*&      Form  ALV_CATALOG_HEADER
*&-------------------------------------------------------------------
*       text
*--------------------------------------------------------------------
*  -->  p1        text
*  <--  p2        text
*--------------------------------------------------------------------
FORM ALV_CATALOG_HEADER.
  DATA : LIT_HEADER TYPE  SLIS_T_LISTHEADER,
       LS_LINE TYPE SLIS_LISTHEADER.
  CLEAR LS_LINE.
  LS_LINE-TYP  = 'H'.
  LS_LINE-KEY = ' '.
  LS_LINE-INFO = 'Customer Sales Month Wise Report' .
  APPEND LS_LINE TO LIT_HEADER.
  CALL FUNCTION 'REUSE_ALV_COMMENTARY_WRITE'
    EXPORTING
      IT_LIST_COMMENTARY = LIT_HEADER
      I_LOGO             = 'ZLOGO'.
*  CALL FUNCTION 'CONVERSION_EXIT_SDATE_OUTPUT'
*    EXPORTING
*      INPUT  = LV_BUDAT_MKPF
*    IMPORTING
*      OUTPUT = LV_BUDAT_MKPF.

**  CALL FUNCTION 'CONVERSION_EXIT_SDATE_OUTPUT'
**
**  EXPORTING
**    INPUT         = LV_BEDAT.

*      I_LOGO             = ' '.

ENDFORM.                    "ALV_CATALOG_HEADER
