"Name: \PR:GPETSN3646RQODZ78DIUHVX2ZH2\FO:GET_DATA_TAB\SE:END\EI
ENHANCEMENT 0 ZSHL_COMPANY_AUTH1.
LOOP AT SP.
    AUTHORITY-CHECK OBJECT 'ZPLANT'
    ID 'ZBUKRS' FIELD SP-VKORG
    ID 'ZWERKS' DUMMY
    ID 'ACTVT' FIELD '03'.
    IF SY-SUBRC NE 0.
      MESSAGE 'NO AUTHORIZATION FOR CERTAIN RECORDS' TYPE 'S'.
    ENDIF.
ENDLOOP.
ENDENHANCEMENT.
