"Name: \PR:GPETSN3646RQODZ5N9DKT4BVCAO\FO:GET_DATA_TAB\SE:END\EI
ENHANCEMENT 0 ZSHL_AUTH_COMPANY.
LOOP AT SP.
    AUTHORITY-CHECK OBJECT 'ZPLANT'
    ID 'ZBUKRS' FIELD SP-BUKRS
    ID 'ZWERKS' DUMMY
    ID 'ACTVT' FIELD '03'.
    IF SY-SUBRC NE 0.
      MESSAGE 'NO AUTHORIZATION FOR CERTAIN RECORDS' TYPE 'S'.
    ENDIF.
    ENDLOOP.
ENDENHANCEMENT.
