"Name: \PR:SAPMJ1IS\FO:FILL_EXCITM\SE:END\EI
ENHANCEMENT 0 ZSL_MM_J1IS_MESSAGE640.
*Customer validation check
    IF MSEG-KUNNR <> SHEADER-KUNNR AND J_1IREG-RFTRTYP <> 'OTHR' AND
       MSEG-KUNNR NE SPACE AND RF02K-LIFNR IS INITIAL.   "Note 1237508
      MESSAGE E806(8I).
    ENDIF.

  MOVE J_1IEXCHDR-GSBER    TO SHEADER-GSBER.
  IF OPTION = 'CREA'.
    IF MSEG-BWART = '351' AND SHEADER-KUNNR NE SPACE.
      SELECT SINGLE * FROM T001W WHERE WERKS = MSEG-UMWRK.
      IF SHEADER-KUNNR <> T001W-KUNNR.
        T_MSGTXT = T001W-KUNNR.
        T_MSGTXT1 = SHEADER-KUNNR.
        CALL FUNCTION 'J_1I6_MESSAGE'
          EXPORTING
            ARBGB     = '8I'
            MSGNR     = '640'
            DEF_MSGTY = 'E'
            MSGTX1    = T_MSGTXT
            MSGTX2    = T_MSGTXT1
          EXCEPTIONS
            OTHERS    = 1.
      ENDIF.
    ENDIF.
  ENDIF.
ENDENHANCEMENT.
