*&---------------------------------------------------------------------*
*&  Include           ZTOP_DEC_VEN_DET
*&---------------------------------------------------------------------*

TABLES :ZVEN_DEBIT_TAB,
        LFA1,
        BSIK.

DATA : LV_DATE TYPE BUDAT.
DATA : LV_FLAG(1) TYPE C,
       LV_FLAG1(1) TYPE C.
DATA : LV_DAYS TYPE I.
DATA : LV_DAYS1(10) TYPE C.
DATA : BAL_LIMIT TYPE ZPURCHASE_LMT.
DATA : PUR_LIMIT TYPE CHAR20.
DATA : CHECK TYPE C.



TYPES : BEGIN OF GS_LFA1,
        LIFNR TYPE LFA1-LIFNR,
        NAME1 TYPE LFA1-NAME1,
        ORT01 TYPE LFA1-ORT01,
        KTOKK TYPE LFA1-KTOKK,
        LOEVM TYPE LFA1-LOEVM,
        END OF GS_LFA1.

DATA : GT_LFA1 TYPE STANDARD TABLE OF GS_LFA1,
       WA_LFA1 TYPE GS_LFA1.


TYPES : BEGIN OF GS_BSIK,
        LIFNR TYPE BSIK-LIFNR,
        SHKZG TYPE BSIK-SHKZG,
        DMBTR TYPE BSIK-DMBTR,
        BUDAT TYPE BSIK-BUDAT,
        BLART TYPE BSIK-BLART,
        ZFBDT TYPE BSIK-ZFBDT,
        ZBD1T  TYPE BSIK-ZBD1T ,
         END OF GS_BSIK.


DATA : DUE_DATE TYPE BSIK-ZFBDT.
DATA : NO_DATE TYPE BSIK-ZBD1T.


DATA : GT_BSIK TYPE STANDARD TABLE OF GS_BSIK,
       WA_BSIK TYPE GS_BSIK.


TYPES : BEGIN OF GS_AMOUNT,
        PURCHASE_LIMIT TYPE ZPURCHASE_LMT,
         AMOUNT TYPE CHAR20,
         LV_DAYS1(10) TYPE C,
         BALANCE TYPE CHAR15,
        END OF GS_AMOUNT.



TYPES : BEGIN OF GS_FINAL,
        LIFNR TYPE LIFNR,
        NAME1 TYPE NAME1,
        ORT01 TYPE ORT01,
        KTOKK TYPE LFA1-KTOKK,
        LOEVM TYPE LFA1-LOEVM,
        based_limit type zpurchase_lmt,
        PURCHASE_LIMIT TYPE ZPURCHASE_LMT,
        AMOUNT TYPE CHAR20,
        allowed_days(10) type c,
        LV_DAYS TYPE I,
        LV_DAYS1(10) TYPE C,
        BAL_LIMIT TYPE  ZPURCHASE_LMT,
        BUDAT TYPE BSIK-BUDAT,
        BALANCE TYPE CHAR15,
        ZFBDT TYPE BSIK-ZFBDT,
        ZBD1T TYPE BSIK-ZBD1T ,
        DUE_DATE TYPE BSIK-ZFBDT,
        NO_DATE TYPE BSIK-ZBD1T,
        CHECK TYPE C,
        END OF GS_FINAL.



TYPES : BEGIN OF GS_FINAL2,
        LIFNR TYPE LIFNR,
        NAME1 TYPE NAME1,
        ORT01 TYPE ORT01,
        based_limit type zpurchase_lmt,
        PURCHASE_LIMIT TYPE ZPURCHASE_LMT,
        AMOUNT TYPE CHAR20,
        LV_DAYS1(10) TYPE C,
        allowed_days(10) type c,
        BALANCE TYPE CHAR15,
        END OF GS_FINAL2.




DATA : GT_FINAL TYPE STANDARD TABLE OF GS_FINAL ,
       WA_FINAL TYPE GS_FINAL.

DATA : GT_FINAL1 TYPE STANDARD TABLE OF GS_FINAL ,
       WA_FINAL1 TYPE GS_FINAL.

DATA : GT_FINAL2 TYPE STANDARD TABLE OF GS_FINAL ,
       WA_FINAL2 TYPE GS_FINAL.

DATA : GT_FINAL3 TYPE STANDARD TABLE OF GS_FINAL2 ,
       WA_FINAL3 TYPE GS_FINAL2.


TYPES : BEGIN OF GS_DB_FINAL,
        LIFNR     TYPE 	LIFNR,
        NAME1	    TYPE NAME1_GP,
        ORT01	    TYPE ORT01_GP,
        based_limit type zpurchase_lmt,
        PURCHASE_LIMIT TYPE ZPURCHASE_LMT,
        AMOUNT TYPE CHAR20,
        LV_DAYS1(10) TYPE C,
       allowed_days(10) type c,
        BALANCE TYPE CHAR15,
END OF GS_DB_FINAL.


TYPES : BEGIN OF GS1_DB_FINAL,
        LIFNR     TYPE 	LIFNR,
        based_limit type zpurchase_lmt,
        PURCHASE_LIMIT TYPE ZPURCHASE_LMT,
        END OF GS1_DB_FINAL.


DATA :GT_DB_FINAL TYPE STANDARD TABLE OF GS_DB_FINAL,
      WA_DB_FINAL TYPE GS_DB_FINAL.

DATA :GT2_DB_FINAL TYPE STANDARD TABLE OF GS_DB_FINAL,
      WA2_DB_FINAL TYPE GS_DB_FINAL.

DATA :GT1_DB_FINAL TYPE STANDARD TABLE OF GS1_DB_FINAL,
      WA1_DB_FINAL TYPE GS1_DB_FINAL.



DATA : OK_CODE TYPE SY-UCOMM.
DATA : LV_AMOUNT TYPE ZPURCHASE_LMT.


CONTROLS TAB TYPE TABLEVIEW USING SCREEN 5000.

SELECTION-SCREEN BEGIN OF SCREEN 4000 AS SUBSCREEN.

SELECT-OPTIONS : S_LIFNR FOR LFA1-LIFNR MATCHCODE OBJECT ZSCR_VENDOR.

SELECTION-SCREEN END OF SCREEN 4000 .
