"Name: \PR:SAPMV50A\FO:USEREXIT_SAVE_DOCUMENT\SE:END\EI
ENHANCEMENT 0 ZTRANSIT.
*

 IF sy-TCODE eq 'VL01' OR SY-TCODE EQ 'VL02' OR SY-TCODE EQ 'VL01N' OR SY-TCODE EQ 'VLO2N' .

DATA : LV_STATUS TYPE ZTRAM_LOG_TABLE-STATUS,
       LV_STATUS1 TYPE ZTRAM_LOG_TABLE-STATUS1.

DATA : MSG(400).

SELECT SINGLE STATUS INTO LV_STATUS FROM ZTRAM_LOG_TABLE WHERE WERKS = VBAK-VKBUR .

SELECT SINGLE STATUS1 INTO LV_STATUS1 FROM ZTRAM_LOG_TABLE WHERE WERKS = VBAK-VKBUR .

  "IF LV_STATUS EQ 'NO' AND LV_STATUS1 EQ 'NO' .


     IF LV_STATUS EQ 'NO'  .
*
*
     IF LV_STATUS1 NE 'YES' .


"IF VBAK-VKBUR EQ '4127' .

 CONCATENATE VBAK-VKBUR 'IS MAXIMUM TRANSIT DAYS' INTO MSG SEPARATED BY SPACE .
MESSAGE MSG TYPE 'E' DISPLAY LIKE 'E' .
*
*SKIP TCODE .
*

ENDIF.
  ENDIF.

ENDIF.

  "break-point.


ENDENHANCEMENT.
