*&---------------------------------------------------------------------*
*& Include ZTRIPSHEETTOP                                     Module Pool      ZTRIP_SHEET
*&
*&---------------------------------------------------------------------*

PROGRAM ZTRIP_SHEET.

TABLES:ZTRIP_ST,ZLOG2,VBRP,KNA1.

*
*
*  DATA: BEGIN OF ST_VBRP,
*          VBELN TYPE VBRP-VBELN,
*          FKIMG TYPE VBRP-FKIMG,
*          BRGEW TYPE VBRP-BRGEW,
*          VOLUM TYPE VBRP-VOLUM,
*          ERDAT TYPE VBRP-ERDAT,
*        END OF ST_VBRP.

TYPES: BEGIN OF STR1_ZTRIP_ST,
        INVOICENO TYPE ZTRIP_ST-INVOICENO,
        INVOICEDATE TYPE ZTRIP_ST-INVOICEDATE,
        NETVOLUMEPERINVOICE TYPE ZTRIP_ST-NETVOLUMEPERINVOICE,
        GROSSVOLUMEPERINVOICE TYPE ZTRIP_ST-GROSSVOLUMEPERINVOICE,
        QUANTITY TYPE ZTRIP_ST-QUANTITY,
      END OF STR1_ZTRIP_ST.


TYPES:BEGIN OF STR_VBRP,
       VBELN TYPE VBRP-VBELN,
       FKIMG TYPE VBRP-FKIMG,
       BRGEW TYPE VBRP-BRGEW,
       VOLUM TYPE VBRP-VOLUM,
       ERDAT TYPE VBRP-ERDAT,

  END OF STR_VBRP.


DATA:OKAY_CODE TYPE SY-UCOMM.

DATA:WA_ZLOG2 TYPE ZLOG2.


DATA:WA_ZTRIP_ST TYPE ZTRIP_ST,

      LV_ZTRIP_ST TYPE ZTRIP_ST,

      IT_ZTRIP_ST TYPE TABLE OF ZTRIP_ST,

          IT_ZTRIP_ST5 TYPE TABLE OF ZTRIP_ST,

       IT_ZTRIP_ST1 TYPE TABLE OF ZTRIP_ST.

DATA:WA_T TYPE ZTRIP_ST,
      IT_T TYPE TABLE OF ZTRIP_ST.



DATA:WA_ZTRIP_ST1 TYPE STR1_ZTRIP_ST,
*      WA_ZTRIP_ST1 TYPE ZTRIP_ST,
      LV_ZTRIP_ST1 TYPE STR1_ZTRIP_ST,
      LV_ZTRIP_ST12 TYPE ZTRIP_ST,

      IT_ZTRIP_ST2 TYPE TABLE OF STR1_ZTRIP_ST.



DATA:LI TYPE I.
DATA:LI1 TYPE WBOBJPOS.
DATA:WS TYPE I.



DATA:LV_VBRP TYPE STR_VBRP,
     LV_VBRP1 TYPE STR_VBRP,
      LV_IT_VBRP  TYPE TABLE OF STR_VBRP.

DATA:LV_QTY TYPE FKIMG,
      LV_VOLUM TYPE VOLUM,
      LV_GROSS TYPE BRGEW.




TYPES:BEGIN OF STR_F1,
      VBELN TYPE VBRK-VBELN,
      KUNRG TYPE VBRK-KUNRG,
       NAME1 TYPE KNA1-NAME1,
       ORT01 TYPE KNA1-ORT01,
  END OF STR_F1.






TABLES:VBRK.

TYPES:BEGIN OF S,
      VBELN   TYPE VBRK-VBELN,
      END OF S.


DATA:WA_VBRK1 TYPE S,
      IT_VBRK1 TYPE TABLE OF S.




DATA:L_COUNT TYPE I.


DATA: EXT TYPE I VALUE '2'.


DATA:NAME1 TYPE ZLOG2-PWORD.
DATA:NAME2 TYPE ZLOG2-PWORD.

DATA:N TYPE I.

DATA:WA_VBRP TYPE VBRP.
DATA:WA_VBRK TYPE VBRK.
DATA:IT_VBRP TYPE TABLE OF VBRP.

CONTROLS:TAB TYPE TABLEVIEW USING SCREEN '9001'.
CONTROLS:TAB1 TYPE TABLEVIEW USING SCREEN '9002'.



DATA: ITAB TYPE TABLE OF DEMO_CONN.
TABLES DEMO_CONN.


DATA: COLS LIKE LINE OF TAB1-COLS,
      LINES TYPE I.



DATA:LIT_VBRK TYPE TABLE OF VBRK,
      LWA_VBRK TYPE VBRK.

DATA:WA_KNA1 TYPE KNA1,
      IT_KNA1 TYPE TABLE OF KNA1.


DATA:WA_F1 TYPE STR_F1,
      IT_F1 TYPE TABLE OF STR_F1.
