"Name: \PR:RVKRED01\FO:VBKRED_FUELLEN\SE:END\EI
ENHANCEMENT 0 ZWHITE_LIST_CUST.
*

DATA : LV1_KUNNR TYPE KNA1-KUNNR ,
       LV_REGIO TYPE KNA1-REGIO.
  if sy-TCODE eq 'ZVKM2' .
    LOOP at postab .
   " BREAK-POINT.
     SELECT SINGLE CUSTOMER_CODE INTO LV1_KUNNR FROM ZWHI_LIST_CUST WHERE CUSTOMER_CODE = POSTAB-KNKLI .
SELECT SINGLE REGIO INTO LV_REGIO FROM KNA1 WHERE KUNNR = lV1_KUNNR.
    IF LV1_KUNNR IS INITIAL AND LV_REGIO EQ 'KA'.

"CLEAR : postab.
    " MODIFY postab[] FROM postab.
delete postab WHERE knkli = POSTAB-KNKLI .
    ENDIF.
    CLEAR : LV1_KUNNR.
    ENDLOOP.
    IMPORT VBELN[] FROM MEMORY ID 'ZYX1'.
    DELETE POSTAB WHERE VBELN NOT IN VBELN .
    ENDIF.



ENDENHANCEMENT.
