"Name: \PR:SAPDBKMV\FO:YVBELN_FUELLEN\SE:END\EI
ENHANCEMENT 0 ZWHITE_LIST_CUSTOMER.
*
RANGES : VBELN2 FOR VBKRED-VBELN.
  IF SY-TCODE EQ 'ZVKM2'.

    "BREAK-POINT.

    IMPORT VBELN2[] FROM MEMORY ID 'ZYX1'.

  "GET PARAMETER ID 'MEM' FIELD VBELN3.

    ENDIF.

ENDENHANCEMENT.
