  INCLUDE MV75AFFC_FELDSYMBOLE_SORTIEREN .  " FELDSYMBOLE_SORTIEREN

  INCLUDE MV75AFFC_FELDSYMBOLE_SUCHEN .  " FELDSYMBOLE_SUCHEN

  INCLUDE MV75AFFC_FELDSYMBOLE_SUMMIEREN .  " FELDSYMBOLE_SUMMIEREN

  INCLUDE MV75AFFC_FELDSYMBOLE_WINDOW .  " FELDSYMBOLE_WINDOW


  INCLUDE MV75AFFC_FELDSYMBOLE_ZUORDNEN .  " FELDSYMBOLE_ZUORDNEN
  INCLUDE MV75AFFC_FELDTAB_FUELLEN .  " FELDTAB_FUELLEN
  INCLUDE MV75AFFC_FIXWERTE_RESTAURIER02 .  " FIXWERTE_RESTAURIEREN_ALT
  INCLUDE MV75AFFC_FIXWERTE_RESTAURIEREN .  " FIXWERTE_RESTAURIEREN

  INCLUDE MV75AFFC_FIXWERT_MERKEN .  " FIXWERT_MERKEN
  INCLUDE MV75AFFC_FNAME_BILDEN .  " FNAME_BILDEN

  INCLUDE MV75AFFC_FORMAT_AUSGEBEN .  " FORMAT_AUSGEBEN

  INCLUDE MV75AFFC_FORMAT_AUSBLENDEN .  " FORMAT_AUSBLENDEN
