MODULE PBO_201 OUTPUT.
  SET PF-STATUS 'ABSA'.
ENDMODULE.

MODULE PBO_202 OUTPUT.
  SET PF-STATUS 'WEIT'.
ENDMODULE.

MODULE FCODE.
  CASE SY-PFKEY.
    WHEN 'ABSA'.
      CASE SY-UCOMM.
        WHEN 'UEBE'.
          SET SCREEN 0. LEAVE SCREEN.
        WHEN 'ERW '.
          TVAGT-ABGRU = '##'.
          SET SCREEN 0. LEAVE SCREEN.
        WHEN 'ABBR'.
          TVAGT-ABGRU = '##'.
          SET SCREEN 0. LEAVE SCREEN.
      ENDCASE.
    WHEN 'WEIT'.
      CASE SY-UCOMM.
        WHEN 'UEBE'.
          SET SCREEN 0. LEAVE SCREEN.
        WHEN 'ERW '.
          VBKRED-SBGRP = '###'.
          SET SCREEN 0. LEAVE SCREEN.
        WHEN 'ABBR'.
          VBKRED-SBGRP = '###'.
          SET SCREEN 0. LEAVE SCREEN.
      ENDCASE.
  ENDCASE.
ENDMODULE.

MODULE SICHERN.
  PERFORM SICHERN.
  SET SCREEN 0. LEAVE SCREEN.
ENDMODULE.

MODULE SUPPRESS_DIALOG OUTPUT.
  SUPPRESS DIALOG.
ENDMODULE.

MODULE TVAGT_READ OUTPUT.
  CLEAR TVAGT-BEZEI.
  CHECK NOT ( TVAGT-ABGRU IS INITIAL ).
  SELECT SINGLE * FROM TVAGT WHERE SPRAS EQ SY-LANGU
                             AND   ABGRU EQ TVAGT-ABGRU.
ENDMODULE.

MODULE T024B_READ OUTPUT.
  CLEAR T024B-STEXT. "#EC CI_USAGE_OK[2227014] " Added by <IT-CAR Tool> during Code Remediation
  CHECK NOT ( VBKRED-SBGRP IS INITIAL ).
  SELECT SINGLE * FROM T024B WHERE SBGRP EQ VBKRED-SBGRP "#EC CI_USAGE_OK[2227014] " Added by <IT-CAR Tool> during Code Remediation
                             AND   KKBER EQ POSTAB-KKBER.
ENDMODULE.
